- epakuranttiajo.php
Jos kaksi yritystä on fuusioitunut ja molempien tapahtumat on siirretty saman yrityksen alle, niin fuusiossa on voitu luoda tapahtumia. Tämmöisiä tapahtumia ei kuulu huomioida epäkuranttilaskelmissa kun tutkitaan koska tuotetta on vimeksi esim myyty.
> Ei huomioida konversioissa muodostuneita tapahtumia

- rajapinnat/relex/relex_products.php
Tuotteen_toimittajat taulun muutokset eivät kaikissa tilanteissa (pääasiassa sisäänlue dataan kautta tehdyt) menneet Relexiin päivittäisissä aineistoissa. Siihen korjaus ja jatkossa menee. 
Lisäksi epäkuranttius huomioon ostoehdotuksessa, eli jos tuote on epäkurantti niin laitetaan aineistoon ostoehdotus "ei".
> Relex: Daily updatet kuntoon

- tilauskasittely/yllapitosopimukset.php
* Tallennetaan laskutuskausi sisviesti1-kenttään viesti-kentän sijasta, koska näkyy muuten väärin laskulla
> Laskutuskausi oikeaan kenttään

- iltasiivo.php
Tarkistetaan iltasiivossa valmistuksien varaukset tuotepaikoille oikein, jotta saadaan poistettua sellaiset paikat joille ei todellisuudessa ole varauksia. Aiemmin tarkistukset olivat siis liiankin tiukat ja varastopaikkoja jäi poistamatta.
> Korjaus iltasiivouksen tuotepaikkapoistoon

- kayttajat.php
- rajapinnat/lumo_handler.inc
- tilauskasittely/tulosta_asiakkaan_kuitti.inc
* Käyttäjähallinnasta mahdollisuus määrittää, mitä maksupäätekonetta käytetään
* Jos käyttäjällä ei ole määritelty maksupäätekoneen IP:tä, osoite otetaan salasanat.php:stä
* Laitetaan kassalipas aukeamaan oletuksena kuitin tulostuksen yhteydessä
Vaatii seuraavan kantamuutoksen:
```sql
ALTER TABLE kuka
ADD COLUMN maksupaate_ip VARCHAR(60)
AFTER maksupaate_kassamyynti;
```
> Käyttäjäkohtainen maksupäätekone

- epakuranttiajo.php
Konversiossa on voitu tietää viimeinen hankintapäivä mutta ei luontiaikaa, jolloin luontiaika tuotteella on voinut muodostua konversiopäivän mukaisesti. Tämmöisessä keississä koitetaan jatkossa käyttää viimeistä hankintapäivää, mikäli tapahtumista ei tuloja löydy.
Lisäksi, jatkossa ei huomioida virheellisesti keskihankintahinnan muutoksia tuloissa, vaikka tapahtumat onkin merkattu tuloiksi.
> Epäkuranttiajoon viimeisin tulo -fiksejä

- inc/tiliote.inc
Tiliotetta luettaessa pupeen, luoton nosto -tapahtuma ei tiliöitynyt edes selvittelytilille
> Luoton nosto -tapahtuma ei mennyt oikein

- tilauskasittely/keraa.php
Jos yhtiön parametri: karayksesta_rahtikirjasyottoon = Keräyksestä siirrytään suoraan rahtikirjan syöttöön, silloin siirrytään keräyksestä rahtikirjan syöttöön myös niillä toimitustavoilla, joille on määritelty Hetitulostus.
Vain jos toimitustapa on määritelty Noudoksi, ei mennä automaattisesti rahtikirjan syöttöön kotimaan toimituksissa.
> Heti-tulostus -toimitustavalla keräyksestä suoraan rahtikirjan syöttöön

- inc/functions.inc
- inc/valitse_tulostin.inc
- inventointi_listat.php
- raportit/inventointiaste.php
Lisätty uusia rajauksia:
- Tuotteen status-vaihtoehtoja enemmän, että saa samat kuin inventointiasteessa. Status A, Status P. 
- Tuki "älä huomioi näitä tuotepaikkoja". Nämä tulisi myös pystyä inventointilistalla näkemään tarvittaessa, että tietää mitkä paikat jätetään huomioimatta.
- Tuki varaston rajaukselle dropdownista nykyisten hyllypaikka-määrityksien lisäksi, ettei tarvitse tietää varastojen koodeja.
Jos piilotetaan tuotteen toimittajan tuotenumerot, niin ei turhaan lisätä hakuihin tuotteen toimittajaa.
> INVENTOINTILISTA: Uusia rajauksia

- tilauskasittely/otsik_siirtolista.inc
Varastosiirroissa kohdevaraston valinta on aina pakollinen. Tähän on nyt lisätty tarkistus joka estää käyttäjää jatkamasta mikäli varastosiirron kohdevarasto on valitsematta.
> Varastosiirroissa kohdevarasto on pakollinen

- tilauskasittely/verkkolasku.php
Sisäisistä laskuista tehdään yksi tiedosto, joka siirretään verkkolaskujen sisäänluku-hakemistoon.
Tämän jälkeen alkuperäistä laskuaineistoa ei ole liitettäväksi laskutuksesta lähtetään emailiin, joten liitettä ei enää yritetä lähettää
> Sisäiset laskut -emailista jätetään liite pois

- inventointi_listat.php
Katsottiin vahingossa väärää parametria reservipaikkojen ja keräysvyöhykkeiden ruksimisien kohdalla, jolloin rajauksia ei käytettykkään, mikäli väärä parametri ei ollut oikeassa asennossa.
> Inventointilistat: reservipaikka- ja keräysvyöhykerajaus fix

- sepa.php
Matkalaskun käsinsyötetty viiteteksti tulee olla aineistossa viestinä ei viitteenä
> Matkalaskun tekstiviite viestinä maksuaineistoon

- tilauskasittely/keikka.php
Saapumisen kautta jos menee tulostamaan purkulista PDF tulostus ruudulle ei toiminut. Tämä on nyt korjattu ja nyt purkulistan saa tulostettua myös ruudulle.
> Purkulistan tulostaminen ruudulle korjattu

- rajapinnat/edi.php
- tilauskasittely/editilaus_in.inc
- salasanat.php:n muuttujalla $verkkokauppa_hinnatedifailistaverollisina voidaan aktivoida tilausrivikohtaisen veron poislaskeminen tuotteen hinnasta tilauksen sisäänluvussa jos verkkokaupan hinnat ovat verollisia ja Pupessa hinnat ovat verottomia.
- vaatii muuttujan lisäksi sen että verkkokaupasta(magentosta) ollaan saatu tilausrivikohtainen verokanta
> * Verkkokaupan hintojen verollisuus

- mobiili/views/inventointi/laske.php
Oletusarvo 0 pois määrä-kentästä, jotta inventointi on nopeampaa. Aikaisemmin piti poistaa nolla ja syöttää luku (mikäli ei inventoitu nollaksi). Nyt riittää että syöttää oikean luvun.
> MOBIILI: Inventointi

- tilauskasittely/lisaarivi.inc
Toimipaikalta myydään tuoteperhe, jolla ei ole riittävästi saldo toimipaikan varastossa.
Päävarastossa on tuoteperhettä saman verran kuin toimipaikalla oli myyty -> tehdään varastosiirto tuoteperheen tuotteista: tarkistetaan isätuotteen saldon riittävyys ja varataan isätuotteelle koko päävaraston saldo. Myös lapsituotten kohdalla tutkittiin isätuotteen myytävissä saldoa, jota ei enää ole, koska se varattiin juuri isätuoteriville, eikä lapsi riville saada tehtyä varastosiirtoa.
Korjattu, että lapsen kohdalla tutkitaan lapsen saldoa ja saadaan tehtyä varastosiirto myös lapsiriville.
> Myynti, tuoteperheen lapsituotteen saldotarkistus

- inc/paakirja.inc
Pääkirjassa päivämäärävälillä haettaessa haetaan ja näytetään myös silloin kumulatiivinen summa oikein. Aiemmin siis kumulatiivinen summa alkoi päivämäärävälin ensimmäisestä päivästä, mutta nyt haetaan kumulatiivinen summa edelliseltä päivältä, jolloin saadaan kumulatiiviseen summaan jatkumo.
> Kumulatiivinen summa pääkirjassa

- tilauskasittely/editilaus_in.inc
- voidaan ohjata sisäänluettava verkkokauppatilaus toiselle yhtiölle antamalla viides parametri $verkkokauppa_erikoiskasittely-muuttujassa
> Verkkokauppatilauksen sisäänluku vaihtoehtoisella OVT-tunnuksella

- yllapito.php
Korjattu virhe mysqlaliaksien oletusarvojen haussa. Querystä puuttui alias_set. Tarkoittaa sitä, että jos oli tehty useampia eri mysqlaliaksia joissa samoille kentille määritelty oletuksia, saattoi tietueen perustuksessa tulla väärän mysqlaliaksen oletusarvoja, esim tuotteen perustuksessa.
> Mysqlalias oletusarvot

- tilauskasittely/keikka.php
- tilauskasittely/ostotilausten_rivien_kohdistus.inc
Saapumisilla tuotenumero vieressä sijaitseva "näytä saldo" infopainike ei kaikilla tuotenumeroilla toiminut - linkki ei siis kaikilla tuotteilla tehnyt mitään. Nyt "näytä saldo" linkki on korjattu ja tuotteen saldot tulevat näkyviin kaikilla tuotteilla infopainikkeen klikkauksen jälkeen.
> "Näytä saldo" saapumisella

- tilauskasittely/keraa.php
Tilavuuteen perustuvien keräyseriä käytettäessä eivät nollakeräykset menneet oikein vaan myös nollana kerätyt tilaukset menivät toimitetuksi ja siten lopulta laskutetuksi. Nyt myös tilavuuteen perustuvien keräyserien käytössä laitetaan kokonaan nollana kerätyt tilaukset oikein mitätöidyiksi.
> Keräyspoikkeamat

- rajapinnat/lumo_handler.inc
* Tallennetaan maksutapahtumat joka tapauksessa kantaan, jos ne menevät läpi, vaikka kuitissa ei lukisikaan sanaa OSTO
* Korjaa bugin, jossa maksutapahtuma on voinu mennä läpi, mutta tapahtumaa ei ole tallentunut kantaan, eikä tulostunut kuitille
> Maksupäätetapahtumien tallennus

- tilauskasittely/verkkolasku_finvoice.inc
Lähetetään verkkolaskut myös ITELFIHH-operaattorille (Säästöpankki)
> * Verkkolaskutus

- inc/avainsanarivi.inc
jatkopulkkari aiemmalle: nyt laji oikein ylläpidon-dropdownissa..
Tuotteille voi lisätä avainsanoina tuotehinnastoryhmiä. Jos näitä on lisätty, näytetään asiakashinnastossa valikko josta saa valita esitetäänkö hinnasto normaalisti vai ryhmiteltynä tuotehinnastoryhmittäin.
Jotta pääsee perustamaan tuotteelle tuoteryhmähinnasto-avainsanoja, täytyy ensin luoda tavallinen avainsana jonka laji on TUOTEULK ja selite on tuoteryhmaosasto
> CRM-asiakashinnasto tuotehinnastoryhmittäin

- inc/laskuhaku.inc
- inc/paakirja.inc
- inc/toimittajahaku.inc
- raportit.php
- raportit/tuloslaskelma.php
- tilauskasittely/monivalintalaatikot.inc
Voidaan rajata tuloslaskelma/tase ja pääkirja näyttämään vain käyttäjän oman osaston, eli kustannuspaikan laskuja. Tämä ominaisuus toimii myös laskuhaku-ohjelmassa ja toimittajahaku-ohjelmassa.
Valikkoihin tulee perustaa uudet rivit:
raportit/tuloslaskelma.php, alatila --> _OKP
raportit.php, alatila --> paakirja_OKP
> * Oman kustannuspaikan tuloslaskelma & pääkirja

- tilauskasittely/uudelleenluo_laskuaineisto.php
- tilauskasittely/verkkolasku.php
Näytettäessä laskulla vain perheen isä ja summattaessa lasten hinnat perheen isälle, käsiteltiin tuoteperheiden hintoja verottominan, vaikka yhtiöllä olisikin käytössä verolliset myyntihinnat. Tämä johti siihen, että kun yhtiöllä on käytössä verolliset myyntihinnat laskettiin vero kahteen kertaan pois hinnoista ja esimerkiksi verkkolaskulle meni liian alhaiset kappalehinnat. Tämä on nyt korjattu ja jatkossa tälläisetkin tuoteperheet käsitellään oikein.
> Tuoteperheiden hinnat verkkolaskulla

- tilauskasittely/tilaus-valmis.inc
Myyntitilaus saattoi jäädä erheellisesti auki ruudulle kun se laitettiin valmiiksi ja myös ruudulle tuli virheellisesti ilmoitus puutteellisista laskutustiedoista vaikka laskutustiedot olivat kunnossa. Tämä on nyt korjattu ja tilaukset saa laitettua oikein valmiiksi.
> Myyntitilauksen luottorajaesto

- monistalasku.php
- tilauskasittely/lisaarivi.inc
Kun laskua monistettaessa alkuperäisen laskun varastopaikkaa ei jollain tuotteella enää ole olemassa meni tälläinen tuote tuotteen oletuspaikalta. Muutettu niin, että perustetaan tarvittaessa tuotteella paikka laskun monistuksen yhteydessä.
Samalla korjattiin ettei ehdoteta hyvitysriveille varastosiirtoa, jos tee_automaattinen_siirto_myyntitilaukselta on päällä.
> Poistettu tuotepaikka laskun monistuksessa

- inventoi.php
- Tarkistetaan relatiivinen inventoinimäärä huolellisemmin, jotta pystytään estämään erien kappalemäärien ja tuotteen saldon erisuuruisuus
- Inventoitaessa päivämäärällä ja kun poistetaan uusi eränumero poista painikkeella palataan takaisin päivämäärällä inventointiin. Aiemmin uuden eränumeron poisto poistopainikkella vei takaisin normaaliin inventointiin
> Eränumerolla inventointi

- ulask.php
Ilman toimittajatietoja syötetyssä ostolaskussa sai maakoodin syötettyä pienillä kirjaimilla, jolloin maakoodi myös tallennettiin pienellä. Tämä aiheuttaa ongelmia SEPA-aineiston kanssa, jossa maakoodin tulee olla isoilla kirjaimilla. Nyt ostolaskujen maakoodin käsinsyötön sijaan ostolaskun tietojen syötössä on alasvetovalikko, josta voi helposti valita oikean maan.
> Ostolaskun maakoodi

- tilauskasittely/tilaus-valmis.inc
Kassamyyjä laittaa myyntitilauksen valmiiksi (ja tilauksen otsikolla on "suoraan laskutukseen" ruksi), jolloin se menee toimitetuksi silloin kun kyse ei ole käteismyynnistä.
Jos tässä vaiheessa halutaan muuttaa myynti käteismyynniksi, menee tilaus kerätty tilaan, eikä anneta tehdä laskua, vaikka valitaan tilauksen otsikolle käteinen/pankkikortti.
Korjattu niin, että ei muuteta toimitetusta kerätyksi. Tällä tavalla saadaan tehtyä käteiskuitti ja saadaan tilaus laskutetuksi.
> Maksuehdon muuttaminen

- tilauskasittely/tulosta_lasku.inc
* Tulostetaan tositteen otsikoksi "Maksutosite", jos kyseessä on erämaksu
* Ei tulosteta eräpäivää, kassa-alennuskenttiä eikä viivästyskorkoa, jos kyseessä on erämaksu
* Tulostetaan maksuehtokenttään "Erämaksu", jos kyseessä on erämaksu
* Tulostetaan "Lasku yhteensä" -tekstin tilalla "Yhteensä", jos kyseessä on erämaksu
* Tulostetaan "Rahoituksella / Osamaksulla" tekstin tilalle "Erämaksulla"
* Ei tulosteta yhteensä-riviä, eikä pankkiyhteystietoja, jos kyseessä on erämaksu
* Tulostetaan tositteita 2 kpl, jos määrää ei ole erikseen määritelty ja jos kyseessä on erämaksu
* Tulostetaan tositteeseen kuka luoton myöntää sekä "Paikka ja aika", "Allekirjoitus" ja "Nimenselvennys" -kentät, jos kyseessä on erämaksu
* Ei enää tarkisteta, että maksettu saldo ei ole 0, jolloin myös kokonaan …
> Parannuksia erämaksuun

- tilauskasittely/tilaus_myynti.php
* Tarkistetaan jäljellä oleva maksupäätesumma vain, jos maksupääte-parametri on päällä, jolloin maksut tiliöityvät oikein
> Kassamyynnin tiliöintien korjaus

- inc/functions.inc
- tilauskasittely/mikrotilaus.inc
- tilauskasittely/mikrotilaus_ostotilaus.inc
Ostotilausten tilausrivien excelissä luvussa pävimääräkentät eivät menneet aina oikein, koska excelin päivämäärätallennusmuodon käsittely ei onnistunut. Tällöin päivämääräksi tuli aina kuluva päivämäärä. Nyt osataan käsitellä myös excelin päivämäärien tallennusmuotoa jolloin päivämäärät saadan luettua oikein sisään.
> Ostotilauksen rivien luku excelistä

- inc/functions.inc
- inc/yhtion_parametritrivi.inc
- tilauskasittely/keraa.php
- tilauskasittely/lahetteen_tulostusjono.php
- tilauskasittely/tilaus-valmis-tulostus.inc
- tilauskasittely/tilaus_myynti.php
- tilauskasittely/tulosta_lahete_kerayslista.inc
- tilauskasittely/vastaanota.php
Uusi ominaisuus jossa purkulistan tulostusjonossa reklamaatiot kasaantuvat yhdeksi purkulistaksi per varasto ja toimipaikka. Purun kuittaus muistaa mitkä reklamaatiot on tulostettu yhdelle purkulistalle ja kuittaus tehdään per lista. Kuittauksessa on myös mahdollisuus vaihtaa tuote lapsivaraston paikoille (tai tehdä purun yhteydessä se automaattisesti).
Tämä ominaisuus kytketään päälle "reklamaation käsittely" -yhtiön parametrin uudella optiolla: "Reklamaation käsittelyssä käytetään laajempaa prosessia purkulistalla ja vastaanottokuittauksella". Tämä toimii kuten laaja reklamaatiokäsittely, mutta "odottaa tuotteita" -vaihe ohitetaan ja reklamaatio menee purkulistan tulostusjonoon heti reklamaation valmiiksi laittamisen jälkeen.
> REKLAMAATIO: Koontipurkulista

- raportit/varastonarvo-super.php
Ei huomioida jatkossa varaston sisäisiä siirtoja.
Optio "Huomioi Varastosiirrot Viimeisin Osto Ja Myyntitiedoissa" huomioi aikaisemmin myös varaston sisällä tapahtuneet siirrot. Jatkossa huomioidaan vain kahden eri varaston väliset siirtolistoilla tehdyt varastosiirrot (eli käytännössä fyysisen tavaran liikuttelua kahden varaston välillä).
> Varastonarvo tuotteittain

- tilauskasittely/jalkilaskenta.inc
Jos jälkilaskenta korjasi myyntilaskun varastonmuutosstiliöintejä, korjattujen tiliöintirivien tilinumero jäi virheellisesti nollaksi
> Saapumisen jälkilaskenta

- tilauskasittely/tulosta_keraysera.php
Tulosta keräyserä -ohjelmassa korjattu nimiongelma. Asiakkaan nimeä ei näytetty jos tarkasteltiin tulostetun keräyserän pakkauksia ja pakkaus sisälsi siirtotilauksen rivejä.
> Tulosta keräyserä

- kayttajat.php
- tilauskasittely/otsik.inc
* Käyttäjän taakse mahdollista tallentaa oletuksiksi maksuehto, toimitustapa ja se, menevätkö tilaukset suoraan laskutukseen
* Uusia tilauksia luotaessa, katsotaan löytyykö käyttäjältä näitä arvoja, ja jos löytyy, niin käytetään niitä
* Jos arvoja ei käyttäjältä löydy, otetaan ne asiakkaan takaa niin kuin ennekin maksuehdon ja toimitustavan tapauksessa
> Käyttäjäkohtaiset otsikkotiedot

- inc/functions.inc
- uutiset.php
Tervetuloa sivulla oli ongelmia liitetiedostojen näyttämisen kanssa, sillä liitetiedostot tallennettiin joka kerta uudestaan tervetuloa sivun avauksen yhteydessä. Tämän on kuitenkin nyt korjattu ja ylimääräisiä tallennuksia ei tehdä.
Samalla korjattiin myös uuden uutisen lisäyksessä tapahtuva uutisen kielen valinta monivalintalaatikoista valitse-yksi-tyyppiseksi valinnaksi.
> Tervetuloa sivun uutiset

- tilauskasittely/otsik.inc
Verkkokaupassa maksettuja tilauksia, jos kävi Pupen puolella muokkaamassa päivittyi laskun kanavointitieto vääräksi. Tämän takia tilausta ei osattu oikein päivittää laskutettu tilaan sen jälkeen, kun tilaus kerätyksi merkitään vaan tilaus jäi toimitettu tilaan siitä huolimatta, että se oli jo todellisuudessa myös laskutettu. Nyt tämä ongelma on korjattu ja verkkokaupasta tulleiden maksettujen tilausten laskun kanavointitietoa osataan käsitellä kuten kuuluu.
> Verkkokaupassa maksetut verkkokauppatilaukset

- tilauskasittely/tilaus-valmis-siirtolista.inc
Varastosiirrosta, jos ollaan jo keräyslista tulostettu ja jos tässä vaiheessa käydään muokkaamassa varastosiirtoa palautetaan varastosiirto takaisin tulostusjonoon. Kun keräyserät ovat käytössä tulisi tässä vaiheessa, kun varastosiirto tulostusjonoon palautetaan niin samalla myös nollata keräyserät. Näin ei aiemmin siis käynyt vaan varastosiirto joutui tilaan jossa sillä oli keräyserät olemassa, mutta se oli tulostusjonossa. Tämä ongelma on nyt siis korjattu ja varastosiirron muokkaus, joka palauttaa sen tulostusjonoon samalla myös mitätöi aiemmat keräyserät.
> Varastosiirron muokkaaminen - keräyserät käytössä

- rajapinnat/relex/relex_products.php
Bugikorjaus, alustetaan parastoimittaja-taulukko, jotta ei vahingossa käytetä edellisen loopin arvoja, mikäli tuotteelta ei löytyisi yhtään toimittajaa.
Lisäksi huomioidaan netto-ostohinnan laskennassa jalkilaskennan_kuluperuste parametrin optio "Virallisen varastonarvon laskentaan käytetään kululaskujen summaa, mikäli kululaskut on syötetty, muuten kulusummaa/kuluprosenttia".
> Relex products

- tilauskasittely/tuote_selaus_haku.php
Korjattu vastaavuusketjujen näkyvyyttä, jos "Näytä vain saldolliset tuotteet"-ruksi on päällä. Saldotonta vastaavuusketjun päätuotetta ei näytetä, jos sillä ei ole yhtään saldollista vastaavaa tuotetta.
> Hae & Selaa

- tilauskasittely/tilaus_myynti.php
Poistettu varastosiirto meni epäloogisesti tilaan "mitätöity myyntitilaus" eikä "mitätöity siirtolista". Nyt poistetut varastosiirrot menevät loogisemmin tilaan "mitätöity siirtolista".
> Varastosiirron poistaminen

- tilauskasittely/lisaarivi.inc
Tilausrivien sisäänluvussa, jos keskellä tiedostoa ollut rivi olisi menossa varastosiirtona toisesta varastosta tuli lopuille tiedoston riveille virheellisesti tämä siirtovarasto varastotiedoksi vaikka tätä tuotetta olisi ollut myös siinä varastossa josta tuotteita varsinaisesti myytiin.
> Myyntitilausrivien excelistä sisäänluku

- tilauskasittely/editilaus_in.inc
Vientitilauksille tulostettiin epähuomiossa kaksi keräyssanomaa. Tämä on nyt korjattu ja nyt tulostetaan myös vientitilauksille yksi keräyssanoma kuten kuuluu.
> Vientitilauksen keräyssanoma ulkoiseen järjestelmään

- inc/muutosite.inc
Huomioidaan pankkitilit, kun lisätään saapumiseen lasku, jossa on kuluja. Aikaisemmin pankkitlit huomioitiin kulutileinä, joka vaikutti virheellisesti laskentoihin.
> Oskolaskun kulut

- raportit/asiakkaantilaukset.php
- tilauskasittely/tulostakopio.php
Näytettäessä lasku ruudulla tuli laskun tietojen yläpuolelle teksti "Tilaus *numero*:". Tämä *numero* ei ollut suinkaan laskun tilauksen numero vaan laskun tunnistenumero. Nyt tämä hämäävä teksti on korvattu tekstillä "Lasku:".
Tämä koskee ohjelmia asiakkaan tilaukset ja lasku kopio (toiminto näytä ruudulla).
> Laskun näyttäminen ruudulla

- tilauskasittely/tilaus-valmis.inc
Tuoteperheiden tapauksessa eri varastosta menossa olevat lapsituotteet päivittyivät erheellisesti samalle tilaukselle isätuotteensa kanssa vaikka isätuote olisi ollut menossa eri varastosta. Tämä korjattu ja jatkossa isätuotteen kanssa eri varastosta menossa olevat lapsituotteet pystyvät menemään oman varastonsa tilaukselle eikä niitä siirretä ns. väärästä varastosta menossa olevalle tilaukselle.
> Myyntitilauksen jakaminen varastoittain

- extranet/asiakashinnasto.php
Tuotehinnastoryhmittäin tulostettavasta asiakashinnastosta oli jääny verollinen myyntihinta sarakkeet pois. Nämä sarakkeet on nyt lisätty myös tällä esitystavalla tulostettavaan asiakashinnastoon.
> Asiakashinnasto: esitystapa tuotehinnastoryhmittäin

- tilauskasittely/lisaarivi.inc
- tilauskasittely/tee_jt_tilaus.inc
Nollataan JT-/Ennakkoselauksessa luodulta otsikolta varasto-kenttä, koska alkuperäisen tilauksen varastolla ei ole uudella otsikolla virkaa. 
JT-/Ennakkoselauksessa ei myöskään toimiteta aitomaattisesti erikoisvarastoista vaikka erikoistoimitus_alarajasumma ylittyisi.
> JT-/Ennakkoselauksen varastovalinta

- inc/yhtion_parametritrivi.inc
- tilauskasittely/tee_jt_tilaus.inc
Siirtolistojen JT-rivien vapautuksessa oli teknisestä bugista johtunut ominaisuus jonka takia tilausrivejä ei JT-rivien vapautuksessa yhdistetty samalle siirtolistalle.
Bugi korjattiin ja "ominaisuus" lähti pois, mutta nyt tämä ominaisuus palautetaan takaisin yhtiön parametrin muodossa. Jos siis uusi yhtiön parametri on päällä tilausrivejä jotka alunperin ovat olleet eri siirtolistoilta ei yhdistetä samalle siirtolistalle JT-rivien vapautuksessa.
> * Siirtorivien yhdistäminen JT-toimituksessa

- inc/yhtion_parametritrivi.inc
- tilauskasittely/tulosta_lahete_kerayslista.inc
Uusi yhtiön parametri lisätty jolla voidaan ohjata näytetäänkö varastosiirtojen kohdepaikkatieto PDF:llä aina, vai ainoastaan varastonsisäisissä siirroissa.
> * Varastosiirrot: Näytä kohdepaikka tulosteessa

- tilauskasittely/otsik.inc
Myyntitilauksen luonnissa oli mahdollista saada aikaan eroavaisuuksia myyntitilauksen otsiko ja tilausrivien kerays- ja toimitusaikatietoihin. Tämä aiheutti eroja mm. joissain raporteissa. Tämä on nyt korjattu ja huolehditaan tarkemmin, että tilausrivien päivämäärätiedot vastaavat otsikon tietoja.
> Myyntitilausrivien päivämääräkäsittely

- tilauskasittely/varastoon.inc
Jos samalle suuntalavalle vietiin tuloutuksessa eri toimittajien tuotteita, varastoonvientivaiheessa tuotteen tulotapahtuman selitteeseen meni yhden toimittajan tiedot kaikille tuotteille riippumatta siitä, miltä toimittajalta tuote oikeasti oli tullut.
Tuloutusrivit olivat kuitenkin oikean toimittajan saapumisella.
> Tuloutus suuntalavoja käyttäen

- mobiili/vahvista_kerayspaikka.php
Kun tuloutetaan yksittäinen tuote suoraan hyllyyn, palataan kohtaan, jossa käyttäjä voi antaa uuden viivakoodin/tuotekoodi/ostotilausnumeron ilman turhaa  virheilmoitusta
> Mobiili-tulouttaminen

- vaihda_tuoteno.php
Kun vaihdetaan tuotenumeroa, päivitetään uusi tuotenumero myös esim. yhteensopivuus_tuote- tauluun ja jos siellä oli jostain syystä jo rivi uudella tuotenumerolla, jouduttiin sql-error -tilanteeseen
> Tuotenumeron vaihtaminen

- mobiili/suuntalavalle.php
Jos ollaan lisäämässä tuottetta suuntalavalle mobiili-tuloutuksessa ja syötetään suuntalavan sscc (viivakoodi), niin tehdään automaaginen "haku" sscc:llä listan suuntalavoihin, ilman että tarvii erikseen painaa "hae". Jos listalta löytyy yksi osuma, valitaan kyseinen suuntalava automaagisesti ja lisätään tuote sille (toimii kuin olisi painettu ok:ta).
Ominaisuus nopeuttaa mobiili-tuloutuksessa tuotteen lisäämistä suuntalavalle.
> Mobiili: vie tuote suuntalavalle

- rajapinnat/relex/relex_products.php
Relexiin siirtyvissä tuote-aineistoissa huomioidaan ostohinnassa tuotekerroin, jotta Relexiin siirtyvä ostohinta olisi yhden kappaleen oma ostohinta, ei toimittajan.
> Relex: tuotekerroin

- tilauskasittely/tilaus_osto.php
Poistetaan kokonaan käytöstä tuotteen avainsanat pakkauskoko2 ja pakkauskoko3, koska ne on korvattu  toimittajan vaihtoehtoisella pakkauskoko -taululla
> Tuotteen avainsanat pakkauskoko2 ja pakkauskoko3

- tilauskasittely/rahtikirja_postitarra_ulkomaa_pdf.inc
Ulkomaan priority lähetyksestä, jos otti rahtikirjakopion tuli tulosteen lähetystunnukseen kahteen kertaan tunnisteen alku- ja loppuosan tunnukset. Tarkistetaan ettei tunniksia ole jo ja ei laiteta niitä kahdesti.
Lisäksi lisättiin yhden puuttuneen valintalaatikon reunat.
> Ulkomaan lähetyksen rahtikirjakopio

- varastopaikkojen_siivous.php
Varastopaikkojen siivous ohjelmalla ei saa nyt kiinni niitä varastopaikkoja, jotka ei kuulu enää minkään varaston alueeseen - vaikkakin se varasto johon niiden tuotepaikat.varasto on viel olemassa niin sen varaston hyllyaluetta on muutettu niin et ne paikat ei enää kuulu siihen. Nyt varastopaikkojen siivous ohjelmalla saadaan kiinni myös ne varastopaikat jotka eivät kuulu enää minkään varaston alueeseen eli ne eivät kuulu enää mihinkään varastoon.
> Varastopaikkojen siivous

- inc/toimitustapatarkista.inc
- rahtikirja.php
Jos toimitustavan tulostustapa on koontitulostus, niin ei esitäytetä rahtikirjan syötössä pakkaustietoja, mikäli on Unifaun käytössä. Lisäksi ei sallita Unifaun toimitustavalle koontierätulostusta, sillä sitä ei tällä hetkellä kunnolla tueta.
> Unifaun: tulostustapa koonti

- inc/functions.inc
Ostotilauksen ostohinnan käsittelyssä oli muutamia ylimääräisiä valuuttamuunnoksia jonka takia saattoi ilmaantua pyöristyseroja käyttäjän syöttämän hinnan ja todellisen hinnan välille. Ylimääräiset valuuttamuunnokset on nyt siivottu pois.
> Ostotilaus: ostohinnan käsittely

- tilauskasittely/lisaarivi.inc
Varastosiirtoa tehtäessä, kun ollaan valittu varastosiirron otsikolle "siirrä kaikista" annetaan käyttäjän todella siirtää tuotteita kaikista varastoista vaikka hänellä ei olisi myyntioikeutta kaikkiin varastoihin.
> Varastosiirto: siirrä kaikista varastoista

- raportit/myyntiseuranta.php
Näytetään laskun maksupäivämäärä oikein myös muilla ajotavoilla kuin "Laskuista (Laskutus)". Aiemmin näillä muilla ajotavoilla maksupäivämääräksi tuli siis 0000-00-00 vaikka lasku olisikin jo maksettu.
> Myynninseurantaraportti: laskun maksupäivämäärä

- inventoi.php
Kun inventoitiin listan avulla, eikä käytössä ollut laajaa inventointilistaa, ei inventointitapahtumaa syntynyt lainkaan. Nyt tämä on korjattu ja tapahtuma syntyy.
> Inventointi listan avulla

- inc/tiliote.inc
Toinen Swedbank erittelykoodipoikkeus. Ei kirjata 770 INTERNATIONAL PAYMENT tapahtumia joilla on viitenumero.
> Swedbank erittelykoodipoikkeus.

- inc/pankkiyhteys_functions.inc
- pankkiyhteysadmin.php
* Annetaan syöttää yrityksen nimi, koska sen täytyy CSR:ssä ainakin Nordean tapauksessa olla täsmälleen sama kuin sopimuksessa
* Laitetaan CSR:n serial numberiksi customer_id, koska Nordea vaatii sen
> Pankkiyhteysfixejä

- inc/toimitustapatarkista.inc
- rahtikirja-tulostus.php
- rahtikirja.php
- tilauskasittely/keraa.php
- unifaun_fetch.php
Unifauniin lisätty tuki myös Pupen koontierätulostukselle ja koontihetitulostukselle.
Koontihetitulostus toimii niin että rahtikirjan syöttö tehdään vasta kun halutaan aineistoa siirtää Unifaunille. Siinä kerrotaan koonnin alusta, esim lava. Yksittäisten kollien kollilaput tulostetaan keräysvaiheessa, ja niistä kolleista ei mene tietoa Unifauniin.
Koontierätulostus toimii niin että rahtikirjan syöttö tehdään normaalisti. Yksittäisten kollien kollilaput tulostetaan keräysvaiheessa, ja niistä kolleista ei mene tietoa Unifauniin. Rahtikirjan tulostuksessa annetaan vasta koonnin alusta, esim lava. Unifaunille lähetetään tässä vaiheessa aineisto lavasta.
> Unifaun: koontitulostus

- sepa.php
* Ei tarkisteta asiakasid:tä pankkiyhteyttä haettaessa, koska ei välttämättä ole sama kuin pankkiyhteydessä käytettävä käyttäjätunnus
> Korjaus pankkiyhteyksiin

- tilauskasittely/tilaus_myynti.php
Laajassa reklamaatiokäsitteyssä (reklamaatio suoraan purkulistan tulostusjonoon, ei vastaanottojonoon) tuki sähköiselle lähetteelle. Tulisi sillon kun reklamaatio laitetaan valmiiksi ja se siirtyy purkulistan tulostusjonoon.
Lisäksi tuki "suoraan laskutukseen" reklamaatioilla laajassa reklamaatiokäsittelyssä (reklamaatio suoraan purkulistan tulostusjonoon, ei vastaanottojonoon), että ohitetaan varasto ja merkitään reklamaatio suoraan valmiiksi laskutettavaksi.
Runkojen purkulistaan vaihtoehto että "ei tulosteta". Tämä käyttöliittymä jos "suoraan laskutukseen" ruksattu otsikolta.
> Reklamaatio koontipurkulista

- palkkatosite.php
Palkkatosite ohjelmasta tuli SQL-errori, jos sille syötetyssä tiedostossa tuli erikoismerkkejä. Siivotaan erikoismerkit nyt pois jotta SQL-virheeltä vältyttäisiin.
> Palkkatosite: SQL-errorin korjaus

- raportit/myyntiseuranta.php
Laskutuspäivämäärän kanssa haettaessa tuloksesta tuli joskus tyhjä, kun valittiin myös "Piilota Nollarivit" vaikka tulos ei tyhjä suinkaan todellisuudessa olisi ollut. Tämä on nyt korjattu ja nyt myös näillä hakuehdoilla saa tuloksen ruudulle.
> Myynninseurantaraportti: laskutuspvm

- inc/unifaun_send.inc
Unifauniin lähettettäessä sähköpostit tulee erotella ";" merkillä. Korjattun niin, että sähköpostit erotellaan aina ";" merkillä, jos esimerkiksi asiakkaan tiedoissa on useita sähköpostiosoitteita.
> Unifaun: sähköpostiosoitteet

- inc/unifaun_send.inc
Unifaun ei ymmärrä, jos email-kentässä useita osoitteita, vaikka ne olisivat puolipisteellä eroteltuna.
Jos asiakkaalla useita sähköpostiosoiteita, laitetaan vain ensimmäinen unifaun-fileen.
> Unifaun-file menee virheeseen, jos useita email-osoitteita

- inc/verkkolasku-in-erittele-laskut.inc
Muihin kuin Finvoiceaineistohin lisätään <xml ?>-tägi jos se puuttuu laskuaineistosta.
> Verkkolasku-xml

- tuotannonsuunnittelu.php
- valmistus.class.php
Palautettaessa tuotannonsuunnittelussa valmistus takaisin parkkiin "Siirrä parkkiin" toiminnolla niin päivitetään samalla myös kerayspvm ja toimaika tiedot laskulle ja tilausriveille 2099-01-01, jotta valmistus ei näkyisi hassusti tuotehallinnassa.
Lisäksi korjattiin samalla yksi typo; "Siirä parkkiin" -> "Siirrä parkkiin".
> Tuotannonsuunnittelu: siirrä parkkiin ominaisuus

- inc/functions.inc
- inc/yhtion_parametritrivi.inc
- muuvarastopaikka.php
Osataan päivittää myös siirtorivien kohdepaikkatiedot, jos oletuspaikkaa muutetaan.
Siirrettiin pelkästään mobiilipuolen toiminnallisuus "Päivitä oletuspaikka"-yhtiöparametrin uudeksi valinnaksi.
```SQL
CREATE INDEX kohde_hyllypaikka ON tilausrivin_lisatiedot (yhtio, kohde_hyllyalue, kohde_hyllynro, kohde_hyllyvali, kohde_hyllytaso);
> * Päivitä oletuspaikka: kohdepaikan päivitys

- inc/avainsanarivi.inc
- inc/avainsanatarkista.inc
- inc/functions.inc
- tilauskasittely/keraa.php
- tilauskasittely/osoitelappu_intrade_pdf.inc
- tilauskasittely/osoitelappu_pdf.inc
- tilauskasittely/rahtikirja_dpd.inc
- tilauskasittely/toimitusvahvistus_desadv.inc
Avainsanoihin lisätty uusi laji "GS1_SSCC". Selitteeseen valitaan toimitustapa (tai kaikki) ja selitetarkiin "expansion code".
SSCC:tä käytetään normaalissa- ja intrade-osoitelapuissa, myös DPD-rahtikirjalla.
> * Kuljetusliikkeelle SSCC

- rahtikirja-tulostus.php
Postitarroille meni rahtikirjannumeroon posti JJFI koodin eteen erheellisesti tilausnumero. Tämä on nyt korjattu niin, että JJFI koodin eteen ei tilausnumeroa mene.
> Rahtikirja: korjaus rahtikirjanumeroon

- inc/functions.inc
- muutosite.php
- raportit.php
Muistiotositteilla näytetään suoraan liitetiedostojen filenimet entinsen "Näytä lasku"-linkkitekstin sijaan. Laskuilla näytetään liitteen filenimi ja selite kun hiirulainen viedään "Näytä lasku"-linkin päälle.
> Liitetiedostolinkkeihin enemmän infoa

- tilauskasittely/tilaus-valmis-siirtolista.inc
Jälkitoimituksen vapautuksen yhteydessä varastosiirrolle saattoi mennä jos suljettu lähtö tai lähtö saattoi jäädä puuttumaan kokonaan. Tämä on nyt korjattu niin, että myös näissä tapauksissa vapautuva varastosiirto saa olemassa olevan ja aktiivisen lähdön.
> Jälkitoimituksen vapauttaminen: lähdöt korjaus

- maksuaineisto_get.php
* Ei tehdä IBM-spesifistä komentoa "NAMEFMT 0" ftp-palvelimelle turhaan
> IBM-spesifinen NAMEFMT 0 -komento pois

- muuvarastopaikka.php
Varastopaikkojen muutos -ohjelmassa jos saldo + hyllyssä + myytävissä oli nolla, ei poistettavaksi merkitty tuotepaikka tullut aikaisemmin ilmi. Näytetään poistettavaksi merkitty tuotepaikka jatkossa aina.
> Poistettava tuotepaikka

- inc/functions.inc
- tilauskasittely/ostotilausten_rivien_kohdistus.inc
Tuotteen sarjanumeroseurantatyypin ollessa T ei näitä tuotteita voinut tulouttaa laisinkaan varastoon. Tämä korjattu nyt niin, että tälle sarjanumeroseurantatyypile ei välttämättä tarvitse vielä tuloutuksen yhteydessä sarjanumeroa syöttää - mutta ostotilauksen kautta se on edelleen mahdollista.
> Sarjanumeroseuranta T: tuloutuskorjaus

- monistalasku.php
Ylläpitosopimuksen monistuksessa sopimusriveille laitetiin virheellisesti monistuspäivän leima, jolloin saattoi käydä niin että rivit eivät olleet synkassa sopimuksen voimassaoloaikojen kanssa. Nyt riveillä säilytetään monistaessa alkuperäisen ylläpitosopimuksen arvot.
> Ylläpitosopimuksen monistus

- inc/pankkiyhteys_functions.inc
- pankkiyhteysadmin.php
* Käytetään 1024-bittistä salausta Nordean avaimessa, koska Nordea vaatii niin
* Ei laiteta sähköpostiosoitetta Nordean certificate requestiin, sillä se luultavasti sekoittaa tunnistuksen
> Korjauksia pankkiyhteyssertifikaatin hakuun Nordeasta

- myyntires/paperikarhu.php
Lähetetään maksukehotuskopio yhtiön parametreissa määriteltyyn maksukehotus_email-osoitteeseen. samalla kaunistellaan tiedoston nimeä lisäämällä asiakkaan nimi.
```SQL
ALTER TABLE yhtion_parametrit ADD COLUMN maksukehotus_cc_email VARCHAR(100) NOT NULL DEFAULT '' AFTER sahkopostilasku_cc_email;
> Maksukehotuskopion lähetys sähköpostilla

- tilauskasittely/monivalintalaatikot.inc
Mm. laskuhaussa ja kirjanpitoraportin monivalintalaatikoissa ei osattu näyttää kustannuspaikkoja, jos isä_tarkenne puuttui
> Monivalintalaatikot ei ymmärtänyt nullia

- inc/functions.inc
- muuvarastopaikka.php
- varastopaikka_aineistolla.php
Kun käytetään ohjelmassa alanimeä "oletuspaikka", niin näytetään käyttäjälle vaihtoehto jonka avulla oletuspaikan voi siirtää lähdepaikasta kohdepaikalle.
* Oletuspaikka-optiota käytettäessä lähdepaikan pitää olla entinen oletuspaikka, tai muuten ei tehdä koko aineistolle mitään
* Hälytysrajojen ja tilausmäärien siirto tuotepaikalla seuraa oletuspaikan vaihdossa mukana
* Tarkistetaan että ei ole mahdollista siirtää oletuspaikkaa mikäli se ei ole saman varaston sisällä
* Oletuspaikan mukana siirretään myynnit, ostot, siirrot yms. vanhalta oletuspaikalta uudelle
* Lisätty tuki rungoille (ohita keräys tuoteperhe). Siirtyy isätuotteen mukana samoilla ehdoilla.
Lisätty tarkistus jos käytetään "varaston hyllypaikka" -ominaisuutta. Tällöin kohdepaikka täytyy olla olemassa "varaston …
> Varastopaikkojen massamuutos: oletuspaikka

- raportit/myyntiseuranta.php
Otettaessa myynninseurantaraportti asiakasosastoittain tai tuoteosastoittain siirtyivät excelissä välisumma ja loppusumma sarakkeet pykälän tai kaksi liian oikealle valituista hakuehdoista riippuen. Nyt tämä oikealle siirtyminen on korjattu ja välisumma ja loppusumma tiedot tulevat oikeaan sarakkeeseen.
> Myynninseurantaraportti: excelkorjaus

- tilauskasittely/tee_jt_tilaus.inc
- tilauskasittely/tilaus-valmis-siirtolista.inc
Kun siirtolistoja vapautui useampi automaattisesti tuloutuksen yhteydessä, vain ensimmäiselle päivitettiin toimitustavan lähtö.
Tämä korjattu niin, että lähtö päivittyy kaikille siirtolistoille
> Siirtolistojen jt-rivien vapauttaminen tuloutuksen yhteydessä

- inventointi_listat.php
Inventointilistojen muodostus käytti turhaan kahta valintaa, vaikka nämä valinnat olisi jätetty tyhjiksi, joka hankaloitti mittatietoihin perustuvien keräyserien käytössä ollessa inventoitilistojen käyttöä.
> Inventointilistat: toimintaviilaus

- inc/functions.inc
- muuvarastopaikka.php
- varastopaikka_aineistolla.php
Korjattiin tilanne, missä yhtiön parametri paivita_oletuspaikka oli arvossa "Päivitetään uusi oletuspaikka avoimille ja saapumisiin liitetyille ostoriveille, myyntiriveille ja siirtoriveille". Aiemmin kävi niin, että esim keskeneräinen myyntirivi päivitettiin uudelle oletuspaikalle, mutta sen varaama saldo jäi vanhalle paikalle. 
Jatkossa koko saldo siirretään uudelle oletuspaikalle tuon parametrin option ollessa käytössä.
> Varastopaikkojen muutos aineistolla fix

- kayttajat.php
Extranet käyttäjän päivittämisessä, jos haki extranet käyttäjän suoraan käyttäjätunnuksella ei extranet käyttäjän ulkoisia tunnuksia pystynyt tällöin päivittämään. Tämä tilanne on nyt korjattu ja jatkossa extranet käyttäjän saa päivitettyä myös silloin, kun käyttäjän on hakenut suoraan extranet käyttäjän tunnuksella.
> Extranetkäyttäjän päivittäminen

- tilauskasittely/otsik.inc
Myyntitilauksen otsikolla oli ongelma käytettävien toimitustapojen vertailun kanssa mistä johtuen tuli virheellinen virheilmoitus: "VIRHE: Varaston toimipaikalla ei ole valittua toimitustapaa". Vertailu on nyt korjattu ja virheellistä virheilmoitusta ei tule.
> Myyntitilaus: toimitustapa otsikko korjaus

- raportit/matkalaskuraportti.php
Päivämäärärajauksen viimeinen päivä jäi hakuehtojen ulkopuolelle, jolloin jos esimerkiksi haki matkalaskuja 1.1 - 31.1 tuli raporttii näkyviin matkalaskut vain ajalle 1.1 - 30.1. Tämä on nyt korjattu ja jatkossa matkalaskuraportissa huomioidaan myös halutun aikavälin viimeinen päivä.
> Matkalaskuraportti: päivämäärärajaus

- inc/muutosite.inc
Ostolaskun eräpäivämäärän muuttamistarkistus tehtiin vertailemalla vääriä päivämääriä, jolloin tarkistus oli todellisuutta tiukempi. Tarkistus on nyt korjattu niin, että vertaillaan oikeita päivämääriä
> Ostolasku: erpäivän muuttaminen

- tilauskasittely/tilaus_myynti.php
Varastosiirrolla jos meni painamaan vaihda asiakasta nappia pääsi vaihtamaan varastosiirrolle oikean asiakkaan (varaston tilalle) - samalle tuli muuttaneeksi varastosiirrosta normaalin myyntitilauksen. Tämä sama ongelma oli myös sisäisillä työmääräyksillä, johon oli mahdollista liittää asiakas vaihda asiakasta toiminnolla ja muutta sisäinen työmääräys normaaliksi myyntitilaukseksi. Tämä ongelma on nyt kuitenkin korjattu.
> Varastosiirto: asiakasvaihtonappi

- inc/asiakasalennustarkista.inc
- inc/asiakashintatarkista.inc
Asiakashinnoilla ja asiakasalennuksilla kuuluu olla vai yksi asiakkaan tunniste eli vain joko asiakasnumero//asiakastunnus, ytunnus, asiakasryhmä, asiakassegmentti tai piiri. Nyt on pystynyt sisäälue dataa ohjelmalla lukemaan Pupeen sisään sellaisia asiakashintoja ja asiakasalennuksia, joilla on ollut useampia asiakkaan tunnisteita kuin yksi. Tämä on nyt korjattu ja jatkossa näin ei enää pääse tekemään.
> Sisäänlue dataa: asiakashinnat ja -alennukset

- inc/functions.inc
- inc/muutosite.inc
Vaihto-omaisuuslaskun tietojen syötössä, jos on käytössä vain osa mahdollisista ostolaskulle syötettävistä kuluista; rahti, kulut ja rivikohtaiset kulu antoi Pupe virheellisen virheilmoituksen, jos näitä kuluja ostolaskulle yritti syöttää. Tämä on nyt kuitenkin korjattu.
> Ostolasku: kulujen syöttö

- tilauskasittely/tuote_selaus_haku.php
Jos käyttäjä oli poistunut esimerkiksi varastosiirrolta niin, että kyseinen varastosiirto oli jäänyt hänelle "kesken" tilaan ja käyttäjän meni normaalin hae ja selaa ohjelmaan niin tällöin kun käyttäjä painoi "takaisin tilaukselle" nappia palautti Pupe käyttäjän myyntitilaukselle. Myyntitilauksen tunnus oli sama kuin varastosiirron, mutta varastosiirron rivejä ei ollut nähtävissä. Tässä vaiheessa käyttäjä pystyi vaihtamaan tilaukselle asiakkaan ja samalla muuttamaan varastosiirrosta myyntitilauksen. Tämä johti ongelmatilanteeseen, jossa aiemmin varastosiirrolle lisätyt rivit jäivät jumiin varaamaan saldoa.
> Hae ja selaa: Takaisin tilaukselle-nappi

- tilauskasittely/otsik.inc
Aiemmin tehtyä myyntitilausta muokattaessa jonka kerays/toimitusviikko on jo mennyt nollataan myyntitilauksen otsikolle mentäessä kerays/toimitusviikko kenttä. Tehdään tämä näin, koska muutoin myyntitilauksen kerayspäivämäärä ja toimitusaika siirtyivät seuraavalle vuodelle seuraavan valitun kerays/toimitusviikkonumeron ollessa vasta seuraavana vuonna.
> Myyntitilausotsikko: kerays/toimitusviikko

- tilauskasittely/tee_jt_tilaus.inc
Jos annettu määrä oli desimaaliluku, lukua ei ymmärretty, kun desimaalierottimena oli käytetty pilkkua.
Tämä korjattu niin, että desimaalierottimena voi käyttää joko pilkkua tai pistettä.
> Jt-selauksen toimitettava määrä

- inc/yhtion_parametrittarkista.inc
Pankkitiedostot-parametriä ei saa muuttaa, jos on laskuja poimittu maksatusta varten. Kun oli poimittuja laskuja ei yhtiön parametrejä voinut päivittää vaikka ei olisi pankkitiedostot-parametriä yritettykään päivittää. Korjattu niin, että pankkitiedostot-parametrin muutokset tarkistetaan oikein.
> Yhtiön parametrit: pankkitiedostot

- inc/muutosite.inc
Kun lasku liitettiin saapumiseen, niin että osa laskusta merkittiin rahdiksi tai kuluksi, jotka muuttivat laskun tiliöintejä, saattoi syntyä pyöristyseroja, jotka muuttivat kokonais-alv:n määrää.
Kokonais-alv pitää kuitenkin pysyä samana, ja nyt tarkistetaan, että kokonais-alv:in määrä ei muutu, vaikka osa laskusta tiliöidään rahdiksi/kuluksi
> Kulujen erottaminen saapumisen laskuilta

- inc/tiliote.inc
Kuitataan viitteellinen NOT DEFINED -tapahtuma, jos kohdistus onnistuu tapahtumalla olevalla maksuviitteellä
> Tiliote -tapahtumat

- tilauskasittely/laskuta_myyntitilirivi.inc
Myyntitilirivien ei kuulu varata varastosta saldoa, koska nehän on jo toimitettu asiakkaalle ja se, että ne ovat myyntitilillä tarkoittaa, että ne ovat jo asiakkaalla. Nyt kuitenkin, kun myyntitilirivin määrän jakoi laskutusta tai varastoon palauttamista varten laittoi Pupe uuden rivin määrän varatuksi, jonka takia tämä uusi rivi näkyi varastosiirtona tuotekyselyssä tuotteen tilauksissa ja varauksena myyntitilivarastopaikan saldolla. Tästä huolimatta rivit pystyi käsittelemään normaalisti, vaikka myyntitilirivit oudosti näkyivätkin.
> Myyntitili: tilausrivien määrän jakaminen

- tilauskasittely/luo_myyntitilausotsikko.inc
Asiakaskortilla määritelty kommentti 2 kentän sisältö ei virheellisesti tullut myyntitilauksen otsikolle, jos myyntitilaus luotiin pikatilauksena. Jatkossa myös pikatilauksessa tuo tieto siirtyy myyntitilaukselle.
> Myyntitilaus kommentti2

- inc/functions.inc
Myyntilaskuja tehtäessä, jos oli asiakkaan takana valittuna kuukauden keskimmäinen päivä ja oli ohitettu jo kuukauden keskimmäinen päivä meni laskun päivämääräksi silti aina sen kyseisen kuukauden keskimmäinen päivämäärä. Esimerkiksi jos tilaus tehdään 23.11 menisi laskun päivämääräksi aina 16.11 eikä 15.12. Nyt tämä on korjattu ja jos kuukauden keskimmäinen päivämäärä on ohitettu menee laskutuspäivämääräksi seuraavan kuukauden keskimmäinen päivämäärä.
> Myyntilaskut: laskutusviikonpäivä

- tilauskasittely/otsik.inc
Myyntitilauksen otsikolla ei pystynyt valitsemaan "ei piiriä" vaihtoehtoa, vaikka sellainen asiakkaiden takana on olemassa. Korjattu nyt niin, että myös myyntitilauksella on vaihtoehtona "ei piiriä" vaihtoehto.
> Myyntitilauksen otsikko: asiakkaan piiri

- raportit/naytatilaus.inc
Mikäli yhtiön avainsanoissa on työmääräyksen kentille valinnaisia nimiä määritelty niin käytetään näitä nimiä yleisten nimien sijaan. Nyt ollaan käytetty yleisiä nimityksiä, vaikka valinnaisia nimiä olisi yhtiön avaisanoissa ollut tarjolla.
> Työmääräyskopio: näytä ruudulla

- rajapinnat/paivita_myytavissa_static.php
* Käytetään kenttää "hinnastoon", kun rajataan tuotteita, "nakyvyys"-kentän sijaan
> Fixaus "myytavissa_static"-kentän päivitykseen

- raportit/matkallaolevat_laskuittain.php
Jos ostotilausrivi oli liitetty saapumiselle, mutta sitä ei oltu vielä viety varastoon näkyi Matkallaolevat laskuittain raportissa varastoonvientipäivämäärän kohdalla 01.01.1970. Tämä siis on virheellinen päivämäärä ja johtuu siitä, että ostotilausrivi oli vain liitetty saapumiseen, mutta ei vielä viety varastoon. Tämä on nyt korjattu ja tälläisissä tapauksissa jossa ostotilausrivi on liitetty saapumisen, mutta ei vielä viety varastoon näytetään jatkossa Matkallolevat laskuittain raportissa varastoonvientipäivämäärän kohdalla tyhjää.
> Matkallaolevat laskuittain: varastoonvientipäivä

- inc/yhtion_parametritrivi.inc
- tilauskasittely/generoi_siirtolista.php
- tilauskasittely/lisaarivi.inc
- tilauskasittely/tarkistarivi.inc
- tilauskasittely/tilauksesta_varastosiirto.inc
Varastosiirroissa huomioidaan tuotteen myyntierä, jolla pyöristetään rivi täyteen myyntierään (kuten myynnissä).
* Lisätty parametri tätä varten, uusi optio parametriin myyntiera_pyoristys ("Myyntirivin ja siirtorivin määrä pyöristetään seuraavaan täyteen myyntierään")
* Normaaleille- ja generoiduille siirtoriveille uusi optio purisi. Kirjanpidollinen- ja palautus-siirtoriveille pyöristystä ei tehdä.
> * Varastosiirto: myyntierän pyöristys

- tilauskasittely/jtselaus.php
Jälkitoimitusrivejä ei voinut aiemmin poistaa, jos oli saldo_kasittely "U" parametri käytössä (jtselauksessa tulevaisuuteen myytyjä jt-rivejä ei sallittu nähdä ollenkaan ennen kuin ne on ajallisesti toimitettavissa). Jatkossa voi, mikäli jtselauksessa ruksataan "huomioi päivämäärät jälkitilauksissa" ruksi pois päältä. Ruksi pysyy kuitenkin saldo_kasittely "U" parametrissa oletuksena aina ruksattuna.
> Jtselaus huomioi päivämäärät fix

- inc/yhtion_parametritrivi.inc
- tilauskasittely/otsik.inc
- Voidaan syöttää viitenumero käsin ylläpitosopimuksille, jos yhtiön parametri viitteen_kasinsyotto on oikeassa asennossa
- Voidaan syöttää laskun kanavointitieto käsin ylläpitosopimukselle, jos yhtiön parametri laskun_kanavointitidon_syotto on oikeassa asennossa
- Arvot kopioituvat ylläpitosopimuksesta generoiduille laskuille
> Muutoksia ylläpitosopimuksiin

- inc/pankkiyhteys_functions.inc
- Ei käytetä sys_get_temp_dir()-funktiota, koska palauttaa toimimattoman dirikan ainakin CentoOS:ssä
> Korjaus pankkiyhteyden sertifikaatin hakuun

- inc/tuotehaku.inc
Tuotetta lisättäessä myyntitilaukselle tuli aiemmin virheellisestä hausta "tuotetta ei löydy"-ilmoitus mikäli haulla ei yhtään tuotetta löytynyt. Nyt tähän oli kuitenkin tullut bugi ja ilmoitusta ei enää tullut, vaikka tuotetta ei olisi löytynytkään. Tämä on nyt korjattu ja jatkossa kun tuotetta ei löydy infromoidaan käyttäjää "tuotetta ei löydy"-ilmoituksella.
> Tuotehaku: tuotetta ei löydy- ilmoitus

- rajapinnat/edi.php
Magentotilausten kanssa, jos oli käytössä usammasta magentomaksuehdosta yhteen Pupen maksuehtoon konversio tämä ei aivan toiminut vaan käyttöön tuli aina asiakkaan oletusmaksuehto. Nyt tämä on korjattu ja jatkossa käytetään aina ennalta määriteltyjä maksuehtomuunnoksia.
> Magentotilausten sisäänluku: maksuehto korjaus

- tilauskasittely/tee_jt_tilaus.inc
Jt-tilausten vapauttamisessa ei otettu kaikkia mahdollisia tilaustyyppejä huomioon eri vaihtoehdoissa. Tätä on nyt korjattu niin, että oikeissa paikoissa otetaan tarpeelliset tilaustyypit huomioon (eg. työmääräys, ennakko jne.)
> JT-tilausten vapauttaminen

- tilauskasittely/valmista_tilaus.php
Kun valmisteella on sarjanumero, niin sarjanumeron syötön yhteydessä tehtiin uusi rivi sarjanumerolliselle tuotteelle, jota ei kuitenkaan päivitetty valmiiksi niin kuin valmistuksen muut rivit. Tästä seurasi se, että valmistetta oli myytävissä valmistuksen verran likaa. Saldo ja hyllyssä -luvut olivat oikein.
> Sarjanumerollisen tuotteen valmistus

- inc/functions.inc
- tilauskasittely/valitse_laskutettavat_tilaukset.php
- tilauskasittely/verkkolasku.php
Yhtiön parametri "Koontilaskut_alarajasumma" on pois päältä, jos siinä on arvo 0.00. Tästä huolimatta automaattisesti tapahtuvassa laskutusajossa ei voinut hyvityslaskuja laskuttaa, koska niiden summa oli alle tuon arvon. Korjattu nyt niin, että parametriä "Koontilaskut_alarajasumma" käsitellään oikein ja näin ollen myös hyvitykset saa laskutettua.
> Laskutusajo: koontilaskut_alarajasumma

- tilauskasittely/tilaus_myynti.php
Myyntitilauksen katelaskut eivät huomioineet tuotteen epäkuranttisuutta - sama virhe oli myös tuotteen keskihankitahintojen näyttämisessä. Tämä on nyt korjattu ja jatkossa epäkuranttisuus huomioidaan oikein näissä luvuissa.
> Myyntitilaus: keskihankintahinta ja kate korjaus

- raportit/abc_tuote_aputaulun_rakennus.php
ABC tuote kulutus raporttiin tarvittavaan ABC-aputaulun rakennukseen oli päässyt bugi joka esti kyseisen taulun rakentamisen. Koska taulua ei saatu rakennettua esti tämä myös koko ABC tuote kulutus raportin ajamisen.
> ABC tuote kulutus: aputaulunrakennuskorjaus

- tilauskasittely/tilaus-valmis.inc
Myyntitilausta valmiiksi laitettaessa, jos asiakkaan luottoraja ylittyi myyntitilauksen valmiiksi laitossa johti tämä ongelmaan lähdön valitsemisessa. Vaikka tämän jälkeen asiakaan luottoraja olisi muutettu tai myyntitilaukselta rivejä poistettu ja tilaus saatu laitettua valmiiksi epäonnistui lähdön valitseminen tilaukselle. Tämä on nyt korjattu ja jatkossa tähän ongelmaan ei pitäisi päätyä.
> Myyntitilaus: lähdön valitseminen

- tilauskasittely/otsik.inc
Reklamaatioiden hinnoittelusääntöjen ollessa käytössä tuli reklamaatioilla mahdollinen asiakkaan erikoisalennus huomioitua kahteen kertaan, jolloin palautuva summa oli erikoisalennuksen verran liian pieni. Muokattu nyt niin, että myös tässä tapauksessa erikoisalennus tulee huomioitua vain kertaalleen.
> Reklamaatio: erikoisalennuskorjaus

- rajapinnat/edi.php
Lasketaan alennusprosentti oikein myös silloin, kun rivin määrä on suurempi kuin yksi
> Tilausrivin alennusprosentti

- tilauskasittely/selaa_tilauksia.php
Selaa saapumisia ohjelmasta puuttui käännösominaisuus osasta otsikoista jonka takia osa otsikoista tuli aina suomeksi käyttäjän kielestä riippumatta.
> Selaa saapumisia: otsikoiden käännökset

- inc/tiliote.inc
Tiliotteella tuli kuittikoodi P, joka tarkoittaa, että pankki lähettää tapahtumasta paperikuitin.
Nyt tuo P käsitellään samalla tavalla kuin kuittikoodia olisi tyhjä, niin että tuollaisenkin tapahtuman pääsee kuittamaan
> Tiliotteella tulee kuittikoodi P

- inc/verkkolasku-in.inc
Jos toimittaja lähettää ostolaskun, jonka loppusumma on nolla, luetaan se silti pupeen
> Saapuneet verkkolaskut

- synkronoi_tuotteet_ulkoiseen_jarjestelmaan.php
Jos ulkoinen järjestelmä on "Helsingin hyllyvarasto", ei vaadita tuotteelta eankoodia
> Ulkoinen järjestelmä: tuotteiden synkronointi

- inc/functions.inc
- inc/yhtiotarkista.inc
Tuki 9 merkkiselle GS1 yritystunnukselle SSCC koodin muodostuksessa.
> GS1 SSCC yritystunnus

- tilauskasittely/tee_jt_tilaus.inc
Myyntitilaukselle on mahdollista määritellä poikkeavia nimityksiä. Nyt jos tälläisen poikkeavan nimityksen omaava tilausrivi jäi jälkitoimitukseen ei tämä poikkeava nimitys seurannut tilausrivin mukana jälkitoimitusrivin vapautuksessa. Laitettiin poikkeava nimi seuraamaan jälkitoimitusrivin vapautuksessa mukana.
> Myyntitilaus: poikkeuksellinen nimitys tilausrivillä

- inc/avainsanarivi.inc
- inc/tuoterivi.inc
- inc/tuotteen_avainsanatrivi.inc
- lue_data.php
- yllapito.php
Sallitut kielialueet määritellään yhtiön avainsanoissa. Tämän jälkeen tuotteen ylläpidossa voi valita halutun kielialueen "Sallitut maat"-kentän alasvetovalikosta. Jos alasvetovalikosta on valittuna muu kuin "Ei kielialuetta", yli ajaa tämä "Sallitut maat"-syöttökentän arvot tallennuksen yhteydessä.
Kielialueen selite on samaa muotoa kuin olemassa olevat "sallitut maat" eli maakoodeja pilkulla eroteltuna.
> * Tuotteen vientirajaukset maahryhmittäin

- rajapinnat/presta/presta_functions.php
- rajapinnat/presta/presta_products.php
- rajapinnat/presta/presta_tuote_export.php
Voidaan siirtää kaikki Pupesoftin tuotteet Prestaan ja piilottaa tuotteet verkkokaupassa, joita ei haluta näyttää. Huom, siirtää myös poistetut tuotteet.
Tuote piilotetaan verkkokaupassa jos nakyvyys -kenttä on tyhjää, tai tuote on poistettu ja sillä ei ole saldoa.
> Presta tuotteen näkyvyys

- tilauskasittely/osoitelappu_intrade_pdf.inc
Toimituspvm otsikko ja arvo viilaus. 
Nyt tilauksen toimitusaika näytetään oikein intrade osoitelapussa (jos se on pienempi kuin tänään, niin laitetaan tämä päivä toimituspäiväksi. Lisäksi tekstiä viilattu niin, että toimituspvm sijaan tulee toimituspvm myymälään.
> Osoitelappu intrade toimituspvm muutos

- generoi_tuotepaikkoja.php
Generoi tuoteppaikkoja ohjelma perusti tuotepaikkoja vailinaisilla tiedoilla, mikä teki uusista tuotepaikoista rikkinäisiä. Niitä ei näkynyt missää eikä niitä voinut siis käyttää. Tämän lisäksi tuotepaikkojen automaattigenerointiohjelma perusti tuotepaikan myyntitilivarastoon mikäli sellainen löytyi - tätä ei kuuluisi tehdä sillä myyntitilivarastossa kuuluu olla pelkästään asiakaskohtaisia tuotepaikkoja. Molemmat ongelmat on nyt korjattu ja jatkossa generoi tuotepaikkoja osaa perustaa tuotepaikat oikein.
> Generoi tuotepaikkoja: korjaus

- tilauskasittely/syotarivi_ostotilaus.inc
Ostotilauksella oli kaksi määrä kenttää uuden rivin syöttössä. Toista kenttä ei pystynyt muokkaamaan ja toinen kenttä oli sellainen, että siihen pystyi syöttämään arvoja. Poistettiin tämä toinen ylimääräinen määrä kenttä.
> Ostotilaus: uuden rivin kentät

- rajapinnat/presta/presta_functions.php
- rajapinnat/presta/presta_product_stocks.php
- rajapinnat/presta/presta_products.php
- rajapinnat/presta/presta_specific_prices.php
* Saldottomien tuotteiden saldoksi null
* Pyöristetään saldot alaspäin, Presta ei tue desimaalilukuja saldoissa
* Sallitaan vaan numeeriset EAN koodit
* Jos nimi on tyhjää, laitetaan "-", koska nimi on pakollinen
* Merkataan tuntemattomat valuutat "all"
* Ohitetaan asiakashinnat, jos hinnalla ei ole valuuttaa
> Presta yhteensopivuus

- maksusopimus_laskutukseen.php
Sallitaan negatiiviset rivit ennakkolaskulla. Ennakkolaskun tulee kuitenkin olla yhteensä positiivinen.
Aikaisemmin ennakkolaskulla ei osattu piirtää negatiivisia rivejä, ja ennakkolaskun summa jyvitettiin tasaisesti positiivisille riveille. Jatkossa osataan näyttää myös negatiiviset rivit.
> Ennakkolaskulle miinus rivi

- tilauskasittely/tulosta_lahete.inc
Automaattinen kielivalinta saatettiin joissain tilanteissa tehdä ytunnuksen perusteella. Tämä saattoi aiheuttaa ongelmia, mikäli samalla ytunnuksella oli eri asiakkuuksia perustettuna, joille oli määriteltynä eri kielet. Tällöin lähete ei välttämättä tulostunut lähetteen asiakkuuden kielellä vaan jollain jonkin toisen saman ytunnuksen asiakkuuden kielellä.
> Lähete: automaattinen kielivalinta

- inc/unifaun_send.inc
Tarkistetaan ennen Unifaun aineiston lähetystä onko Pupesoft UTF8 muodossa. Jos on, niin lähetetään Unifaunin aineistokin UTF8 muodossa. Aikaisemmin lähti ISO:na.
> Unifaun unicode check

- tilauskasittely/tulosta_lasku.inc
- Piilotetaan toimituspvm sekä tilausnumerot myös otsikkotasolla käytettäessä tyyppi 6 laskupohjaa ("ei näytetä tilausnumeroa/toimitusaikaa")
> Laskupohjamuutokset

- tilauskasittely/otsik.inc
- Voidaan tehdä ylläpitosopimuksia ilman eräpäivän käsinsyöttöa sallivaa maksuehtoa, mikäli toistuvaa eräpäivämäärää ei syötetä
> Ylläpitosopimusten toistuva eräpäiväfix

- tilauskasittely/ostotilausrivien_hallinta.php
Avoimet ostorivit ohjelmassa rivikohtaisia toimitusaikoja syötettäessä Pupe käsitteli hassusti pp.kk.vvvv muodossa syötettyjä päivämääriä ja muutti ne kummalisiksi. Tämä on nyt korjattu ja jatkossa päivämääriä voi syöttää myös muodossa pp.kk.vvvv.
> Avoimet ostorivit: toimitusajan muuttaminen riveille

- inc/functions.inc
Luettaessa seurantakoodeja ulkoisesta järjestelmästä saatettiin laskutettu lasku päivittää samalla virheellissesti aiempaan tilaan. Nyt tehdään tarkistus, että lasku ei ole laskutettu ja muutetaan vain laskuttamattomien laskujen tilaa.
> Seurantakoodi ulkoisesta järjestelmästä: laskutetu tarkistus

- intrastat.php
Intrastat ilmoituksessa näytettään päänäkymässä aina aakkosissa viimeinen tuotenumero. Tämän lisäksi tässä näkymässä näytettiin aakkosissa viimeinen tuotenimitys. Tässä ei osattu ottaa huomioon sitä, että tämä tuotenumero - tuotenimitys - pari ei välttämättä täsmääkkään. Korjattu nyt niin, että katsotaan päänäkymään tuotenumeroa vastaava nimitys.
> Intrastatilmoitus: tuotenimitykset

- tilauskasittely/tulosta_lahete_kerayslista.inc
Reklamaatioiden purkulistojen tulostuksessa saattoi tulla ongelmia rivien tulostuksen kanssa mikäli tilausrivit sattuivat olemaan tietyn korkuisia. Nyt tämä on korjattu niin, että kaikki rivit pitäisi tulla hyvin näkyviin.
Tämän lisäksi Reklamaatio/Purkulista otsikko oli hieman vinossa, jonka takia se ei näkynyt kokonaa, joten otsikkoa siirrettiin hieman.
> Reklamaatiot: purkulistakorjaus

- inc/tuotetarkista.inc
- synkronoi_tuotteet_ulkoiseen_jarjestelmaan.php
Sanomalle menevä status riippuu nyt tuotteen statuksesta. Sanoman tyyppi on U jos uusi tuote, ja M jos aiemmin synkronoitu.
Jos tuotteen  eankoodia, yksikköä, nimitystä, tuoteryhmää, massaa tai statusta muuttaa, tyhjennetään mahdollinen tuotteen synkronointi-avainsana, jotta seuraavalla synkronointikerralla tuote menisi aineiston mukana.
> Synkronoi tuotteet ulkoiseen järjestelmään: status

- tilauskasittely/otsik.inc
Ennakkotilauksien kohdalla osatoimituskielto-ominaisuutta ei ole olemassa. Tästä huolimatta ennakkotilauksien otsikolla on ollut valittavissa osatoimituskielto-täppä. Nyt osatoimituskielto täppä on otettu kokonaan ennakkotilauksilta pois hämäämästä.
> Ennakkotilaukset: osatoimitustäppä

- inc/tuotehaku.inc
- inc/yhtion_parametritrivi.inc
Poistuvat tuotteet -parametri on herätetty henkiin ja nyt se puree tuotekyselyyn vain jos hakutuloksia on monta ja piirretään tästä johtuen pudotusvalikko. Pudotusvalikossa ei näytetä poistuvia, poistettuja, saldottomia tai varastoimattomia tuotteita.
> Poistuvat tuotteet parametri & tuotekysely

- rahtikirja.php
- tilauskasittely/rahtikirja_erittely_pdf.inc
- tilauskasittely/tulosta_dgd.inc
- Käytetään rahtikirjaerittelyssä sekä dgd:llä ensisijaisesti toimitustavan takaa löytyviä osoitetietoja, mikäli sellaiset on asetettu
> Koontilähetysfix

- budjetinyllapito.php
- raportit/tuloslaskelma.php
Taseessa tasojen nimet menivät sekaisin ja sinne tuli vääriä nimiä. Korjattu niin, että näkyviin tulevat oikeat nimet.
> Tase/tuloslaskelma: tasonimikorjaus

- db_sql_query.php
SQL-hakugeneraattorissa, jos valitsi tuote taulun ja haettavaksi myös tuotteen parametrejä. Sitten tuotteen parametreissä valitsi haettavaksi tuotteen lisätietoja. Tällöin ei exceliin kuitenkaan tullut valitttuja lisätietoja vaikka kyseisiä tietoja olisi tuotteelle ollutkin syötettynä. Lisäksi haun suorittamisen jälkeen valikoituivat kaikki tuotteen lisätiedot ruksatuiksi. Korjattu nyt niin, että tuotteen lisätiedot tulevat exceliin ja valikoituina pysyvät vain ne kohdat, jotka haussa oikeasti olivat valittuina.
> SQL-hakugeneraattori: tuotteen lisätietojen korjaus

- inc/functions.inc
- tilauskasittely/osoitelappu_intrade_pdf.inc
Intrade osoitelapun SSCC koodissa tuli ylimääräinen nolla yrityksen tunnuksen eteen, jos yrityksen tunnus on kuuden merkin mittainen. Korjattu niin, että ylimääräinen nolla tulee yrityksen tunnisteen loppuun.
> Osoitelapun SSCC-koodi 

- tilauskasittely/lisaarivi.inc
- tilauskasittely/tarkistarivi.inc
Jos on vastaavat taulukko myynnissä auki ja automaattinen varastosiirto myynnistä päällä, saattoi aikaisemmin käydä niin että rivi meni varastosiirroksi automaattisesti kun vastaavat taulusta vaihdettiin tilauksen tuote, mikäli tilaus oli jo aikaisemmin laitettu valmiiksi. Enää näin ei tapahdu.
> Myynnistä varastosiirto fix

- inc/tilaa_ajax.inc
Korjattu tilanne jossa tilausriville meni virheellinen tuotenumero jos tuotenumerossa oli Ä tai Ö -kirjaimia
> Ostoehdotus CS: Tuotenro & ääkköset

- tilauskasittely/tulosta_lasku.inc
Ennakkolaskulle tehty ominaisuus tuotenumeron näyttämisestä koski virheellisesti myös tavallisia laskuja, mikäli yritys käytti tuota tiettyä ennakkolaskun ominaisuutta (ennakkolaskun_tyyppi parametrin alin vaihtoehto). Virhetilanne korjattu ja enää ei tehdä tavallisille laskuille tuota samaa käsittelyä.
> Ennakkolasku tuoteno fix

- crm/asiakasmemo.php
- crm/kalenteri.php
Esim. Edustajaraportti ei osaa hakea kuin suomenkieliset tapahtumat, joten tallennetaan tapahtumatapa aina suomeksi kantaan
> Kalenterintapahtumatapa tallennetaan aina suomeksi

- raportit/ostoehdotus_cs.php
Lisätty valintaruutu "Ei huomioida vuosikulutusta" jonka avulla käytetään laskennassa nollaa vuosikulutuksen sijaan.
> Ostoehdotus CS: Ei huomioida vuosikulutusta

- tilauskasittely/tilausvahvistus-email.inc
Teksti-tyypisessä sähköpostiin lähetettävässä tilausvahvistuksessa pitkä nimitys jaetaan kahdelle riville. 
Nimityksen loppuosa tulostui virheellisesti seuraavillekin riveille, jos niiden nimitystä ei tarvnnut jakaa kahdelle riville. Tämä on nyt korjattu.
> Näytetään nimityksen loppu vain oikeassa paikassa

- tilauskasittely/tilauksesta_myyntitilaus.inc
Mikäli tarjouksen päivämäärät olivat menneisyydessä muutettiin otsikon päivämäärät tälle päivälle, mutta rivien päivämäärät jäivät menneisyyteen. Ristiriita aiheutti sen, että rivien päivämäärät eivät olleet enää päivitettävissä myyntitilauksella.
Korjattu nyt niin, että myös rivien päivämäärät päivitetään tälle päivälle mikäli ne ovat olleet menneisyydessä tarjouksen hyväksymishetkellä.
> Tarjous: keräyspäivämäärä ja toimitusaika

- tilauskasittely/keikka.php
Saapumiset ohjelmassa, kun haettiin saapumisia joille ei ole vielä liitetty laskua niin näkymässä ei tullut mukaan niitä toimittajia, joilla oli sekä saapumisia joilla on laskuja ja saapumisia joilla ei ole laskuja. Nyt tämä on korjattu niin, että mukaan tulevat myös ne toimittajat joilla on kaikenlaisia saapumisia haettaessa saapumisia joihin ei ole liitetty laskua.
> Saapumiset: saapumiset joilla ei ole laskua

- inc/functions.inc
Myynninseurantaraportissa, jos teki tallennetun haun niin että oli laittanut rajauksen ytunnuksen mukaan. Kun tälläisen tallennetun raportin myöhemmin ajoi uudestaan niin ajo ei toiminut vaan rajaukset katosivat kesken ajon. Nyt tämä on korjattu ja jatkossa myös ytunnuksen mukaan tehtyjen hakujen rajaukset jäävät talteen ja toimivat tallennetun haun ajossa.
> Myynninseuranta: tallennetun kyselyn ajaminen

- raportit/ostoehdotus_cs.php
Ostoehdotusraportti toi tilaustuotteita ostoehdotukseen, vaikka näillä tuotteilla olisi ollut saldo + ostossa olevat määrät yhtä suuri kuin myyntitilauksilla oleva määrä. Korjattu nyt niin, että tälläisissä tilanteissa tilaustuotteet eivät ostoehdotusraportille tule.
> Ostoehdotusraportti: ei varastoitavat tuotteet

- rahtikirja-tulostus.php
- tilauskasittely/rahtikirja_pdf.inc
- tilauskasittely/tulosta_dgd.inc
* Tulostetaan koontirahtikirjalle vastaanottajan tiedot toimitustavan takaa
* Käsitellään myös Koonti-erätulostus tulostustapa koontina DGD-lomakkeen tulostuksessa, jolloin consigneen tiedot haetaan toimitustavan takaa.
* Fixataan bugi, joka estää osoitelappujen tulostuksen koontirahtikirjan tulostuksen yhteydessä.
* Ei tulosteta Hornbach-tyyppisiä osoitelappuja, jos ollaan tulostamassa koontirahtikirjaa
> Korjaus koontiosoitelappuun

- inc/verkkolasku-in-finvoice.inc
Ei lueta Finvoicen summarivejä mukaan loppusummaan.
http://www.finanssiala.fi/finvoice/dokumentit/Finvoice_2_1_soveltamisohje.pdf:
> 12 SubInvoiceRow
> SubInvoiceRow- kooste-elementti on tarkoitettu laskuriveistä muodostettujen yhteenvetorivien esittämiseen. Finvoice-sanomina välitettävistä laskuista ei muodosteta koontilaskuja. SubInvoice-Row:n avulla voidaan helpottaa laskun tarkastamiskäsittelyä laskun visualisoinnin yhteydessä.
> SubRowAmount-elementtiin tulee edeltävien RowAmount-elementtien yhteenlaskettu summa. Sanoman layoutissa (XSL) rivit tulostuvat tummennettuna tekstinä.
> Laskun loppusummien ja alv-yhteenvetojen laskemiseen käytetään InvoiceRow- kooste- elementin tietoja. SubRow-elementtien tietoja ei käytetä laskun loppusumman laskentaan, koska siitä saattaa aiheutua …
> Korjaus Finvoicen sisäänlukuun

- inc/functions.inc
Laitetaan Postnordiin lähtevän keräyssanoman TransportAccount-kentän arvoksi avainsanoissa määritelty TOIM_TAPA_TA ainoastaan, jos tilauksen ohjelma_moduli on MAGENTO.
> Korjaus Postnordiin lähtevään keräyssanomaan

- tuotannonsuunnittelu.php
- valmistuslinjat.inc
- valmistuslinjat_json.php
- valmistuslinjojen_tyojonot.php
* Sortataan valmistuslinjat numerojärjestyksessä
* Näytetään kokonaiskesto tuotannon suunnittelun taulukon lopussa
* Näytetään valmistuslinjojen työjonoissa 8 valmistusta 4:n sijaan
> Parannuksia tuotannon suunnitteluun

- monistalasku.php
Monista lasku ohjelma kopioi automaattisesti verkkotunnuksen suoraan monistettavalta laskulta. Nyt uusi yhtiön parametri, jolla voidaan säätää kopioidaanko verkkotunnus asiakkaan takaa vai monistettavalta laskulta monistusta tehtäessä.
> Monista lasku: verkkotunnus

- monistalasku.php
Käytetään laskun monistuksessa oletuksena asiakkaan nykyistä verkkolaskutustunnusta. Vaihtoehtoinen täppä laskun monistuksessa, jolla saa monistettua laskun alkuperäisen laskun tunnukselle.
> Monista lasku: verkkolaskutustunnus

- inc/functions.inc
- tilauskasittely/lisaarivi.inc
- tilauskasittely/tilaus_myynti.php
Käänteiset ALVit meni solmuun jos tuotteella oli oletuksena ALV = K.V. 
Käänteiset ALVit meni solmuun myös kun käyttöliittymästä vaihtoi tilauksen alvioletusta ja muokkasi rivejä.
> Käänteinen ALV

- rahtikirja_custom.php
Tulostimien esivalinnan tuki korjattu rahtikirjan syötössä. Osaa nyt esivalita "PDF ruudulle" ja myös osoitelapun tulostimen.
> Tyhjä rahtikirja: tulostimien esivalinta

- tuote.php
Tuotekyselyssä tuotteen tilaukset kohdassa tulivat näkyviin myös vastaanotetut siirtolista. Korjattu nyt niin, että vastaanotetut siirtolistat eivät tässä näkymässä näy.
> Tuotekysely: vastaanotettujen siirtolistojen näkyminen

- tilauskasittely/tilaus_myynti.php
Osatoimitusten tapauksessa, mikäli eri osatoimitusotsikoilla oli eri kerattypvm & toimajat saattoi käydä niin, että kun tilausrivejä siirrettiin otsikolta toiselle kävi niin ettei tilausrivi kerattypvm ja/tai toimaika enää otsikon tietoja vastannut. Tämä eroavaisuus aiheuttaa se ettei otsikkoon tehtävät muutokset vaikuta enää tämän rivin tietoihin. Korjattu nyt niin, että kerattypvm ja toimaika päivitetään siirrettäville tilausriveille siirron yhteydessä vastaamaan uuden otsikon tietoja.
> Myyntitilaus: osatoimitukset

- tilauskasittely/otsik.inc
Tarjouksille voi valita näytetäänkö toimitusaikaa vai ei. Toimitusajan tarjoukselta piilottaminen saattoi välillä saada tilausriveille tallennettavan toimitusajan eroamaan tilauksen otsikon toimitusajasta. Tämä aiheutti sen ettei tilausrivien toimitusaikaa saanut enää muutettua. Nyt korjattun niin, ettei tälläistä eroa pääsee enää tapahtumaan.
> Tarjous: toimitusaika

- tilauskasittely/tilaus_myynti.php
Extranetissä näytettiin maksusuunnitelma-nappi ja "tilauksella ei ole maksusopimusta"-virheilmoitus, mikäli extranet käyttäjään liitetyllä asiakkaalla oli oletuksena maksusopimuksellinen maksuehto. Nyt korjattu niin, ettei näitä tule näkyviin, mikäli kyseessä on extranetkäyttäjä.
> Extranet: maksusopimustekstit

- inc/functions.inc
- tilauskasittely/tulosta_lahete.inc
Tilausvahvistuksen tilaustuotteiden toimitusaikoja koskevat tiedot menivät aina oletuksena käyttäjän kielelle, jolloin nämä tekstit saattoivat olla eri kielellä kuin koko muu tilausvahvistus. Korjattu niin, että myös nämä tekstit menevät samalla kielellä kuin muu tilausvahvistus.
> Tilausvahvistus: toimitusaikakommentit oikealle kielelle

- tilauskasittely/tilaus_myynti.php
Jälkitoimitusrivien vapauttamisessa suoraan myyntitilauksille ei huomioitu ollenkaan myyntitilauksen tilaa vaan jälkitoimitusrivejä vapautettiin myös esimerkiksi toimitettu-tilassa oleville tilauksille. Korjattu nyt niin, että jälkitoimitusrivejä vapautetaan vain kesken tai tulostujononssa oleville myyntitilauksille - eli tilauksille jota ei ole vielä käsitelty liian pitkälle eteenpäin.
> Jälkitoimitukset: jälkitoimitusten vapauttaminen myyntitilaukselle

- tuote.php
Tuotekyselyssä tuotteen tilaukset kohdassa tulivat näkyviin vastaanotettujen varastosiirtojen puuterivit. Korjattu nyt niin, että vastaanotettujen varastosiirtojen puuterivit eivät tuotteen tilaukset kohdassa näy.
> Tuotekysely: tuotteen tilaukset - puuterivit

- mobiili/vahvista_kerayspaikka.php
Mobiilin varastoonviennissä oli erittäin pieni mahdollisuus, että laitteen jumittuessa saattoi olla mahdollista viedä sama rivi kahteen kertaan varastoon. Nyt mobiilin varastonvietiin-ohjelmaan on lisätty lukkoja, jotka estävät tämän tuplavarastoonviennin mahdollisuuden.
> Mobiili: vie varastoon

- tuote.php
Mikäli käytössä oli suppeampi toimipaikkakäsittely, mutta käyttäjän ja varastojen takana oli toimipaikkoja määriteltynä saattoi tuotekyselyssä tuotteen tapahtumat kohdassa tulla näkyviin erikoisia lukuja juoksevassa saldossa. Korjattu nyt niin, että saldot lasketaan oikein määritellyistä toimipaikoista huolimatta.
> Tuotekysely: tuotteen tapahtumien juokseva saldo

- raportit/myyntitilasto_gauge.php
Myyntitilastoraportissa kun pystyy porautumaan kustannuspaikkojen riveihin tarkemmin ei tämä porautuminen toiminut mikäli kustannuspaikan nimessä oli erikoismerkkejä. Korjattu nyt niin, että toimii myös erikoismerkillisten kustannuspaikkojen tapauksessa.
> Myyntitilasto: kustannuspaikkojen tiedot

- tilauskasittely/syotarivi_ostotilaus.inc
- tilauskasittely/tilaus_osto.php
Ostotilausrivin muokkaamisen yhteydessä päivitettiin rivin luontiaika. Tämä aiheutti ongelmia muun muassa tuotekyselyssä, jossa tuotteen tilaukset kohdassa käytetään ostotilausrivien luontiaikaa. Korjattu nyt niin, että ostotilausrivin muokkaamisesta huolimatta ei rivin luontiaikaa päivitettäisi.
> Ostotilaus: rivien paivittaminen

- iltasiivo.php
- muuvarastopaikka.php
Tuotepaikkojen poistamisessa oli kaksi tilannetta, joissa sai käytössä olevan tuotepaikan poistettua. Nämä molemmat tilanteet on nyt korjattu niin, ettei poistaminen tälläisessä tapauksessa onnistu heti.
- Tuotepaikka oli käsittelemättömänä inventointilistalla
- Tuotepaikalla oli avoimia jälkitoimitusrivejä
> Tuotepaikkojen muutos: varastopaikan poistaminen

- tilauskasittely/jalkilaskenta.inc
Jälkilaskenta osasi korjata kerrallaam vain yhden myyntilaskun, jonka kate muuttui.
Nyt voidaan korjata yhdellä kaikkien tarvittavien myyntilaskujen kattenn kohdalleen
> Jälkilaskennan myyntilaskujen korjaus

- inc/functions.inc
LogMasterissa tuotekoodi max 22 merkkiä (tai 25 mutta kolme tarvitaan sisäiseen käyttöön).
> LogMaster max 22 merkkiä

- inc/muutosite.inc
- inc/pankkitiedot.inc
- inc/toimitarkista.inc
- ulask.php
Perustettaessa ostolasku ilman toimittajatietoja sai laskun perustettua ilman swift-koodia. Nyt on muutettu niin, että mikäli IBAN muotoisen tilinumero ilman swift-koodia syöttää, niin osataan swift koodia muodostaa automaattisesti. 
Päivitetty samalla swift-koodit ajantasaisiksi (rahalaitostunnus 36 on S-pankki eli swift SBANFIHH).
> Ostolaskun perustus & swift-koodit

- inc/functions.inc
Itella EDI: EIH-1.4 sähköinen lasku -verkkolasku voidaan jatkossa lähettää myös EU-alueen asiakkaalle kotimaisten lisäksi.
> Sallitaan EIH-1.4.0 verkkolasku EU maihin.

- tilauskasittely/lisaarivi.inc
Merkitään yksittäinen hyvitysrivi kerätyksi myyntitilauksella niin, että päivitetään myös keratty-tieto.
Jos näin ei tehdä ja maksusopimus-tilauksella on yksittäinen hyvitysrivi, loppulaskutus ei onnistunut, vaikka muut rivit olisi merkitty toimitetuksi
> Yksittäinen hyvitysrivi myyntitilauksella

- inc/toimitustapatarkista.inc
Toimitustavan nimen vaihtaminen ei päivittänyt uutta nimeä kaikissa tiloissa oleville tilauksille tai siirtolistoille. Korjattu nyt niin, että kaikkien paitsi laskutettujen tilausten kohdalla ja kaikkien paitsi vastaanotettujen siirtolistojen kohdalla päivitetään toimitustavan nimi.
> Toimitustavat: nimen vaihtaminen

- tilauskasittely/tilaus_myynti.php
HUOM: Luottoraja ylittynyt teksti saattoi tulla myyntitilaukselle, vaikka luottoraja ei olisi ollut edes käytössä asiakkaalla. Tämä on nyt korjattu ja teksti ei tule enää virheellisesti näkyviin.
> Myyntitilaus: luottoraja ylittynyt-teksti

- tilauskasittely/verkkolasku_finvoice_201.inc
Finvoice 2.01 -versioon lisätty rivi, jossa SellersBuyerIdentifier-kenttään viedään asiakkaan tilausnumero
> Asiakkaan tilausnro myös SellersBuyerIdentifier-kenttään

- extranet/extranet_siirto.sh
- rajapinnat/logmaster/logmaster-functions.php
- rajapinnat/logmaster/outbound_delivery.php
- rajapinnat/logmaster/resend_logmaster.php
- rajapinnat/logmaster/stock_report.php
- rajapinnat/logmaster/tracking_code.php
- tilauskasittely/lahetteen_tulostusjono.php
- tilauskasittely/tarkistarivi.inc
- tilauskasittely/tilaus_myynti.php
- "Logmaster-functions"-tiedosto siirretään myös extranettiin
- Näytetään "Tulosta keräyslista"-näkymässä kenellä ulkoisen varaston tilaus on kesken
- Stock report käyttää nyt logmaster_field-funktiota
- Tracking code -ohjelmaa muutettu niin että päivitetään yhden rahtikirjan seurantakoodit kerralla
- Korjattu "Tulosta keräyslista"-taulukon yhteensä-rivi
- Lähtevän sanoman uudelleen lähetys päivittää aikaleiman jos sitä ei ole asetettu
- Ulkoisen järjestelmän tilauksella:
- Maksuehto ei saa olla jälkivaatimus
- Ei saa sisältää sarjanumeroseurannassa olevia tuotteita
- Rivien kappalemäärät täytyy olla kokonaislukuja
> Logmaster: QoL muutoksia

- crm/asiakasmemo.php
- rahtikirja_custom.php
- raportit/asiakkaantilaukset.php
- tilauskasittely/rahtikirja_pdf.inc
- tilauskasittely/tilaus_myynti.php
- Tilaus-myynti näyttää nyt tilausrivin yksikön tuote yksikön sijaan.
- Asiakasmemon lisättyjen memomerkintöjen liitetiedoston esitystapaa korjattu.
- Asiakkaan tilaukset "Vaihda asiakas"- ja "Tee uusi haku"-nappi korjattu. Antaa jatkossa tehdä uuden haun, mutta päävalikosta tultaessa ohjelmaan muistaa vielä kesken olevan myyntitilauksen asiakkuuden.
- Tyhjän rahtikirjan "Lähettäjän viite" ja "Vastaanottajan viite" kentät osataan näyttää PDF:llä
> QoL: Bugikorjauksia

- tilauskasittely/tulosta_hintalaput.inc
- tulosta_tuotetarrat.php
* Voidaan valita koko hintalapulle. Tällä hetkellä tuettuja koko ovat 49 x 30 mm & 62 x 29 mm.
* Tuetaan EAN-koodia viivakoodissa
> * Hintalappujen tulostus (6.2x2.9cm)

- rahtikirja.php
Rahtikirjan tietojen syötössä pystyi jättämään kollimäärä kohdan tyhjäksi. Tämä aiheutti ongelmia rahtikirjan muokkauksessa ja rahtikirjan heti-tulostuksessa. Korjattu nyt niin, että rahtikirjan tietojen syötössä on kollimäärä syötettävä tai kilot /-syntaksilla.
> Rahtikirjat: kollimäärät

- muuvarastopaikka.php
Varattujen siirto ominaisuus toimimaan vain käyttöliittymästä. Tätä samaa ohjelmaa käytetään myös muualta, mutta varattuja tilauksia tulee voida siirtää paikalta toiselle vain silloin kun ohjelmaa käytetään suoraan.
> Varastopaikkojen muutos: varattujen siirron korjaus

- tyomaarays/tyojono.php
Jos työmääräyksellä oleville avainsanoille teki kieliversioita, näytettiin työmääräys työjonossa jokaisella määritellyllä kielellä. Tämä on nyt korjattu, ja näytetään työmääräys vain kerran.
> Näytetään työmääräys vain kerran työjonossa

- aloita_synkronointi.php
- inc/functions.inc
Korjattu virheet ja lisätty ohitettavia sarakkeita. Myyntiihinnoille tehdään valuuttakonversio jos lähde- ja kohdevaluutat ovat eri.
Tuotetta päivitettäessä ei kosketa seuraaviin kenttiin:
sarjanumeroseuranta
tuotetyyppi
ei_saldoa
> Tuotesynkronointi

- tilauskasittely/sarjanumeroseuranta.php
Myyntitilaukselta, jos lisäsi sarjanumeroita ja meni sitten linkkin kautta katsomaan ostoja tai myyntejä niin sarjanumeroille takaisin palaaminen aiheutti virhetilanteen. Ongelma on nyt korjattu ja takaisin sarjanumeroille vievä linkki toimii taas.
> Sarjanumerot: linkki takaisin

- inc/tiliote.inc
Tiliotteella saattoi olla saajan nimessä useita välilyöntejä, jotka ruudulle tulivat näkymään kuitenkin yksinä välilyönteinä. Ja jos Pupeen oli toimittajan nimi perustettu yksillä välilyönneillä ei näitä kahta nimeä osattu yhdistää toisiinsa. Ostosuoritusten kohdistukseen on nyt lisätty uusia hakuja, joissa siivotaan moninkertaiset välilyönnit pois ja korvataan ne yhdellä välilyönnillä, jotta voidaan paremmin tarkistaa löytyykö Pupesta ostosuoritukseen liittyvä lasku.
> Tiliotteen sisäänluku: ostosuoritusten kohdistus

- peru_valmistus.php
Peru valmistus-ohjelmassa, jos unohti laittaa ruksin kohtaan "Peru tuotteen valmistus" ja perui valmistuksen, niin siirsi Pupe valmistuksen otsikon takaisin Valmistus kerätty-tilaan, mutta valmistuksen rivit jäivät valmistettu-tilaan. Näin ollen valmistus siis hajosi ja jäi jumiin. Tämä on nyt korjattu ja Peru valmistus-ohjelma ei tee mitään, mikäli käyttäjä kyseisen kohdan unohtaa ruksittaa.
> Peru valmistus: korjaus

- valmistatuotteita.inc
Kun yhtiön parametri Automaattinen_jt_toimitus_valmistus on sellaisessa asennossa, että jälkitoimitusrivit on määritelty toimitettavaksi vain, jos kysessä on suoraan asiakkaalle valmistus niin saattoi siitä huolimatta jälkitoimitusrivejä vapautua myös normaalien valmistusten yhteydessä. Korjattu niin, että parametrin asennot toimisivat niin kuin niissä lukee.
> Jälkitoimitusrivien automaattinen vapautus: valmistukset

- muokkaatilaus.php
Tulostusjonossa olevat extranet tilaukset eivät näkyneet avoimet tilaukset näkymässä, sillä siitä rajattiin kaikki extranet tilaukset kokonaan pois. Muutettu tätä nyt niin, että tulostusjonossa olevat extranet tilausket Avoimet tilaukset näkymässä näytetään.
> Avoimet tilaukset: extranet tilaukset

- tilauskasittely/lisaarivi.inc
Mikäli yhtiön parametreissä Alv_kasittely_hintamuunnos-parametrillä oli mahdollistettu hintojen syöttäminen verollisena/verottomana sen sijaan, että hinnat syötettäisiin saman kaavan mukaan kuin millä hinnat on tallennettuna Pupeen saattoi tilausrivin hinnassa olla pyöristysero syötettyyn hintaan nähden. Tämä on nyt korjattu ja syötetyt hinnat tallennetaan tarkemmin mahdollisimman tarkan lopputuloksen aikaansaamiseksi.
> Myyntitilaus: hinnan syöttäminen

- tilauskasittely/otsik.inc
Myyntitilauksen otsikolta, jos meni Muuta asiakasta-linkin kautta katselemaan ja muokkaamaan asiakkaan tietoja, niin kun palasi takaisin myyntitilaukselle saattoi myyntitilaus tietyissä tapauksissa mennä takaisin tulostusjonoon ja päivittyä väärään tilaan. Korjattu nyt niin, että myyntitilauksen alkuperäinen tila säilyy.
> Myyntitilaus: muuta asiakasta-painike otsikolla

- tilauskasittely/yllapitosopimukset.php
Yritettäessä laskuttaa ylläpitosopimusta, jonka asiakas on myyntikiellossa teki Pupe oikein uuden myyntitilauksen ja jätti sen Myyntitilaus kesken-tilaan. Erheellisesti uuden myyntitilauksen luontipäivämääräksi jäi ylläpitosopimuksen luontipäivämäärä eikä tullut ylläpitosopimuksen kauden päivämäärää. Tämän takia, kun poisti myyntikiellon ja laskutti myyntitilauksen niin se meni väärälle päivälle ja näytti siltä että kyseistä kautta ei olisi vielä laskutettu ja sen pääsi laskuttamaan uudestaan. Korjattu nyt niin, että päivämäärä menee oikein.
> Ylläpitosopimukset: sopimusten laskutus

- tilauskasittely/lahetteen_tulostusjono.php
Käytetään implisiittistä flushausta, sillä flushaus kesken kaiken hajottaa skriptin joillain selaimilla.
> Poistetaan ob_end_flush

- inc/valitse_tulostin.inc
- tilauskasittely/tulosta_ostotilaus.inc
Voidaan tulostaa ostotilauksen PDF:lle asiakkaiden nimet tuotekohtaisesti, joilla on avoimia myyntitilauksia.
Asiakkaiden nimet haettaisiin kaikilta avoimilta myyntitilauksilta, joilla ko. tuotetta. Avoimilla myyntitilauksilla tarkoitetaan tulostusjonossa olevia ja niitä, joiden keräyslista tulostettu, mutta ei kerätty. Kesken olevia myyntitilauksia ei huomioida.
Tämä on tehty niin että ostotilauksen tulostukseen on lisätty valintaruksi "Tulosta myös asiakkaiden nimet". Tämä ominaisuus tulee tuoteriville rivikommenttiin lisättynä mahdollisten muiden rivikommenttien lisäksi.
> Ostotilaus PDF: asiakkaiden nimet

- tilauskasittely/tilaus_myynti.php
Vaikka ulkoista varastoa ei ollut käytössä saattoivat tilaukset silti mennä ulkoisen varaston muokkauslukkoon. Korjattu nyt niin, että tilaukset eivät tästä syystä muokkauslukkoon mene.
> Myyntitilaus: ei ulkoista varastoa

- inc/tilaa_ajax.inc
- tilauskasittely/otsik_ostotilaus.inc
Kun ostoehdotuksesta tehtiin uusi ostotilaus, otsikolle päivittyi toimitusaika, mutta ei riveille. Tämän jälkeen riveille ei voinut päivittää otsikolta uutta toimitusaikaa, koska rivien toimitusaika oli nolla.
> Ostoehotukselta tehdyn oston riveille otsikon toimitusaika

- budjetinyllapito_tat.php
Ajettaesa asiakasmyyjien myytitavoitteita, niin että tavoitteet syötetään indekseittäin, niin kaatui ohjelma tavoitteiden tallennuksen yhteydessä. Korjattu nyt niin, ettei ohjelma kaadu ja tallennus sujuu ongelmitta.
> Asiakasmyyjien myyntitavoitteet: tavoitteet indeksillä

- rahtikirja.php
Rahtikirjojen tulostuksessa, mikäli oli käytössä koontierätulostus, saattoivat rahtikirjannumerot mennä väärin. Korjattu nyt niin, että rahtikirjannumerot menisisvät varmemmin oikein.
> Rahtikirja: rahtikirjnannumerokorjaus

- rajapinnat/presta/presta_addresses.php
- rajapinnat/presta/presta_client.php
- rajapinnat/presta/presta_customers.php
- rajapinnat/presta/presta_functions.php
- rajapinnat/presta/presta_products.php
- rajapinnat/presta/presta_sales_orders.php
- rajapinnat/presta/presta_specific_prices.php
- rajapinnat/presta/presta_tuote_export.php
PrestaShopin asiakkaan määrittely joko "asiakkaittain" tai "yhteyshenkilöittäin".
* **Asiakkaittain.** Pupesoftin yhteyshenkilöstä tehdään PrestaShopin asiakas. PrestaShopin asiakkaalla on yksi osoite, joka tulee Pupesoftin yhteyshenkiloltä.
* **Yhteyshenkilöittäin.** Pupesoftin asiakkaat yhdistetään yhteyshenkilön mukaan. PrestaShopin asiakkaalle tulee useampi osoitetieto, jotka tulevat Pupesoftin eri asiakkailta.
> Presta asiakkaat yhteyshenkilöittäin

- unifaun_fetch.php
Unifaun toimitustapojen kohdalla oli ongelmia toimitusvahvistuksen lähetyksessä ja toimitusvahvistuksia ei saatu sähköpostiin. Tätä on nyt korjattu ja jatkossa toimitusvahvistusten lähetys toimii taas.
> Unifaun toimitustavat: toimitusvahvistus sähköpostiin

- inc/tuotteen_toimittajattarkista.inc
Lisätty tuki toimittajan valuutan ja toimittajan lähetysmaan hakuun toimittajalta sillon kun tuotteen toimittajat on jo perustettuna. Aikaisemmin perustuksen jälkeen ei voinut esim valuuttaa hakea uudestaan toimittajalta. Jatkossa voi, kunhan alasvetolaatikkoon valitsee "toimittajan valuutta".
> Tuotteen toimittajat oletuksia

- inc/functions.inc
- inc/toimitarkista.inc
- ulask.php
Jatkossa yrityksen käyttäjien ei ole pakko hyväksyä ostolaskuja. 
Toiminnallisuus vaatii että yksikään yrityksen käyttäjä ei ole merkitty hyväksyjäksi (tätä säädetään käyttäjäylläpidossa). Ominaisuuden myötä toimittajalle ei tarvitse kertoa oletushyväksyjää eikä uuden laskun syötössä tarvitse kertoa hyväksyjiä. Ostolasku menee luonnin jälkeen suoraan maksatukseen.
Jos yrityksessä on yksikin käyttäjä merkitty hyväksyjäksi, niin toiminnallisuuteen ei tule muutoksia.
> * Ostolaskujen hyväksyntä valinnaiseksi

- rahtikirja-tulostus.php
Unifaun erätulostuksessa saattoi käytä niin, että aiemmin Toimita ja laskuta-ohjelman laskutetut tilaukset palautettiin virheellisesti ohjelmassa takaisin toimitettu-tilaan, minkä seurauksena laskutettuja tilauksia oli jumissta Myyntitilaus toimitettu-tilassa. Korjattu nyt niin, että laskutettuja tilauksia ei erätulostuksessa huomioida.
> Erätulostus Unifaun-toimitustavalla: tulostettavien tilausten tila korjaus

- muuvarastopaikka.php
Ei kutsuta javascripti-funktioita jos ajetaan komentoriviltä. Näin ei tule cron-maileihin ylimääräistä sisältöä.
> Cron-sähköpostit: Javascriptit pois viesteistä

- inc/unifaun_send.inc
OPAY lisäpalvelulle ("Maksaja muu kuin lähettäjä") laajempi tuki Postin palveluissa. Aikaisemmin vain IT09 ja IT14 tukivat tuota ominaisuutta.
> Unifaun Posti OPAY lisäpalvelu

- inc/toimitarkista.inc
Toimittajien ytunnus tarkistettiin aina vertaamalla sitä ytunnusten rakentumistapaan, mutta koska toimittajan ytunnus voi olla myös hetu, niin pitää se tarkistaa henkilötunnusten tapaan.
> Toimittajat: ytunnus voi olla hetu

- tilauskasittely/sarjanumeroseuranta.php
Nyt voi massakohdistaa sarjanumeroita suoraan Excelistä. Käyttöliittymään on lisätty kohta "Lisää Excelistä". Excelistä ajetut sarjanumerot käyvät läpi saman logiikan kuin yksittäisen sarjanumeron lisäys.
Excelin rakenne on yksinkertainen: A-sarakkeeseen listataan haluttuja sarjanumeroita.
> Sarjanumeroseuranta: massakohdistus

- inc/unifaun_send.inc
Unifaun aineistossa siivotaan erikoismerkit pois annetusta "tilauksen puhelinnumerosta", ettei esim Postin lisäpalvelu "saapumisilmoitus" kaadu annetun puhelinnumeron erikoismerkkeihin, esim välilyönteihin. Jatkossa laitetaan pelkkiä numeroita puhelinnumeroksi.
> Unifaun Posti saapumisilmoitus fix

- tilauskasittely/tulosta_lasku.inc
Muutetaan termi Käteiskuitti ➔ Kuitti, koska "käteismaksu" on voitu suorittaa myös pankki- tai luottokortilla.
> Laskupohjamuutos

- inc/unifaun_send.inc
Pikahakuarvo tarvittaessa varaston takaa. Oletuksena käytetään yhtiön parametrien tunnusta (kuten ennenkin). Tämä ominaisuus mahdollistaa useamman varastokohtaisen lähettäjätiedon käyttämisen Unifaun Onlinessa.
> Unifaun pikahakuarvo varastoittain

- inc/functions.inc
Jos kentällä on "synkronointikielto", niin asiakasta, tuotetta yms. perustettaessa käytetään mahdollisia oletusarvoja. Näissä huomioidaan vain MYSQLALIAS-avainsanojen oletusarvot.
> Synkronointi: Synkronointikielto & MYSQLALIAS oletusarvo

- tilauskasittely/otsik.inc
Kertaalleen valmiiksi laitetun (ei enää kesken tilassa olevan) etukäteen maksetun verkkokauppatilauksen otsikolla käyminen sai sisäisen laskutuksen täppäytymään uudelleen päälle, mikä sai tilauksen toimittumaan heti ja johti tilauksen jumittumiseen hankalaan tilaan. Korjattu nyt niin, että laskuta heti sisäinen täppää ei automaattisesti uudestaan päälle täpätä.
> Korjaus verkkokauppatilauksen muokkaamiseen

- inc/unifaun_send.inc
Toimipaikan pikahakuarvo Unifauniin, mikäli halutaan toimipaikka-kohtaisia lähettäjätietoja käyttää. Unifaun Onlinessa tulee olla lähettäjätiedon pikahakuarvo sama kuin Pupesoftin toimipaikan takana, jotta Unifaun osaa valita oikean lähettäjän
> Unifaun toimipaikka lähettäjäksi

- inc/parametrit.inc
- rahtikirja-tulostus.php
- rajapinnat/logmaster/tracking_code.php
- rajapinnat/woo/woo-functions.php
- tilauskasittely/editilaus_in.inc
- tilauskasittely/tilaus_in.php
- unifaun_fetch.php
Merkataan tilaukset toimitetuiksi kauppaan. Toimii rahtikirjan syötössä sekä Logmaster ja Unifaun rajapinnan yhteydessä.
Suoratoimitus eikä JT-prosessi ei ole tuettuna.
> WooCommerce rajapinta

- tilauskasittely/valmista_tilaus.php
Eränumerollisten valmistusten korjaus ei välttämättä aina onnistunut, vaikka periaatteessa ei olisi syytä miksi pitäisi se estää. Tämä korjattu ja nyt myös nämä valmistukset voi Korjaa valmistus-ohjelmalla käsitellä.
> Valmistuksen korjaus

- tilauskasittely/valmista_tilaus.php
Mikäli valmistukselle oli epähuomiossa laittanut pelkästään raaka-aineita ja yritti tälläisen valmistuksen valmistaa niin tuli ruudulle pelkästään epäselvä virheilmoitus. Tätä on nyt viilattu niin, että saataisiin ruudulle hieman selkeämpi virheilmoitus, jolloin käyttäjän olisi helpompi tietää mitä tapahtuu.
> Valmistuksien valmistus: vain raaka-aineita

- tuote.php
Tuotekyselyssä tuotteen ostohinta laskettiin tuotteen toimittajan taakse määriteltyyn valuuttaan, mutta valuuttakoodiksi laitettiin tuotteen toimittajatiedoissa oleva valuuttakoodi. Tämä aiheutti ristiriidan hinnan ja valuutan välillä mikäli toimittajan valuutta ja tuotteen toimittajatiedoissa oleva valuutta olivat eri.
> Tuotekysely: ostohinnan valuutta

- inc/unifaun_send.inc
Pakkausryhmä tulee esittää roomalaisilla numeroilla. Osataan nyt kääntää numerot roomalaisiksi.
> Unifaun sanoman pakkausryhmä

- kayttajaprofiilit.php
Mikäli Extranet-nimerllä oli vain yksi osio valikoissa, niin ei pystynyt perustamaan Extranet-käyttäjäprofiileja. Korjattu nyt niin, että yksikin Extranet-sovellus valikoissa riittää siihen, että pystyy perustamaan extranetkäyttäjäprofiileja.
> Käyttäjäprofiilienhallinta

- tilauskasittely/tilaus_myynti.php
Ennakkoon maksettuja verkkokappatilauksia pystyi edelleen Pupessa mitätöimään, mitä ei saisi missään tapauksessa tehdä. Nyt etukäteen maksettujen verkkokauppatilausten eli tilausten, joille on jo lasku olemassa, mitätöiminen on estetty.
> Etukäteen maksetun verkkokauppatilauksen muokkaaminen

- tilauskasittely/rahtikirja_postitarra_ulkomaa_pdf.inc
Tyhjä rahtikirja ohjelmassa tehtyjen rahtikirjojen rahtikirjannumeron eteen tulee --merkki ja 4 numeroa. Tätä tunnistetta ei osattu ottaa huomioon tyhjien rahtikirjojen syötössä, joten jos syötti monta tyhjää rahtikirjaa peräjälkeen saivat nämä kaikki saman rahtikirjannumeron. Korjattu nyt niin, että tyhjä rahtikirja osaa ottaa huomioon tyhjässä rahtikirjassa tehdyt rahtikirjat.
> Tyhjä rahtikirja: korjaus rahtikirjannumeron tekoon

- inc/functions.inc
- tilauskasittely/tilaus_myynti.php
Myyntitilaukselta saattoi tietyissä tapauksissa puuttua tilaus valmis-nappi, jos tilaus oli tietyssä tilassa ja oli käytössä alhaisella katteella myynnin esto siitä huolimatta, että tilauksen kate oli kohdillaan. Tämä on nyt korjattu ja tilaus valmis-painikkeet tulevat jatkossa oikein myyntitilaukselle. Samalla korjattiin virhe jonka takia kaikkien rivien "tulossa"-tiedote tuli rivin itsensä lisäksi myös myyntitilauksen ensimmäiselle riville.
> Myyntitilaus: tilaus valmis-napit ja tulossa-tekstit

- tilauskasittely/verkkolasku.php
Laskutusvaiheessa, kun lisätään mahdolliset kuljetusvakuutus ja rahtikulurivit, niitä ei merkitty toimitetuiksi, jolloin saattoi näyttää tilauksen otsikolla, että tilausta ei ole toimitettu lainkaan, vaikka todelliset tuoterivit oli toimitettu
> Merkitään myös rahtimaksu- ja kuljetusvakuutusrivit toimitetuiksi

- tilauskasittely/tarkistarivi.inc
- tilauskasittely/tilaus_myynti.php
Yksinäisiä valmisterivejä pystyi lisäämään valmistukselle ilman raaka-aineita. Valmistuksen sai kyllä eteenpäin ja valmistuksen toisen valmistuksen valmistettua, mutta valmistus ei mennyt yksinäisen valmisteen takia valmistettu tilaan, mikä aiheutti ongelmia. Nyt on tarkistuksia korjattu niin, että yksinäisistä valmisteriveistä infotaan käyttäjää samaan tapaan kuin yksinäisistä raaka-aineriveistä.
Lisäksi otetaan mitätöinti-nappi pois muokkaa tilausta näkymästä mikäli valmistuksella on valmistettuja rivejä.
> Valmista tuotteita: reseptien tarkistus

- inc/unifaun_send.inc
Palvelukohtainen pakollinen attribuutti goodsdescription. Jotkut palvelut eivät toimi Unifaunissa ilman tätä, eli käytetään vain niillä palveluilla jotka on tunnistettu. Sisältää jatkossa rahtikirjan kuljetusohjeet.
> Unifaun goodsdescription

- tilauskasittely/tilaus_myynti.php
Myyntitilauksilla tuoteperheiden kohdalla oleva jälkitoimitus-nappi ei toiminut oikein. Jälkitoimitus-nappi sai kyseisen rivin muokattavaksi, mutta jätti perheen kuitenkin koskemattomana tilausrivilistaan. Tämä on nyt korjattu ja tuoteperheiden jälkitoimitus-nappi toimii taas normaaliin tapaan.
> Myyntitilaus: tuoteperheen jälkitoimitus-nappi

- inc/functions.inc
- tilauskasittely/lahetetyt_saldovahvistukset.php
- tilauskasittely/saldovahvistus.php
Saldovahvistus-ohjelmasta lähetettyihin sähköposteihin ei tullut saldovahvistusviestiä mukaan. Nyt tämä on korjattu niin, että saldovahvistusviesti saadaan sähköpostiin mukaan.
Muokattu myös samalla niin, että saadaan viestin sisältö asiakkaan kielelle.
> Saldovahvistusviestin sisältö

- inc/avainsanarivi.inc
- tilauskasittely/tilaus_myynti.php
Uusi yhtiön avainsana, jolla voidaan määritellä ennalta kommentteja tarjouksen hylkäyksen syiksi. Tarjouksen hylkäämisvaiheessa pystyy valitsemaan alasvetovalikosta syyn tarjouksen hylkäykselle. Hylkäyksen jälkeen tarjouksen asiakkaan memoon lisätään muistiinpano tarjouksen hylkäyksestä, sekä tarjouksen kommenttiin lisätään tämä syyteksti.
> Tarjous: tarjouksen hylkäyksestä syykommentti

- tilauskasittely/ostotilausten_rivien_kohdistus.inc
Jos meni saapumisrivien järjestämisen tai sivunvaihdon jälkeen Kohistus valmis painikkeella saapumisen valintanäkymään ja tästä sitten Varastopaikat-näkymään, niin Pupe ei osannut varastopaikkoja tuoda ruudulle vaan tuloksena oli tyhjä ruutu. Tämä ongelma on nyt kuitenkin korjattu ja varastopaikat osataan haeka ruudulle oikein.
> Saapuminen: siirtyminen varastopaikkanäkymään

- rajapinnat/magento_client.php
- rajapinnat/tuote_export.php
- rajapinnat/tuote_export_functions.php
- yllapito.php
Asiakashintojen päivitystä muutettu niin, että poistot ja lisäykset tehdään massana
--jos virheitä, poistot/lisäykset yksitellen vasta virheellisestä blockista lähtien.
Myös arvot nolla ja tyhjä huomioidaan päivityksinä.
Erikoishinnan poisto päivittää automaattisesti tuotteen muutospäivää, jolloin muutos päivittyy seuraavan päivitysajon yhteydessä verkkokauppaan.
> Tuotepäivitys Magentoon

- tilauskasittely/tilaus_myynti.php
Extranetin saldotarkistus ei osannut käsitellä tuoteperheellisiä tuotteita. Saldotarkistuksen jälkeen, kun tilausrivit lisättiin takaisin tilaukselle, niin tässä kohdin tuoteperheen lapset lisättiin sekä itsenäisinä tuotteina, että osana tuoteperhettä. Tämä on korjattu ja jatkossa tuoteperheiden lapset lisätään vain osana tuoteperhettä saldotarkistuksen yhteydessä.
> Extranet: saldotarkistus tuoteperheelle

- tilauskasittely/valmista_tilaus.php
Korjattiin kaksi ongelmaa valmituksien valmistamisen tilapäivityksiin liittyen:
- Kaksi eri valmistetta samalla tilauksella ja valmistettiin vain toinen tuote Valmista tuotteita-ohjelman kautta -> koko valmistus meni valmistettu tilaan, vaikka toinen valmisteista ei ollut vielä valmistettu
- Kahdella eri tilauksella samaa tuotetta ja nämä valmistetaan kerralla Valmista tuotteita-ohjelmalla -> toinen valmistus menee valmistettu tilaan ja toinen (/loput) jäävät kerätty tilaa vaikka kaikki tilaukset valmistuvat muuten ok
> Valmistuksien valmistus: korjaus tilakäsittelyyn

- tilauskasittely/vastaanota.php
Sallitaan vain yksi varastosiirtojen vastaanotto ajettavaksi kerrallaan, jotta pystyttäisiin varmistamaan ettei samaa varastosiirtoa päästäisi vastaanottamaan kahdesti.
> Varastosiirtojen vastaanotto: tuplavastaanottojen esto

- inc/liitetiedostot.inc
Mikäli ostolaskujen hyväksyntää ei ole käytössä eli ketään käyttäjistä ei ole merkitty laskujen hyväksyjäksi ei laskua pitäisi missään vaiheessa hyväksyttäväksi laittaa. Nyt kuitenkin, jos meni laskulta liitetiedoston poistamaan niin tässä tapauksessa lasku laitettiin hyväksyttäväksi. Korjattu nyt niin, että jos hyväksyjiä ei ole niin ei laskua myöskään tässä tapauksessa hyväksyttäväksi laiteta.
> Ei hyväksyjiä käytössä: laskun liitteen poisto

- rahtikirja.php
Kollit päivitetään sille tilaukselle, jonka numeroa käytetään rahtikirjanrona, niin että saadaan siirrettyä tarvittaessa tiedot oikein Unifauniin
> Useita tilauksia samalle rahtikirjalle

- inc/avoimet.inc
Avoimet laskut-ohjelmassa, sekä myynnin että oston puolella oli ongelmia toimipaikka-rajauksen kanssa mikäli käyttäjän takana oli toimipaikka määriteltynä. Tällöin käyttäjä ei pystynyt tekemään hakua kaikista toimipaikoista vaan "kaikki toimipaikat"-rajaus sai rajauksen muttumaan käyttäjän toimipaikaksi. Kaikki muut toimipaikkarajaukset siis toimivat normaaliin tapaan, mutta "kaikki toimipaikat"-rajausta ei pystynyt käyttämään. Tämä on nyt korjattu ja jatkossa myös ne käyttäjät joiden taakse on toimipaikka määriteltynä pystyvät tekemään avoimet laskut haun "kaikki toimipaikat"-rajauksella.
> Avoimet laskut: toimipaikkahakuun korjaus

- tilauskasittely/tulosta_tarjous.inc
Tarjouksen avainsanoista tuleva vakioviesti saattoi mennä muiden tarjouksen tekstien päälle, mikäli kyseinen teksti oli pitkä. Tätä on nyt korjattu niin, että tekstille annetaan enemmän tilaa sen pituuden mukaan.
> Tarjoustulostus: vakioviestille enempi tilaa

- lue_data.php
Perustettaessa tuotteen toimittajia käyttöliittymästä laitetaan valuutaksi ja alkuperämaaksi aina oletuksena toimittajan takaa löytyvät maa ja valuutta - mikäli näitä tietoja ei siis ole erikseen määritelty. Excelistä perustettaessa, jos jätti maa tai valuutta sarakkeen pois menivät nämä tiedot tyhjinä kantaan, mikä saattoi aiheuttaa ongelmia myöhemmin. Nyt tuotteen toimittajien sisäänlukua excelistä on muutettu vastaamaan käyttöliittymää ja jatkossa tuotteen toimittajatietoihin haetaan toimittajan takaa maa ja valuuttakoodtiedot mikäli kyseisen tiedon saraketta ei excelissä ole.
> Sisäänlue dataa: tuotteen toimittaja

- tilauskasittely/verkkolasku_finvoice_201.inc
Ei laiteta verkkolaskuaineistoon MessageTransmissionDetails-elementtiä, mikäli aineisto on menossa Maventaan ja vastaanottajan välittäjänä on pankki. Tämä siksi, että tämä elementti on turha silloin ja saattaa vain sotkea aineiston lähetyksessä.
> Verkkolasku pankkiputkeen Maventan kautta

- tilauskasittely/tilaus_myynti.php
Jatkossa 100% ennakkolaskua (ennakkolasku_myyntitilaukselta parametrin ollessa päällä) ei voi luoda käteismyynnissä eikä laskuta heti (sisäinen) -ominaisuudessa.
> Ennakkolaskun luonnin ehdot fix

- inc/unifaun_send.inc
Jos tilaukselle on asetettu erillinen toimitussähköposti, käytetään
sitä asiakkaan sähköpostina Unifauniin siirtyvässä aineistossa
> Unifaun toim_email

- tilauskasittely/otsik.inc
Etukäteen maksettu verkkokauppatilaus ja sen maksuehdon korjaus tapauksessa jossa tilauksen otsikkoa käytiin muokkaamassa. Aikaisemmin valikoitiin automaattisesti tallennuksen yhteydessä yhtiön maksuehto, joka tuki eräpäivän käsinsyöttöä, jos eräpäivä oli syötetty. Etukäteen maksetulta tilaukselta se löytyy aina, joten jatkossa ei vaihdeta sitä.
> Maksetun tilauksen maksuehto fix

- inc/unifaun_send.inc
- tilauskasittely/rahtikirja_unifaun_uo_siirto.inc
Unifauniin siirtyvät vak-tuotteiden painot jaettu rahtikirjan kollien lukumäärällä, ettei vak-painot moninkertaistu.
> Unifaun VAK painot fix

- tilauskasittely/lisaarivi.inc
Tilanteessa, jossa tuoteperheellä oli saldoton isätuote & oli asetuksissa valittuna, että saldottomia tuotteita ei kerätä niin sitten kävi tuoteperheen isätuotetta myyntitilauksella muokattaessa niin, että tuoteperheen lapset saivat myös "saldoton"-kerättytiedon vaikka lapsia ei olisi vielä todellisuudessa kerätty. Tätä on nyt korjattu niin, että lapsille ei tätä "saldoton"-kerättytietoa lisätä isää muokattaessa.
> Myyntitilaus: tuoteperheiden käsittely

- tilauskasittely/varastoon.inc
Mikäli tuoteperheellä on määriteltynä ohita keräys-täppä niin tuoteperheen isää ostettaessa tuloutetaan isätuotteen saavutusvaiheessa myös lapsituotteita. Tähän ominaisuuteen tehtiin lisäys, että tuoteperheen lapsituotteiden määräkertoimet osataan ottaa tuloutusvaiheessa huomioon ja tuoteperheiden saldoja tuloutetaan perheen määräkertoimien mukaan.
> Saapumiset: tuoteperheiden tulouttaminen

- inc/kate_jyvita_riveille.inc
Katteen pyöristyksessä riveille ei osattu ottaa huomioon tuotteen epäkuranttiustilaa vaan katepyöristys laskettiin aina tuotteen täydellä keskihankintahinnalla. Tämän seurauksena, kun tilausrivinäkymässä kun kate laskettiin rivikohtaisesti ei kate ollutkaan sama kuin mihin kate "pyöristettiin", koska tässä kohtaa epäkuranttiustila osattiin ottaa huomioon. Tämä on nyt korjattu, että katteen pyöristys osaa tuotteen epäkuranttiustilan ottaa huomioon.
> Katteen pyöristys riveille

- tilauskasittely/tulosta_tarjous.inc
Pelkistetyllä tarjouspohjalla vaihdettiin tuoteperheen isätuotteen ja tuoteperheen kommentin järjestys. Muiden tarjouspohjien tuoteperheiden järjestykseen ei koskettu. Samalla muutettiin tuotenumero skaalautuvaksi, jotta se ei tuotenimityksen päälle menisi.
> Tarjoustuloste: Pelkistetty tarjouspohja

- muokkaatilaus.php
- tilauskasittely/otsik.inc
Työmääräyksiä pystyy luomaan sekä työmääräys- että myynti-valikoiden kautta. Aiemmin eri valikoista tehtyjä työmääräyksiä ei ole pystynyt erottelemaan toisistaan vaan työmääräykset ovat olleet samassa tilassa ja käytännössä samankaltaisia kaikkien tietojen suhteen. Nyt on lisätty kommenttikenttä luontitapa, johon tallennetaan tieto siitä missä työmääräys on luotu sen mukaan onko kyseessä työmääräys-valikosta tehty työmääräys vai myynti-valikosta tehty työmääräys.
Lisätty kenttä: laskun_lisatiedot.luontitapa
> Työmääräykset: jako luontitavan mukaan

- raportit/varastotilasto.php
Ajettaessa Varastotilasto-raportti listaustyypillä "Listauksessa näytetään myynti kappaleina, rajattu" ei hakutulokseen tullut mukaan tuotteen osastoa, tuoteryhmää tai mallia, mutta silti nämä otettiin huomioon tuloksen järjestyksessä ennen tuotenumeroa. Muokattiin tätä niin, että kun raportti ajetaan tällä listaustavalla, niin otetaan järjestyksessä huomioon ainoastaan tuotenumero.
> Varastotilasto: tuloksen järjestys

- tilauskasittely/tuote_selaus_haku.php
Korvaaville tuotteille sama alv-käsittely kuin normituotteille extranetissa:
- jos asiakkaalle näytetään verottomat hinnat, niin myös korvaavat tuotteet näytetään verottomalla hinnalla
> Korvaavien tuotteiden alv-käsittely extranetissa

- tilauskasittely/tilaus_myynti.php
- tilauskasittely/tilaus_osto.php
Myynnistä pystyy tekemään ostotilauksia suoraan ja näiden tilausten tilausrivien välille syntyy linkki. Tilaukset ovat siis linkittyneet keskenään näiden tilausrivien kautta. Aika monet tilausriveille tehtävät muokkaukset siirtyivät jo suuntaan ja toiseen, mutta osa muokkauksista oli vielä sellaisia, että ne eivät linkittyneelle tilaukselle muuttuneet. Lisättiin alla listatut uudet yhteydet tilausten välille.
Myynti -> osto
- Mikäli tilausrivin poisti myyntitilaukselta niin ei se ostolta poistunut. Poistetaan myyntitilausriviin liitetty ostotilausrivi mikäli myyntirivi poistetaan, jos ostotilaus on vielä kesken.
Osto -> Myynti
- Oston puolelle lisättyjä uusia rivejä ei saanut lisättyä myyntiin millään. Lisätty uusi painike, jolla voi halutulle myyntitilaukselle uudet ostotilausrivit …
> Myynnistä ostotilaus: muokkausominaisuuksia molempiin suuntiin

- tilauskasittely/keraa.php
Jos on keräyspoikkeama-sähköposti ja sähköinen lähete per toimitus samanaikaisesti käytössä, niin jatkossa lähetetään keräysvahvistus-sähköposti jos lähetteellä ei ole puuterivejä näkyvillä.
> Keräyspoikkeama fix

- maksa.php
Maksa laskuja ohjelmassa ilmoitetaan mikäli toimittajalle on maksuvalmiita hyvityksiä olemassa. Mikäli useammalla eri toimittajalla oli sama factoring käytössä niin saattoi tilinumeroita verrattaessa erheellisesti tulla toisen toimittajan laskun kohdalle ilmoitus "Toimittajalle on X maksuvalmista hyvitystä!". Lisätty tarkistukseen kohta, että hyvityksiä haetaan aiempien ehtojen lisäksi myös ytunnuksella, jotta ei toisen toimittajan hyvityksistä erheellisesti toisen kohdalla ilmoitettaisi.
> Maksa laskuja: toimittajalla hyvityksiä ilmoitus

- index.php
Yläpalkin linkeissä ei osattu aina mennä oikeaan ohjelman versioon. Esimerkiksi avoimet laskut-ohjelmassa voidaan katsella myyntilaskuja ja ostolaskuja. Kun linkki oli tehty avoimiin ostolaskuihin niin vei linkki silti avoimiin myyntilaskuihin. Tämä on nyt korjattu ja avoimiin ostolaskuihin pääsee linkistä käsiksi.
> Yläpalkin linkit

- raportit/ostoehdotus_cs.php
Pyöristetään ostoehdotus ylöspäin seuraavaan kokonaislukuun sen sijaan, että se pyöristetään nyt alaspäin seuraavaan kokonaislukuun.
> Ostoehdotus KK: viilaus ostoehdotuksen laskentaan

- inc/muutosite.inc
Ostolaskun summan muuttaminen ei muuttanut laskun tiliöintejä mikäli kyseessä oli valuttalasku. Tämä johtui siitä, että tiliöinnit on tallennettu yhtiön valuuttaan, mutta laskun summa on laskun valuutassa ja tässä vertailussa ei osattu ottaa tätä huomioon. Korjattu nyt niin, että tämä osataa huomioida vertailussa ja tiliöinnit osataa muuttaa laskun summan muuttamisen yhteydessä oikein.
> Ostolaskut: summan muuttaminen valuuttalaskulla

- inc/verkkolasku-in.inc
Laitetaan Apix ja Maventa verkkolaskujen vastaanoton “vastaanotettiin
onnistuneesti” viestin mukaan laskun PDF, jos semmoinen löytyy.
> Verkkolaskusähköpostiin PDF

- tilauskasittely/keraa.php
Jos etukäteen maksetulla tilauksella on pelkästään saldottomia tuotteita, mutta ne 'kerätään', merkitään tilaus suoraan toimitetuksi
> Etukäteen maksettu saldoton

- directdebit.php
Koska käytössä on vain B2B väylä niin muutettiin LclInstrm-elementtiin CORE -> B2B.
> Direct debit Core -> B2b

- inc/asiakashaku.inc
- tilauskasittely/otsik.inc
- tilauskasittely/tilaus_myynti.php
Vaihdettaessa myyntitilaukselle asiakasta ja mikäli haettua asiakasta ei löytynyt tarjoaa Pupe vaihtoehdon että asiakkaan pystyy lennosta perustamaan. Mikäli asiakkaan perusti ja klikkasi "perusta asiakas" ei Pupe osannut käyttäjää tälle olemassa olevalle myyntitilaukselle palauttaa vaan näkyviin tuli uusi myyntitilaus-ruutu. Tätä on korjattu nyt niin, että Pupe käyttäjän takaisin myyntitilaukselle osaisi palauttaa.
> Myyntitilaus: vaihdetaan asiakasta

- crm/kalenteri.php
Jos kalenterimerkintä on koko päivälle ja selite jää tyhjäksi, ei
kalenterimerkintää pääse jälkikäteen muokkaamaan, koska linkki tehtiin
selitteen avulla. Lisätään tämmöisessä tapauksessa jatkossa selitteeksi
kalenteritapa, josta tehdään linkki.
> Kalenterimerkintä fix

- inc/functions.inc
Jos keräyserä painaa yhtä paljon kuin max pakkaus, jää luuppiin, eikä vaihda pakkausta.
> Painoon perustuvan keräyserän luominen

- raportit/myyntiseuranta.php
- tilauskasittely/editilaus_in.inc
Voidaan ottaa myynninseurannan tulosta jatkossa tilauksen
kohde-kentällä rajattuna tai kohteittain. Lisäksi editilauksen
vastaanotossa laitetaan OSTOTIL.OT_VIITTEEMME sisältö kohteeseen, jos
kohdetta ei ole aikaisemmin saatu.
> Myynninseuranta kohteittain

- inc/avainsanarivi.inc
- inc/functions.inc
Alehinta-funktio osaa jatkossa hakea piiriin sidottuja hinnoitteluja joko asiakkaan takaa (oletus, sama kuin ennenkin) tai uutena vaihtoehtona myös tilauksen takaa. 
Tilauksen takaa hakeminen pitää erikseen aktivoida avainsanoissa “Muut avainsanat / Piiriin sidottu hinnoittelu”.
> Piiriin sidottu hinnoittelu

- inc/verkkolasku-in.inc
Sisään luetun verkkolaskun valuuttakoodi talletetaan isoilla kirjaimilla kantaan, koska pankki ei hyväksy valuuttakoodi, joka on kirjoitettu pienillä kirjaimilla
> Verkkolaskun valuuttakooodi

- inc/parametrit.inc
- tilauskasittely/editilaus_in.inc
Verkkokaupan tilauksen sisäänluvussa sallitaan jatkossa nollahintaisen rivin myynti, mikäli kaupan hinnoilla on tarkoitus myydä ja on erikseen sallittu nollahintainen myynti $verkkokauppa_nollahintaok = “JOO” muuttujalla salasanat.php:ssä.
Nollahintainen myynti tehdään antamalla riville alennukseksi 100%.
> Editilaus sallitaan nollahinta

- inc/functions.inc
Osataan näyttää Unifaun Kaukokiito toimitustavan seurantalinkki mm “näytä tilaus” ohjelmassa. Linkki muodostetaan rahtikirjanumerolla sscc-numeron sijaan.
> Unifaun kaukokiito seurantalinkki

- inc/toimitustavan_avainsanat.inc
- inc/toimitustavan_avainsanatrivi.inc
- inc/toimitustavan_avainsanattarkista.inc
- inc/unifaun_send.inc
- yllapito.php
Toimitustavan avainsanoissa voidaan jatkossa aktivoida Unifaun ennakkoilmoitus. Pupe ei tarkista onko ennakkoilmoituksen aktivointi toimitustavalle ok, eli se pitää itse varmistaa Unifaunilta, tai testata ennen laajempaa käyttöä.
Ennakkoilmoitus tehdään sähköpostitse, eli jos sitä ei tilauksella / asiakkaalla ole, tulee Unifaunissa errori.
> Unifaun ennakkoilmoitus

- raportit/myyntiseuranta.php
Jos yritti ottaa raporttia pelkistä kappalemääristä kuukausittain ja ruksasi piilota myynnit, myynnit tuli silti kappaleitten lisäksi raporttiin.
> Myyntiseuranta kuukausittain ei saanut piilotettua myyntejä

- rahtikirja-kopio.php
- rahtikirja-tulostus.php
Voidaan ottaa toimitussanomat tarvittaessa rahtikirjakopioissa. Aikaisemmin ne otettiin aina automaattisesti, mutta nyt se on valinnainen. Oletuksena ei oteta.
> Ohitetaan toimitussanomat rahtikirjakopiossa (oletus)

- tilauskasittely/lisaarivi.inc
Myyntierä != 0 tai alle tässä keississä, jossa katsotaan täysiä myyntieriä loopin sisällä. Ei haluta ikuista looppia.
> Pienviilaus myyntierään

- inc/verkkolasku-in-finvoice.inc
- inc/verkkolasku-in-pupevoice.inc
- inc/verkkolasku-in-teccom.inc
- inc/verkkolasku-in.inc
- inc/yhtion_parametritrivi.inc
Sisääntulevan verkkolaskun ibania ja bicciä voidaan tarvittaessa
käyttää oletuksena, jos uusi parametri ostolaskujen_oletusiban
kytketään päälle. Vanha oletus oli toimittajan takana.
> Verkkolaskun iban käyttöön ostolaskuissa

- tilauskasittely/tilaus_myynti.php
Pyöristys ei enää kysy erillistä varmistusta käyttäjältä ellei kyse ole tarjouksen luonnista.
> Pyöristys myyntitilauksella fix

- inc/avainsanarivi.inc
- tilauskasittely/tulosta_tarjous.inc
Siirretty pelkistetyn tarjouspohjan muutama ehtoihin liittyvä kohta avainsanoihin, jossa tekstiä voi itse määritellä. Ilman avainsanoja toimii oletusteksteillä kuten ennenkin.
> Pelkistetty tarjouspohja, ehdot

- raportit/myyntiseuranta.php
Voidaan ottaa tulos jatkossa niin että kerrotaan mitä tuotteita
ajanjaksolla tulee löytyä.
Esim tuotteet A1 ja A2, ajankohta tammikuussa ja listaus asiakkaittain.
Tulos ajetaan niin että kaikkien asiakkaiden on pitänyt ostaa tammikuun
aikana molempia tuotteita millä tahansa laskuilla. Kunhan vähintään
yhden kerran on myyty kumpaakin tuotteita, esim 1.1 A1:stä ja 31.1
A2:sta.
Myyntiluvut näytetään kuitenkin kaikista myydyistä tuotteista, eli
rajaus filtteröi pois ne asiakkaat joilla ei ole ollut myyntiä
annettuihin tuotteisiin.
Ominaisuus ei toimi jos tulos listataan tuotteittain (listan tuotteita
verrataan per hakutuloksen rivi, eli rivin pitää olla grouppi missä on
eri tuotteita).
> Myynninseuranta tuotelista 2

- tilauskasittely/editilaus_in.inc
- tilauskasittely/tilaus_in.php
Voidaan asettaa salasanat.php:hen muuttuja + arvo $editilaus_hyvaksyttavaksi_jos_virhe = "JOO", joka pistää jatkossa editilaukset (mm futursoft ja apix_edi, ei kuitenkaan mm magentoa) hyväksyttäväksi Pupesoftin hyväksyttävät tilaukset -ohjelmaan, mikäli tilauksella on seuraavia asioita:
- tilattiin tuntematonta tuotetta
- myytävissä määrä ei riittänyt
Jos millä tahansa tilauksen rivillä esiintyy jompikumpi, niin tilaus menee hyväksyttäväksi.
> Editilaus hyväksyttäväksi, jos virheitä

- tilauskasittely/tulosta_lahete.inc
Voidaan asettaa salasanat.php:ssä tietty toimipaikka semmoiseksi, ettei kyseisen toimipaikan tilausvahvistukselle ja lähetteelle tulosteta lähete-pohjan footerissa olevaa ytunnusta ja kotipaikkaa.
Esim $lahete_piilota_ytunnus_toimipaikka = array(1); jossa 1 on valitun toimipaikan tunnus.
> Lähete ilman ytunnusta

- tilauskasittely/tulosta_lahete.inc
Tilausvahvistuksella katsottiin tuotenumeroiden ja tuotenimitysten keskiarvon perusteella oliko siellä pitkiä rivejä. Jos siis sattui niin, että paria pitkää riviä oli lyhyempien joukossa ei pitkiä rivejä huomioitu ja tuotteiden nimitykset sekä tuotenumerot menivät päällekkäin tilausvahvistuksella. Katsotaan siis jatkossa jokaisen rivin pituus erikseen, jolloin tilausvahvistus rakentuu pisimmän rivin perusteella.
> Tilausvahvistus tekstien viilaus

- inc/functions.inc
- tilauskasittely/valitse_laskutettavat_tilaukset.php
Rahtimaksun käsittelyssä haettaessa rahtimaksu matriisista sitä käsiteltiin niin kuin se olisi ollut laskun valuutassa vaikka todellisuudessa rahtimatriisissa on hinnat yhtiön valuutassa. Muutetaan tarpeellisissa kohdin hinta siihen valuuttaa jossa sitä käsitellään.
> Rahtimaksujen käsittely toisessa valuutassa

- dokumentti_raportti.php
Dokumenttien listauksessa sarakkeiden otsikossa olevat järjestelypainikkeet eivät toimineet. Ne korjataan tässä, joten jatkossa nuolilla taas voi sarakkeissa vaikuttaa listauksen järjestykseen.
> Dokumenttien listauksen järjestelynapit

- tilauskasittely/keraa.php
Keräys vaiheessa luotua puuteriviä täytyy käsitellä samaan tapaan kuin muitakin puuterivejä, joten sille täytyy laittaa alunperin_puute-kenttään 1. Tämä edesauttaa sitä, että keräyksessä luotu puuterivi saadaan oikeaan kohtaan lavatarra.pdf:n kollilaskennassa.
> Alunperin puute-tieto keräyksessä

- inc/functions.inc
- tilauskasittely/tulosta_tarjous.inc
- tilauskasittely/tulostakopio.php
Korjattu tarjouksen tulostuksen asettelua, jotta tiedot eivät menisi päällekkäin ja ne olisivat helpommin luettavissa.
Samalla lisätty admin käyttäjälle mahdollisuus kaikkien tarjouspohjien tulostukseen.
> Tarjous pdf asettelu & admin kaikki tarjoustyypit tulostus

- extranet_tyomaaraykset.php
Työmääräimen teko extranetin kautta toi maksuehdoksi oletuksena kaikille asiakkaille maksuehtolistan ensimmäisen maksuehdon.
Korjattu niin, että maksuehto haetaan asiakaan takaa.
> Extranet työmääräys maksuehto korjaus

- intrastat.php
Mikäli tuotteella oli useampi toimittaja eri maista alkuperämaa saattoi intrastat ilmoitukseen tulla väärän toimittajan alkuperämaa.
> Intrastat-ilmoitukset alkuperämaan haku tuotteelta

- muuvarastopaikka.php
Muuvarastopaikka ohjelmassa siirtoja tehdessä mikäli siirrettävässä määrässä oli desimaaleja saattoi se aiheuttaa ongelmia määrien vertailuissa. Muokattu vertailuja nyt niin, että ne olisivat entistä tarkempia myös desimaalilukujen kohdalla.
> Muuvarastopaikka siirto korjaus

- inc/tuoterivi.inc
- yllapito.php
Lisätty uusi ominaisuus automaattiseen tuotenumerointiin liittyen ja laajennettu tuotenumerointiautomatiikkaa. Tuotenumero kentän viereen on lisätty "Etsi seuraava vapaa"-nappi, jolla pystyy hakemaan manuaalisesti hakemaan seuraavan vapaan tuotenumeron. Mikäli tuotteen perustukseen mentäessä ruudulle tuotu tuotenumero on vielä vapaana niin tämä pysyy ruudulla, mutta siinä tapauksessa, että joku onkin jo ehtinyt sillä numerolla tuotteen perustamaan, niin tällä uudella napilla pystyy hakemaan seuraavaksi suurimman vapaan tuotenumeron.
> Automaattiseen tuotenumerointiin seuraavan numeron hakunappi

- inc/yhtion_parametritrivi.inc
- tilauskasittely/tulosta_lahete_kerayslista.inc
Uusi siirtolistatyyppi, jolle saa tulostettua siirtolistan tuotteiden ostohinnan summan. Ostohinnat eivät siis tulostu rivikohtaisesti vaan siirtolistan rivien yläpuolelle tulostetaan kaikkien rivien ostohintojen summa.
> Mahdollisuus saada siirtolistalle ostohintojen summa

- inc/valitse_tulostin.inc
- tilauskasittely/tulostakopio.php
Mahdollisuus ottaa siirtolistakopioita exceliin. Excelin pohja on samanlainen kuin tilausvahvistuksella, jonka voi ottaa exceliin. Exceliin otettava siirtolista tulostetaan käyttäjän sähköpostiin.
> Siirtolistan Excel-tulostus

- tilauskasittely/tulostakopio.php
Mikäli rahtikirjalla oli useita pakkauksia saattoi se aiheuttaa DGD-lomakkeen tulostuksessa SQL-errorin. Tämä ongelma on nyt korjattu ja SQL-erroreita ei pitäisi enää tulla.
> Korjattu ongelma DGD-lomakkeen tulostuksesta

- inc/avainsanarivi.inc
- tilauskasittely/verkkolasku_finvoice_201.inc
Uusi yhtiön avainsanojen laji Verkkolaskukentän sisältö (VERKLASKKENTSIS), jolla pystyy pakottamaan muutaman kentän sisältö tietynlaiseksi. 
- SellersBuyerIdentifier kenttään voi pakottaa asiakasnumeron
- OrderIdentifier kentän voi pakottaa tyhjäksi
> Uusi avainsanatyyppi verkkolaskun kenttien sisällön muokkaukseen

- tilauskasittely/tulosta_ostotilaus.inc
Ostotilaus näytä nappulan kautta tulostettavasta ostotilauksesta oli kadonnut tuotteiden nimitykset toisen ostotilauksen tulostukseen liittyvän muutoksen yhteydessä. Tehty pieni korjaus, jolla palautettiin nimitykset tulosteelle, mikäli yhtiön parametri ostotilaustyyppi on sellaisessa asennossa, että nimitykset oletuksena tulostetaan.
> Ostotilaus näytä korjaus

- inc/unifaun_send.inc
DB schenker kotimaankuljetuksen rahtisopimusnumero on oikein mikäli sen on vähintään 3 merkkiä pitkä, muutettu ehtoa siis nykyisestä jotta myös lyhyemmät rahtisopimusnumerot hyväksytään.
> Rahtitisopimusnumeron pituuden ehto

- verkkolasku_resend.php
Otetaan epäonnistuneesta lähetyksestä tuleva virheilmoitus talteen ja laitetaan se virhelogiin ja epäonnistumisesta lähetettävään sähköpostiin.
> Lisää logetuksia Maventan verkkolaskutukseen

- crm/kalenteri.php
Kalenterin päivän ensimmäisen tapahtuman pystyi laittaa alkamaan vasta tunti kalenterin ensimmäisen ajan jälkeen. Tämä on nyt korjattu ja kalenteritapahtuman saa aloitettua päivän alusta. Samalla korjattiin se, että jos muutti alkuaikaa niin loppuaika päivittyi aina, jatkossa loppuaika päivittyy vain jos alkuaika laitetaan myöhemmäksi kuin loppuaika.
> Korjaus kalenteritapahtuman aikavalintaan

- tilauskasittely/laskutus.inc
Kun erä myydään kokonaan loppuun jää siitä jäljelle erä jonka era_kpl on 0. Tälläiset rivit näkyvät häiritsevästi ainakin inventoinnissa. Siivotaan nämä 0 kpl rivit heti pois mikäli niitä meinaa syntyä, jotta eivät jäisi roikkumaan turhaan. 0kpl erällä kun ei mitään myöskään edes tee (sehän on myyty loppuun).
Myynnissä on tehty kokonaan oma rivi myynnin eränumeroa varten ja kpl määrä siirtyy sinne laskutuksessa, joten senkin puoleen tuo 0kpl rivi on turha.
Tähän liittyy valmistuksen vastaava korjaus: https://github.com/devlab-oy/pupesoft/pull/4114
> Eränumeroiden myynnissä ongelma kappaleiden kanssa

- valmistatuotteita.inc
Kun erä käytetään raaka-aineena kokonaan loppuun jää siitä jäljelle erä jonka era_kpl on 0. Tälläiset rivit näkyvät häiritsevästi ainakin inventoinnissa. Siivotaan nämä 0 kpl rivit heti pois mikäli niitä meinaa syntyä, jotta eivät jäisi roikkumaan turhaan. 0kpl erällä kun ei mitään myöskään edes tee (sehän on myyty/käytetty loppuun).
Valmistuksessa on tehty kokonaan oma rivi myynnin eränumeroa varten ja kpl määrä siirtyy sinne valmistuksen yhteydessä, joten senkin puoleen tuo 0kpl rivi on turha.
Tähän liittyy myynnin vastaava korjaus: https://github.com/devlab-oy/pupesoft/pull/4113
> Valmistuksiin korjaus eränumerokäsittelyyn
