devlab-oy/pupesoft

- sepa.php
Reverts devlab-oy/pupesoft#2206
> Revert "Uusi maksuerien muodostus laajempaan testaukseen"

- tilauskasittely/editilaus_in.inc
Käsitellään Anvia verkkokaupan tilaukset kuten Magento tilaukset
> Anvia tilaukset kuten Magento

- crm/asiakaslista.php
- tilauskasittely/lahetteen_tulostusjono.php
- tilauskasittely/valitse_laskutettavat_tilaukset.php
* Haetaan asiakasta myös nimitarkenteella keräyslistan tulostuksessa, toimita ja laskuta tilauksessa ja CRM asiakaslistassa
> Asiakkaan haku nimitarkenteella

- infobar.php
Hyväksyttävät EXT-tilaukset -teksti ja OHJE-teksti menivät aikaisemmin päällekkäin. Enää ei mene
> OHJE-linkin päälle tuli muuta tekstiä

- raportit/myyntiseuranta.php
Tavoitteet oli päivitetty tietokantaan, mutta asiakkaan osastokohtaisia myyntitavoitteita ei osattu hakea oikein raportille.
> Myynninseurantaan ei saanut asiakas-osasto -tavoitteita oikein

- tilauskasittely/tilaus_myynti.php
Aikaisemmin uuden takuun luonnin jälkeen siirryttiin luomaan uutta reklamaatiota. Tilaustyyppi muistetaan jatkossa, joten jatkossa siirrytään luomaan uusia takuita takuun luonnin jälkeen.
> Muistetaan tilaustyyppi uuden takuun luonnissa

- inc/functions.inc
Muutettu miten tallennetaan tiedot Resque jonoon.
> Email Worker päivitetty

- tilauskasittely/tarkistarivi.inc
Myyntitilauksella on aikaisemmin estetty varastosiirtojen luonti tilausriviltä, mikäli myyntitilauksen maksuehtona oli jälkivaatimus. Ei estetä enää.
> Sallitaan myynnissä jälkivaatimus ja var S rivit

- index.php
Mm Varasto / Kerää -ohjelman varaston esivalinta käyttäjän oletusvarastolla ei toiminut.
> Pupenext pikalinkkeihin indexvas fix

- tilauskasittely/selaa_tilauksia.php
* Näytetään kate myyntiselausraportissa tilaus, päivä ja kuukausinäkymissä
* Kate näytetään ainoastaan, jos ohjelman alatilana on MYYNTI_KATE
> * Kate myyntiselausraporttiin

- tyomaarays/tulosta_tyomaarays.inc
Työmääräykselle tulostetaan teksti hinnat verollisia tai hinnat verottomia sen mukaan onko hinnoissa mukana arvolisävero vai ei.
> Tulostetaan työmääräykselle ovatko hinnat verollisia vai verottomia

- monistalasku.php
Pitää pystyä hyvittämään koko lasku, vaikka laskulla olisi useamman asiakkaan tilauksia. Asiakkailla on kuitenkin sama ytunnus.
> Laskun hyvitys, kun laskulla usean as. tilauksia

- inc/yhtion_parametritrivi.inc
- tilauskasittely/luo_myyntitilausotsikko.inc
Uusi yhtiön parametri ohjaa extranet-tilauksen prioriteettia.
```SQL
ALTER TABLE yhtion_parametrit ADD COLUMN extranet_keraysprioriteetti CHAR(1) NOT NULL DEFAULT '' AFTER extranet_poikkeava_toimitusosoite;
> * Myyntitilaus: Extranet & prioriteetti

- rajapinnat/relex/relex_products.php
Vaihdettu rekkareiden hakua, lopputulos sama kuin ennenkin
> Relexiin päivitetty rekkarihaku

- inventoi.php
Tehtäessä inventointia relatiivisella määrällä (+/-) oli tietyissä tapauksissa ongelmia erämäärän vs. varastosaldon tarkistuksen kanssa. Erämäärän ja varastosaldon yhtäsuuruisuus tarkistus on nyt siis korjattu.
> Relatiivisen inventointimäärän tarkistuksen korjaus

- inventoi.php
Reverts devlab-oy/pupesoft#2221
> Revert "Relatiivisen inventointimäärän tarkistuksen korjaus"

- inc/paakirja.inc
> SQL-error korjaus

- tilauskasittely/otsik.inc
Kun myyntitilauksen otiskolla muutetaan toimitustapaa päivitetään rahtisopimus sen mukaisesti.
> Päivitetään rahtisopimus toimitustavan mukaiseksi

- myyntires/luotonhallinta.php
Jos käyttäjällä vain selailuoikeus Luotonhallintaan, niin ei saa olla mahdollisuutta päivittää luottorajoja
> Luottorajan selailuoikeudella ei saa päivittää

- tuote.php
Tuotteiden tietojen päivityksen jälkeen palataan aina päivitetyn tuotteen tuotetietoihin. Aiemmin satunnaisesti palattiin ns. edellisen tuotteen tietoihin.
> Palataan oikean tuotteen tietoihin tuotteen päivityksen jälkeen

- tilauskasittely/selaa_tilauksia.php
* Huomioidaan epäkurantointi katteen laskemisessa
> Huomioidaan epäkurantointi katteen laskemisessa

- inc/functions.inc
- tilauskasittely/lisaarivi.inc
- tilauskasittely/vastaanota.php
Kun lisätään uusi varastopaikka myyntitilille, pitää sen olla asiakaskohtainen
> Myyntitilin varastopaikka asiakaskohtaiseksi

- inc/laskuhaku.inc
- inc/toimittajahaku.inc
- raportit.php
Voidaan rajata laskuhaku ja toimittajahaku näyttämään vain käyttäjän oman osaston==kustannuspaikan laskuja! KUKAOSASTO-avainsanan selite tulee olla sama kuin kustannuspaikan tunnus.
> * Voidaan rajata laskuhaku ja toimittajahaku näyttämään vain tietyn kustp:n laskuja

- tuote.php
> TUOTEKYSELY: Valmistuksen tapahtumat

- inc/tilaus_in_multi.inc
- tilauskasittely/luo_myyntitilausotsikko.inc
Usean asiakkaan tilauksen sisäänlukuun lisätty mahdollisuus antaa myös tilausviite ja toimitustapa.
> TILAUKSEN SISÄÄNLUKU: Usea asiakas

- inc/avainsanarivi.inc
- kopioituote.php
Uusi avainsanojen laji "Kopioi tuote parametri", joka ohjailee "Kopioi tuote"-ohjelmaan lisättyjä 2 uutta valintaa:
- Kopioi tuotteen toimittajat
- Ehdotetaan ostoehdotusohjelmissa tilattavaksi
> * KOPIOI TUOTE: Lisävalintoja

- monistalasku.php
Ruksataan valinta aina oletuksena jos yhtiön parametri "reklamaation_hinnoittelu" on päällä.
> MONISTA LASKU: "Käytetään hyvityshintoja"-valinta

- yllapito_tuotekuvat.php
Tuotekuvien poisto oikutteli tuotekuvien ylläpidossa, jos oli vaihtanut sivua, mutta nyt tämä on korjattu ja tuotekuvia voi poistaa taas normaalisti.
> Korjaus tuotekuvien poistoon tuotekuvien ylläpidossa

- raportit/varastonarvo-super.php
Slave siirretty 2 -> 1. CSV-tuki lisätty.
> VARASTONARVO TUOTE: CSV-tuki

- inc/valitse_tulostin.inc
- inc/yhtion_parametritrivi.inc
- tilauskasittely/tulosta_tarjous.inc
- tilauskasittely/tulostakopio.php
* Uusi tarjouspohjatyyppi, lyhyt tarjouspohja, yhtiön parametreihin
* Lyhyestä tarjouspohjasta poistettu hieman tekstiä ja muutettu yhteystietojen asettelua
* Mahdollista piilottaa yhteissummarivi tarjousta tulostettaessa
> * Tiiviimpi tarjouspohja

- inc/valitse_tulostin.inc
- inventointi_listat.php
Inventointilista voidaan ottaa nyt myös pelkästään Exceliin.
> INVENTOINTILISTA: "Vain raportti"-ominaisuus

- inc/luedata_ja_dataimport_spessuvalinnat.inc
- inc/pakolliset_sarakkeet.inc
- inc/tuotepaikattarkista.inc
- lue_data.php
Lisätty toimipaikkavalinta "Sisäänlue dataa"-ohjelmaan. Valittu toimipaikka käyttää kyseisen toimipaikan yhtiön parametreja.
> SISÄÄNLUE DATAA: Toimipaikan valinta

- raportit/naytatilaus.inc
Paluulinkit korjattu, jatkossa tullaan takaisin tulostakopio -ohjelmaan jos ollaan alunperin siitä lähdetty liikenteeseen (aikaisemmin mentiin virheellisesti asiakkaan tilaukset -ohjelmaan). 
Lisäksi jatkossa ei tule useampaa samankaltaista paluulinkkiä perätysten.
> Korjattu paluulinkkejä tulostakopioon

- inc/unifaun_send.inc
Jos asiakkaan sähköpostiosoite on annettu, viedään se unifauniin
> Asiakkaan email unifauniin

- pupe-backup.sh
Ei enää erikseen backupata binlogeja.
> Ei enää erikseen backupata binlogeja.

- inventointi_listat.php
Otetaan huomioon myös monivalintalaatikoitten valinnat, kun poimitaan tuotteita inventointilistalle
> Inventointilistan monivalintalaatikkovallinnat

- mobiili/inventointi.php
Korjattu inventointilistan näyttämistä
> MOBIILI: Inventointilistaan parannuksia

- raportit/varastonarvo-super.php
Tallennusmuoto-tarkistuksen korjaus.
> VARASTONARVO TUOTE: Tallennusmuoto

- tilauskasittely/lisaarivi.inc
- tilauskasittely/tilaus_myynti.php
Siirtolistoilla ei näytetä JT-muiden mukana nappia
> SIIRTOLISTAT: JT-muiden mukana

- rajapinnat/relex/relex_warehouse_location.php
> RELEX: Warehouse location

- raportit/varastonarvo-super.php
"Huomioidaan varastosiirrot tulona"-valinta lisätty.
> VARASTONARVO TUOTE: Siirrot tulona

- inc/functions.inc
- inc/tiliote.inc
- myyntires/maksunsyotto.php
Siivotaan nimestä hakua häiritsevät merkit
> TILIOTE: Nimellä haku

- pupesoft_changelog.php
- svn-pupeen.sh
Uusi yhtiön parami jonne voidaan tallentaa sähköpostiosite johon lähetetään muutoslokiviesti aina kun pupe päivitetään.
> * Lähetetään infomeili kun pupe päivitetään

- inc/functions.inc
Korjattu keräyserien teon pakkauksen valintaa. Nyt myös pakkausten suuruusrajoilla oleville tuotteille löydetään pakkaukset oikein.
> Keräyserän tulostus: pakkausvalintakorjaus

- tilauskasittely/yllapitosopimukset.php
* Tulostetaan laskutuskausi ainoastaan, jos kuukausihinnoittelu on käytössä
> Laskutuskausi ainoastaan kuukausihinnoittelussa

- makai.php
Ei-SEPA-maksuaineistoon viedään matkalaskun vapaamuotoinen viite viestiksi
> Matkalaskulle viite viestiksi

- lue_data.php
Selkeytetty virheilmoitusta sisäänlue dataa ohjelmassa ja paranneltu ohjelman toimivuutta.
> Sisäänlue dataan viilaus

- inc/functions.inc
Korjattu nimen putsaus funktio
> TILIOTE: Nimellä haku & nimen putsaus

- raportit/naytatilaus.inc
- tilauskasittely/keraa.php
- unifaun_fetch.php
Osataan hakea tilauksen seurantakoodi Unifaunista myös kun Pupessa käytetään kevyempää logistiikkaprosessia.
> * Unifaun seurantakoodit

- tilauskasittely/tilauksesta_ostotilaus.inc
Myydän tuoteperhettä, jota ei löydy varastosta, ja joka halutaan siksi tilata suoraan tomittajalta.
Jos ko. tuoteperheen lapsi löytyy useasta tuoteperheestä, yritettiin virheellisesti tehdä ostotilausrivi kaikkien näiden tuoteperheiden lapsista
> Tehdään vain käsiteltävän tuoteperheen lapsesta ostotilausrivi

- rajapinnat/relex/relex_products.php
Uusia kenttiä lisätty product_update_ ja supplier_update_ aineistoihin. Kentät:
Tullinimike
Tullinimikkeen lisäkoodi
Kohtelukoodi (Tulli)
VAK/ADR-koodi
VAK-määrä
Leimahduspiste
Kuluprosentti
Kuluprosentti luetaan toimittajan takaa.
> Relex: Uusia kenttiä tuotedataan

- raportit/tuloslaskelma.php
Tuloslaskelman Alkukausi ja Loppukausi haetaan nyt Yrityksen tilikaudet-taulusta.
> Tuloslaskelman kaudet

- inc/tulosta_tuotetarrat_pdf.inc
- tulosta_tuotetarrat.php
* Lisätään tuotetarrojen tulostukseen uusi malli, PDF, jolla tulostuu yksittäisiä PDF-tuotetarroja
> Yksittäinen PDF-tuotetarra

- inc/functions.inc
Tilaus ei saa löytyä keräyserät-taulusta
> KERÄYSERÄT: Uniikki tilaus

- tiedostofunkkarit.inc
- tiedostokirjasto.php
* Näytetään liitetiedoston tuote tiedostokirjastossa, jos ei olla extranetissä
> Tuote tiedostokirjastoon

- tilauskasittely/lisaarivi.inc
Jos alkuperäinen tilausrivi joudutaan jakamaan, laitetaan mahdollinen rivikommentti molemmille riveille
> Alkuperäisen rivin kommentti myös jt-riville

- tuote.php
Sarjanumerollisten tuotteiden tuotteen tapahtumissa tuotteen kokonaissaldo näkyi väärin. Nyt tämä on korjattu ja tuotteen tapahtumissa näytetään taas tuotteen kokonaissaldo oikein.
> Sarjanumerollisten tuotteiden kokonaissaldo

- tilauskasittely/tilauksesta_ostotilaus.inc
Jos myydään tuoteperheitä myyntitilauksella, josta tehdään automaattisesti ostotilaus, laitetaan myös ostotilausriveille perheid:t kuntoon.
Jos perheid:t puuttuu, tuloutus tekee ylimääräisiä lapsirivejä niistä lapsista, joita ei erikseen kerätä.
> Myyntitilauksesta ostotilaus

- tilauskasittely/rahtikirja_pdf.inc
Kun asiakkaan omat tilausnumerot tulostettiin rahtikirjalle, menivät ne päällekkäin pupen tilausnumeroitten kanssa
> Rahtikirjan tulostus

- extranet/asiakashinnasto.php
Ohjeet:
1.) laaditaan uusi avaisana lajia "Tuotteen avainsanojen laji". Selitteeksi "hinnastoryhmittely".
2.) Laaditaan uusi avainsana lajia "Tuotehinnastoryhmä" jokaista haluttua hinnastoryhmää kohden. Näille voidaan perustaa kieliversiot avainsanojen ylläpidossa. Vaihtoehtoisesti hinnastoryhmiä voidaan lukea sisään "Sisäänlue dataa" ohjelman avulla. Tällöin saman hinnastoryhmän eri kieliversiot tulee kytkeä toisiinsa samalla "selite" -sarakkeen arvolla. itse kieliversio "selitetark" -sarakkeeseen.
3.) Tuotehallinnassa voi tuotteelle perustaa "hinnastoryhmittely" -lajisen avainsanan ja valita mihin hinnastoryhmiin tuotteen halutaan kuuluvan syöttämällä avainsanan selitteeksi kaikkia haluttuja ryhmiä vastaavat numerot pilkulla eroteltuna. 
Myös hinnastoryhmiä voidaan lukea sisään …
> * Tuoryhmähinnastoryhmittely

- tilauskasittely/splittaa_crossdock_editilaus.php
Varastotilausten käsittely CrossDock-putkessa
* tunnistetaan tilaustyyppi, onko kyseessä crossdock vai varastotilaus
* ohjataan orders91.1 formaatin luontia tilaustyypin mukaan
> CrossDock Edi-tilaukset

- tilauskasittely/ostotilausten_rivien_kohdistus.inc
* Otetaan alennukset huomioon laskettaessa katetta saapumisessa
> Kateprosentti saapumisella

- tilauskasittely/tulosta_valmistus.inc
Tulostetaan rahtisopimusnumero samalla tavalla valmistuslistalle kuin se on jo ennestään tulostettu keräyslistalle
> * Valmistuslista

- myyntires/paperikarhu.php
Tulostetaan laskujen perintäkerrat oikein maksukehotukselle
> Maksukehotukset

- inc/functions.inc
- inc/yhtion_parametritrivi.inc
Uusi yhtiön parametri. 
Tehdään automaattisesti inventointitapahtuma jos kohdehyllypaikan viimeinen tapahtuma on "uusi paikka" tai "inventointi" jonka saldo on 0.
> Automaattinen inventointi siirron yhteydessä

- inc/functions.inc
- tilauskasittely/tilaus-valmis-tulostus.inc
- tilauskasittely/tilaus-valmis.inc
- tilauskasittely/tilaus_myynti.php
Myyjä voi valita erikseen haluaako tulostaa keräyslistan ja/tai lähetteen. 
Tämä ominaisuus on päällä jos yhtiön parametri "lähetteen tulostusjono" on asennossa "Myyntitilausten keräyslistat ja lähetteet tulostetaan automaattisesti ja tilaus laitetaan toimitetuksi".
> MYYNTITILAUS: Keräyslista- ja lähete-checkboxit

- tilauskasittely/tilaus-valmis.inc
- tilauskasittely/tilaus_myynti.php
- tyomaarays/tyomaarays.inc
Luottorajan ylittäessä ei anneta laittaa tilausta/reklamaatiota valmiiksi, vaan jäädään tilausnäkymään.
> LUOTTORAJAT: Ylittäessä jäädään tilausnäkymään

- inc/functions.inc
- tilauskasittely/tulosta_lahete.inc
- tilauskasittely/tulosta_tilausvahvistus_pdf.inc
Tulostetaan kaikki eankoodit ean-tyyppisinä viivakoodeina lähetteelle ja tilausvahvistukselle. 
Ennen tulostettiin tietyssä tapauksessa eankoodi code128-tyyppisenä viivakoodina.
> Eankoodi lähetteellä

- raportit/naytatilaus.inc
- unifaun_fetch.php
Osataan käsitellä Unifaunin palautesanomia joissa on useita rivejä. Aikaisemmin käsiteltiin vain palautteen ensimmäinen rivi.
> Unifaun pakettikoodit

- kerayksen_kuittaus_ulkoisesta_jarjestelmasta_cron.php
Laitetaan ulkoisessa järjestelmässä kerätyt tilaukset takaisin laskutettu tilaan mikäli ne on jo laskutettu & maksettu etukäteen.
> Tilausten keruu ulkoisessa järjestelmässä

- tilauskasittely/tilaus-valmis.inc
Eräpäivän ylityscheck korjattu
> MYYNTITILAUS: Eräpäivän ylitys

- tilauskasittely/otsik_siirtolista.inc
Korjattu tilanne jossa toimitettu siirtolista päivitettiin virheellisesti kesken-tilaan kun siirtolistan otsikkoa muokattiin.
> Siirtolistan muokkaus

- myyntires/myyntilaskut_asiakasraportti.php
Myyntireskontran asiakasraportti ohjelmassa ei enää tulosteta suorituksen viestiä suoraan "Maksusuoritukset"-sarakkeeseen, vaan näytetään infopallo josta saa viestin auki kun hiiren kursorin vie infopallon päälle.
Viestit olivat usein pitkiä ja vaikeuttivat taulukon lukemista kun ne tulostettiin sellaisinaan "Maksusuoritukset"-sarakkeeseen. Nyt luettavuus on parempi kuin aikaisemmin.
> Myyntireskontran asiakasraportti

- inc/functions.inc
- tilauskasittely/tilaus_myynti.php
- tilauskasittely/varaston_tulostusalue.inc
Osataan hakea oikea tulostin riippuen siitä mistä lähetteestä on kyse.
Esim. jos reklamaatiolähetteille määritelty muu tulostin kuin muille lähetteille, niin käytetään sitä.
> Lähetteen tulostus

- tilauskasittely/suuntalavat.inc
Estetään sql-errorin syntyminen. 
Jos poistettiin suuntalava saapumiselta ja sen relaatiot saapumisiin puuttui, syntyi aikaisemmin sql-error.
> Suuntalavan poistaminen

- css/pupesoft.css
- css/pupesoft_legacy.css
- inc/functions.inc
- inc/myymyyjat.inc
- raportit/myymyyjat.js
- raportit/myymyyjat.php
- tervetuloa_signa.inc
* Uusi, tarkempi versio myyjien myynnit raportista
* Näytetään katteet osastoittain
* Näytetään raportin luvuille otsikot
* Näytetään myyjäkohtaisesti kauden katteiden summat
* Piilotetaan valinnat oletuksena
* Raporttia voi rajata myyjällä ja osastolla
* Raportin oletuspäivämääräväli on kuluva kvartaali
* Raportin valinnat voidaan tallentaa oletuksiksi (Ei päivämääräväliä, koska on dynaaminen)
* Myyjien etusivuilla näytetään katteet myös osastoittain
> * Myyjien myynnit osastoittain

- inc/avainsanarivi.inc
Purkulistalle tuki varaston toimipaikan tulostimet (laji vartoimtulostin) -avainsanoissa.
> Toimipaikan reklamaatiotulostin

- rajapinnat/relex/relex_products.php
Uusi ominaisuus jolla voidaan vaikuttaa miten Relex tuoteaineistoon valitaan päätoimittaja. 
Oletuksena päätoimittajaksi tulee Pupen päätoimittaja (järjestykseltään ensimmäinen). Jatkossa tuotteen avainsanoissa voi kertoa että tämän tuotteen kohdalla päätoimittaja valitaan sen mukaan mikä tuotteen toimittajista on edullisin. Vertailussa huomioidaan tuotteen ostohinnat, alennukset, mahdollinen toimittajan kuluprosentti ja vaihto tehdään vain jos halvin tuote on yli 5% halvempi kuin Pupen päätoimittaja. Lisäksi avainsanoissa voidaan antaa erillinen kuluprosentti, mikäli se nähdään tarpeelliseksi. Tämä kulu huomioidaan halvimmassa tuotteessa.
> Relex, tuotteen päätoimittajan valinta

- myyntires/myyntilaskut_asiakasraportti.php
Nimitiedot haetaan aktiivilta asiakkaalta, mutta laskut sekä aktiiveilta että poistetuilta asiakkailta, joilla sama ytunnus
> Myyntireskontra: asiakasraportti

- rajapinnat/edi.php
- tilauskasittely/editilaus_in.inc
* siirretty vaihtoehtoisen yhtiökäsittelyn koodi editilaus_in.inc -> edi.php
> RE: Editilauksen vaihtoehtoinen yhtiökäsittely

- inc/asiakastarkista.inc
- kopioiasiakas.php
Luottoraja kopioituu muitten tietojen mukana vaikka olisi "näytetään saatavat per y-tunnus" valittuna.
Uutta asiakasta luotaessa katsotaan löytyykö annetun Y-tunnuksen perusteella luottoraja ja jos löytyy, kopioidaan se uudelle asiakkaalle.
> Asiakkaan luottoraja

- rajapinnat/tuote_export.php
- rajapinnat/tuotexml.inc
Anvian tuotesiirtoon lisätty 3 kenttää
* description - Tuotteen mainosteksti
* handlingunit - Tuotteen yksikkö
* handlingunitfactor - Tuotteen myyntierä
> * Anvia-rajapinnan uudet kentät

- raportit/myohassa_olevat.php
- raportit/naytatilaus.inc
Näytetään nyt myös "Asiakkaan tilaukset" -ohjelmassa, sekä "Myöhässä olevat" -ohjelman excelissä
> * Tilausrivin korvamerkintä

- tilauskasittely/tilaus_myynti.php
Reklamaatioilla valitaan tulostimet aina manuaalisesti reklamaation valmiiksi laittamisen jälkeen (lyhyt reklamaatiokäsittely). Kun reklamaation pistää valmiiksi, tulee ruudulle mahdollisuus kertoa mihin printteriin purkulistan tulostaa (ja joissakin tapauksissa myös lähetteen).
> Reklamaation paperit

- rahtikirja-tulostus.php
Toimituksen puhelinnumero otetaan tilauksen otsikolta postitarralle
> Toimituksen puhelinnumero

- tilauskasittely/sarjanumeroseuranta.php
Vähennettäessä sarjanumerollisen tuotteen kappalemäärä saapumisella johon oli jo liitetty tarvittava määrä sarjanumeroita tuli ongelma sarjanumeroiden määrän vähentämisen kanssa. Sarjanumeroita ei saanut enään kappalemäärän vähentämisen jälkeen irroitettua saapumisrivistä, jos sarjanumeroita oli rivillä useampia kuin saapumisirivin kappalemäärän verran. Tämä on nyt korjattu ja myös tälläisessä tilanteessa on mahdollista irroittaa sarjanumeroita saapumisrivistä.
> Sarjanumerolliset tuotteet saapumisella

- tuote.php
Jos toimipaikan varasto merkittiin poistetuksi, näkyi se varastopaikat -luettelossa, mutta sen tapahtumia ei näytetty.
Nyt näytetään tuotteen tapahtumissa myös poistokoodatun varaston tapahtumat
> Tapahtumat tuotekyselyssä

- inc/tuotteen_avainsanattarkista.inc
Poistettujen tuotteiden avainsanoja saa poistaa.
> Lue data: tuotteen avainsanojen päivitys

- inc/tuotteen_avainsanatrivi.inc
Tuotteen avainsanoihin lisätty uusi laji 'hinnastoryhmittely'.
Nyt tätä avainsanaa pystyy päivittämään myös käyttöliittymän kautta
> Tuotteen avainsanat

- tervetuloa_signa.inc
Revertoidaan tervetuloasivun muutokset
> Revert muutokset toistaiseksi

- raportit/ostoehdotus_cs.php
- käyttöliittymään optio rajata ostoehdotusta keräyspäivämäärällä
> Ostoehdotusraportin rajausperustemuutos

- tilauskasittely/vastaanota.php
Näytetään varastosiirtojen vastaanotossa toimipaikkarajaus vain jos on käytössä laaja toimipaikkakäsittely.
> Varastosiirtojen vastaanotto: toimipaikkarajaus

- inc/functions.inc
- kerayksen_kuittaus_ulkoisesta_jarjestelmasta_cron.php
- uudelleenlaheta-postnord.php
* Sallitaan myös siirtolistojen manuaalinen lähetys PostNordiin Varasto --> PostNord-keräyssanoma -valikosta
* Merkitään siirtolistat kerätyksi, kun ne luetaan PostNordista sisään
> Siirtolistat PostNordiin

- inc/functions.inc
- kerayksen_kuittaus_ulkoisesta_jarjestelmasta_cron.php
- uudelleenlaheta-postnord.php
Reverts devlab-oy/pupesoft#2374
> Revert "Siirtolistat PostNordiin"

- inc/functions.inc
- tilauskasittely/mikrotilaus.inc
- tilauskasittely/mikrotilaus_ostotilaus.inc
Reverts devlab-oy/pupesoft#2377
> Revert "Ostotilauksen rivien luku excelistä"

- inc/functions.inc
- inc/yhtion_parametritrivi.inc
- tilauskasittely/keraa.php
- tilauskasittely/lahetteen_tulostusjono.php
- tilauskasittely/tilaus-valmis-tulostus.inc
- tilauskasittely/tilaus_myynti.php
- tilauskasittely/tulosta_lahete_kerayslista.inc
- tilauskasittely/vastaanota.php
Reverts devlab-oy/pupesoft#2387
> Revert "Revert "REKLAMAATIO: Koontipurkulista""

- inc/functions.inc
- kerayksen_kuittaus_ulkoisesta_jarjestelmasta_cron.php
- uudelleenlaheta-postnord.php
Reverts devlab-oy/pupesoft#2386
> Revert "Revert "Siirtolistat PostNordiin""

- raportit/myyntiseuranta.php
- raportit/ostoseuranta.php
* Mahdollista ajaa myynti- ja ostoseurantaraportit toimitusehdoittain
> Myynti- ja ostoseurantaraportit toimitusehdoittain

- tilauskasittely/saldovahvistus.php
Korjattu "Näytä PDF"-toiminto. Nyt PDF aukeaa uuteen ikkunaan.
> Saldovahvistus

- inc/functions.inc
- raportit/sql-query.php
* Lisätään SQL haku -ohjelmaan mahdollisuus tallentaa hakuja, jos ohjelmaa käytetään alanimellä SUPER
* Hauille tallennetaan myös nimi ja haluttaessa kuvaus
* Tallennetut haut näkyvät dropdownissa otsikon alapuolella
* Hakuja voi poistaa, jos alanimenä on SUPER
> * SQL-hakujen tallennus

- inc/functions.inc
- tilauskasittely/mikrotilaus.inc
- tilauskasittely/mikrotilaus_ostotilaus.inc
Toimituspäivämäärät toimimaan excelistä oikein. Aiemmin päivämääräksi meni excelistä aina tämä päivämäärä.
> Ostotilauksen luku excelistä

- tilauskasittely/tarkistarivi.inc
- tilauskasittely/tilaus-valmis.inc
Ei anneta luoda myyntitilaukselta varastosiirtoja, mikäli myyntitilaus ollaan painettu jo kerran valmiiksi.
> Myynnistä varastosiirto

- raportit/myyntiseuranta.php
* Kirjoitetaan myynninseurantaraportin summat numeroina Exceliin
> Myynninseurantaraportin summat numeroina

- rajapinnat/relex/relex_products.php
Aineiston rakennuksessa voidaan sanoa toisena parametrina "weekly", jolloin aineiston luomiin tiedostoihin merkitään ennen ajopäivää "weekly" ja aineistoon haetaan kaikki mahdolliset tuotteet. 
Lisäksi aineisto toimitetaan ftp:llä Relexille kuten dailyssä, mikäli ftp-tunnukset on asetettu.
> Relex products

- inc/functions.inc
- inc/yhtion_parametritrivi.inc
- rajapinnat/relex/relex_products.php
- tilauskasittely/lahtojen_hallinta.php
- tilauskasittely/tilaus_myynti.php
- tyomaarays/tyomaarays.inc
- ulask.php
Yhtiön parametrillä reklamaation_kasittely ja arvolla "Reklamaation käsittelyssä käytetään laajempaa prosessia purkulistalla ja purkukuittauksella. Takuu lyhyemmällä prosessilla" käsitellään jatkossa takuut lyhyellä prosessilla.
Lisäksi korjattu tehdaspalautustilauksen luonti reklamaatiolta (toimi aikaisemmin vain lyhyessä prosessissa).
> Lyhyt takuuprosessi

- raportit/myyntiseuranta.php
* Näytetään myyntiseurantaraportin data oikein excelissä myös siinä tapauksessa, jos näytetään laajat asiakastiedot
> Myyntiseurantaraportin exceldata

- raportit/sql-query.php
* Lisätään SQL haku -ohjelmaan mahdollisuus ajaa tallennettuja hakuja, jos ohjelmaa käytetään alanimellä READ
* READ oikeuksilla käyttäjä ei voi itse kirjoittaa SQL:ää, vaan hän voi vain ajaa tallennettuja hakuja
> * Tallenettujen SQL-hakujen ajo

- inc/unifaun_send.inc
- tilauskasittely/rahtikirja_unifaun_uo_siirto.inc
* Siirretään unifauniin summa ja viite, jos kyseessä on postiennakko
> Postiennakon tiedot Unifauniin

- inc/valitse_tulostin.inc
* Tiliöidään summat oikein työmääräyksissä käteismyynnissä
> Työmääräysten tiliöintien korjaus

- inc/functions.inc
Uudelleenlähetys tilauksen tilasta riippumatta
> Keräyssanoman lähetys ulkoiseen järjestelmään

- tilauskasittely/tilaus_myynti.php
* Käytetään oikeaa columnia asiakasryhmälle asiakashinnassa
> Asiakasryhmä oikeaan sarakkeeseen

- raportit/ostoehdotus_cs.php
* Korjauksia Ostoehdotus BIO-raporttiin
> Ostoehdotus BIO fix

- raportit/sql-query.php
* Encodetaan tallennettava query myös, kun se setataan javascriptillä, jolloin se tallentuu oikein
> Korjaus SQL-hakujen tallennukseen

- optiscan.php
Jos syystä tai toisesta Optiscaniin otettava keräyserä jää kesken, mutta itse keräyserä on päivittynyt kerayserat-tauluun ja kerääjä pyytää uudelleen keräyserää. Pupe huomaa, että kerääjällä on kesken oleva keräyserä ja antaa sen, ja samalla tarkistetaan, että myyntitilauksen/siirtolistan otsikolla tila-tiedot ovat kunnossa
> Keräyserän muodostus jää kesken

- tilauskasittely/jtselaus.php
Jt- ja ennakkoselaus ohjelmiin on lisätty "Toimitettavat jälkitoimitusrivit yhteensä" rivi "Kaikki jälkitoimitusrivit yhteensä" yhteyteen. Riville lasketaan kaikkien toimitettavien jälkitoimitusrivien arvo yhtensä. Kuten myös kaikki yhteensä rivi näytetään toimitettavat yhteensä rivi aina.
> JT- ja ennakkoselaus

- raportit/ostoseuranta.php
* Mahdollista ajaa ostoseurantaraportti maittain
> * Ostoseurantaraportti maittain

- rajapinnat/lumo_handler.inc
- tilauskasittely/tilaus_myynti.php
* Maksupäätteellä tehdyt hyvitysmaksut merkitsevät tilauksen nyt oikein valmiiksi, jos summa täyttyy, jolloin myös kuitti tulostuu
> Korjaus maksupäätteellä tehtyihin hyvityksiin

- inc/functions.inc
- inc/keikan_toiminnot.inc
- tilauskasittely/ostotilausten_rivien_kohdistus.inc
Saapumisen summan päivitys funktioitu. Päivitetään summa saapumisen otsikolle aina kun kohdistetaan rivi.
> Saapumisen summa

- tilauskasittely/ostotilausten_rivien_kohdistus.inc
Kun myyntihintaa muutetaan saapumisrivillä, päivitetään myös muutospäivä. Näin saadaan uusi myyntihinta päivittymään esim. verkkokauppaan silloin, kun päivitetään vain muuttuneet tiedot
> Myyntihinta saapumisrivillä

- inc/functions.inc
- tyomaarays/tyojono.php
* Korjattu työjononäkymän työstatus / työjono dropdownien livesearch
> Työjononäkymäfix

- inc/muutosite.inc
- raportit/kateismyynnit.php
- tilauskasittely/teelaskuntiliointi.inc
- tilauskasittely/tilaus_myynti.php
Osataan näyttää käteismyynnit-raportissa myös sellaiset laskut jotka on maksettu vain osittain käteisellä.
> Osittain käteisellä maksettujen täsmäytys

- inc/toimitustapatarkista.inc
Ei uudelleennimetä toimitustapojen sarakkeita vak_kielto ja vaihtoehtoinen_vak_toimitustapa virheellisesti luotaessa uutta toimitustapaa
> Korjaus uuden toimitustavan perustamiseen

- inc/unifaun_send.inc
Jälkivaatimussumman ja -viitteen yhteydessä Unifauniin on lähetettävä myös pankkitilitiedot.
> Jälkivaatimus Unifauniin

- tilauskasittely/rahtikirja_pdf.inc
Useamman pakkauksen tapauksessa rahtikirjalle jäi välillä tulostumatta osa pakkausriveistä. Nyt tämän on korjattu ja rahtikirjalle tulostetaan aina kaikki pakkausrivit.
> Rahtikirjan rivit kuntoon

- inc/naytaviitteet.inc
- inc/viitemaksut.inc
Nordean viiteaineistossa tulee myös oikaisurivejä, jotka on aikaisemmin jätetty käsittelemättä.
Nyt oikausurivit päivitetään pupeen miinumerkkisillä summilla ja kohdistetaan asiakkaaseen, jos mahdollista
> Viiteaineiston oikaisutapahtumat miinusmerkkisenä

- tilauskasittely/tilaus-valmis.inc
Ei unohdeta aiempaa sorttausta, kun sortataan tuotteen vakkoodin mukaan
> Tilausten splittauksen sorttaus fix

- inc/unifaun_send.inc
Unifaun rajapinnassa kuljetusliikkelle Posti välitetään jatkossa saapumisilmoituksen tekoon tarvittavat kentät. Saapumisilmoitus voidaan tehdä puhelinnumerolla ja sähköpostilla. Toimii Postin koodeilla IT09, IT14, IT16 ja IT21.
> * Unifaun: Postin saapumisilmoitus

- css/pupesoft.css
- css/pupesoft_legacy.css
- tilauskasittely/sarjanumeroseuranta.php
Korjataan sarjanumeroseurannan ulkoasua
> Sarjanumeroseurannan CSS fix

- unifaun_fetch.php
DPD:n palautustiedoston numeerisiin SSCC koodeihin lisättiin ylimääräiset nollat.
> Unifaun palautustiedoston käsittely

- tilauskasittely/valmista_tilaus.php
Tarkistetaan, että kaikki tarvittavat tiedot valmistettavista tuotteista on olemassa, jottei jouduta SQL virheeseen. Ilmoitetaan käyttäjälle jos selkeästi jos virhetilanteeseen on päädytty.
> Valmista tilaus virhetarkistus

- tilauskasittely/tilaus-valmis-siirtolista.inc
* Splitataan VAK-tuotteet omalle tilaukselleen varastosiirroissa VAK-tuotteet hyväksyvällä toimitustavalla, jos niin on valittu toimitustavan takaa
> VAK-splittaus varastosiirroissa

- inc/parametrit.inc
- inc/pupenext_functions.inc
- inc/tulosta_tuotetarrat_pdf.inc
- tulosta_tuotetarrat.php
* Tuotetarroja tulostettaessa voidaan valita viivakoodityypiksi QR-koodi, jolloin tuotetarroihin tulostuu perinteisen viivakoodin tilalle QR-koodi
* QR-koodi sisältää saman datan kuin viivakoodikin
> * QR-koodin tulostus tuotetarroihin

- mobiili/tuotteella_useita_tilauksia.php
Kun tuotekoodilla/viivakoodilla haetaan tulouttamattomia rivejä, näytetään sekä ostotilauksilla olevat että suoraan saapumiselle tehdyt rivit, jotka tulouttamatta.
> Mobiili-tulouttaminen

- view.php
Chromella tuli ostolaskuhaun näytä lasku napista esiin pelkästään harmaa ruutu. Tämä korjattu.
> Ostolaskuhaun näytä lasku ominaisuus

- monistalasku.php
- raportit/tyomaarays_seurantaraportti.php
- Työmääräystä monistettaessa ei kopioida sarjanumeroa
- Seurantaraportissa voidaan rajata myös asiakkaalla
- Seurantaraporttia ajettaessa tulee ilmoitus jos annetuilla rajauksilla ei löydy rivejä
> Työmääräyksen ja seurantaraportin muutokset

- rajapinnat/relex/relex_transfer_import.php
- tilauskasittely/tilauksesta_varastosiirto.inc
Relex siirtoehdotuksen sisäänluvussa lisätään jatkossa tuoteperheen lapsirivit siirtolistalle.
> Relex: siirtoehdotuksen tuoteperheet

- rajapinnat/relex/relex_customers.php
- rajapinnat/relex/relex_products.php
- rajapinnat/relex/relex_replacements.php
- rajapinnat/relex/relex_suppliers.php
Ostoehdotus-update, korvaavat, toimittajat ja asiakkaat -aineistoihin tuki "weekly" ajoille. Weekly-ajo on muuten sama kuin täysi aineisto, mutta tiedoston nimessä tulee ilmi weekly ja aineistot toimitetaan ftp:llä automaattisesti.
> Relex: weekly

- inc/unifaun_send.inc
Samalla myös muutama toimitustapa pois MPS:n piiristä.
> Unifaun MPS toistaiseksi pois päältä

- dumppaa_mysqlkuvaus.php
- synkronoi_sanakirja.php
- tullinimikkeet.php
- viranomaistuotteet.php
Hanskataan referenssisynkronoinnit oikein myös Unicode-moodissa.
> * Referenssisynkronoinnin UTF8-moodissa

- raportit/naytatilaus.inc
Asiakkaan tilaukset ohjelmassa oli SQL virhe joka esti tilauksen näyttämisen ruudulle tietyissä tapaukissa. Tämä korjattu.
> Asiakkaan tilaukset

- rajapinnat/paivita_myytavissa_static.php
Uusi kenttä myytavissa_static tuotepaikalle. Tänne päivitetään tarpeen mukaan esim kerran tunnissa tuotteen myytävissäolevamäärä.
> * Myytävissä oleva määrä esim. verkkokaupalle

- inc/functions.inc
- yllapito.php
* Jos piirretään iframe aliassettinäkymästä, niin piirretään ensisijaisesti myös iframe samasta aliassetistä
> Parannus aliassetteihin

- kerayksen_kuittaus_ulkoisesta_jarjestelmasta_cron.php
Jo käsin kerätyksi ja laskutetuksi merkityt tilaukset palautuivat toimitettu tilaan, kun niistä tuli ulkoisesta järjestelmästä kuittaus tilauksen keräyksestä. Tämä on nyt korjattu ja jo laskutettuja tilauksia ei enää palauteta toimitettu tilaan vaikka kuittaus niiden keräyksestä ulkoisesta järjestelmästä vielä tulisi.
> Kerayksen kuittaus ulkoisesta jarjestelmasta

- tuoteperhe.php
* Haetaan myös isätuotteen nimityksellä tuoteperhehaussa tuoteresepteissä
> Korjaus tuoteperhehakuun tuoteresepteissä

- rajapinnat/magento_client.php
- verokanta lisätty kauppakohtaisiin parametreihin
- voidaan määritellä salasanat.phpssä
> Magenton kauppakohtainen verokanta

- muokkaatilaus.php
Oletuksena avoimia tilauksia näytetään 50 uusinta, mutta käyttäjä voi valita, että näytetään kaikki avoimet.
Kun otti avoimet exceliin, siinä ei huomioitu aikaisemmin käyttäjän valitsemaan rajausta, vaan exceliin meni aina vai 50 uusinta tilausta. Nyt exceliin menee 50 tai kaikki avoimet riippuen käyttäjän rajauksesta.
> Avoimet tilaukset exceliin

- inc/maksupaate_funktiot.inc
- raportit/naytatilaus.inc
> Viennin lisätietojen syöttö

- yllapito.php
Perustietojen ylläpidon koodissa ollut virhe korjattu. Aiheutti valkoisen sivun.
> Perustietojen ylläpito

- tilauskasittely/otsik.inc
Näytetään asiakasfakta aina kun mennään otsikolle jos se on asiakkaan takana olemassa.
> Myyntitilauksen otsikko: asiakasfakta

- rajapinnat/tuote_export.php
- Anvian hinnat muuten verottomia, mutta myymälähinta verollinen
> Export hintatuunaus

- inc/verkkolasku-in-erittele-laskut.inc
- inc/verkkolasku-in.inc
- verkkolasku-in.php
Hanskataan verkkolaskujen merkistökoodaukset paremmin
> Verkkolaskujen merkistökoodaus

- tilauskasittely/tilaus_myynti.php
Tarjouksen kuittaaminen maksetuksi on estetty, mutta nyt oli maksupäätteen oleessa käytössä mahdollista kuitata tarjouksia jo maksetuiksi. Estetään tarjousten maksaminen myös maksupäätteen ollessa käytössä.
> Tarjous: käteismaksuehto

- inc/functions.inc
- inventoi.php
- muuvarastopaikka.php
- tilauskasittely/tulosta_purkulista.inc
- tilauskasittely/vastaanota.php
Siirtolistojen vastaanotossa virheellisesti hukattiin kohdepaikka. Enää ei hukata!
> Siirtolistojen vastaanotto

- tilauskasittely/rahtikirja_postitarra_pdf.inc
Kasvatattiin postitarran puhelinnumeron fontin kokoa hieman.
> Postitarra: puhelinnumeron fontin koko

- inc/avainsanarivi.inc
- inc/valitse_tulostin.inc
- inc/yhtion_parametritrivi.inc
- inventoi.php
- inventointi_listat.php
- raportit/inventointipoikkeamat.php
```SQL
ALTER TABLE inventointilista ADD COLUMN vapaa_teksti text not null default '' AFTER naytamaara;
ALTER TABLE inventointilistarivi ADD COLUMN rivinro integer not null default 0 AFTER aika, ADD COLUMN hyllyssa decimal(12,2) not null default 0.0 AFTER rivinro, ADD COLUMN laskettu decimal(12,2) default null AFTER hyllyssa;
ALTER TABLE yhtion_parametrit ADD COLUMN laaja_inventointilista char(1) not null default '' after inventointi_yhteenveto;
> Laaja inventointilista

- inventoi.php
Voidaan inventoida myös toisten sivujen nollarivi
> Inventointilista: nollarivin inventointi

- inventoi_korjaus_tiliointi_kirjanpitoon.php
Jos inventoitiin yksittäinen tuote ilman inventointilistaa, tiliöinnit jäi puuttumaan
> Puuttuvat tiliöinnit inventointitapahtumiin

- maksuaineisto_get.php
- maksuaineisto_send.php
- lisätty porttituki maksuaineisto_get ja maksuaineisto_send skripteille
> Maksuaineiston haku ftp:llä

- kayttajat.php
Voidaan valita myös extranet käyttäjile poikkeava käyttöliittymä
> Extranet käyttäjien käyttöliittymä

- myyntires/paperikarhu.php
Sähköiselle maksumuistutukselle myyjän tiedot uusimmasta karhuttavasta laskusta
> Sähköinen maksumuistutus

- matkalasku.php
Kulujen kirjapidon tiliöinteihin selitteeseen mukaan päivämäärä- ja aikatiedot.
> Matkalaskut: kulujen päivämäärät

- inc/yhtion_parametritrivi.inc
- tilauskasittely/sarjanumeroseuranta.php
* Vaihdetaan automaattisen sarjanumeroinnin kaavaksi kuluva vuosi - 100 alkava numerointi, esim "2015-118"
> Automaattisen sarjanumeron muodostus

- inc/unifaun_send.inc
Postin IT16 saapumisilmoitus osataan jatkossa tehdä vaikka puhelinnumeroa ei löydykkään, mutta email löytyy. Laitetaan siinä tapauksessa saapumisilmoitukseen pelkkä email. Jos puhelinnumerokin löytyy, niin laitetaan sekin.
> Unifaun: Postin saapumisilmoitus, email

- css/pupesoft.css
- tuoteperhe.php
* Parannetaan tuotereseptitaulukon ulkoasua tekemällä siitä mukautuvampi sisältöön
* Poistetaan kertoimesta ja kehahinnasta turhat desimaalit
* Näytetään reseptin riviä muokatessa myös nimitys ja yksikkö
* Vaihdetaan avainsanoista tulevien kenttien paikkaa taulukossa
* Lisätään mahdollisuus kirjoittaa Exceliin myös malli, mallitarkenne ja tuotemerkki
> Parannuksia tuotereseptinäkymään

- maksuaineisto_send.php
Maksuaineistot UTF8 silloin kun Pupesoft on UTF8.
> Maksuaineistot UTF8 merkistönä

- inc/laskuhaku.inc
Laajennettu laskuhaun vuosirajausta; aiemmin sallittiin katsoa 4 vuotta taakseppäin nyt väliä pidennetty 10 vuoteen.
> Laskuhaku: haun alku- ja loppupvm

- inc/tallenna_keraysera.inc
Pidetään tallessa paremmin keräyserän tilausnumeroita.
> Tallenna keräyserä: tilausnumeroiden käsittely

- inc/functions.inc
* Ei haeta samaa reseptiä monta kertaa, jolloin vältytään infinite loopilta
> Korjaus tuotereseptien rekursiivisuuteen

- inc/asiakkaan_avainsanatrivi.inc
- inc/avainsanarivi.inc
- optiscan.php
Optiscan keräyskommentti lisätty asiakkaan avainsanoihin. 
- Vaatii avainsanoihin uuden asiakkaan avainsanalajin "OPTISCAN_KERAYSKOMMENTTI".
- Alasvetovalikon valinnat perustetaan avainsanoihin (laji OPTISCANKOM)
> Optiscan: keräyskommentti

- rajapinnat/relex/relex_products.php
Myyntihinta mukaan tuoteaineistoon
> Relex: myyntihinta

- rajapinnat/relex/relex_warehouse_location.php
Jos tuotepaikalle on merkitty "D" eli poistettu, niin lisätään aineistoon TRUE, muuten FALSE.
> Relex: warehouse location poistettava-kenttä

- inc/verkkolasku-in.inc
- inc/yhtion_parametritrivi.inc
Käytetään toimittajan oletusvaluuttaa verkkolaskujen vastaanotossa, jos parametri on päällä.
```SQL
ALTER TABLE yhtion_parametrit ADD COLUMN ostolaskujen_oletusvaluutta CHAR(1) NOT NULL DEFAULT '' AFTER ostolaskujen_paivays;
> * Verkkolaskujen vastaanoton oletusvaluutta

- inc/unifaun_send.inc
Nimistä vaihdetaan "&"-merkki -> "&amp;"-merkeiksi
> Unifaun: ampersand

- myyntires/paperikarhu.php
Maksukehotuskopioilta puuttui yhteensä summa kohta maksukehotuksen lopusta. Yhteensä kohta on nyt lisätty myös maksukehotuskopioille.
> Maksukehotus: yhteensä summa kopioissa

- tuoteperhe.php
> Tuoteperhe: tekstikorjaus

- inc/tuoterivi.inc
- tilauskasittely/lisaarivi.inc
- tilauskasittely/tilaus_osto.php
- tuotteelle voi antaa ostokommentin joka lisätään kommentiksi ostotilausriville
```sql
alter table tuote add column ostokommentti text after purkukommentti;
> Tuotteen ostokommentti

- inventointi_listat.php
Jos yritti tehdä inventointilista niin, että listalle rajautuisi tietyt tuotteet varastonarvovaikutuksen mukaan, niin tästä seurasi SQL virhe. Tämä virhe on nyt korjattu ja jatkossa myös tälläisillä rajauksilla voi tehdä inventointilistoja.
> Inventointilista: SQL korjaus

- kayttajat.php
Generoidaan salasana javascriptin avulla.
> Käyttäjähallinta: Generoi salasana

- inc/asiakashaku.inc
- tilauskasittely/otsik.inc
Nyt asiakasta vaihdettaessa toim_puhno haetaan samalla tavalla kuin asiakasta lisättäessä myyntitilaukselle
> Myös asiakasta vaihdettaessa päivitetään toim_puhno

- tilauskasittely/ostotilausten_rivien_yhdistys.inc
Saapumisen yhdistämisessä päivitetään suuntalavat "isäsaapumiselle".
> Saapumisen yhdistys & suuntalavat

- mobiili/hyllytys.php
- mobiili/ostotilaus.php
- mobiili/suuntalavalle.php
- mobiili/tuotteella_useita_tilauksia.php
- mobiili/uusi_kerayspaikka.php
- mobiili/vahvista_kerayspaikka.php
Tulouttaessa voidaan nyt hakea ostotilauksen rivejä myös saapumisnumerolla. Saapumisnumero muistetaan koko prosessin ajan ja vaikuttaa vain rivien hakuprosessiin.
> Mobiili: tuloutus saapumisnumerolla

- tilauskasittely/tulostakopio.php
Takuukopiossa saattoi joutua SQL-virheesee asiakkaalla takuukopioita haettaessa. Virhe on nyt korjattu eikä enään jouduta SQL-erheeseen.
> Takuukopio: SQL-virheen korjaus

- tilauskasittely/tulostakopio.php
* Lisätään ohjelma, jolla voi tulostaa koonti-dgd -kopioita
> Koonti-DGD -kopio

- tilauskasittely/maksutapahtumaselaus.php
* Näytetään maksutapahtumaselauksessa myös sellaiset tilaukset, joilla ei ole maksupäätetapahtumia
> Käteistapahtumat maksutapahtumaselaukseen

- crm/asiakaslista.php
- inc/asiakas.inc
- inc/functions.inc
- inc/kevyt_toimittajahaku.inc
- inc/liitetiedostot.inc
- inc/toimi.inc
- inc/toimittajahaku.inc
- kopioitoimittaja.php
- tiliointisaannot.php
- yhdistaasiakas.php
- yllapito.php
Liitetiedostojen järjestykseen ei pystynyt vaikuttamaan liitetiedoston järjestys tiedolla. Tämä on nyt korjattu ja jatkossa järjestystiedolla voidaan vaikuttaa liitetiedostojen järjestykseen.
Samalla deprikoitu asiakas.selaus ja toimi.selaus-kenttien ominaisuudet.
> Tuotetiedot: liitetiedostojen järjestys

- ulask.php
Ostolaskuun voidaan nyt liittää KOLME liitetiedostoa!
> *Ostolaskun liitteet

- inc/functions.inc
- inc/parametrit.inc
- inc/tuotehaku.inc
- tilauskasittely/tilaus_myynti.php
- tilauskasittely/tuote_selaus_haku.php
* Ei näytetä tuotteen epäkurantiutta pikahaussa extranetissä
* Ei korosteta epäkurantteja tuotteita livesearchissa extranetissä
* Näytetään myös extranetissä tilauksen tilausrivien hinnat yhtiön alv-käsittelyn mukaan
* Korjataan tilauksella olevat alvillisuus radiobuttonit toimimaan oikein
> Korjauksia extranettiin

- tilauskasittely/teeulasku.inc
Laskunkommenteista siivottiin aiemmin : ja _ merkit pois. Tätä muutettu nyt niin, että nämä merkit säästetään kommenteissa.
> Laskun kommetti: erikoismerkit

- tilauskasittely/tilaus_myynti.php
Asiakkaan tilausnumero katosi myyntitilaukselta tilauksen tietoja muokattaessa. Tämä ongelma on nyt korjattu ja asiakkaan tilausnumeroa ei kadoteta päivitettäessä muita tietoja myyntitilauksella.
> Myyntitilaus: asiakkaan tilausnumero

- inc/edifact_functions.inc
- toimitusten_seuranta.php
* Käsitellään samaan autoon eri aikoina tapahtuvat lastaukset eri lastauksina
> Saman auton eri lastaukset

- kayttajat.php
* Tehdään salasanan generointinapista tyypiltään buttoni, jotta nappi ei varasta enterin painamista
> Korjaus salasanan generointiin

- inc/yhtion_parametritrivi.inc
- tilauskasittely/tulosta_lahete.inc
* Lisätään yhtiön parametri, jolla voi valita, tuleeko tilausvahvistuksen saatesähköpostiin tilausnumero vai asiakkaan tilausnumero. Jos parami on päällä myös tilausvahvistus-pdf-tiedosto nimeen lisätään asiakkaan tlausnumero.
> * Asiakkaan tilausnumero tilausvahvistukseen

- inc/edifact_functions.inc
* Otetaan myös konttierittelyssä huomioon saman auton käyttö useassa lastauksessa
> Konttierittely lastauksittain

- inc/tulosta_tuotetarrat_pdf.inc
- tilauskasittely/sarjanumeroseuranta.php
* Sarjanumeroseurannassa voidaan tuotteiden valmistuksessa tulostaa valituille sarjanumeroille tarrat PDF:nä ruudulle
> * Sarjanumerotarrojen tulostus

- inc/edifact_functions.inc
* Poistetaan lastausaika konttierittelystä
> Lastausaika pois konttierittelystä

- tilauskasittely/ostotilausten_rivien_yhdistys.inc
Otetaan huomioon vain rivit joilla on suuntalava
> Saapumisten yhdistäminen: suuntalavat

- tilauskasittely/tilaus_myynti.php
* Poistetaan kpl-kentästä autocomplete
> Autocomplete pois kpl-kentästä

- rajapinnat/logisticar.php
* Lisätään tuotteen epäkuranttiustiedot Logisticarin siirtotiedostoon
> Epäkuranttitiedot Logisticariin

- tuoteperhe.php
Raaka-aineiden lisäyksessä voi muokata jo kaikkia muokattavissa olevia rivejä. Aiemmin kaikki rivit muokattavissa olevat raaka-aineiden tiedot eivät olleen lisäysvaiheessa vielä muokattavissa vaan riviä piti käydä erikseen muokkaamassa, jotta näitä tuetoja pystyi päivittämään.
> Tuotereseptit: korjauksia raaka-aineiden lisäämiseen

- css/pupesoft.css
- css/pupesoft_legacy.css
- extranet_tilaukset_ilmoitus.php
- inc/functions.inc
- inc/pupeExcel.inc
- muuvarastopaikka.php
- pupe_xslx_template/xl/styles.xml
- rahtikirja-tulostus.php
- tilauskasittely/lahtojen_hallinta.php
- tilauskasittely/ostotilausten_rivien_yhdistys.inc
- tilauskasittely/sarjanumeroseuranta.php
- tilauskasittely/tilaus_myynti.php
- tilauskasittely/tuote_selaus_haku.php
- tuote.php
- tuoteperhe.php
- vahvista_asiakas_jt_rivit_email.php
* Lisätään tuotteen ostohinta reseptinäkymään
* Järjestetään reseptien raaka-aineet tuotenumeron mukaan
* Yliviivataan poistetut tuotteet reseptinäkymässä ja sieltä tallennettavassa excel-tiedostossa
> Tuotereseptiparannuksia

- tilauskasittely/lahetteen_tulostusjono.php
* Lisätään tilauksen kokonaispaino tulosta keräyslistä -näkymään
> Paino tulosta keräyslistaan

- inc/tuotehaku.inc
* Haetaan tuotehaussa tuotetta myös asiakaskommentilla, kun kyseessä on myyntitilaus ja, jos ei muuten löydy
> Tuotehaku asiakaskommentilla

- tilauskasittely/sarjanumeroseuranta.php
- tilauskasittely/tilaus_osto.php
Sarjanumeroseuranta. Myynti / Keskihinta-varastonarvo (T) herää henkiin oikeasti vasta myyntipuolella. Ostopuolella ei voi eikä pidä jumpata näitten sarjanumeroien kanssa.
> Sarjanumeroseuranta T

- inc/edifact_functions.inc
- inc/laskutyyppi.inc
- saapuva_rahti.php
- sarjanumero/hae_tiedot.php
- sarjanumero/kontitus.php
- sarjanumero/tuloutus.php
- toimitusten_seuranta.php
- varastotilanne.php
* Otetaan laskun tila ja alatila käyttöön rullatilauksille
> Laskun tila ja alatila käyttöön RP:lle

- tilauskasittely/tarkistarivi_ostotilaus.inc
- tilauskasittely/tilaus_osto.php
* Annetaan mahdollisuus lisätä annettu määrä tuotetta aiemmalle tilausriville ostotilauksella, jos on valittu, että samaa tuotetta ei voi lisätä useammalle tilausriville
> Parannus saman tuotteen lisäykseen ostotilaukselle

- hyvaksyttavia_laskuja_cron.php
* Lähetetään sähköpostiviesti hyväksyttävistä laskuista kyseisten laskujen nykyisille hyväksyjille
> * Sähköpostiviesti hyväksyttävistä laskuista

- inc/hyvaksynta.inc
Päivämäärällä sorttaus korjattu toimimaan oikein
> Hyväksyttävänä olevien laskujen sorttaus

- tilauskasittely/tilaus_myynti.php
'Näytetään kate' ja 'Ei näytetä katetta' laitettu käännettäviksi sanoiksi
> Lisätty t-funktiot katteen näyttämis-nappuloihin

- tuote.php
* Tarkistetaan tuotekyselyssä, onko käyttäjällä oikeus johonkin tuotteen aliassettiin ja näytetään muokkauslinkki sinne
> Tuki tuotehallinnan aliasseteille tuotekyselyyn

- muokkaatilaus.php
- tilauskasittely/tilaus_myynti.php
Piilotettu rivien verollisuvalintanappulat ja rivien katenäyttönappulat.
> Myyntitilauksen käyttöliittymästä "turhat" piiloon

- inc/verkkolasku-in-finvoice.inc
- inc/verkkolasku-in.inc
- tiliointisaannot.php
"Tuotesäännöt"-tyyppisellä tiliöintisäännöllä voidaan täpätä, että verollisella rivillä ei ole vähennettävää veroa.
> * Tiliöntisääntö

- suori.php
Korjattiin tilanne, jossa jos käyttäjä ei ollut syöttänyt summaa kotivaluutassa eikä laskun valuutassa jouduttiin SQL erroriin. Nyt tälläisessä tapauksessa informoidaan käyttäjää syöttämään jompi kumpi näistä tiedoista, koska tieto tarvitaan.
> Ostoreskontra/suoritukset: SQL virheen korjaus

- raportit/myyntiseuranta.php
Tallennetaan varastonarvo, kierto ja varastonkpl sarakkeiden tiedot jatkossa numeerisina exceliin, jotta niitä pystyy helpommin excelissä käsittelemään.
> Myynninseurantaraportti: kenttien tyypit

- inc/pankkitiedot.inc
Muutamilla pankeilla oli vaihtunut BIC-koodit, joten päivitetty automaattinen BIC-koodien luonti vastaamaan tämän hetken tilannetta.
> BIC-koodin luonti: koodien päivitys

- tilauskasittely/otsik.inc
Voidaan lisätä tarkiste käsinsyötettyyn viitenumeroon myyntitilauksen otiskolla nappia painamalla
> *  Tarkiste käsinsyötettyyn viitenumeroon

- inc/tiliote.inc
SEB kuittikoodihäkki. Triggeröidään kuittikoodi jos koodi on 705 ja selite INCOMING BATCH WITH REFERENCES
> SEB tiliote

- inc/muutosite.inc
Voidaan vaihtaa myös suljetun kauden ostolaskun tyyppiä. Tällöin ei kuitenkaan kosketa kirjanpitoon.
> * Ostolaskun tyyppi

- tilauskasittely/tulosta_ostotilaus.inc
Ostotilaustulosteen alalaidan tekstien sijainteja muokattu hieman, jotta päällekkäisyyksiä ei tulisi niin herkästi.
> Ostotilaus: pdf viilaus

- inc/tiliote.inc
Lisätty poikkeus: SEPA CREDIT TRANSFER
> tiliotteen sisäänluku

- inc/asiakastarkista.inc
- inc/toimitarkista.inc
Muutos asiakkaan ja toimittajan sähköposti tarkistukseen.
> Sähköpostitarkistus

- pupesoft_changelog.php
- update-pupesoft.sh
Add Pupenext changes to Pupesoft-changelog
> Add Pupenext changes to Pupesoft-changelog

- maksuaineisto_get.php
- Poistetaan ftp-palvelimelta haettu tiedosto ettei sisäänluku tukkiudu
> Maksu ja viiteaineiston hakuscriptfix

- inc/functions.inc
Osatoimituksiin vaikuttavan yhtiön parametrin "Myyntitilaus_osatoimitus" kokonaan osatoimitukset kieltävä vaihtoehto ei aiemmin vaikuttanut työmääräyksiin toisin kuin parametrin muut vaihtoehdot. Muutettu niin, että osatoimitukset kokonaan kieltävä vaihtoehto vaikuttaa samoissa paikoissa kuin muut parametrin vaihtoehdot.
> Työmääräys: osatoimituskieltoparametri

- rajapinnat/M3_customers.php
Voidaan dumpata asiakasdata M3-järjestelmään.
> Voidaan dumpata asiakasdata M3-järjestelmään.

- inc/yhtion_parametritrivi.inc
- tilauskasittely/valitse_laskutettavat_tilaukset.php
- tilauskasittely/verkkolasku.php
Laskutetut laskut voidaan nappia painamalla avata ruudulle laskutuksen jälkeen.
> * Laskutetut laskut ruudulle

- tilauskasittely/editilaus_in.inc
- Haetaan asiakasta ensin toim_ovt + ovt-tunnuksella, jos molemmat tiedot löytyvät
> Editilauksen asiakaskohdistusfix

- rajapinnat/M3_customers.php
- rajapinnat/bynfo/bynfo_balances.php
- rajapinnat/cognos_sales.php
Asiakas, Myynti ja Saldo-rajapintoja
> Uusia rajapintoja

- inc/yhtion_parametritrivi.inc
- tilauskasittely/tulosta_tarjous.inc
Uusi tarjous: kuvallinen tarjouspohja. Uusi tarjouspohja eroaa normaalista tarjouspohjasta niin, että uudessa näytetään tuotenumeroiden vasemmalla puolella tuotteen kuva. Lisäksi tarjouspohjassa on alvierittely tarkemmin, sekä muita pieniä asetteluun liittyviä muutoksia.
> Uusi tarjouspohja

- tyomaarays/etsi.php
- Toiminnallisuutta muutettu hieman, voidaan rajata yhdellä hakusanalla useasta eri sarakkeesta
- Kaksi uutta saraketta rajaukseen: Työn kuvaus sekä Toimenpiteet
> Työmääräysten hakumuutos extra

- iltasiivo.php
- inc/functions.inc
- inc/viitemaksut_kohdistus.inc
- inc/yhtion_parametritrivi.inc
- myyntires/manuaalinen_suoritusten_kohdistus.php
- tilauskasittely/maksusopimus.inc
- tilauskasittely/tilaus-valmis.inc
- tilauskasittely/tilaus_myynti.php
- tilauskasittely/valitse_laskutettavat_tilaukset.php
Kytkemällä päälle "ennakkolasku_myyntitilaukselta"-parametri niin saadaan myyntitilaukselle uusi nappi jolla saa luotua 100% / 0% maksusopimus ja laskutettua ennakkolasku yhdellä klikkauksella.
> * Ennakkolasku yhdellä klikkauksella

- matkalasku.php
Päivärahojen tiliöinneille meni aikakommentti tuplana. Korjattu nyt niin, että päivärahojen tiliöinneille menee kommentit yhden kerran.
> Matkalasku: kommenttikorjaus

- inc/yhtion_parametritrivi.inc
- tilauskasittely/tilaus_myynti.php
- tilauskasittely/tilaus_osto.php
Yhtiön parametrillä "tilaukselle_mittatiedot" voidaan tuoda myyntitilaukselle, ostotilaukselle ja tarjoukselle näkyviin lisättyjen tuotteiden tilavuus ja paino, sekä mahdollinen asiakasosasto.
> Myyntitilaus: tuotteen mittatiedot

- tilauskasittely/tilaus_myynti.php
Tarjouksen toiminto "Siirrä tuotteet asiakashinnoiksi" tehty kaksivaiheiseksi. Painamalla nappia siirrytään näkymään jossa voidaan valita haluttu liitos ja loppupäivämäärä
> Tarjous & "Siirrä tuotteet asiakashinnoiksi"

- rajapinnat/alehinta.php
* Voidaan hakea asiakkaan ja asiakasryhmän alehinta komentoriviltä
> Asiakkaan alehinta komentoriviltä

- rajapinnat/export/balances.php
- rajapinnat/export/bookings.php
- rajapinnat/export/customers.php
- rajapinnat/export/customers_m3.php
- rajapinnat/export/ledgers.php
- rajapinnat/export/sales.php
Kirjanpitorajapinta. Dumpatana ulos kaikki tiliöinnit, lisätyt ja yliviivatut.
> Uusi rajapinta

- extranet/asiakashinnasto.php
- inc/avainsana.inc
- inc/avainsanarivi.inc
- inc/avainsanatarkista.inc
- tuote.php
Asiakashinnasto tukemaan myymälähintaa, jolloin hinnastossa voidaan näyttää asiakkaan hinta ja myymälähinta. Myymälähinta näytetään otsikolla suositushinta. Vaatii avainsanan ASIAKASHINNASTO (muut avainsanat) määrittelyn myymälähinnaksi.
Lisäksi tuotekysely näyttää jatkossa avoimen myyntitilauksen tilausnumero-solun värjättynä, mikäli luokituksia (label-avainsanaa, jossa voidaan antaa värejä) on käytetty myyntitilauksella.
> * Asiakashinnastoon myyntihinta tai myymälähinta

- tilauskasittely/syotarivi.inc
* Käytetään livesearchia myös, jos yhtiön parametri livetuotehaku_tilauksella on J
> Livesearch fix

- vahvista_asiakas_jt_rivit_email.php
* Lisätään asiakkaan tilausnumero JT-vahvistussähköpostiin
> Asiakkaan tilausnumero JT-vahvistukseen

- varastopaikka_aineistolla.php
Varastopaikkojen massamuutoksessa sisäänluettavan tiedoston datan käsittely sujui hieman hassussa järjestyksessä jonka seurauksena saattoi olla SQL errori. Nyt dataa käsitellään fiksummin jolloin SQL erroreihin ei jouduta.
> Varastopaikkojen massamuutos: datan käsittelykorjaus

- tilauskasittely/tilaus_myynti.php
Korjattu napin näyttäminen. Nyt huomioidaan myynti_asiakhin_tallenna-yhtiöparametrin kaikki asennot.
> Myyntitilauksen hinnat asiakashinnoiksi

- tilauskasittely/tulosta_tarjous.inc
Korjattu vakioviestin asettelu & verollinen hinnan laskenta
> Tulosta tarjous tuotekuvilla

- crm/asiakasmemo.php
- crm/asiakasmemo_cron.php
- inc/parametrit.inc
Lisätty valintaruutu CRM asiakasmemo-ohjelmaan, jolla voidaan näyttää vain omat tai kaikki memot. Valinta tallennetaan keksiin.
Lisätty cron-tiedosto joka lähettää sähköpostiviestin CRM:n kautta tehdyistä muistutuksista.
> * CRM - ominaisuuksia

- crm/asiakasmemo.php
- inc/parametrit.inc
- tilauskasittely/tilaus_myynti.php
Asiakasmemon "näytä"-ruksia ei näytetä myyntitilauksella.
> Asiakasmemo myyntitilauksella

- tilauskasittely/tilaus_myynti.php
Reklamaatiot eivät aina ketjuttuneet oikein samalle laskulle veloitusten kanssa, vaikka olisi pitänyt, koska reklamaatiolle ei päivitetty kaikkia ketjutuksessa tarvittavia tietoja
> Reklamaatioiden ketjutus laskulle

- tilauskasittely/tulosta_tarjous.inc
Tarjouksen loppusumma menee tällä hetkellä aina yhtiön valuuta mukaan vaikka muu tarjous olisikin toisella valuutalla. Korjattu niin, että menee tarjouksen valuutan mukaiseksi myös loppusumma.
> Tarjoustuloste: loppusumman valuutta

- inc/functions.inc
- raportit/asiakkaantilaukset.php
Osataan jatkossa hakea tilausviitteitä, kuten asiakkaan tilausnumeroitakin.
> Asiakkaan tilaukset, tilausviite

- extranet/asiakashinnasto.php
- inc/avainsanarivi.inc
- inc/hinnastorivi.inc
Myyntihinnan / suositushinnan kohdalla osataan jatkossa hakea hintoja myös tuotehinnastosta. Tuotehinnastossa hinta voi olla joko brutto myyntihintana tai informatiivisena hintana. Informatiivinen hinta toimii kuten tuotteen takana myymälähinta, eli se käsitellään asiakashinnastossa verollisena hintana.
Asiakashinnaston saa toimimaan myymälähinnan kanssa syöttämällä avainsanoihin "Asiakashinnasto" avainsanan ja laittamalla sen arvoksi myymälähinnan. Ilman avainsanaa asiakashinnasto toimii myyntihintojen kanssa.
> Asiakashinnasto tukemaan tuotehinnastoja

- rahtikirja.php
- tilauskasittely/keraa.php
Annetaan käyttäjän syöttää maksimissaan kaksinumeroinen luku tulosteen kappalemääräksi
> Osoitelapun, lähetteen & rahtikirjan tulostus

- tilauskasittely/tulosta_tarjous.inc
* Tulostetaan nettotarjouspohjaan myös yksikköhinnat
> Tarjousmuutoksia

- tilauskasittely/tilauksesta_ostotilaus.inc
Käytössä on laaja toimipaikkakäsittely ja kun tehdään myynnistä osto ja tutkitaan pitääkö perustaa uusi ostotilaus, huomioidaan varaston lisäksi myös toimipaikka
> Uusi ostotilaus toimipaikoittain

- inc/avainsanarivi.inc
- tiedostofunkkarit.inc
- tiedostokirjasto.php
- tiedostotallennus.php
- tiedostokirjasto.php sekä tiedostotallennus.php-ohjelmat toimivat nyt myös luville ja lisensseille, alanimellä luvat_ja_lisenssit
> Luvat ja lisenssit asiakirjavalikkoon

- inc/muutosite.inc
Tarkennettu alkuperäisen alv:n hakemista, että osataan verrata oikeaan alv-summaan
> Saapumisen lasku, osa laskusta rahdiksi/kuluksi

- inc/valitse_tulostin.inc
- tilauskasittely/tulosta_lasku.inc
- tilauskasittely/valitse_laskutettavat_tilaukset.php
Korjattu ja viilattu miten tullinimike ja alkuperämaa näytetään laskulla silloin kun ne näytetään.
> Tullinimike ja alkuperämaa laskulla

- tilauskasittely/editilaus_in.inc
Reverts devlab-oy/pupesoft#2659
> Revert "Editilauksen asiakaskohdistusfix"

- inc/asiakashaku.inc
- raportit/menossa_olevat.php
Lisätty valintaruutu "Vain toimittamattomat", joka näyttää toimittamattomia / laskuttamattomia tilauksia.
> Menossa olevat -raportti: vain toimittamattomat valintaruutu

- rahtikirja.php
Rahtikirjan muokkauksessa tsekataan, että tilauksen tila on järkevä.
> Ei muokata laskutettuja tilauksia

- inc/parametrit.inc
- menut.php
Ohjelinkit Pupen valikoiden kylkeen
> * Käyttöohjeet

- pdflib/phppdflib.class.php
* Lisätään PDF-kuvissa tuki Exif-tyyppisille JPEG-kuville
> Tuki Exif-kuville PDF:ään

- rajapinnat/edi.php
Kun Magentosta tulee samaan aikaan tilauksia eri yrityksiin, ei aina osattu ohjata niitä oikeaan yritykseen
> Magentosta tulee tilauksia kahteen eri yritykseen

- datain/Finvoice2.01.xsd
- inc/yhtion_parametritrivi.inc
- myyntires/paperikarhu.php
- tilauskasittely/uudelleenluo_laskuaineisto.php
- tilauskasittely/verkkolasku.php
- tilauskasittely/verkkolasku_finvoice.inc
- tilauskasittely/verkkolasku_finvoice_201.inc
Osataan lähettää verkkolaskut Finvoice 2.01-muodossa.
Ohjataan yhtiön parametrillä: "finvoice_versio"
> * Finvoice 2.01

- inc/verkkolasku-in-finvoice.inc
- inc/verkkolasku-in.inc
Osataan hakea tuotenumero myös `InvoiceRow -> SubInvoiceRow -> SubArticleName` elementin sisältä, mikäli `InvoiceRow -> ArticleIdentifier` tai `InvoiceRow -> ArticleName` kentät ovat tyhjiä.
> Finvoice sisäänlukuun laajempi tuotetietojen haku

- inc/functions.inc
- inc/tuotehaku.inc
- inc/yhtion_parametritrivi.inc
- muokkaatilaus.php
- raportit/myohassa_olevat.php
- tilauskasittely/jtselaus.php
- tilauskasittely/keraa.php
- tilauskasittely/lisaarivi.inc
- tilauskasittely/tarkistarivi.inc
- tilauskasittely/tee_jt_tilaus.inc
- tilauskasittely/tilaus_myynti.php
- tilauskasittely/tulosta_lahete_kerayslista.inc
- tilauskasittely/tuote_selaus_haku.php
- tilauskasittely/valmista_tilaus.php
- tuote.php
Uusi asento "saldo_kasittely"-paramiin: Myytävissämäärä lasketaan keräyspvm:n mukaan niin, että myös tulevat tapahtumat vaikuttavat tämän hetken myytävissämäärään.
> * Ajasta riippuvainen myytävissämäärä

- tilauskasittely/ostotilauksen_lisatiedot.inc
Jos jälkilaskenta kuluperuste on arvossa "ei liitetä ostolaskuja saapumiselle", niin sillon yhtiön valuutasta poikkeavalle toimittajan saapumiselle voidaan käsin antaa kurssi.
> Saapumisen kurssi käsin

- monistalasku.php
* Laskua monistettaessa kopioidaan myös rivikommentit, jos on täppä valittuna
> Rivikommentin kopiointi

- myyntires/karhu.php
- annetaan käyttäjän valita, mihin asiakkaan takaa löytyvään sähköpostiosoitteeseen tämä lähetetään
> * Maksukehoituksen sähköpostiosoitevalinta

- tilauskasittely/tulosta_tarjous.inc
Tarjoukselle parempi termi otsikkoriville
> HF: vaihdettu termi

- crm/viikkosuunnitelma_raportti.php
- piilotetaan enemmän matkasarakkeita
> Edustajaraportin viilaukset

- kopioi_laitteita.php
- laiterekisteri.php
- muokkaatilaus.php
- raportit/selaasopimuksia.php
- tilauskasittely/otsik.inc
- tilauskasittely/tilaus_myynti.php
- tilauskasittely/tulosta_lasku.inc
- tyomaarays/tyojono.php
- Sopimukselle voi liittää usean laitteen yhdellä klikillä
- Laitteita voi kopioida sopimusriviltä toiselle
- Sopimuksen uusi sarake: sopimus_numero, näkyy sopimusselauksessa ja muokkaa sopimusta ohjelmissa sekä ylläpitosopimuksen laskulla sekä otsikolla
- Työjonoon lisätty työmääräyksen luontipäivämäärä
> * Laiterekisterin muutokset

- rajapinnat/magento_client.php
- muutetaan asiakaskohtaisten tuotehintojen logiikkaa tehokkaammaksi
- poistetaan ja lisätään tuotepäivityksen yhteydessä voimassaolevat asiakashinnat
- ei aseteta rajapinnan yli asiakashintoja, elleivät ne eroa tuotteen myyntihinnasta
> Magenton asiakaskohtaiset hinnat-muutos

- rajapinnat/edi.php
- Mahdollisuus ohjata useita Magentosta tulevia maksuehtoja yhteisen maksuehdon alle Pupeen
> Editilauksen maksuehdon ohjaus

- UTF8_konversio.php
- inc/asiakasrivi.inc
- inc/toimitarkista.inc
- inc/yhtion_parametritrivi.inc
- tilauskasittely/tulosta_lahete.inc
- tilauskasittely/tulostakopio.php
Haetaan pankkiyhteystiedot maksuehdon takaa jos ne on sinne laitettu
> Gs ko pikafixit

- inc/yhtion_parametritrivi.inc
- tilauskasittely/valitse_laskutettavat_tilaukset.php
- tilauskasittely/verkkolasku.php
Voidaan määrittää yhtiön parametreihin koontilaskujen alarajasumma. Manuaalisessa laskutuksessa käyttäjälle näytetään jos alarajasumma on asetettu. Tämä ei estä kuitenkaan manuaalista laskutusta.
Automaattisessa koontilaskutuksessa alarajasumma estää laskutuksen, jos ehdot eivät täyty.
> * Laskutus: koontilaskujen alarajasumma

- budjetinyllapito_tat.php
- raportit/myyntiseuranta.php
- tilauskasittely/monivalintalaatikot.inc
Lisätty tuki maakohtaisille myyntitavoitteille.
> * Maakohtaiset myyntitavoitteet

- inc/puun_alkiorivi.inc
- yllapito.php
Kun tuotteen tiedoista meni tuote-segmentit kohdan alta Valitse segmentit linkillä tekemään tuotteelle liitosta tuotepuuhun, niin täältä ei ollut enää paluulinkkiä takaisin tuotteen tietoihin. Nyt paluulinkkin tuotepuu-ohjelmasta takaisin tuotteen tietoihin ja muihin ohjelmiin on tehty, niin että tuotepuu-ohjelmasta pääsee siirtymään takaisin aiempiin ohjelmiin.
> Tuotteet: tuotesegmentti

- inc/avainsanarivi.inc
- inc/functions.inc
- inc/valitse_tulostin.inc
- tilauskasittely/tilaus_myynti.php
- tyomaarays/tulosta_huoltosaate.inc
- tyomaarays/tyomaarays.inc
Voidaan tulostaa huoltosaate työmääräyksestä, kun työmääräyksen laittaa valmiiksi.
> Työmääräys: huoltosaate

- raportit/myyntiseuranta.php
- Käytetään myynninseurannassa monivalintalaatikoissa autosubmittia, jos ohjelmaa käytetään alanimellä AUTOSUBMIT
> Myynninseuranta monivalintasubmit

- alehinta_cleanup.php
- inc/asiakasalennusrivi.inc
- inc/asiakasalennustarkista.inc
- inc/functions.inc
- inc/perusalennustarkista.inc
- Lisätty uusi 'kaikki tuotteet' - "aleryhmä"
- Tällä voidaan antaa asiakkaalle sama alennus kaikkiin tuotteisiin yhdellä rivillä
> * Asiakasalennus kaikille tuotteille

- inc/pankkiyhteys_functions.inc
- inc/pankkiyhteys_tilioteviite.inc
- pankkiyhteysadmin.php
* Voidaan hakea OP:n tileille reaaliaikainen saldo aineistojen haun yhteydessä
* Saldo näytetään aineistojen haun aikana, eikä sitä tallenneta mihinkään
* Pankkiyhteyden takaa voi valita haetaanko saldo vai ei
> * OP Reaaliaikainen saldo

- tilauskasittely/tulosta_tarjous.inc
* Käytetään termiä "Yhteistyöterveisin" "Kunnioittavasti" termin sijaan, jos tarjoustyyppi on 4.
> Tarjouksen sanavalinta

- tilauskasittely/teeulasku.inc
Ei puhuta tavarasta jos laskulla ei myydä tavaraa.
> Vientilaskun verokommentti

- tilauskasittely/tilaus_myynti.php
- tilauskasittely/tilaus_osto.php
- Ei piirretä headia, kun kutsutaan ajax_popup-parametrillä
> Hover popup fix

- tilauskasittely/tilaus_myynti.php
Sopimusten "Lisää laitteita" ja "Kopioi laitteita" linkeistä oli jäänyt käännösominaisuus uupumaan. Näihin linkkeihin on nyt tuo käännösominaisuus lisätty.
> Sopimukset: laitteita tekstit

- inc/functions.inc
- myyntires/manuaalinen_suoritusten_kohdistus.php
- myyntires/suoritusselailu.php
Voidaankohdistaa täsmäävät viitesuoritukset suoritus -näkymässä yhdellä klikkauksella.
> * Viitesuoritusten manuaalikohdistus

- inc/tiliote.inc
- Päivitetään muutospvm ja muuttaja yritiin, kun päivitetään maksulimittiä
> Maksulimitin päivitysmuutos

- inc/laskuhaku.inc
- inc/maksuvalmius.inc
- myyntires/myyntilaskuhaku.php
Maksuvalmius-raportissa voidaan nyt käyttää kotivaluutassa olevien pankkitilien maksulimittiä laskennan alkusaldona.
Maksuvalmius-raportiin lisätty linkki myyntireskontran laskuhakuun.
Myyntireskontran laskuhakuun lisätty uusia ominaisuuksia. Käyttöliittymä yhdenmukaistettu ostoreskontran laskuhaun kanssa.
> * Maksuvalmius ja laskuhaku

- inc/pakolliset_sarakkeet.inc
Pakollisissa sarakkeissa oli tuoteno kahteen kertaan virheellisesti
> Tuotedatan sisäänluku

- tuote.php
Tuotekyselyssä tuli tietyissä tilanteissa näkyviin virheellinen myytävissä nyt arvo tuotteen tilaukset kohtaan. Tämä on nyt korjattu ja jatkossa tuohon kohtaan tulee oikeat arvot.
> Tuotekysely: tuotteen tilaukset-kohta

- lue_data.php
Tallennetaan tietokantaan null, jos arvo on tyhjä abs_pvm- ja kassa_abspvm-kenttien osalta.
> Lue data: maksuehto

- monistalasku.php
Jos "laiterekisteri käytössä" yhtiön parametri on päällä, ei monisteta sarjanumeroa.
> Monista työmääräys: sarjanumero

- raportit/myohassa_olevat.php
Muutettu sarakkeiden järjestystä. Lisätty myös tuotteen "myytävissä ja hyllyssä oleva määrä" -sarake.
> Myöhässä olevat: sarakkeiden muutos

- inc/yhtion_parametritrivi.inc
- tilauskasittely/keraa.php
Uusi yhtiön parametri lisätty "Kerää riveittäin". Kerää-ohjelmassa voidaan merkata koko tilaus kerätyksi vasta kun kaikki rivit ovat merkitty kerätyiksi.
> * Kerää: keräys riveittäin

- myyntires/myyntilaskuhaku.php
Voidaan hakea laskuja asiakkaan tilausnumerolla.
> * Laskuhaku: Asiakkaan tilausnumero

- inc/yhtion_parametritrivi.inc
- tilauskasittely/kululaskut.inc
- tilauskasittely/ostotilausten_rivien_kohdistus.inc
- tilauskasittely/varastoon.inc
- Lisätään yhtiön parametrille `jalkilaskenta_kuluperuste` uusi arvo, jonka ollessa valittuna, saapumisilla kuluprosentti lasketaan ensisijaisesti tuotteittain käyttäen tuotteen kuluprosenttia.
- Jos tuotteen takaa ei löydy kuluprosenttia, käytetään saapumiselle syötettyä kuluprosenttia
- Näytetään saapumisen tuoteno-hoverissa tuotteen kuluprosentti
> * Tuotteen kuluprosentti saapumisissa

- raportit/asiakkaantilaukset.php
Asiakkaan tilaukset ohjelmassa, kun näytettiin asiakkaan tilaukset taulukossa oli taulukko rikki, joka aiheutti virheilmoituksen. Tämä on nyt korjattu.
> Asiakkaan tilaukset: taulukorjaus

- inc/functions.inc
- inc/yhtion_parametritrivi.inc
- tilauskasittely/uudelleenluo_laskuaineisto.php
- tilauskasittely/valitse_laskutettavat_tilaukset.php
- tilauskasittely/verkkolasku.php
- verkkolasku_resend.php
Trust Point FTP Finvoice-rajapinta. Eli lähtevien laskujen osalta Pupesoftissa on nyt myös tuki Trust Point operaattorille.
> * Trust Point - rajapinta

- inc/sftp-send.inc
- verkkolasku_resend.php
> SFTP-lähetys

- nordeafactoring.php
UTF8-korjauksia nordeafactoring-aineistoon
> UTF8-korjauksia nordeafactoring-aineistoon

- inc/tilaus_in_multi.inc
- tilauskasittely/tilaus_in.php
"Useita asiakkaita" tilausfileä voi lukea nyt myös niin, että asiakas valitaan asiakasnumerolla.
> Tilausten sisäänluku

- myyntires/eikateinen.php
Sallitaan maksupäiväksi myös tilikauden alku- ja loppupäivä
> Laskusta käteinen

- inc/avainsanarivi.inc
- tervetuloa.php
- tilauskasittely/otsik.inc
- Työjonolle avainsana laji 'tyom_tyojono', voidaan määrittää työjonon oletusvastuuhenkilö
- Jos työmääräykselle asetetaan jonon oletusvastuuhenkilö, ellei listasta ole jo valittu vastuuhenkilöä
- Vastuuhenkilön vaihtaminen tallentuu työmääräyksen tapahtumat-lokiin
- Oletusvastuuhenkilön etusivulla näkyy myös työmääräykset, joissa hän on vastuuhenkilö
> * Työmääräys - Työjonon omistaja

- inc/tilaus_in_multi.inc
- raportit/naytatilaus.inc
- tilauskasittely/tilaus_in.php
- tilauskasittely/tulostakopio.php
- tyomaarays/etsi.php
Etsi työmääräys - ohjelmassa voidaan nyt aktivoida laajahaku jolloin voidaan hakea kaikilla työmääräyksen kentillä.
Lisäksi:
Voidaan estää tilausvahvistuksen teko kun luetaan sisään tiedostoja "Useita asiakkaita"-muodossa
> * Etsi työmääräys - laajahaku

- tilauskasittely/keraa.php
Piilotetaan "Kuittaa toimitetuksi"-nappi, jos "Keräys riveittäin"-parametri on päällä ja kaikki rivit eivät ole kuitattu kerätyiksi.
> Kerää riveittäin

- tilauskasittely/tilaus_myynti.php
Tuotetiedot exceliin meni ylimääräistä koodia tallennusvaiheessa joka rikkoi tuon excelin. Tämä on nyt korjattu niin ja jatkossa exceliin ei tuota ylimääräistä koodia mene.
> Myyntitilaus: tuotetiedot-excel

- tilauskasittely/keraa.php
Korjattu poikkeava määrän käsittely kun käytössä on "Keräys riveittäin"
> Kerää riveittäin: poikkeava määrä

- inc/functions.inc
- tilauskasittely/tilaus-valmis.inc
- uudelleenlaheta-postnord.php
Laitetaan tuoteno eankoodin tilalle, jos käytössä on LogMaster-ulkoinen järjestelmä käytössä varaston takana.
> Posten outbounddelivery

- extranet/extranet_siirto.sh
- Poistetaan duplikaattitiedosto extranet-siirrosta
> Korjaus extranet-siirtoon

- tilauskasittely/varastoon.inc
- Joinataan lasku tilausrivin uusiotunnuksella otunnuksen sijaan
> Korjaus saapumisen kuluprosenttiin

- inc/functions.inc
Laitetaan vastaanottajan nimi ulkoisen järjestelmän mukaan
> Ulkoinen järjestelmä: keräys-sanoma

- raportit/kuukautisostot.php
Vuosineljännekset lasketaan kuluvasta päivästä taaksepäin
> Ostoehdotus kuukausittain vastaavien vuosineljännesmyynnit

- inc/pankkiyhteys_tilioteviite.inc
- pankkiyhteys.php
- pankkiyhteysadmin.php
- Lisätään mahdollisuus hakea factoring-aineistot pankkiyhteyden välityksellä, kun käytössä on Nordea.
> Factoring-aineistojen haku pankkiyhteydellä

- tilauskasittely/tilaus_myynti.php
- tilauskasittely/tilaus_osto.php
- tilauskasittely/tuotetiedot.inc
- Näytetään globaali tilattu ja varattu popupissa tilauskohtaisten sijaan
- Haetaan hälytysraja tuotteen takaa, jos se tuotepaikassa on 0
> Korjaus popuppiin

- tilauskasittely/tilaus-valmis-tulostus.inc
Näytetään niputettujen tilauksien tilausviitteet keräyslistalla.
> Keräyslista: tilausviitteet

- raportit/myyntiseuranta.php
Lisätty erikoismyyntien seurannan tuki.
> Myynninseuranta: erikoismyynti

- rajapinnat/presta/presta_products.php
- rajapinnat/presta/presta_tuote_export.php
- rajapinnat/presta/test_presta.php
- Presta-rajapintaan mahdollisuus määritellä dynaamisia tuoteparametrejä
- Lisäksi mahdollisuus ohittaa tuotepäivityksen yhteydessä tehtävä kategoriapäivitys
> Prestan dynaamiset tuoteparametrit

- tilauskasittely/tulosta_tarjous.inc
Tarjouksen lopussa luki Lasku yhteensä kun olisi pitänyt lukea Tarjous yhteensä.
Tämä on korjattu.
> Tarjous pdf

- muokkaatilaus.php
- Näytetään rivillä myös tilausviite, mikäli sellainen löytyy
- Lisätty mahdollisuus rivikohtaiseen mitätöintiin
> 'Muokkaa tilausta'-näkymän muutokset

- inc/functions.inc
- tilauskasittely/tulosta_lasku.inc
-Tuotenumero ja nimitys toisinpäin, eli tulostetaan eka tuotenumero ja sitten nimitys.
-Alennussarake piiloon jos alennuksia ei ole
-Kommentit tilausrivien jälkeen
-Väliviiva tilausrivien otsikkotietojen jälkeen
-Vientilaskulla ALV-erittely piiloon
-Desimaalinollat piiloon hinnoista
-Desimaalinollat piiloon kappalemääristä
> * Uusi laskupohja

- tilauskasittely/tilauksesta_myyntitilaus.inc
Tarjouksen hyväksymisen yhteydessä tarjouksen otsikon keräys- ja toimitusajat jäivät samoiksi mitä tarjouksella oli, vaikka kyseiset päivät olisivat olleet menneisyydessä. Nyt laitetaan tämä päivä, jos kyseiset päivät on jo ohitettu. Muuten samat päivät kuin tarjouksella.
> Tarjouksen hyväksyminen: päivämäärät

- inc/avainsanarivi.inc
- inc/functions.inc
- Voidaan avainsanalla valita, mikä TransportAccount-kentän arvo PostNordille menee
> PostNord MyPack

- tilauskasittely/yllapitosopimukset_cron.php
Voidaan ajaa yllapitosopimukset_cron.php kaikille yhtiöille antamalla ensimmäiseksi argumentiksi KAIKKI_YHTIOT
> Ylläpitosopimusten laskutus kaikille yhtiöille

- rajapinnat/relex/relex_transactions.php
> Relex: Transactions

- tilauskasittely/tilaus_myynti.php
Tuetaan tilausvahvistusta myös keskipitkässä reklamaatiossa
> Reklamaatio: tilausvahvistus

- raportit/naytatilaus.inc
- tilauskasittely/tulosta_lasku.inc
- tilauskasittely/uudelleenluo_laskuaineisto.php
- tilauskasittely/verkkolasku.php
- tilauskasittely/verkkolasku_finvoice.inc
Käsitellään verollinen rivihinta valuutassa oikein.
> Verollinen valuuttarivihinta finvoicella

- pikavalinnat.php
Käännetään pikakuvakkeiden nimet.
> Pikavalinnat: kuvakkeiden käännökset

- rajapinnat/presta/presta_addresses.php
- rajapinnat/presta/presta_client.php
- rajapinnat/presta/presta_customer_groups.php
- rajapinnat/presta/presta_customers.php
- rajapinnat/presta/presta_functions.php
- rajapinnat/presta/presta_sales_orders.php
- rajapinnat/presta/presta_specific_prices.php
- rajapinnat/presta/presta_tuote_export.php
- tilauskasittely/editilaus_in.inc
* Tuki myös asiakasalennuksille
* Korjattu sisääntulevien EDI-tilausten käsittelyä
> Presta specific prices API

- inc/avainsanarivi.inc
- inc/tuotteen_avainsanatrivi.inc
- Lisätään uusi avainsana ALA_TRY - Alatuoteryhmä
- Lisätään uusi tuotteen avainsana ala_try - Alatuoteryhmä
> Alatuoteryhmä

- rajapinnat/relex/relex_balances.php
- rajapinnat/relex/relex_customers.php
- rajapinnat/relex/relex_groups.php
- rajapinnat/relex/relex_locations.php
- rajapinnat/relex/relex_orders.php
- rajapinnat/relex/relex_products.php
- rajapinnat/relex/relex_replacements.php
- rajapinnat/relex/relex_suppliers.php
- rajapinnat/relex/relex_transactions.php
- rajapinnat/relex/relex_warehouse_location.php
Voi antaa FTP-pathin parametriksi
> Relex: path-parametri

- rajapinnat/presta/presta_functions.php
- rajapinnat/presta/presta_products.php
- rajapinnat/presta/presta_tuote_export.php
Poistetaan Pupesta poistetut tuotteet Prestashopista
> Prestashop products API

- synkronoi_tuotteet_ulkoiseen_jarjestelmaan.php
Laitetaan aineistoon tuotenumero, jos ulkoiseksi järjestelmäksi on valittu Helsingin Hyllyvarasto.
> Synkronoi tuotteet ulkoiseen järjestelmään: tuoteno

- budjetinyllapito_tat.php
- raportit/myyntiseuranta.php
- Mahdollisuus ylläpitää asiakasmyyjätavoitteita
- Mahdollisuus näyttää asiakasmyyjätavoitteet myynninseurantaraportissa
> * Asiakasmyyjätavoitteet

- inc/yhtion_parametritrivi.inc
Saldo-käsittelyparametrin muutos ei aina onnistunut
> Yhtiön parametrit: saldokäsittely

- inc/functions.inc
UTF-8 / ISO-8859-1 enkoodaus & tiedostonimen muutos
> Ulkoinen järjestelmä: keräyslista

- tilauskasittely/teeulasku.inc
Laskulle tulevan factoring tekstin perään kaksi rivinvaihtoa selkeämmän lukemisen vuoksi
> Factoring lasku

- saapuminen_ulkoiseen_jarjestelmaan.php
Korjattu XML-tiedoston kirjoitus levylle.
> Saapuminen ulkoiseen järjestelmään: tiedoston kirjoitus

- inc/toimitustapatarkista.inc
Sisäänluettaessa sisäänlue dataa ohjelmalla uusia toimitustapoja päivitti tämä tietojen sisäänluku virheellisesti jo olemassaoleville toimitustavoille uudet toimitustavat vak_kielto ja vaihtoehtoinen_vak_toimitustapa kenttiin. Tämä virhe on nyt korjattu ja jatkossa tälläistä virheellistä päivitystä ei tehdä toimitustapoja excelistä Pupeen luettaessa.
> Sisäänlue dataa: toimitustavat

- yllapito.php
Mentäessä tuoteylläpidosta tuotesegmenttien liittämiseen (tuotepuu) ei ollu paluulinkkejä aiempiin ohjelmiin. Nyt nämä paluulinkit aiempiin ohjelmiin on lisätty.
> Tuotepuu: paluulinkki tuotteelle

- tilauskasittely/osoitelappu_intrade_pdf.inc
Asiakkaan avainsanalla voidaan lisätä Reitti / Alue / Ehto-tiedot Intrade/SOK:n osoitelapulle.
> * Reittitiedot Intrade-osoitelapulle

- rajapinnat/presta/presta_categories.php
- rajapinnat/presta/presta_client.php
- rajapinnat/presta/presta_products.php
- rajapinnat/presta/presta_tuote_export.php
Parametri Pupesoftin verokantojen konvertoimiseksi Prestashopin tax_group_id arvoiksi.
> Presta verokannat

- rajapinnat/presta/presta_functions.php
- rajapinnat/presta/presta_products.php
- rajapinnat/presta/presta_tuote_export.php
Tuki tuotteen nimityksen, kuvauksen sekä lyhytkuvauksen käännöksille.
> Presta käännökset

- rajapinnat/presta/presta_functions.php
- rajapinnat/presta/presta_specific_prices.php
- rajapinnat/presta/presta_tuote_export.php
* Tuki asiakashinnoille eri valuutoissa.
* Varmistetaan, että asiakasalennukset/-hinnat poistuu Prestan asiakkaalta, jos ne poistetaan Pupesoftin päästä.
> Presta asiakashinnat

- tilauskasittely/tulosta_tilausvahvistus_pdf.inc
Lisätty sähköpostiin lähetettävään PDF tilausvahvistukseen asiakasnumero.
> Tilausvahvistus email

- synkronoi_sanakirja.php
Siirretään synkronoi-nappi myös ylös
> Synkronoi sanakirja

- rajapinnat/presta/presta_categories.php
Kategorian nimi kaikille kielille.
> Presta kategoriat

- tervetuloa.php
Ei ilmoiteta kesken olevasta matkalaskusta tervetuloa -näkymässä
> Tervetuloa-näkymä

- inc/functions.inc
- rajapinnat/presta/PSWebServiceLibrary.php
- rajapinnat/presta/presta_client.php
- rajapinnat/presta/presta_functions.php
- rajapinnat/presta/presta_products.php
- rajapinnat/presta/presta_tuote_export.php
Presta rajapintaan tuki tuoteperheille.
> Presta tuoteperheet

- lahetamuistutus.php
Ei muistuteta keskeneräisitä matkalaskuista
> Muistutus sähköpostiin

- inc/functions.inc
> Mb_str_pad funktio uusiksi

- rajapinnat/presta/presta_client.php
- rajapinnat/presta/presta_functions.php
- rajapinnat/presta/presta_product_feature_values.php
- rajapinnat/presta/presta_product_features.php
- rajapinnat/presta/presta_products.php
- rajapinnat/presta/presta_tuote_export.php
Voidaan lisätä Pupesoftin tuotteen arvoja Prestan "tuote ominaisuudet" arvoiksi.
Uusi parametri presta_tuoteominaisuudet, jolla määritellään relaatio Pupesoftin tuotteen ja Prestan product_feature_id -arvon välille.
> Presta tuotteen ominaisuudet

- inc/functions.inc
- saapuminen_ulkoiseen_jarjestelmaan.php
- synkronoi_tuotteet_ulkoiseen_jarjestelmaan.php
setataa ftputf8-muuttuja jos PUPE_INVOICE setattu
> Ulkoinen järjestelmä: UTF-8 & FTP

- rajapinnat/presta/presta_client.php
- rajapinnat/presta/presta_manufacturers.php
- rajapinnat/presta/presta_product_feature_values.php
- rajapinnat/presta/presta_products.php
Lisätään Pupesoftin tuotemerkit Prestan Manufacturers -tauluun ja linkataan tuotteeseen.
> Presta valmistajat

- tilauskasittely/rahtikirja_kirjetarra_pdf.inc
Uusi rahtikirjatyyppi lisätty.
> * Osoitetarra kirjelähetyksille

- yllapito.php
Mukautettujen ylläpitonäkymien kautta ei pystynyt tietoja poistamaan. Muutettu nyt niin, että tietojen poistaminen onnistuu myös mukautettujen ylläpitonäkymien kautta, kun alanimi on mallia tuote!!!kissa!!!true_poisto.
> Mukautetut ylläpitonäkymät: tietojen poistaminen

- rajapinnat/presta/presta_functions.php
- rajapinnat/presta/presta_specific_prices.php
Siirretään Pupesoftin hinnastot Prestashoppiin
> Presta hinnastot

- rajapinnat/presta/presta_functions.php
- rajapinnat/presta/presta_products.php
Päivitetään aina kaikkien tuotteiden saldo
> Presta saldopäivitys

- rajapinnat/presta/presta_customers.php
- rajapinnat/presta/presta_tuote_export.php
Voidaan lisätä asiakkaat aina johonkin vakioryhmään.
> Presta asiakkaan vakioryhmät

- inc/unifaun_send.inc
- rajapinnat/edi.php
- tilauskasittely/editilaus_in.inc
- Magentorajapinnasta tulevalla tilauksella otetaan talteen Matkahuolto lähellä-noutopisteen tunnus
- Unifauniin lähettäessä tarkistetaan löytyykö laskun lisätiedoista noutopisteen tunnus ja jos se löytyy niin lisätään agentto sekä agentto receiver-osa
> * Unifaunin Matkahuolto lähellä-paketti

- rajapinnat/presta/presta_client.php
- rajapinnat/presta/presta_products.php
Lisätään tuotteelle yksikkö. 
Tuotteen yksikköhintaa ei voi lisätä Prestan rajapinnan kautta, joten yksikköhinta on Prestassa aina nolla.
> Presta tuotteen yksiköt

- myyntires/myyntilaskut_asiakasraportti.php
Asiakkaan tiliote ja asiakasraportin kautta otettu laskukopio asiakkaan kielellä
> Asiakasraportti

- iltasiivo.php
Tarkistetaan tuotepaikka pienillä kirjaimilla
> Iltasiivo: tuotepaikat

- inc/unifaun_send.inc
- rajapinnat/edi.php
- tilauskasittely/editilaus_in.inc
Reverts devlab-oy/pupesoft#2856
> Revert "Unifaunin Matkahuolto lähellä-paketti"

- inc/toimitustaparivi.inc
- rahtikirja-tulostus.php
- rahtikirja.php
- rahtikirja_custom.php
- tilauskasittely/keraa.php
- tilauskasittely/osoitelappu_hornbach_pdf.inc
- tilauskasittely/tulostakopio.php
> * Hornbach osoitelappu

- tilauskasittely/toimitusvahvistus_email.inc
Käännetään asiakkaalle sähköpostiin lähetettävä toimitusvahvistus asiakkaan kielelle.
> Toimitusvahvistus sähköpostiin: käännökset

- inc/functions.inc
- inc/yhtion_parametritrivi.inc
Voidaan livehakea myös tuotteen lempinimellä
> * Livehaku tuotteen lempinimellä

- inc/pankkiyhteys_tilioteviite.inc
- pankkiyhteysadmin.php
Danske factoring-viiteaineisto -tuki
> * Pankkiyhteys: Danske factoring-viiteaineisto

- tilauskasittely/laskutus.inc
- tilauskasittely/lisaarivi.inc
- tilauskasittely/valitse_laskutettavat_tilaukset.php
Loppulaskutus nollana jos veroton arvo on nolla
Joissakin harvinaisissa tilanteissa saattoi ennakkolaskun loppulaskusta (jos loppulaskun positio on 0%) tulla nollan sijaan sentin hyvitys tai velotus. Jatkossa katsotaan verottomat hinnat ja jos ne on nolla, laitetaan verollinen hinta myöskin nollana.
> Loppulaskutus fix

- rajapinnat/presta/presta_functions.php
- rajapinnat/presta/presta_specific_prices.php
Sallitaan ainoastaa hinnastohinnat Prestaan ilman, että asiakas tai asiakasryhmä on määritelty.
> Presta hinnoittelu

- rajapinnat/presta/presta_functions.php
- rajapinnat/presta/presta_tuote_export.php
Voidaan rajata mistä varastoista lasketaan verkkokaupan saldot
> Presta sallitut varastot

- rajapinnat/presta/presta_functions.php
- rajapinnat/presta/presta_product_stocks.php
- rajapinnat/presta/presta_products.php
- rajapinnat/presta/presta_tuote_export.php
Tilaustuotteet merkataan Prestassa jälkitoimitettaviksi. Niitä saa lisätä koriin, vaikka saldo on loppu. Saldotekstiksi lisätään niille teksti "Tilaustuote".
> Presta tilaustuotteet

- db_sql_query.php
> DB SQL Query: Maaryhmät

- rahtikirja_custom.php
- tilauskasittely/postiedi.inc
Tietyin ehdoin voidaan laittaa jokin ytunnus myös tyhjälle rahtikirjalle edi-sanomaa varten
> Tyhjä rahtikirja

- inc/toimitustaparivi.inc
- inc/toimitustapatarkista.inc
- uusiyritys.php
Poistetaan turha sarake sallitut_alustat toimitustavalta
> Poistetaan sallitut_alustat toimitustavalta

- inc/generoi_laskun_saate.inc
- tilauskasittely/editilaus_in.inc
- tilauskasittely/tulosta_lasku.inc
- tilauskasittely/verkkolasku.php
Perustamalla "Verkkokauppa"-niminen laskun saatekirje, niin kuittikopio lähetetään asiakkaalle sähköpostilla kun asiakkaan tilaus luetaan Pupesoftiin.
> * Verkkokauppatilauksesta kuittikopio asiakkaan sähköpostiin

- tuoteperhe.php
Näytetään lapsituotteen myyntihinta (hintakerroin vaikuttaa tähän sarakkeeseen)
Näytetään laspituotteiden myyntihinnat yhteensä.
Näytetään laspituotteiden + isätuotteen hinnat yhteensä.
> * Tuoteperhe-ylläpito: myyntihinnat

- tilauskasittely/osoitelappu_hornbach_pdf.inc
- lisätään lappuun toimitustavan nimitys
> Hornbach osoitelappu

- inc/yhtion_parametritrivi.inc
- tilauskasittely/verkkolasku.php
- tyomaarays/tyomaarays.inc
Kassamyyjälle näytetään myös PDF-nappi kun kassamyyjän oletustulostin on PDF-ruudulle.
Uusi yhtiön parametri jolla voidaan ohittaa keräysprosessi työmääräyksille.
> Uusia ominaisuuksia

- inc/valitse_tulostin.inc
- tyomaarays/tyomaarays.inc
Työmääräykset, huoltosaatteet, reklamaatiot ja takuut saadaan jatkossa myös PDF-nappia painamalla auki ruudulle. Kätevää esim. kun tulostimia ei ole integroitu Pupeoftiin.
> * Työmääräykset, huoltosaatteet, reklamaatiot ja takuut ruudulle

- inc/valitse_tulostin.inc
- tilauskasittely/tulosta_tarjous.inc
- tyomaarays/tyomaarays.inc
> Tarjous myös ruudulle.

- rajapinnat/yrityspeli.php
- Yrityspeli-ohjelma, jolla voidaan luoda automaattitilauksia kuluvalle viikolle yrityksille, joilla ei vielä sellaisia ole
> Yrityspeli

- rajapinnat/magento_client.php
- voidaan asettaa useita kauppakohtaisia hintoja samaan kauppanäkymään eri sarakkeista, arvoa ei päivitetä jos se on 0 tai tyhjää, jolloin voidaan yliajaa esimerkiksi myyntihinta hinnastohinnalla, jos sellainen tuotteelta löytyy
> Magenton kauppanäkymäkohtaiset hinnat

- raportit/abc_luokka.php
Asiakas ABC analyysin luokkayhteenvedossa ei toiminut rivien luokan mukaan järjestäminen vaan tämä aiheutti virhetilanteen. Tämä on nyt kuitenkin korjattu niin, että luokan mukaan järjestäminen toimii myös.
> ABC-analyysi: luokka järjestys

- inc/asiakashaku.inc
- Näytetään piirit asiakashaussa, jos avainsanoissa on yksikin piiri
> Piirit asiakashakuun

- tilauskasittely/ostotilausten_rivien_kohdistus.inc
Saapumisen rivikohdistusnäkymässä ei voinut hakea toimajalla normaalissa muodossa pp.kk.vvvv vaan haku tuli tehdä mysql muodossa vvvv-kk-pp. Nyt tätä on korjattu niin, että haku myös muodossa pp.kk.vvvv toimii.
> Saapuminen: toimajalla haku

- inc/functions.inc
xml-tiedoston teko ei keskeydy jos puhelinnumerossa erikoismerkkejä tai postinumero ei ole numeerinen
> OutboundDelivery

- tilauskasittely/tulosta_lasku.inc
- Annetaan laskun kommentille tilaa 2 riviä pdf-laskulla
> Korjaus laskun kommenttiin

- myyntires/suoritusselailu.php
Paremmat virheviestit ongelmatilanteissa.
> Suoritusten selailu

- inc/unifaun_send.inc
- rajapinnat/edi.php
- tilauskasittely/editilaus_in.inc
> Unifaunin Matkahuolto lähellä-paketti

- inc/functions.inc
- inc/tuotetarkista.inc
Tuotepaikka tuotteen perustuksessa osaa nyt tehdä oletuspaikan.
> Tuotepaikan perustus: oletuspaikka

- myyntires/paperitiliote.php
Jos asiakkaalla on oletusmaksuehtona Factoring-maksuehto, tulostetaan paperitiliotteelle Factoring-sopimuksen pankkitili(t) ja swift(it). Muussa tapauksessa kuten ennenkin, eli tiedot tulevat yrityksen takaa.
> Paperitiliotteen tilinumero

- inc/avainsanatarkista.inc
Päivitetään tuotteiden sallitut maat kun maaryhmää muutetaan.
> Avainsanat: maaryhmä

- tilauskasittely/tulosta_purkulista.inc
Lisätty saapumisen tulosteista tulostettavaan exceliin kappalemäärä-sarake.
> Saapumisen tulosteet: Tullinimike Excel

- muokkaatilaus.php
- tilauskasittely/tulosta_tarjous.inc
"Avoimet tarjoukset"-ohjelmaan lisätty tilausviite. Tarjous PDF lisätty asiakaskommentti.
> Tarjous: tilausviite & asiakaskommentti

- inc/yhtion_parametritrivi.inc
- tilauskasittely/tilaus-valmis.inc
Uusi parametri joka tarkistaa onko tuotetta ostettu tarpeeksi ja tarvitseeko lähettää jälkitoimitus-sähköpostia.
> Myyntitilaus: JT-email

- js/tilaus_myynti/tilaus_myynti.js
- tilauskasittely/tilaus_myynti.php
Varmistetaan käyttäjältä haluaako hän varmasti muokata tilausriviä, jos tilaus on jo kerätty  / toimitettu.
> Myyntitilaus: Kerätty / toimitettu

- inc/avainsanarivi.inc
- tilauskasittely/toimitusvahvistus_email.inc
- Sähköpostitoimitusvahvistukseen (toimitusvahvistus_email.inc) voidaan valita avainsanassa lähteekö email myyjälle, asiakkaalle vai molemmille
> * Toimitusvahvistus myyjän sähköpostiin

- raportit/varastonarvo-super.php
Lisätty "saldo myytävissä"- & "näytä ostohinta"-ruksit
> * Varastonarvo tuote: saldo myytävissä & näytä ostohinta

- inc/avainsanarivi.inc
- tilauskasittely/tuote_selaus_haku.php
- Mahdollisuus syöttää käyttöliittymässä ale1 kappalemäärän lisäksi
- Ominaisuus kytketään päälle HAE_JA_SELAA-avainsanan valinnalla.
> * Hae ja selaa - Alennuksen syöttö

- raportit/naytatilaus.inc
Näytetään postin rahtikirjana JJFI-alkuinen sscc-koodi
> Näytä tilaus -näkymä

- tuoteperhe.php
Tuotereseptille oli jäänyt pituus kerroin tieto, joka ei tehnyt enää mitää pituuteen tai kertoimiin liittyvää. Otettiin hämäävät pituus kerroin kentät siis kokonaan pois.
> Tuoteresepti: pituus kerroin

- inc/hyvaksynta.inc
Ei näytetä hyväksyttävissä olevissa keskeneräisiä matkalaskuja
> Hyväksyttävänä olevat laskut

- uusiyritys.php
Korjattu kopioinnissa kentät joihin tarvii null-arvot
> Uusiyritys: maksuehto

- inc/unifaun_send.inc
Muutamaan Postin toimitustapaan MPS tuki, jos käytetään Unifaun Printserveriä.
> Unifaun Posti MPS

- inc/ftp-send.inc
- inc/functions.inc
- maksuaineisto_send.php
- saapuminen_ulkoiseen_jarjestelmaan.php
- synkronoi_tuotteet_ulkoiseen_jarjestelmaan.php
Varmistetaan tiedostojen merkistön oikeellisuus.
> FTP tiedostojenlähetys

- inc/yhtion_parametritrivi.inc
- js/tilaus_myynti/tilaus_myynti.js
- raportit/asiakasinfo.php
- tilauskasittely/syotarivi.inc
- tilauskasittely/tilaus_myynti.php
Tilausriviä lisättäessä esisyötetään hinta, netto, alet ja näytetään kate%
> * Tilausrivi:  esisyötetään hinta, netto, alet ja näytetään kateprossa

- monistalasku.php
Sopimusriville sama toimaika kuin monistettavalla.
> Monista sopimus fix

- tilauskasittely/yllapitosopimukset.php
Automaattiseen päivämäärän korjaukseen lisätty uusi toiminto: %tse avulla saadaan seuraava kokonainen kuukauden mittainen ajanjakso.
> Sopimuksien voimassaoloaika

- inc/tiliote.inc
- tilauskasittely/tulosta_tiliotekuitti.php
- tilioteselailu.php
Pankkiaineistojen selailussa voi tulostaa tiliotekuitin.
> * Tiliotekuitti

- inc/pupeExcel.inc
- raportit/matkallaolevat_laskuittain.php
- raportit/naytatilaus.inc
- raportit/toimitetut_rivit.php
- saapumisien_kulut.php
Voidaan tutkia toimitettuja myyntirivejä tiettynä päivämääränä.
Lisäksi:
Matkallaolevat laskuittain näyttää nyt myös kuinka paljon saapumisella on viety kamaa varastoon per rapparin loppupäivä. (Jos lasku siis on liitetty saapumiseen)
Saapumisien kulut rappariin laitettu homma oletuksena niin, että näytetään lista toimittajittain, napista saa edelleen kaikki saapumiset näkyviin jos haluaa.
> * Toimitetut myyntirivit

- rajapinnat/presta/presta_functions.php
- rajapinnat/presta/presta_products.php
Jos tuote merkataan Pupesoftissa tähtituotteeksi, laitetaan se Prestassa aina myös home -kategoriaan. Tämä tarkoittaa, että tuote näkyy Prestan etusivulla "suositellut tuotteet" näkymässä.
> Presta suositellut tuotteet

- tilauskasittely/jtselaus.php
- tilauskasittely/lahetteen_tulostusjono.php
Lisätty nimitarkenne ja toimitusosoitteen nimitarkenne keräyslistan tulostus näkymään ja JT-selaus näkymään.
> JT-selaus ja kerää-näkymät: nimitarkenne

- raportit/matkallaolevat_laskuittain.php
Otetaan mukaan kaikki laskut, joilla on matkallaolevat -tiliöintejä. Riippumatta laskun tyypistä.
Voidaan rajata laskuja tyypin mukaan.
> Matkallaolevat laskuittain raportti

- rajapinnat/presta/presta_customer_groups.php
- rajapinnat/presta/presta_tuote_export.php
Voidaan asettaa näytetäänkö asiakasryhmässä hinnat ja onko hinnat verollisia vai verottomia.
> Presta asiakasryhmien hinnat

- extranet/extranet_siirto.sh
- extranet_laiterekisteri.php
- extranet_tyomaaraykset.php
- huoltopyynto_pdf.inc
- inc/functions.inc
- nayta_tyomaarayksen_tapahtumat.php
- tilauskasittely/tulostakopio.php
- Muutoksia ja uusia ohjelmia Extranetin RMA portaaliin
> RMA portaalin laajennukset

- extranet/asiakashinnasto.php
- extranet/tervetuloa.php
- hinnat_cron.php
- inc/functions.inc
- inc/hinnastorivi.inc
- rajapinnat/alehinta.php
- raportit/asiakashinnasto_raportti.php
- tilauskasittely/tuote_selaus_haku.php
- verkkokauppa/verkkokauppa.php
- Hinnastolle voi valita toimipaikan, johon hinnasto on voimassa
> * Yhtiön toimipaikka hinnastoon

- inc/teemaksutosite.inc
Päivitetään valuuttalaskun tilliöinneille valuuttasumma ja valuutta, muuten pääkirja ilmoittaa, että 'Ostovelkatiliöinnin summa virheellinen!', vaikka tiliöinnit ovat muuten ok
> Kun tiliotteella kuitataan valuuttalaksu suoritetuksi

- myyntires/myyntilaskuhaku.php
Laskut sortataan nyt oikein laskunron mukaan
> Myyntireskontran laskuhaku

- raportit/myyntiseuranta.php
Kumlatiivinen tavoite myynninseurannassa
> Kumlatiivinen tavoite myynninseurannassa

- inc/avainsanarivi.inc
- inc/toimi.inc
- inc/toimirivi.inc
- yllapito.php
Toimittajaryhmä lisätty toimittajien ylläpitoon (informatiivinen-kenttä).
> Avainsanat: toimittajaryhmä

- inc/ftp-send.inc
- inc/functions.inc
- kerayksen_kuittaus_ulkoisesta_jarjestelmasta_cron.php
- rajapinnat/logger.php
- rajapinnat/presta/presta_categories.php
- rajapinnat/presta/presta_client.php
- saapuminen_ulkoiseen_jarjestelmaan.php
- saldovertailu_ulkoisesta_jarjestelmasta_cron.php
- seurantakoodi_ulkoisesta_jarjestelmasta.php
Mahdollisuus kirjoittaa lokitiedostoja, joita käyttäjät voi käyttöliittymästä katsoa.
Lisätty FTP -lähetykseen sekä ulkoisen varastojärjestelmän siirtoihin/vastaanottoihin lokitus.
> Pupesoft lokitiedostot

- tilauskasittely/verkkolasku.php
Jos asiakkaan laskun kanavointitietona on sähköposti, ei lähetetä sinne nollalaskua
> Laskun loppusumma nolla

- inc/pakkauskoodit.inc
- inc/pakkauskooditrivi.inc
- yllapito.php
Käyttöliittymän korjaus, aikaisemmin käyttäjälle näytettiin pakkauksien tunnus ja relaation luonnissa piti tietää pakkauksien tunnus. Jatkossa pakkaus voidaan valita alasvetovalikosta selkokielisenä ja se myös näkyy pakkauskoodien listauksessa selkokielisenä.
> Pakkauskoodit käyttöliittymä fix

- raportit/varastonarvo-super.php
Saldo myytävissä ottaa summaustason huomioon
> Varastonarvo tuote: saldo myytävissä

- myyntires/paperitiliote.php
Jos paperitiliotteelle tuli useampi sivu niin päädyttiin erroriin. Enää ei päädytä.
> Paperitiliote fix

- UTF8_konversio.php
- inc/functions.inc
- rajapinnat/presta/presta_product_feature_values.php
- rajapinnat/presta/presta_product_stocks.php
- rajapinnat/presta/presta_sales_orders.php
* Tuoteominaisuuksien monikielisyydenhallinta
* Saldo aina numeerinen
* Otetaan kaikki osoitetiedot verkkokauppatilaukselta
> Presta rajapintamuutoksia

- extranet_laiterekisteri.php
- extranet_tyomaaraykset.php
- huoltopyynto_pdf.inc
- siistimpi tiedostonimi huoltopyynnölle
- sarakkeet järjestykseen valmistaja - malli - sarjanumero
> RMA portaalin fixejä

- inc/functions.inc
> Ulkoinen järjestelmä: keräyslista & JT-rivit

- rahtikirja-tulostus.php
- rahtikirja.php
- Voidaan luoda Excel-muotoinen koontilähete rahtikirjojen tulostuksen yhteydessä
- Lähete lähetetään käyttäjän sähköpostiin
> * Excel-koontilähete

- inc/pankkiyhteys_functions.inc
- Varmistetaan, että yhdellä viitteellä haetaan aineisto vain kerran
> Parannus tiedostojen hakuun pankkiyhteydellä

- inc/asiakashaku.inc
- monistalasku.php
- muokkaatilaus.php
- raportit/asiakkaantilaukset.php
- raportit/naytatilaus.inc
- raportit/saatanat.php
- raportit/selaasopimuksia.php
- tilauskasittely/tilaus_myynti.php
- tilauskasittely/tulostakopio.php
- tilauskasittely/yllapitosopimukset.php
Sopimuksien listauksissa korjattu ytunnuksen näyttäminen.
> Sopimukset: y-tunnus

- tilauskasittely/ostotilausten_rivien_yhdistys.inc
Saapumisten yhdistykseen korjaus suuntalavoihin liittyen, jos yritys käyttää tuloutuksessa niitä.
> Saapumisten suuntalava fix

- rajapinnat/relex/relex_customers.php
Voidaan neljännellä parametrillä (arvolla "extra") ottaa Relex customers aineistoon myös asiakasnumero ja myyjänumero (tuossa järjestyksessä).
> Relex customer extras

- tilauskasittely/tuote_selaus_haku.php
Otetaan yhtiön ALV-käsittely huomioon kun näytetään asiakashintoja extranet-käyttäjälle.
> Hae & selaa: extranet ja asiakashinnat

- raportit/naytatilaus.inc
Haetaan aina pienin kerättyaika, toimaika ja toimitettuaika. Jos pienin aikaleima on 0000-00-00, niin haetaan tällöin isoin aikaleima.
> Asiakkaan tilaukset: aikaleimat

- inc/avainsanarivi.inc
- inc/avainsanatarkista.inc
- inc/yhtion_parametritrivi.inc
- maksusopimus_laskutukseen.php
- tilauskasittely/luo_myyntitilausotsikko.inc
- tilauskasittely/otsik.inc
- tilauskasittely/teeulasku.inc
- tilauskasittely/tulosta_lasku.inc
- tilauskasittely/verkkolasku_finvoice.inc
- tilauskasittely/verkkolasku_finvoice_201.inc
Yhtiön parametriin "ennakkolaskun_tyyppi" lisätty uusi optio, jonka avulla ei näytetä ennakkolaskun PDF:ssä ennakkolasku-tekstejä. 
Lisätty vakioteksti 2, joka tulostuu laskun alaosaan.
> Ennakkolasku: muutoksia laskupohjaan

- js/tilaus_myynti/tilaus_myynti.js
Lisätään toim-muuttuja mukaan jotta oikeustarkistus ei feilaa
> Tilaus myynti: JS & tilausrivin esisyöttö

- tilauskasittely/myyntierat_ja_tuotetiedot.inc
Tuotiedot exceliin lisätty myymälähinta.
> Lisätään Myymälähinta tuotetietoihin

- extranet/extranet_siirto.sh
tarkistahetu-tiedosto mukaan Extranetiin.
> Extranet: siirtotiedostot

- rajapinnat/presta/presta_functions.php
- rajapinnat/presta/presta_products.php
- rajapinnat/presta/presta_sales_orders.php
* Tuotteen kuvaus ja lyhytkuvaus -kenttiin voi syöttää nyt rivinvaihtoja
* Käännetään tuotetietojen erikoismerkit Prestalle sopiviksi
* Tuoterakenteen tieto mukaan EDI -tilaustiedostoon
> Presta tuotteen tiedot

- yllapito.php
Korjattu info-popupin ikonin näkyvyys alustamalla tarkistuksessa käytettävä muuttuja.
> Mysqlalias: info-popup

- inc/unifaun_send.inc
Unifaun Printserverissä IT09 palvelu kuuluu MPS piiriin, joten lisätään sille tuki.
> Unifaun Printserver, IT09 MPS

- inc/asiakashintatarkista.inc
Ryhmä ja tuoteno ei saa olella molemmat valittu samaan aikaan
> Asiakashinnat: ryhmä & tuoteno

- inc/functions.inc
- inc/yhteyshenkilorivi.inc
- rajapinnat/presta/presta_addresses.php
- rajapinnat/presta/presta_client.php
- rajapinnat/presta/presta_customers.php
- rajapinnat/presta/presta_order_histories.php
- rajapinnat/presta/presta_products.php
- rajapinnat/presta/presta_shops.php
Voidaan määritellä asiakkaalle mihin Presta -kauppaan se lisätään. Asiakas voi kuulua vain yhteen kauppaan.
> Presta monikauppatuki asiakastiedoille

- tilauskasittely/rahtikirja_erittely_pdf.inc
- Käytetään toimitustavan osoitetietoja myös koontierätulostuksella, jos ne on annettu
> Koontierätulostuksen osoitetiedot

- js/tilaus_myynti/tilaus_myynti.js
- tilauskasittely/tilaus_myynti.php
Katteen korjaus & käännetään valuuttaan
> Tilausrivin esisyöttö: Kate & valkoodi

- rajapinnat/relex/relex_transactions.php
Lisätty extra-kenttiä sanomaan. Ominaisuuden saa päälle antamalla viidennen parametrin arvolla "extra".
> Relex transactions: Extra-kentät

- rahtikirja-tulostus.php
- Tulostetaan oikea nimitys excel-lähetteelle
> Nimitys oikein Excel-lähetteelle

- rajapinnat/presta/presta_categories.php
- rajapinnat/presta/presta_client.php
- rajapinnat/presta/presta_functions.php
- rajapinnat/presta/presta_manufacturers.php
- rajapinnat/presta/presta_products.php
- rajapinnat/presta/presta_tuote_export.php
Siirretään tuotekategorioiden nimet kaikilla kielillä. 
Lisäksi korjattu merkistöongelmia ja parannettu performanssia.
> Presta tuotepuun käännökset

- inc/functions.inc
- maksusopimus_laskutukseen.php
- Kopioidaan alkuperäisen laskun viesti ennakkolaskuille
- Laajennetaan tilausviite livesearchia niin, että se löytää tiedolla myös viestikentän lopusta
> Ennakkolaskujen viesti

- inc/functions.inc
- kerayksen_kuittaus_ulkoisesta_jarjestelmasta_cron.php
Keräyslistan lähetys:
- Ei lähetetä JT-rivejä
Keräyksen kuittaus:
- Korjattu toimitusajan parsiminen.
- HHV:lla rakenne on hieman erilainen ja korjattu rivien käsittely.
> Ulkoinen järjestelmä: HHV

- synkronoi_tuotteet_ulkoiseen_jarjestelmaan.php
Kenttien oletusarvot vaihdettu 0 -> ''
> Synkronoi tuotteet ulkoiseen järjestelmään

- inc/valitse_tulostin.inc
- Voidaan tulostaa ostotilaus ostotilaus_emailiin mikäli sellainen on yhtiön parametreihin määritelty
> Ostotilaus-email

- inc/avoimet.inc
> Avoimet laskut -raportti: Excel

- inc/functions.inc
- inc/yhtion_parametritrivi.inc
Private-label ominaisuus vain extranettiin. Lisätty uusi yhtiön parametri. Eli jos param on "vain extranet" ja jos ei ole extranet niin saa myydä. Jos on extranet niin pitää löytyä niitä aleja yms.
> Extranet: private label

- myyntires/manuaalinen_suoritusten_kohdistus.php
- näytetään käyttöliittymässä vain käyttökelpoiset tilivalinnat
> Kohdistusfix

- kerayksen_kuittaus_ulkoisesta_jarjestelmasta_cron.php
Korjattu aineistossa tulevien rivien lukeminen.
> Keräys ulkoisesta järjestelmästä: HHV

- dynaaminen_puu.php
Avainsanoille voidaan määritellä kieli.
> Asiakas- ja tuotekategorioiden avainsanojen kieli

- inc/yhtion_parametritrivi.inc
- tilauskasittely/valitse_laskutettavat_tilaukset.php
- tilauskasittely/verkkolasku.php
Uusi yhtiön parametri lisätty joka sallii tulevaisuuteen laskuttamisen jos tilauksella on vain saldottomia tuotteita.
> Laskutus tulevaisuuteen

- inc/tuotehaku.inc
- inc/yhtion_parametritrivi.inc
- tuote.php
Näytetään ruksi jos "Poistuvat tuotteet"-yhtiön parametri on päällä. Ruksi toimii kuten "Poistuvat tuoteet"-parametri aiemmin ("Älä näytä poistuvia, poistettuja, saldottomia ja varastoimattomia tuotteita").
> Tuotekysely: Poistuvat tuotteet -ruksi

- rajapinnat/presta/presta_product_stocks.php
- rajapinnat/presta/presta_products.php
- rajapinnat/presta/presta_tuote_export.php
Korjattu erikoistapauksia multishop ympäristössä.
> Presta varastosaldot

- tilauskasittely/tulosta_lasku.inc
- Näytetään koontilaskulla aina alkuperäisen tilauksen tilausyhteyshenkilö
> Koontilaskun tilaajatieto

- tilauskasittely/mikrotilaus.inc
Nollataan lopetusmuuttuja jotta nähdään tilauksen valmiiksi laittamisen jälkeen "Tilaus valmis"-tiedot.
> Lue tilausrivit tiedostosta

- rajapinnat/pupenext.php
Lisätään pupenext-komentorivirajapintaan funktio lisaa_rivi
> Pupenext-funktiot: lisaarivi

- rajapinnat/pupenext.php
Voidaan luoda ennakkolasku samalla, kun merkitään tilaus valmiiksi.
> Pupenext-funktiot: tilaus_valmis, ennakkolaskutus

- inc/functions.inc
- rajapinnat/pupenext.php
* Haetaan oikeasta indexistä funktiossa tee_ennakkolasku
* Declaretaan force_web globaaliksi
> Huutokauppa fixes

- kerayksen_kuittaus_ulkoisesta_jarjestelmasta_cron.php
Korjattu saldottomien tuotteiden päivitys HHV-keississä.
> Kerayksen kuittaus: Saldottomat tuotteet

- raportit/naytatilaus.inc
- tilauskasittely/selaa_tilauksia.php
- tilauskasittely/varastoon.inc
Korjattu laskentaa, jolla varastonarvoon lasketaan sekä rahtikuluja että kulukertoimella kuluja
> Jälkilaskennan kulut

- tilauskasittely/tilaus_myynti.php
Tarkistetaan hae & selaa oikeus myynnissä ja näytetään "Selaa tuotteita" nappi vain jos ohjelmaan "Hae & selaa" on käyttöoikeus.
> Hae & selaa oikeus

- kerayksen_kuittaus_ulkoisesta_jarjestelmasta_cron.php
Osataan käsitellä tilanne jos yksi tilausrivi tulee monella eri rivillä aineistossa.
> Keräyksen kuittaus: Monirivituki

- raportit/naytatilaus.inc
- tilauskasittely/tulostakopio.php
"Tulosta Vastaanottoraportti kopioita"-ohjelmassa ei näytetä "tilausnumeroa", koska se on saapumisen tunnus mikä ei kerro käyttäjälle mitään.
> Vastaanottoraportti: tulosta kopioita

- inc/functions.inc
- tilauskasittely/tulosta_lasku.inc
- tilauskasittely/verkkolasku_finvoice.inc
- tilauskasittely/verkkolasku_finvoice_201.inc
Osataan näyttää hetu oikein lähetteellä, tilausvahvistuksella, tarjouksella, laskulla ja Finvoicella.
> Tulosteet: hetu

- tilauskasittely/osoitelappu_hornbach_pdf.inc
Pudotettu logon paikkaa hieman alemmas.
> Spesiaali osoitelappu: logon paikka

- inc/valitse_tulostin.inc
- tilauskasittely/tulosta_lahete_kerayslista.inc
- tilauskasittely/tulostakopio.php
- Voidaan tulostaa sähköpostiin excel tilausvahvistuskopio jossa näkyy myös rivihinnat
> Excel tilausvahvistuskopio rivihinnoilla

- tilauskasittely/tilaus_osto.php
Tehdään hyllypaikan tarkistus ja päivitys vain jos tilausrivillä ei ole hyllypaikkaa asetettu
> Ostotilaus: tilaus valmis & hyllypaikka

- inc/pankkiyhteys_functions.inc
- pankkiyhteysadmin.php
Lisätään tuki sertifikaatin uusimiselle, kun pankki on Nordea
> Sepa certificate renewal

- rajapinnat/presta/presta_client.php
- rajapinnat/presta/presta_products.php
- rajapinnat/presta/presta_shop_groups.php
Tuotteet on mahdollista lisätä kaikkiin kauppohin.
> Presta multistore parannuksia

- inc/functions.inc
- rajapinnat/logger.php
- rajapinnat/presta/presta_addresses.php
- rajapinnat/presta/presta_categories.php
- rajapinnat/presta/presta_client.php
- rajapinnat/presta/presta_countries.php
- rajapinnat/presta/presta_customer_groups.php
- rajapinnat/presta/presta_customers.php
- rajapinnat/presta/presta_functions.php
- rajapinnat/presta/presta_manufacturers.php
- rajapinnat/presta/presta_order_histories.php
- rajapinnat/presta/presta_product_feature_values.php
- rajapinnat/presta/presta_product_features.php
- rajapinnat/presta/presta_product_stocks.php
- rajapinnat/presta/presta_products.php
- rajapinnat/presta/presta_sales_orders.php
- rajapinnat/presta/presta_shop_groups.php
- rajapinnat/presta/presta_shops.php
- rajapinnat/presta/presta_specific_prices.php
- rajapinnat/presta/presta_tuote_export.php
Rajapinnan eri ajoja voi ajaa rinnakkain. Jokaisella on ajolla on nyt omat lokit sekä lukkotiedostot.
> Presta rajapinnan tehostaminen

- rajapinnat/presta/presta_client.php
- rajapinnat/presta/presta_customers.php
- rajapinnat/presta/presta_product_stocks.php
- rajapinnat/presta/presta_products.php
- rajapinnat/presta/presta_specific_prices.php
- rajapinnat/presta/presta_tuote_export.php
Lisätään Prestan Specific Prices aina kaupparyhmälle.
Muutettu Presta exportin parametrien järjestystä.
> Presta multistore korjauksia

- mobiili/tuotteella_useita_tilauksia.php
Mobiilipupen yksi kysely splitattu kahteen osaan ja joinit korjattu.
> Jaetaan kysely osiin

- rajapinnat/presta/presta_carriers.php
- rajapinnat/presta/presta_sales_orders.php
Haetaan toimitustavan tiedot EDI -tilaukselle
> Presta toimitustavat

- muuvarastopaikka.php
Tarkistetaan varaako reklamaatio tuotepaikkaa
> Varastopaikan muutos: reklamaatio

- crm/asiakasmemo.php
Muutettu CRM Haas-kenttien näkyvyyttä.
Jos CALL_TYPE on "Prospecting Call" niin seuraavia infoja ei anneta valita:
- OPPORTUNITY
- QTY
-  OPP_PROJ_DATE
- END_REASON
Ja ainoastaan won, lost ja dead call CALL_TYPE:llä annetaan valita END_REASON
> CRM Haas: Kenttien näkyvyys

- saapuminen_ulkoiseen_jarjestelmaan.php
- saapumisen_kuittaus_ulkoisesta_jarjestelmasta.php
- tilauskasittely/ostotilausten_rivien_kohdistus.inc
Poistetaan kaikki ostotilauksen kohdistukset saapumiselta ja kohdistetaan uudestaan aineiston mukaisesti.
> Saapumisen kohdistus ulkoisesta järjestelmästä

- muuvarastopaikka.php
Varastopaikkojen muutos ohjelmaan pieni korjaus tuotepaikan poisto-ominaisuuden tarkistuksiin. Pupesoft esti poiston virheellisesti myös joiltakin paikoilta joissa se olisi ollut ihan ok poistaa.
> Varastopaikkojen muutos

- raportit/naytatilaus.inc
- tilauskasittely/varastoon.inc
Korjattu kotimaan vaihto-omaisuuslaskun omaavan saapumisen tuloutuksessa tapahtuvan rivisumman ja saapumisen summan vertailu. Tämä aiheutti ongelmia mikäli saapumisella oli vain yksi tilausrivi.
> Saapuminen rahtikulut

- inc/functions.inc
- tilauskasittely/tuote_selaus_haku.php
- tuote.php
Tehdään linkki jos selitteestä löytyy http:// tai https://
> Hae & selaa: tuotteen avainsanan linkki

- tilauskasittely/keikka.php
- tilauskasittely/ostotilausten_rivien_kohdistus.inc
Voidaan viedä varastoon normivaraston tuotteita
> Saapuminen ulkoiseen järjestelmään: varastoon vienti 

- rajapinnat/presta/presta_addresses.php
- rajapinnat/presta/presta_categories.php
- rajapinnat/presta/presta_countries.php
- rajapinnat/presta/presta_products.php
* Virtual tuotteen myös 1.6.1 versiossa
* Asiakkaan maan oletukset
* EAN koodin tarkistus
* Tuotteen nimityksen kielletyt merkit
> Presta rajapintapäivitys

- myyntires/suoritusselailu.php
Voidaan poistaa viitteellinen suoritus
> Sallitaan viitteellisen suorituksen poisto

- raportit/myyntiseuranta.php
- Lisätäppä jolla voi rajata raportista pois poistetut asiakkaat
> Myynninseurantaraportin asiakasrajaus

- rajapinnat/edi.php
Lahjakortti ei saa vähentää loppusummaa pupessa, vaan tilaus/lasku päivitetään todellisilla rivi- ja loppusummilla pupeen
> Magento-tilausten sisäänluku

- tuote.php
Näytetään tuotteen toimittajan toimitusaika päivissä
> Tuotekysely: toimitusaika

- rajapinnat/edi.php
- tilauskasittely/editilaus_in.inc
- Tallennetaan sisääntulevan tilauksen tilauskommentti laskulle
> Magento-tilauksen tilauskommentti

- raportit/asiakkaantilaukset.php
Näytetään hauissa paremmin ennakkolaskuun ja loppulaskuun liittyvät osaset, jos haku tehdään johonkin tuon kokonaisuuden osiin.
> Asiakkaan tilaukset, ennakkolaskut

- sepa.php
Määritetään $pankkitiedostot_polku-muuttujalle oikea arvo myös silloin, kun otetaan maksuaineistosta kopio ja lähetetään se pankkiin pankkiyhteyden kautta.
> Korjaus maksuaineistokopioon

- rajapinnat/presta/presta_functions.php
- rajapinnat/presta/presta_products.php
* Tuotekuvia voi hallinnoida nyt Prestassa ja tilanne peilataan Pupesoftiin
> Presta tuotekuvat
