- inc/functions.inc
Passataan $override-muuttuja myös tuoteperheen_lapsien_kertoimet-funktioon
> Korjaus tuoteperheiden hinnoitteluun

- laiterekisteri.php
- Voidaan rajata laitteita sopimusasiakkaalla
TAI
- Voidaan rajata laitteita sarjanumeroseuranta-asiakkaalla
> Laiterekisterin sopimusasiakashaku

- rajapinnat/magento_client.php
- rajapinnat/tuote_export.php
- rakennetaan url_key kenttään arvo tuotteen attribuuteista jotka on merkitty tähän tarkoitukseen
> Magentotuotteiden url_key

- muuvarastopaikka.php
- Siirretään myös varattua saldoa
> Tuotteen varastopaikkojen muutos

- inc/tuoterivi.inc
- inc/tuotetarkista.inc
- matkalasku.php
- Tietyn kilometrimäärän täytyttyä käytetään viranomaistuotteelle(Kilometrikorvaus) asetettua myymälähintaa myyntihinnan sijaan
- Jos kilometrimäärän ylittävä kirjaus syötetään kerralla, jaetaan kilometrit riveille automaattisesti
> Matkalasku: Alennettu kilometrikorvaus

- tilauskasittely/valitse_laskutettavat_tilaukset.php
Näytetään saatavat, kun mennään muokkaaman tilausta Toimita ja laskuta-ohjelmasta. Tämä saavutetaan laittamalla kaytiin_otsikolla-query paramiin arvo NOJOO! muokkaa-linkkiin.
> Saatavat näkyviin laskutusvaiheessa

- inc/functions.inc
- tilauskasittely/keikka.php
- tilauskasittely/ostotilausten_rivien_kohdistus.inc
Tarkistetaan varasto tilausriveiltä ja näytetään nappi vain jos kaikkien tilausrivien varasto on LogMasterin ulkoiseen järjestelmään.
> Saapumisen rivien kohdistus: ulkoinen järjestelmä

- rajapinnat/presta/presta_client.php
- rajapinnat/presta/presta_currencies.php
- rajapinnat/presta/presta_sales_orders.php
- tilauskasittely/editilaus_in.inc
Osataan käsitellä verkkokauppatilauksia eri valuutoissa.
> Verkkokaupan valuutat

- rajapinnat/magento_tilaukset.php
- Voidaan vaihtaa tilaa josta tilaukset noudetaan
> Magento tilaushaku

- saapumisen_kuittaus_ulkoisesta_jarjestelmasta.php
Ulkoisen järjestelmän saapumisen kuittaus -sanomasta lähetetään sähköpostiin viesti mitä kuitattiin, jos uudeksi parametriksi cronille on annettu sähköpostiosoite.
> Saapumisen kuittaus sähköpostiin

- rahtikirja-tulostus.php
Voidaan lähettää Excel-lähete omaan sähköpostiin tilauksittain rahtikirjaa tulostettaessa.
> Excel-lähete tilauksittain

- tilauskasittely/keikka.php
Näytetään saapumisnumero info-popupissa kommentin edessä.
> Keskeneräiset saapumiset: info-popup

- inventoi.php
- kayttajaprofiilit.php
- raportit/myyntiseuranta.php
- raportit/varastotilasto.php
- tilauskasittely/maksutapahtumaselaus.php
- tilauskasittely/monivalintalaatikot.inc
- tilauskasittely/tilaus_myynti.php
Tehty joitain viilauksia kassamyyntiprosessiin.
> * Kassamyyntiin ominaisuuksia

- tuote.php
- näytetään tuotteen tilauksissa myös puuterivit, mutta ne eivät vaikuta muihin summauksiin
> Tuotekyselyn puuterivit

- inc/functions.inc
- tilauskasittely/jtselaus.php
- tilauskasittely/tee_jt_tilaus.inc
- tilauskasittely/tilaus-valmis.inc
Haetaan $yhtiorow uudestaan tilaus-valmis.inc:ssä varaston toimipaikan parametreillä, jos kyseessä on jt-tilaus ja, jos tilauksella oli alunperin varasto määritettynä.
> Korjaus yhtiön parametrien hakuun JT-tilauksilla

- rahtikirja.php
Rahtikirjantietojen syötössä näytetään osoitetietojen alla maan nimet kokonaisuudessaan.
> Rahtikirjantietojen syöttö: maat osoitetietoihin

- tilauskasittely/tilaus_osto.php
- Voidaan vahvistaa ostotilausrivien toimituksia rivi kerrallaan
> Ostotilausrivin toimituksen vahvistaminen

- inc/yhtion_parametritrivi.inc
- tilauskasittely/keikka.php
- tilauskasittely/tilaus-valmis-siirtolista.inc
- tilauskasittely/tilaus-valmis.inc
- uudelleenlaheta-postnord.php
Jos ulkoista järjestelmää käytetään varastossa, niin uudella parametrilla voidaan ohjata sallimalla sen toiminta joko keräyksessä, saapumisella tai molemmissa.
Parametri tukee nyt seuraavia ulkoisia järjestelmiä:
- Posten Logistik keräyksessä
- Helsingin Hyllyvarasto keräyksessä ja saapumisessa
> Uusi yhtiön parametri "Ulkoinen järjestelmä"

- mobiili/hyllytys.php
- mobiili/tuotteella_useita_tilauksia.php
Ei joinata tilausrivilinkillä, jonka arvo on 0.
> Mobiilituloutuksen queryn optimointi

- css/pupesoft.css
- inc/functions.inc
- maksusopimus_laskutukseen.php
- tilauskasittely/laskutus.inc
- tilauskasittely/lisaarivi.inc
- tilauskasittely/maksusopimus.inc
- tilauskasittely/otsik_ostotilaus.inc
- tilauskasittely/syotarivi_ostotilaus.inc
- tilauskasittely/tilaus_myynti.php
- tilauskasittely/tilaus_osto.php
- tilauskasittely/valitse_laskutettavat_tilaukset.php
* Parannettu ennakkoklasutuksen ja loppulaskutuksen valuuttakäsittelyä tilanteessa jossa ennakkolaskun ja loppulaskun valuuttakurssit poikkeavat toisistaan.
* Parannettu/kornattu ostotilauksen käsittelyn ja ostorivin syötön käyttöliittymiä.
> Ennakkomaksut ja Ostotilauksen UI

- rajapinnat/magento_client.php
- Configurable tuotteen url_key jonka voi määritellä avainsanalla
> Magentotuotteiden url_key jatko

- raportit/myyntiseuranta.php
Myynninseurantaraportin jos ajoi asiakasmyyjittäin, mutta oli jättänyt asiakasmyyjittäin ruksin pois, mutta sen sijaan oli laittanut jonkin muun myyjittäin ruksin sai aikaan SQL-errorin.
> Myynninseurantaraportti: asiakasmyyjittäin ajo

- tilauskasittely/tilaus-valmis-tulostus.inc
Yhdistettäessä useita tilauksia samalle keräyslistalle haetaan kaikkien näiden tilausten keräyslistoille tulevat kommentit yms. tiedot, jotka keräyslistoille on tarkoitettu tulevaksi. Aiemmin yhdistettyjen keräyslistojen kommentteihin tuli vain ensimmäisen tilauksen kommentit.
> Keräyslista: useiden tilausten kommentit

- tuote.php
Tuotekyselyssä saldoton tuote näkyi virheellisesti varastoitavana, tämä korjattu
> Saldoton tuote

- inc/functions.inc
- inc/viitemaksut_kohdistus.inc
- myyntires/eikateinen.php
- myyntires/factoring.php
- myyntires/factoringkorko.php
- myyntires/karhu.php
- myyntires/maksunsyotto.php
- myyntires/paperikarhu.php
- myyntires/paperitiliote.php
- myyntires/tratta.php
- nordeafactoring.php
- raportit/factoringstemmuutus.php
- sampofactoring.php
- sveafactoring.php
- tilauskasittely/seb_factoring.php
- tilauskasittely/teelaskuntiliointi.inc
- tilauskasittely/teeulasku.inc
- tilauskasittely/tulosta_lasku.inc
- tilauskasittely/uudelleenluo_laskuaineisto.php
- tilauskasittely/verkkolasku.php
- tilauskasittely/verkkolasku_finvoice.inc
- tilauskasittely/verkkolasku_finvoice_201.inc
- uusiyritys.php
Voidaan käyttää useita factoringsopimuksia per rahoittaja.
> * Useita sopimuksia samaan factoring-yhtiöön

- raportit/topten.php
- Yhdistää samaan näkymään myydyimmät tuotteet, asiakkaat ja asiakasryhmät joille eniten myyntiä on tehty sekä eniten myyneet myyjät
> Top 10 Raportti

- raportit/myyntiseuranta.php
Budjetin kumulatiivinen tavoite lasketaan kokonaisina kuukausina
> Myynninseuranta: kumulatiivinen tavoite

- inc/functions.inc
- tilauskasittely/tilaus_myynti.php
Poistetaan valmisteelle linkitetty sarjanumero/eränumero, mikäli koko valmistus mitätöidään tai mikäli rivi mitätöidään.
> Valmistus: sarja- ja eränumerot

- palkkatosite.php
Voidaan sisäänlukea Palkka.fi-palvelun CSV-palkkatosite
Voidaan sisäänlukea EmCe-palkkahallinnon XLS-palkkatosite
> *Palkka.fi ja EmCe palkkatositteiden sisäänluku

- inc/functions.inc
- tilauskasittely/tulosta_lahete.inc
- tilauskasittely/tulosta_lahete_kerayslista.inc
- tilauskasittely/tulosta_lasku.inc
- tilauskasittely/uudelleenluo_laskuaineisto.php
- tilauskasittely/verkkolasku.php
Uusi funkkari joka tarpeen mukaan poistaa koontilaskutuksen yhteydessä lisätyt yhteensäkommentit riviltä
> Rivikommentti

- tilauskasittely/keikka.php
- tilauskasittely/ostotilauksen_lisatiedot.inc
- tilauskasittely/ostotilausten_rivien_kohdistus.inc
Voidaan valita näytetäänkö rivien erikoisale vai ei
Voidaan valita näytetäänkö verollinen vai veroton nettorivihinta
> * Saapumisen rivien kohdistus

- raportit/varastotilasto.php
Korjattu myyntihinta oikeaan kohtaan
> Varastotilasto: Excel

- inc/yhtion_parametritrivi.inc
- tilauskasittely/tilaus_myynti.php
- tilauskasittely/toimita.php
Voidaan mennä muokkaamaan tilausta "Toimita"-ohjelmassa.
> Toimita: muokkaa tilausta

- rahtikirja-tulostus.php
Lähtöjen hallinnassa, jos yritti sulkea useamman lähdön kerralla tämä ei onnistunut vaan ohjelma joutui virheeseen. Tämä on nyt korjattu ja jatkossa useamman lähdön sulkeminen onnistuu.
> Lähtöjen hallinta: rahtikirjojen tulostus

- inc/pankkiyhteys_functions.inc
Add link to pankkiyhteysadmin.php to certificate expiry notice
> SEPA certificate renewal tweak

- inc/hinnastorivi.inc
- rajapinnat/presta/presta_functions.php
- rajapinnat/presta/presta_specific_prices.php
- rajapinnat/presta/presta_tuote_export.php
- yllapito.php
* Näytetään tuotteen hinnastohinnat tuoteylläpidossa
* Siirretään informatiiviset hinnat Prestashoppiin
> Hinnasto tuoteylläpitoon

- inc/tuotteen_avainsanatrivi.inc
- rajapinnat/magento_client.php
- rajapinnat/tuote_export_functions.php
Voidaan säätää Magenton Attribute Settiä Pupesoftin tuotteen avainsanalla. Jos avainsanaa ei ole määritelty, käytetään Magenton ensimmäistä Attribute Settiä.
> Magento rajapintapäivitys

- inc/asiakashintatarkista.inc
- tilauskasittely/tilaus_myynti.php
Voidaan siirtää myös valuuttahintoja
> Siirrä tuotteet asiakashinnoiksi

- inc/avainsanarivi.inc
- inc/avainsanatarkista.inc
- inc/functions.inc
- synkronoi_tuotteet_ulkoiseen_jarjestelmaan.php
- Voidaan asettaa avainsanalla mistä kentästä ItemNumber tulee Postenin OutboundDelivery sekä MaterialMaster sanomiin
- Ei synkronoida viranomaistuotteita
> Ulkoisen logistiikan tuotekoodi

- raportit/naytatilaus.inc
Aiemmasta järjestelmästä konvertoiduille laskuille ei ole olemassa myyntitilauksia. Nämä laskut näkyvät kuitenkin normaaliin tapaan asiakkaan tilaukset ohjelmassa. Mikäli tälläistä konvertoitua laskua yritti päästä tarkastelemaan kaatui ohjelma. Korjattu nyt niin, että informoidaan käyttäjää tilauksen puuttumisesta.
> Asiakkaan tilaukset: konvertoidut laskut

- inc/toimitustaparivi.inc
Oletusmäärämaan ja Koontirahtikirjan Maan oletettiin olevan maakoodi, vaikka sinne pystyi kirjoittamaan maan nimen. Nyt maa pitää valita olemassa olevista maakoodeista
> Toimitustavan maakoodit

- hyvak.php
Korjattu laskun kuvan näkyminen oikealla puolella jos ollaan ensimmäinen hyväksyjä.
> Laskun hyväksyntä: Taulukon korjaus

- lue_data.php
Avainsana.selitetark -kentät tyhjiksi, jos niihin ei päivitetä mitään
> Avainsana.selitetark -kentät

- menut.php
Valikoihin jos yritti epähuomiossa lisätä ohjelmaa samoilla tiedoilla ja samoilla parametreillä samaan valikkoon sai aikaan virhetilanteen. Käyttäjän ruudulle tuli tällöin vain ilmoitus "virhe tietokantapalvelimess". Korjattu nyt niin, että informoidaan käyttäjää valikon olemassaolosta ja estetään ohjelman kaatuminen virheeseen.
> Valikot: duplikaattiohjelman lisäys

- tilauskasittely/tilaus_osto.php
- Lähetetään sanoma vain mikäli varasto mihin tilataan on merkattu ulkoiseen järjestelmään
> Saapuminen ostotilaukselta fix

- inc/tilaus_in.inc
- inc/yhtion_parametritrivi.inc
- tilauskasittely/lisaarivi.inc
- tilauskasittely/tilaus_osto.php
Tuotekommentti tilausriville -optio lisätty yhtiön parametreihin jolla voidaan rajata tuotteen takana olevaa  "tuotekommentti tilausriville"-syöttökentän toiminnallisuutta myyntiin ja/tai ostoon.
> * Tuotekommentti tilausriville

- tilauskasittely/editilaus_in.inc
Lisätty uusi kenttä "OSTOTIL.OT_HYVAKSYTTAVA", jolla voidaan ohjata tilaus hyväksyntäjonoon
> Editilauksen sisäänluku: tilaus hyväksyntäjonoon

- tilauskasittely/tilaus_myynti.php
Muutos, jolla myös mitätöityjen tilausten vapautuvat saldot saadaan päivittymään verkkokauppaan
> Mitätöityjen tilausten tuotesaldojen vapautuminen

- raportit/halytysraportti.php
Excelin ehdotussarakkeisiin samat nimet kuin käyttöliittymässä
> UI ja Excel samoilla termeillä

- tilauskasittely/uudelleenluo_laskuaineisto.php
- tilauskasittely/verkkolasku.php
Lähetetään SOAP -kehys myös Apixiin.
> Apix verkkolaskurajapintamuutos

- tilauskasittely/ostotilauksen_lisatiedot.inc
- tilauskasittely/tulosta_purkulista.inc
Reverts devlab-oy/pupesoft#3181
> Revert "Purkulista: kommentti"

- tilauskasittely/otsik.inc
Ei pakoteta verkkokauppatilauksia noudoiksi vaikka teknisesti ovatkin käteistä.
> Verkkokaupatilaukset eivät noudoiksi

- crm/tarrat.php
- inc/functions.inc
- inventoi.php
- inventointi_listat.php
- raportit/inventointipoikkeamat.php
- raportit/kateismyynnit.php
- raportit/tuotepaikkalistaus.php
- sampofactoring.php
- tilauskasittely/taydentava_vientiilmo.php
- tilauskasittely/tulosta_tuotetarrat.inc
Postscript konversio ei tue UTF-8 merkistöä, joten konvertoidaan tuloste aina ISO-8859-15 merkistöön.
> Raporttien merkistöt

- tilauskasittely/keikka.php
- tilauskasittely/tulosta_purkulista.inc
- tilauskasittely/tulostakopio.php
Toimii nyt myös Purkulistakopio -toiminnon kautta.
> Tullinimike excel

- saapumisen_kuittaus_ulkoisesta_jarjestelmasta.php
- tuetaan myös toisenlaista sanoman rakennetta missä rivit ovat eri elementin sisällä
> Saapuminen ulkoisesta järjestelmästä

- inc/functions.inc
Lisätään ulkoisen varaston keräyslistaan Pupen tilausviite
> Poistettu <CustReference> / tilausviite kommenteista

- inc/functions.inc
- Lisätään kohde-tieto receiverille RecCustStreet2-elementtiin, mikäli se löytyy
> Outbound-sanoman kohde-tieto

- rajapinnat/presta/presta_functions.php
- rajapinnat/presta/presta_sales_orders.php
- rajapinnat/presta/presta_tuote_export.php
Voidaan säätää käytetäänkö asiakkaan verkkokaupassa antamaa laskutusosoitetta, vai otetaanko laskutusosoite aina Pupesoftin asiakastiedoista.
> Prestashop tilausten laskutusosoite

- raportit/tuloslaskelma.php
Voidaan valita vapaavalintainen vertailujakso tuloslaskelmaan/taseeseen
> Taseraportti vertailukausi

- inc/verkkolasku-in.inc
- inc/yhtion_parametritrivi.inc
Luetaan verkkolaskut sisään nolla verokannalla.
> Alv velvollisuus

- inc/functions.inc
- kerayksen_kuittaus_ulkoisesta_jarjestelmasta_cron.php
- synkronoi_tuotteet_ulkoiseen_jarjestelmaan.php
- käytetään samaa tietoa kuin lähettäessä
> Ulkoisen järjestelmän keräyssanoma

- inc/pankkiyhteys_functions.inc
- pankkiyhteysadmin.php
* Lisätään tuki Danske Bankin varmenteen uusimiselle
> SEPA: Danske Bankin varmenteen uusiminen

- inc/functions.inc
- rajapinnat/presta/presta_carrier_files.php
- rajapinnat/presta/presta_sales_orders.php
- rajapinnat/presta/presta_tuote_export.php
- tilauskasittely/editilaus_in.inc
Tallennetaan EDI-tilauksen liitetiedostot myyntitilauksen liitetiedostoiksi.
> Editilausten liitetiedostot

- pankkiyhteys.php
Laitetaan focus salasanakenttään Pankkiyhteys-ohjelmassa
> Pankkiyhteys: Focus salasanaan

- tilauskasittely/editilaus_in.inc
Voidaan säätää mihin tilaan laitetaan verkkokauppatilauksen tuotteet, jos saldo on loppu.
> Verkkokauppatilaukset

- inc/functions.inc
- tilauskasittely/keraa.php
Näytetään varastossa verkkokaupan liitetiedostoille tulostusnapit, jos lähetteetkin tulostetaan nappien avulla.
> Verkkokaupan liitteet

- tilauskasittely/tilaus_myynti.php
Ei vaihdeta verkkokauppatilauksia väkisin noudoiksi vaikka ovat "käteismaksuja"
> Verkkokauppatilaukset ei noudoiksi

- inc/functions.inc
- kerayksen_kuittaus_ulkoisesta_jarjestelmasta_cron.php
- saapumisen_kuittaus_ulkoisesta_jarjestelmasta.php
- saldovertailu_ulkoisesta_jarjestelmasta_cron.php
- seurantakoodi_ulkoisesta_jarjestelmasta.php
> Ulkoisen varaston sanomatyyppien tarkastus

- inc/functions.inc
- Utf8 encode myös viestille ja asiakkaan tilausnumerolle sillä saattavat sisältää erikoismerkkejä
> Posten OutboundDelivery-fix

- tilauskasittely/lisaarivi.inc
Tuotekkommentti tilausriville ei tullut enää näkyviin, kuin myynnille. Nyt palautettu näkymään tarjoukselle, ennakkotilaukselle, varastosiirrolle, työmääräykselle ja valmistuksille.
> Tuotekommentti tilausriville

- rahtikirja-tulostus.php
Määrä-sarakkeessa (Qty) pitää olla toimitettu määrä ei tilattu määrä.
Myös funktio siirretty koodin alkuun.
> Excel-koontilähete

- tilauskasittely/otsik.inc
- Korjataan SQL error joka syntyy, jos kampanjavalikkoa ei piirretä otsikolle
> Kampanjavalinta otsikolla fix

- kerayksen_kuittaus_ulkoisesta_jarjestelmasta_cron.php
- Huomioidaan sanoman rakenne, jossa tilausrivin tiedot ovat line-elementin sisällä
> Saapuminen ulkoisesta järjestelmästä fix

- rajapinnat/relex/relex_orders.php
Muutama extrakenttä saadaan parametrillä mukaan avoimet tilaukset -aineistoon
> Extrakenttiä avoimiin tilauksiin

- tilauskasittely/otsik.inc
- tilauskasittely/tilaus_myynti.php
Muistetaan verkkokauppatilaustyyppi seuraavallekin tilaukselle, jos se ollaan valittu myyntitilaukselle.
> Muistetaan tilaustyyppi myyntitilauksella

- inc/functions.inc
- saapuminen_ulkoiseen_jarjestelmaan.php
- synkronoi_tuotteet_ulkoiseen_jarjestelmaan.php
* Sanomat tehdään ja lähetetään aina UTF-8 merkistössä
* Koodia järkiperäistetty
> Logmaster rajapinta

- .gitignore
- inc/functions.inc
- tilauskasittely/editilaus_in.inc
- tilauskasittely/tilaus_in.php
- tilauskasittely/vientitilauksen_lisatiedot.php
Näytetään listalla myös laskutetut tilaukset avoimelta kaudelta, joiden lisätiedot ovat kesken
> Vientitilauksen lisätiedot

- inc/functions.inc
Tallennetaan nodelle aina parent_id
> Asiakas- ja tuotekategoriat

- rajapinnat/presta/presta_client.php
- rajapinnat/presta/presta_customers.php
- rajapinnat/presta/presta_functions.php
- rajapinnat/presta/presta_products.php
- rajapinnat/presta/presta_tuote_export.php
Voidaan määritellä dynaamisia atribuutteja myös asiakastietoihin.
> Prestashop asiakasrajapinta

- inc/tuoterivi.inc
Revertataan hidas/bugaava koodi.
> Revert "Haetaan seuraava vapaa"

- tilauskasittely/keikka.php
Laitetaan pakkaus pois päältä excelin luonnin yhteydessä.
> Saapuminen: tullinimike excel

- inc/functions.inc
- muuvarastopaikka.php
Jos haulla ei löytynyt osumaa, niin aiemmin livehaku ei virheen takia pystynyt tekemään uutta hakua. Tämä on nyt korjattu.
> Muuvarastopaikka: Livehaku

- inc/valitse_tulostin.inc
- inventointi_listat.php
Lisätty tuki inventointilista PDF:n tulostamiseen ruudulle
> Inventointilista: PDF ruudulle

- inc/functions.inc
- kerayksen_kuittaus_ulkoisesta_jarjestelmasta_cron.php
- Ei syötetä sanomaan duplikaattiosoitetta
- Keräyksen kuittauksessa sallitaan myös tapaukset joissa vientitiedot syötetty
> XML-sanomien viilaukset

- kerayksen_kuittaus_ulkoisesta_jarjestelmasta_cron.php
- Käsitellään useita rivejä yhdessä sanomassa
> XML-sanoman rivituki

- inc/abc_parametritrivi.inc
Aktivoidaan ylläpito-ominaisuudet asiakas ABC -parametreihin.
> Aktivoidaan asiakas ABC parametrien ylläpito

- rajapinnat/logmaster/resend_logmaster.php
Korjattu parametrit.inc require
> Logmaster: resend

- inc/functions.inc
- rajapinnat/magento_client.php
- rajapinnat/tuote_export.php
Voidaan valita minkä lapsituotteen tietoja käytetään isätuotteella (configurable). Vaihtoehtoja on joko ensimmäinen lapsituote tai halvin lapsituote.
> Magento rajapinta

- inc/varastopaikattarkista.inc
- rajapinnat/logmaster/inbound_delivery.php
- rajapinnat/logmaster/inbound_delivery_confirmation.php
- rajapinnat/logmaster/logmaster-functions.php
- rajapinnat/logmaster/outbound_delivery_confirmation.php
- rajapinnat/logmaster/resend_logmaster.php
- rajapinnat/logmaster/stock_report.php
- rajapinnat/logmaster/synchronize_products.php
- rajapinnat/logmaster/tracking_code.php
- tilauskasittely/keikka.php
- tilauskasittely/tilaus-valmis-siirtolista.inc
- tilauskasittely/tilaus-valmis.inc
- tilauskasittely/tilaus_osto.php
Korjattu lokiviestejä paremmaksi
> Logmaster: korjauksia

- inc/functions.inc
- inc/parametrit.inc
- rajapinnat/logmaster/inbound_delivery.php
- rajapinnat/logmaster/inbound_delivery_confirmation.php
- tilauskasittely/keikka.php
- tilauskasittely/ostotilausten_rivien_kohdistus.inc
Sallitaan saman saapumisen sisäänluku moneen kertaan
> Logmaster: Saapumisen osatoimitus

- inc/yhtion_parametritrivi.inc
- tilauskasittely/tilaus-valmis-tulostus.inc
- tilauskasittely/tilaus-valmis-valitsetila.inc
Uusi lähetteen tulostustapa "X", jolla ohitetaan keräyslistan ja lähetteen tulostus ja siirretään tilaus suoraan keräykseen
> Lähetteen tulostustapa: ohita tulostus & suoraan keräykseen

- extranet_tyomaaraykset.php
- Uutta huoltopyyntöä tehdessä ei avata pdf:ä ruudulle automaattisesti
> RMA portaalin uusi huoltopyyntö

- inc/asiakasrivi.inc
- inc/yhtion_parametritrivi.inc
- myyntires/paperikarhu.php
Yhtiön/asiakkaan parametrillä "Maksukehotuksen osoitetiedot" voidaan nyt valita näytettäväksi sekä virallinen että laskutusosoite maksukehotuksella.
> * Maksukehotuksen osoitetiedot

- raportit/varastotilasto.php
Voidaan ajaa myös "ostoraportti" varastotilasto-ohjelmalla
> * Varastotilastoraportin "ostoraportti"

- rajapinnat/logmaster/outbound_delivery.php
- rajapinnat/logmaster/outbound_delivery_confirmation.php
Korjattu aikatarkistus & tiedoston looppaus
> Logmaster: Confirmation-sanomat & 15min viive

- inc/functions.inc
- tilauskasittely/tarkistarivi.inc
- tilauskasittely/valitse_laskutettavat_tilaukset.php
Huomautetaan jos osaluettelon hinta on epäsyncissä tilauksen hinnan kanssa.
> Osaluettelon hintatarkistus

- rajapinnat/yrityspeli/yrityspeli.php
- rajapinnat/yrityspeli/yrityspeli_functions.php
Voidaan valita tuoteryhmä, josta valitaan tuotteet generoidulle ostotilaukselle yrityspelissä
> Tuoteryhmät yrityspeliin

- rajapinnat/yrityspeli/yrityspeli.php
- rajapinnat/yrityspeli/yrityspeli_functions.php
Voidaan valita toimipaikka yrityspelissä ostotilauksia generoitaessa
> Toimipaikka yrityspeliin

- tuote.php
* Lisätään Tuotekysely-ohjelmaan Tuotteen tapahtumat-kohtaan yhteensä-rivi
* Rivillä näytetään summaukset määrälle ja arvolle
* Rivi näytetään ainoastaan, jos on valittu laji.
> Tuotetapahtumiin yhteensä-rivi

- tilauskasittely/editilaus_in.inc
Myyntitilaukselle saattoi mennä automaattikommentteja käyttäjän eikä asiakkaan kielellä.
> Myyntitilaus: kommentteja asiakkaan kielellä

- raportit/myyntiseuranta.php
- Myynninseurannassa voidaan tarkastella joko kaikkien tai vain yhden kampanjan lukuja
> Kampanjatilausten seuranta

- crm/asiakaslista.php
> CRM: Asiakaslista

- rajapinnat/logmaster/logmaster-functions.php
> Logmaster: outbound delivery

- extranet/login_extranet.php
Ei näytetä extranet-loginissa yrityksiä, joihin ei ole oikeuksia.
> Extranet-login parannus

- raportit/myyntiseuranta.php
Myynninseurantaraportin excelin tallenttaminen ei toiminut kunnolla vaan lopputuloksena oli rikkinäinen excel. Korjattu nyt niin, että excelin tallentaminen toimii oikein.
> Myynninseurantaraportti: xls-korjaus

- rajapinnat/yrityspeli/yrityspeli_functions.php
* Tallennetaan yrityspelissä generoidulle tilaukselle asiakkaan tiedot toimittajan sijaan
* Tulostetaan ostotilaus-pdf:ään valitun toimipaikan tiedot
> Korjauksia yrityspeliin

- muistutus_vahvistamattomista_ostotilauksista.php
- raportit/ostotilausten_seuranta.php
- tilauskasittely/tilauksesta_ostotilaus.inc
- tilauskasittely/tilaus_osto.php
Päivitetään ostotilaukselle jälki milloin ja kuka laittoi sen valmiiksi
> Ostotilaus: Tilaus valmiiksi jälki

- hyvak.php
- inc/tiliointirivit.inc
Laitetaan oikealle tulevan laskun kuva lähemmäksi taulukoita
> Laskujen hyväksyntä: laskun kuva

- tilauskasittely/otsik.inc
Kun muokattiin laskutusvalmista vientitilausta, kuljetusmuoto nollautui. Nyt tämä on korjattu
> Kuljetusmuoto laskutusvalmista vientitilauksella

- rajapinnat/magento_client.php
- rajapinnat/tuote_export.php
- rajapinnat/tuote_export_functions.php
- Saldotiedot voidaan määritellä siirtymään erikseen myös tuotteen taakse erilliseen kenttään
- Tätä saldotietoa varten voidaan käyttää erillisiä varastoja
> Magenton saldotiedot tuotekenttään

- aloita_synkronointi.php
- lue_data.php
Kun esim. tuotetta muutettiin käyttöliittymästä, se synkronoitiin, mutta jos muutokset tehtiin excelillä, ei synkronointia tehty.
Nyt synkronoidaan myös excelillä muutetut
> Synkronoidaan myös muutetut

- rajapinnat/logmaster/logmaster-functions.php
- rajapinnat/logmaster/outbound_delivery.php
- rajapinnat/logmaster/resend_logmaster.php
- tilauskasittely/tee_jt_tilaus.inc
Halutaan "lahetetty_ulkoiseen_varastoon"-kentälle null arvo
> Logmaster: Ennakkotilaus

- tilauskasittely/editilaus_in.inc
Special case eräälle yritykselle
> Futursoft tilauksen sisäänluku

- inc/functions.inc
- inc/yhtion_parametritrivi.inc
- js/tilaus_myynti/tilaus_myynti.js
- raportit/asiakkaantilaukset.php
- tilauskasittely/syotarivi.inc
- tilauskasittely/tilaus_myynti.php
- tilauskasittely/tilauskanta.php
- tilauskasittely/tulosta_lahete.inc
- tilauskasittely/tulosta_lahete_kerayslista.inc
- Tilausrivin esisyötön lisäyksiä: kateprosentin lisäksi myös yksikköhinta ja rivihinta näkyviin. Lisäksi, jos riviä muokataan, niin näytetään siellä nuo kate%, yks.hinta ja rivihinta.
- "Asiakkaan tilaukset"-ohjelmaan lisätty "Lasku PDF"-nappi jos käyttäjällä on oikeus laskukopioon
- Myyntiraportit / Tilauskanta ohjelmaan viimeiseksi sarakkeeksi tilauksen myyjä selkokielisenä
- Lisätty yhtiön parametri jolla voidaan ohjata livesearchin syötettävien merkkien minimimäärää tuotehaussa.
- Lisätty yhtiön parametri jolla voidaan ohjata keräyslistalle tuotepaikan alle tuotteen toinen tuotepaikka saman varaston sisältä, jos semmoinen löytyy
> QoL: muutoksia

- raportit/varastonarvo-super.php
- Voidaan rajata osto ja myyntitiedot vain tuotteilta joiden toimittaja kuuluu konserniin
> Varastonarvo tuotteittain

- raportit/naytatilaus.inc
Korjataan paluulinkki jos tullaan "Tulosta keräyslista"-ohjelmasta
> Näytä tilaus: paluulinkki

- inc/functions.inc
- inc/tilaa_ajax.inc
- inc/yhtion_parametritrivi.inc
- tilauskasittely/lisaarivi.inc
- tilauskasittely/ostotilausten_rivien_kohdistus.inc
- tilauskasittely/otsik_ostotilaus.inc
- tilauskasittely/tarkistarivi_ostotilaus.inc
- tilauskasittely/tilaus_osto.php
Tuki uudelle "ostotilaukseen_toimittajan_toimaika"-parametrin asennolle:
"Tuotteen toimittajan toimitusaika ensisijaisesti ja toimittajan toimitusaika toissijaisesti päivitetään automaattisesti riville"
Ostotilauksen syötön käyttöliittymään päivitys:
Vahvista toimitusaika ja päivitä toimitusaika ominaisuudet nyt linkeillä ja AJAX-kutsulla.
> * Ostotilauksen toimitusaika

- inc/pankkiyhteys_tilioteviite.inc
Otetaan pankkikohtaiset tiedostotyyppierot huomioon laskujen sisäänluvussa
> Korjaus laskujen hakemiseen pankkiyhteydellä

- inc/tuotehaku.inc
Sallitaan jatkossa wildcard haku (=voi hakea osittaisella toim_tuotenumerolla) ja rajataan myös haku toimittajalla, jos ollaan ostotilauksella hakemassa tuotetta.
> Toimittajan tuotenumerolla hakeminen

- tilauskasittely/tilaus-valmis-siirtolista.inc
- tilauskasittely/tuote_selaus_haku.php
Korjattu myyntitilin keräyslistan tulostus "PDF ruudulle".
> Myyntitili: Keräyslista "PDF ruudulle"

- js/tilaus_myynti/tilaus_myynti.js
Laitetaan tarkistus oikean iffin sisään
> Myyntitilaus: javascript

- inc/yhtion_parametritrivi.inc
- tilauskasittely/ostotilauksen_lisatiedot.inc
- tilauskasittely/tulosta_purkulista.inc
Purkulistalle pitkä kommentti. Lisätty yhtiön parametriin "Purkulistan asettelu" uusi valinta joka mahdollistaa pitkän kommentin.
> Purkulista: kommentti

- rajapinnat/magento_client.php
- ei muuteta configurable-isätuotteen tuoteryhmiä updatessa jos tuoteryhmäyliajo on päällä
> Magenton configurable-tuotteen päivitys

- raportit/hinnoittelupoikkeamat.php
- yhdenmukaistetaan funktion käyttö
- korjaa sql errorin hinnoittelupoikkeamat-raportilla
> Rahtituotefix

- inc/pankkiyhteys_tilioteviite.inc
* Tulkitaan oikein, tuliko SEPA-aineistoistossa mukana laskuja.
> Korjaus laskujen sisäänlukuun

- rajapinnat/logger.php
- rajapinnat/presta/presta_customer_messages.php
- rajapinnat/presta/presta_customer_threads.php
- rajapinnat/presta/presta_sales_orders.php
Tallennetaan Prestashopissa asiakkaan jättämät viestit tilauksen kommenttiin.
> Prestashop asiakkaan viestit

- inc/avainsanarivi.inc
- inc/functions.inc
- tilauskasittely/lahetteen_tulostusjono.php
* Voidaan halutessa näyttää ohjelma_moduli keräyslistan tulostuksessa
* Valinta tehdään laittamalla ohjelman alanimeen muuttujan show_ohjelma_moduli arvoksi true eli siis &show_ohjelma_moduli=true
> Ohjelmamodulin näyttäminen

- basw_siirto.php
Basware-siirto raportissa voidaan jatkossa ryhmitellä tulosta ajanjakson mukaan vuosittain tai kuukausittain. Oletus on että ei ryhmitellä.
Lisäksi jos kirjanpidon tarkenteissa käytetään projekteja, voidaan lisäoptiolla ryhmitellä tulosta kustannuspaikkojen lisäksi myös projekteilla. Oletus on kustannuspaikoittain.
> Basware-siirto lisäoptioita

- inc/functions.inc
Hyväksytään myös viitemaksuissa saman päivän aineistoja monessa osassa
> Tuetaan useita viiteaineistoja samalle päivälle

- tilauskasittely/ostotilausten_rivien_kohdistus.inc
Siirretään tooltip linkistä omaan ikoniin.
> Saapuminen: rivien kohdistuksen tooltip

- inc/functions.inc
- inc/toimitustavat_toimipaikat.inc
- inc/toimitustavat_toimipaikatrivi.inc
- tilauskasittely/tilauksesta_varastosiirto.inc
- yllapito.php
> Toimitustavan toimipaikat

- rajapinnat/magento_client.php
- rajapinnat/tuote_export.php
- voidaan asettaa kaikki tuotteet aina tilaan 'varastossa' saldotiedoista riippumatta
> Magento-tuotteen varastotila

- rajapinnat/magento_client.php
Mahdollistetaan tuotekuvien käsittely vain tuotteen luontivaiheessa.
> Magenton tuotekuvat

- tilauskasittely/keikka.php
- tilauskasittely/ostotilausten_rivien_kohdistus.inc
> Saapumisen kohdistuksen infopallerot

- raportit/varastotilasto.php
Silloin kun on ruksattuna 'Näytä vapaa saldo' ja jälkitoimitukset varaavat saldoa, näkyvät ne varattu -luvussa, muuten jälkitoimituksessa olevat näytetään omassa sarakkeessa
> Jälkitoimitukset varastotilastossa

- inc/toimitustavat_toimipaikatrivi.inc
- yllapito.php
Korjattu toimipaikan tunnuksella tai nimellä haku
> Toimitustavan toimipaikat: toimipaikan haku

- matkalasku.php
Toisen käyttäjän toiselle tekemät kesken jääneet matkalaskut eivät näkyneet enää missään. Matkalasku super ohjelmaa on nyt muutettu niin, että käyttäjän toiselle käyttäjälle tekemät matkalaskut näkyvät nyt myös matkalaskun laatijalla, joka voi niitä muokata.
> Matkalasku super: toiselle käyttäjälle tehdyt matkalaskut

- inc/unifaun_send.inc
- rajapinnat/unifaun/unifaun-functions.php
- tilauskasittely/rahtikirja_unifaun_uo_siirto.inc
Lisätään tuotteiden VAK tiedot Unifauniin lähteviin sanomiin
> * Unifaun sanomiin VAK tuki

- tilauskasittely/tuote_selaus_haku.php
Livetuotehaku "Hae ja selaa"-ohjelmaan
> Hae ja selaa: livetuotehaku

- tilauskasittely/tulosta_lasku.inc
Korjattu päivämäärän esitys viivakoodille. Tarvitaan etunollia
> Tulosta lasku: viivakoodi

- crm/viikkosuunnitelma_raportti.php
- tilauskasittely/verkkolasku_elmaedi.inc
Lisättiin muutama uusi kenttä aineistoon.
Lisäksi korjattiin edustajaraportin tiivistetty näkymä, jossa rivitasolle porautuminen ei toiminut oikein.
> Elma edi inhouse muutos

- datan_massalisays.php
Voidaan antaa kuvan nimessä käyttötarkoitus mukana =-merkillä eroteltuna.
> Tuo/vie tuotekuvia: käyttötarkoitus

- tilauskasittely/tilaus_myynti.php
Korjattu näkymän formi kassamyynnissä, kun näytetään "Tulosta kuitti"-nappi ja apulaskuri.
> Myyntitilaus: kassamyynti

- tilauskasittely/tilaus_myynti.php
Laitetaan tilaus lukkoon, jos tilaus on lähetetty ulkoiseen varastoon
> Myyntitilaus: ulkoisen järjestelmän lukko

- inc/avoimet.inc
- inc/parametrit.inc
"Avoimet laskut"-ohjelmaan lisätty ruksi joka näyttää maksukehotuksien lukumäärän ja viimeisimmän maksukehotuksen päivämäärän. Muistetaan käyttäjän valinta.
> Avoimet laskut: maksukehotukset

- inc/yhtion_parametritrivi.inc
- muokkaatilaus.php
Ennakkotilaukset halutaan siirtää ennen toimitusta myyntitilaus kesken-tilaan.  Yhtiön parametriin "Ennakkotilausten toimitus" on lisätty uusi valinta.
> Ennakkotilaus: myyntitilaus kesken

- inc/functions.inc
- inc/jaaostolasku.inc
- maksusopimus_laskutukseen.php
- monistalasku.php
- tilauskasittely/keraa.php
- tilauskasittely/kopioi_tilaus.inc
- tilauskasittely/tee_jt_tilaus.inc
- tilauskasittely/teeulasku.inc
- tilauskasittely/tilauksesta_myyntitilaus.inc
- tilauskasittely/tilaus-valmis-siirtolista.inc
- tilauskasittely/tilaus-valmis.inc
- valmistuslinjat.inc
Varmistetaan, että aikaleimaan tallennetaan `NULL`.
> Lähetetty ulkoiseen varastoon aikaleima

- inc/functions.inc
- tuoteperhe.php
Uusi hintatyyppi. Hinta määritellään isätuotteelle, lapsituote ei tarvitse keskihankintahintaa.
> Tuoteperheiden hintatyyppi

- extranet/login_extranet.php
- extranet/tervetuloa.php
- inc/avainsanarivi.inc
- inc/avainsanatarkista.inc
- inc/parametrit.inc
- Extranetin otsikkoteksti avainsanasta
- Extranetin kirjautumisruutuun tuki omalle logolle
- Kirjautumisruudun kieli selaimen kielen perusteella sallituilla kielillä (sanakirjatuki)
> RMA portaali

- inc/functions.inc
- tilauskasittely/otsik_ostotilaus.inc
* Annetaan ostaa ostotilauksella myös erikoisvarastoihin, joihin käyttäjällä on oikeus
* Refaktoroidaan ostotilauksen sallitut-varastot-logiikka sallitut_varastot-funktioon
> Korjaus ostotilauksen varaston valintaan

- rajapinnat/magento_client.php
- Tilaustenhaun parannus: jos statuspäivityksessä tapahtuu jotain odottamatonta, ei kaaduta virheeseen
> Magento-tilaukset fix

- inc/functions.inc
- tilauskasittely/tuote_selaus_haku.php
Korjattu javascript niin että enterin painallus käynnistää haun
> Hae & selaa: tuotenumerolla haku

- inc/avainsanarivi.inc
- inc/functions.inc
- inc/tuoterivi.inc
- inc/tuotetarkista.inc
- inventointi_listat.php
- rajapinnat/presta/presta_functions.php
- raportit/abc_luokka.php
- raportit/abc_osastotry.php
- raportit/abc_yhteenveto.php
- raportit/inventointiaste.php
- raportit/myyntiseuranta.php
- raportit/ostoehdotus_cs.php
- raportit/raaka-aine_ostoraportti.php
- raportit/toppivarastopaikat.php
- raportit/valmistuksen_suunnittelu.php
- raportit/varastonarvo-super.php
- tuote.php
- vaihda_tuoteno.php
- yllapito_tuotekuvat.php
Tuotteelle kiinteät statukset A (aktiivi), T (tilaustuote), E (ehdokastuote), X (Poistuva), ja P (poistettu).
> Tuoteylläpito: status

- inc/functions.inc
- tilauskasittely/teeulasku.inc
- tilauskasittely/uudelleenluo_laskuaineisto.php
- tilauskasittely/verkkolasku.php
- tilauskasittely/verkkolasku_finvoice.inc
- tilauskasittely/verkkolasku_finvoice_201.inc
- tilauskasittely/verkkolasku_pupevoice.inc
Funktoitu laskustringin puhdistus ja lisätty muutama merkki sallittujen joukkoon
> Kommenttien puhdistus

- tilauskasittely/tuote_selaus_haku.php
Käyttöliittymän ulkoasuparannuksia
> Hae ja selaa

- tilauskasittely/tulosta_lasku.inc
- tilauskasittely/verkkolasku_finvoice.inc
- tilauskasittely/verkkolasku_finvoice_201.inc
- tilauskasittely/verkkolasku_pupevoice.inc
Ei laiteta hetun loppuosaa sellaisenaan laskulle vaan korvataan se äksillä - XXXX.
> Myyntilaskut: hetun näkyminen

- myyntires/paperikarhu.php
- tilauskasittely/uudelleenluo_laskuaineisto.php
- tilauskasittely/verkkolasku.php
- tilauskasittely/verkkolasku_finvoice.inc
- tilauskasittely/verkkolasku_finvoice_201.inc
Tägätään Talenom fatoringlaskut.
> Talenommyyntilaskurajapinta / factoringlaskut

- tilauskasittely/tulosta_ostotilaus.inc
> Tulosta ostotilaus: asiakkaiden nimet

- tilauskasittely/tilaus_myynti.php
Tarkistetaan missä tilassa tilaus on ennen kuin laitetaan se lukkoon
> Myyntitilaus: Ulkoinen varasto & muokkauslukko

- inc/avoimet.inc
Uusi toimipaikka-rajaus aiheutti sen, että yhtiössä, jossa oli toimipaikkoja käytössä, raporttiin haettiin virheellisesti laskuja vaihtoehdolla 'Kaikki toimipaikat'.
Lisäksi muutos aiheutti sen, että jaettuja laskuja ei tullut raportille enää lainkaan.
Nämä on nyt korjattu
> Avoimet laskut

- tilauskasittely/tarkistarivi_ostotilaus.inc
- tilauskasittely/teeulasku.inc
- tilauskasittely/uudelleenluo_laskuaineisto.php
- tilauskasittely/verkkolasku.php
- tilauskasittely/verkkolasku_finvoice_201.inc
Nimikenttien splittausta korjailtu.
Myyntilaskut merkataan pupessa maksetuiksi, koska reskontra hoidetaan Talenomissa.
> Talenom lisäyksiä

- inc/parametrit.inc
- defaultkieli joka ei yliaja Suomea
> Kirjautumisruudun kieli

- inc/toimitarkista.inc
Tarkempi henkilötunnuksen tarkistus matkalaskukäyttäjille.
> Matkalaskukäyttäjät: hetun tarkastus

- inc/functions.inc
Jälkilaskenta ei osannut ottaa huomioon hintamuutoksia valmistuksen jälkilaskenassa oikein kun muutettiin erä- tai sarjanumerollisen tuotteen ostohintaa jota oli valmistuksella käytetty raaka-aineena.
> Jälkilaskenta: sarjanumerollisten tuotteiden käsittely

- tilauskasittely/toimitusvahvistus_email.inc
Lokitetaan sähköpostin lähetys
> Toimitusvahvistus email: lokit

- rajapinnat/magento_client.php
Kaapataan virhe loopin sisällä
> Magento tuote-export: Asiakaskohtaiset hinnat

- hyvak.php
Annetaan myös laatijan poistaa keskeneräinen matkalasku
> Keskeneräisen matkalaskun poistaminen

- inc/unifaun_send.inc
Unifaun lähettäjän / vastaanottajan rahtisopimus korjaus. Sanoma ei huomioinut esim rahtikirjan syötössä annettua rahtisopimusnumeroa tai jos vaihdettiin esim lähettäjän rahtisopimus vastaanottajan rahtisopimukseen.
> Unifaun rahtisopimus

- hyvak.php
- inc/functions.inc
Suositaan PDF-liitetiedostoja kun avataan se samaan näkymään
> Laskujen hyväksyntä: Avaa lasku -liite

- tilauskasittely/tee_jt_tilaus.inc
Jos jälkitoimitusrivi vapautetaan esim tekemällä odottavalle tuotteelle tuloutus, siirretään jatkossa alkuperäisen tilauksen laatija uudelle jälkitoimitustilaukselle laatijaksi. Aikaisemmin tuloutuksen tehnyt henkilö meni laatijaksi.
> Jälkitoimituksien laatija

- inventoi.php
Kevyessä tuloutuksessa voidaan antaa ostohinta, joka myös tallentuu päätoimittajan ostohinnaksi.
> Kevyt tuloutus ostohinta

- extranet/login_extranet.php
Korjataan extranet-login tukemaan useampaa yritystä per käyttäjä
> Korjaus extranet-kirjautumiseen

- tilauskasittely/verkkolasku_finvoice_201.inc
ToIntermediator ei saa olla tyhjä
> Finvoice 2.01

- inc/functions.inc
- inc/yhtion_parametritrivi.inc
- tilauskasittely/tulosta_lasku.inc
- tilauskasittely/uudelleenluo_laskuaineisto.php
- tilauskasittely/verkkolasku.php
- tilauskasittely/verkkolasku_finvoice.inc
- tilauskasittely/verkkolasku_finvoice_201.inc
- verkkolasku_resend.php
Alustava tuki Arvato-operaattorille
> * ARVATO laskutuspalvelu

- tilauskasittely/toimitusvahvistus_email.inc
Fixataan toimitusvahvistus_email ilman hintoja
> Fixation ilman hintaa

- inventoi.php
Kevyt tuloutuksessa osataan jatkossa luoda tuotteelle toimittajatiedot. Ohjelma siirtää käyttäjän tuotteen_toimittajat ylläpitoon ja perustuksen palauttaa takaisin kevyeeseen tuloutukseen.
> Kevyt tuloutus toimittajatiedot

- tilauskasittely/tulosta_lasku.inc
> Pankkiviivakoodi laskulla

- raportit/tyojonossa.php
- tilauskasittely/otsik.inc
Haetaan työmääysten statukset avainsanoista vain käyttäjän kielellä.
> Työmääräysten statukset

- magento_toimita_tilaus.php
- raportit/naytatilaus.inc
- tilauskasittely/lahetysten_seuranta.php
Fixataan Postin seurantalinkit
> Postin seurantalinkki

- raportit/tyojonossa.php
- tervetuloa.php
Haetaan avainsanat vain kerran, ettei tyojonojen rivit tuplaannu
> Tyojonoista tuplat pois

- tilauskasittely/otsik.inc
- tilauskasittely/tilaus_myynti.php
Estetään nolla-viitteen syöttäminen myyntitilauksella
> Myyntitilaus: Viitenumero ei saa olla nolla

- monistalasku.php
- tilauskasittely/uudelleenluo_laskuaineisto.php
- tilauskasittely/verkkolasku.php
- tilauskasittely/verkkolasku_finvoice_201.inc
PienviilauksiaTalenom ja PPG rajapintoihin.
> Talenom / PPG ominaisuuksia

- tilauskasittely/tilauksesta_ostotilaus.inc
- tilauskasittely/tulosta_ostotilaus.inc
Koitetaan tulostaa edi-tiedoilla. Jos niitä ei ole syötetty niin koitetaan tulostaa toimittajan sähköpostiin.
> Tilauksesta ostotilaus: tulostus

- tilauskasittely/tee_jt_tilaus.inc
Reverts devlab-oy/pupesoft#3421
> Revert "Jälkitoimituksien laatija"

- inc/functions.inc
- js/tilaus_myynti/tilaus_myynti.js
Otetaan huomioon valuutta. Lisätty myös 500ms viive muutoksiin.
> Myyntitilaus: esisyöttö & valuutat

- tilauskasittely/otsik.inc
Jos käydään asiakasylläpidossa ja tullaan takaisin, niin haetaan tiedot tilaukselta.
> Myyntitilaus: muuta asiakkaan tietoja

- raportit/varastotilasto.php
Uusi ajotapa jolla saa räätälöidyn excelin ulos
> Uusi, rajattu excel

- rajapinnat/magento_client.php
- rajapinnat/tuote_export.php
Jos kaikkia asiakasalennuksia ei voi poistaa kerralla, poistetaan ne yksitellen.
> Magento asiakasalennus

- ftp-get.php
- inc/functions.inc
- sftp-get.php
- tehdas_saldot.php
SFTP-tuki lisätty "Tehtaan saldot" -ohjelmaan. Voidaan laittaa laittaa ajastettuun ajoon tai ajaa yksinään.
> Tehtaan saldot: SFTP-haku

- inc/avainsanarivi.inc
- tilauskasittely/verkkolasku_finvoice_201.inc
Etsitään tulostuspalvelua Finvoice_senderintermediatorille  avainsanoista, jos ei muuten löydy
> Parannus tulostuspalveluun

- rajapinnat/tuote_export.php
- rajapinnat/tuote_export_functions.php
Voidaan halutessa lisätä ensimmäisen tuotteen toimittajan tehtaan saldo myytävissä olevaan määrään.
> Magento tuote export: Tehdas saldot

- raportit/atk-tilintarkastus.php
ATK-tilintarkastus ohjelmalla saa nyt Pupesta helposti tallennetua kaiken kirjanpitomateriaalin arkistoitavaksi.
> * Tilinpäätösdatan tallennus

- rajapinnat/tuote_export_functions.php
Jos tehdas-saldoja on päivitetty, triggeröidään siintä Magentoon saldojen päivitys
> Magento: Tuote export & tehdas-saldot

- raportit/topten.php
Näytetään raportissa aina kokonaismyynti. Kokonaismyyntiin vaikuttaa aikarajaus.
> Top10-raportti: kokonaismyynti

- inc/functions.inc
Reverts devlab-oy/pupesoft#3442
> Revert "Synkronointi: Synkronointikielto & MYSQLALIAS oletusarvo"

- tilauskasittely/mikrotilaus.inc
Lisätty E-netto riveille tuki myyntitilauksella tuotteiden tiedostosta sisäänlukuun.
> Tilauksen sisäänluku fix

- rajapinnat/presta/presta_addresses.php
- rajapinnat/presta/presta_functions.php
Prestan osoitetietoihin lisätään asiakkaan ytunnus ja nimi.
> Presta asiakasrajapinta

- inc/functions.inc
Alennusprosentti ei tullut enää myyntitilausrivien esisyötössä näkyviin vaan alennusprosentti jäi esisyötössä tyhjäksi. Tämän on nyt korjattu ja jatkossa alennusprosentti täytetään esisyötössä oikein.
> Myyntitilauksen esisyöttö: alennusprosentti

- inc/yhtion_parametritrivi.inc
- tilauskasittely/tilaus_myynti.php
ulkoinen_jarjestelma_lukko, jolla voidaan säätää saako ulkoiseen varastoon lähettyjä tilausia muokata
> Uusi yhtiön parametri

- tilauskasittely/tilausvahvistus-email.inc
Jos halutaan tilausvahvistus vain omaan sähköpostiin, niin ei lähetetä sitä silloin asiakkaan sähköpostiin
> Email-tilausvahvistus

- inc/yhtion_parametritrivi.inc
- tilauskasittely/lisaarivi.inc
- tilauskasittely/tarkistarivi.inc
- tilauskasittely/tilauksesta_varastosiirto.inc
- tilauskasittely/tuote_selaus_haku.php
Uusi yhtiön parametri, jolla voi säätää pyöristetäänkö myyntitilauksella tuotteen määrä ylöspäin minimimäärään.
> Tuotteen minimimäärä

- inc/yhtion_parametritrivi.inc
- tilauskasittely/tilaus_myynti.php
Voidaan tallentaa tarjouksen tai myyntitilauksen alennukset asiakasalennuksiin.
Myyntipuolella ominaisuutta säädetään "myynti_asiakhin_tallenna" -parametrillä. Tarjouspuolella ominaisuus on aina käytettävissä. Käyttäjällä tulee lisäksi olla käyttöoikeudet asiakashintojen ja/tai asiakasalennusten ylläpitoon.
> * Asiakasalennusten tallennus

- tuote.php
Myyjä näkyviin tapahtumiin jos tyyppi on laskutus
> * Tuotekysely: tapahtumat & myyjä

- tilauskasittely/tulosta_hintalaput.inc
- tulosta_tuotetarrat.php
Voidaan valita halutaanko tulostaa verollinen vai veroton hinta
> Tuotteen hintalappu

- inc/functions.inc
- tilauskasittely/tulosta_lasku.inc
Normaali laskupohja (Näytetään myös yhteensä ilman alennuksia)
> Uusi laskupohja

- rajapinnat/presta/presta_addresses.php
- rajapinnat/presta/presta_client.php
Prestan osoitteen yrityksen nimessä saa olla numeroita
> Presta rajapinta

- tilauskasittely/lisaarivi.inc
- tilauskasittely/syotarivi.inc
- tilauskasittely/tilaus_myynti.php
Saldotarkistusta ei tehdä jo kerätylle riville, kun sitä muokataan
> Kerättyjen ja toimitettujen rivien saldotarkistus 

- inc/toimitarkista.inc
Lue datassa iban/bic tarkistus kuntoon
> Toimittajan tarkistus

- inc/functions.inc
- rajapinnat/presta/presta_functions.php
Siirretään kaikki hinnastohinnat PrestaShoppiin. Aikaisemmin siirrettin ainoastaan tuorein.
> PrestaShop rajapintamuutos

- rajapinnat/presta/presta_kayttoliittyma.php
Käyttöliittymä PrestaShop rajapintojen manuaaliseen käynnistykseen
> PrestaShop rajapinta

- tilauskasittely/lisaarivi.inc
Sallitaan tuoteperheen lapselle negatiivinen kappalemäärä.
> Myyntitilaus: negatiivinen kappalemäärä lapsella

- hyvak.php
Kun poisti laskun, kaikki muut hyväksyttävänä olevat laskut katosivat näytöltä.
Tämä on nyt korjattu.
> Hyväksyttävät laskut

- tilauskasittely/ostotilauksen_lisatiedot.inc
Alennuksen voi nyt syöttää myös desimaalipilkulla.
Talletetaan erikoisalennus normaalihintaisille riveille annetun suuruisena, vaikka saapumisella olisi nettohintaisia rivejä
> Ostotilauksen erikoisalennus saapumisella

- inc/yhtion_parametritrivi.inc
- rahtikirja.php
- tilauskasittely/tilaus-valmis-valitsetila.inc
- Lisätty uusi parametri "Saldottomat rahtikirjansyöttöön. Ohjataan koko tilaus rahtikirjojen tulostukseen.
- Ehdot:
- Tilauksen kaikki rivit ovat saldottomia
- Tilausrivin tuotteen tyyppi on "Normaali / Valmiste"
> Saldottomat tuotteet rahtikirjansyöttöön

- tilauskasittely/sarjanumeroseuranta.php
Jos tiedostossa oleva sarjanumero löytyy jo, ruksataan se. Jos ei löydy, lisätään ja ruksataan.
> Sarjanumeroiden lisääminen tiedostosta

- tilauskasittely/tarkistarivi.inc
Myyntitilauksella saattoi tulla virheellisesti ilmoitus "HUOM: tämä on korvaava tuote, haluatko hyväksyä?". Nyt tarkistus on tarkennettu ja tuotenumeroita osataan verrata oikein.
> Myyntitilaus: korvaavuusketjut

- tilauskasittely/uudelleenluo_laskuaineisto.php
Pupesoft-Pupesoft verkkolaskujen uudelleenkäsittely
> Verkkolaskun uudelleenläheys

- inc/functions.inc
- tilauskasittely/tilaus_myynti.php
"Toimita kaikki"-nappi myyntitilaukselle
> Myyntitilaus: Toimita kaikki rivit

- inc/functions.inc
Jos syötetään manuaalisesti komentti2, niin ei hävitetä sitä, kun laitetaan laskutettu tilaus keräyslistan tulostusjonoon
> Uusi verkkokauppatilaus

- dynaaminen_puu.php
Korjattiin tuotepuun linkkiä tuotteisiin.
> Tuotepuu linkki fix

- inc/toimitustaparivi.inc
- inc/unifaun_send.inc
Tuetaan jatkossa Postin Parcel Connectia Unifaun-toimitustapana.
> Unifaun Posti Parcel Connect

- yllapito.php
Ei palauteta hyväksyntään jos yhtään hyväksyjää ei ole.
> Hyväksyntä

- tilauskasittely/tilaus-valmis.inc
- tilauskasittely/tuote_selaus_haku.php
Kun tuotteita lisättiin extennakolle tuoteselauksen kautta, sitä ei saatu laitettua oikein valmiiksi, vaan ennakko jäi kesken-tilaan. Tämä on nyt korjattu.
> Extranet-ennakot

- raportit/ostoehdotus_cs.php
Voidaan päivittää myös tuotteen hälytysraja sekä verkkokauppanäkyvyys.
> Ostoehdotus

- inc/functions.inc
Mahdollisuus antaa negatiivisia alennusprosentteja myös tuotenumerolle.
> Alennuskäsittely

- raportit/verottomat_korvaukset.php
Muutettu verottomat korvaukset raportti vastaaamaan verohallinnon uutta muotoa kyseiselle raportille.
> Verottomat korvaukset raportti

- inc/tulosta_reittietiketti.inc
- inc/unifaun_send.inc
- rajapinnat/unifaun/unifaun-functions.php
- tilauskasittely/rahtikirja_unifaun_uo_siirto.inc
Siirretään enemmän tietoa VAK -tuotteista Unifaun sanomassa.
> Unifaun rajapinta

- aloita_synkronointi.php
- inc/functions.inc
- inc/parametrit.inc
- inc/yhtion_parametrittarkista.inc
Nyt voidaan asettaa myös vain tietyt kentät, jotka halutaan synkronoida.
> Tietojen synkronointi

- rajapinnat/logisticar-paluuarvot.php
Haetaan ja käsitellään Logisticar paluuarvot.
> Logisticar paluuarvot

- inc/avainsanarivi.inc
- inc/avainsanatarkista.inc
- inc/unifaun_send.inc
- rajapinnat/unifaun/unifaun-functions.php
Voidaan avainsanalla valita mitä tilauksen kenttää käytetään lähettäjän viitteenä.
> Unifaun lähettäjän viite

- tilauskasittely/tulosta_tarjous.inc
Tarjouksen kommenttien rivityksestä johtuen tarjouksen sivutuksessa saattoi ilmetä ongelmia. Tätä on nyt korjattu niin, että tarjouksen sivutus toimii taas normaaliin tapaan ja uusi sivu osataan tehdä oikein.
> Tarjouksen tulostus

- tilauskasittely/tilaus_myynti.php
Mikäli tilauksella tai valmistuksella ei ollut ollenkaan rivejä niin siltä puuttui mitätöintinappi. Korjattu nyt niin, että mitätöintinappi näkyy myös tyhjällä valmistuksella ja myyntitilauksella.
> Valmistus & myynti: mitätöinti-nappi

- tilauskasittely/lisaarivi.inc
Reverts devlab-oy/pupesoft#3535
> Revert "Valmisteella ja kulutuksella eri varastot"

- inc/toimitustaparivi.inc
Lisätty PostNord Domestic Road toimitustapojen virallisiin nimityksiin.
> Toimitustapojen viralliset nimitykset

- inc/functions.inc
- magento_toimita_tilaus.php
- raportit/naytatilaus.inc
- tilauskasittely/toimitusvahvistus_email.inc
Lisätty tuki Schenker kotimaankuljetusten seurantaan sekä refaktoroitu koodia.
> Tilauksen seurantakoodit

- tilauskasittely/tarkistarivi.inc
Näytetään myyntitilauksella aina info mikäli tuotetta on tilauksessa tai siirtolistalla.
> Myyntitilauksen tulossa olevat

- inc/yhtion_parametritrivi.inc
- tilauskasittely/tulosta_vientierittely.inc
Voidaan yhtiön parametrillä säätää lasketaanko vientierittelyn painot tuotteen painoilla vai rahtikirjan painolla.
> * Vientierittelyn painot

- sepa.php
Pakotetaan summiin 2 desimaalia
> Sepa-maksuaineisto

- verkkolaskuvirheet.php
Siirretään oletuksena IBAN oikeaan kenttään
> Perustetaan uusi toimittaja virheeseen menneen verkkolaskun perusteella

- inc/functions.inc
- tilauskasittely/tulosta_asiakkaan_kuitti.inc
Osataan jatkossa näyttää oikeat maksutavat käteiskuitissa, vaikka ei ole maksupääteintegraatio käytössä
> Käteiskuittiin maksutavat fix

- tilauskasittely/jalkilaskenta.inc
Tarkennettu korjaustapahtumien hakua jälkilaskennan teossa, jotta voidaan olla entistä varmempia siitä, että saadaan oikan tuotteen korjaustapahtumat haettua.
> Jälkilaskenta: kehahinnan laskenta

- raportit/topten.php
> Top 10 viilaus

- dynaaminen_puu.php
- inc/functions.inc
Tuotepuuhun nimi_en kenttä Pupeshop-verkkokauppoja varten.
Toistaiseksi ei muuta funktionaalisuutta kentällä.
> Dynaaminen tuotepuu

- rajapinnat/magento_client.php
- rajapinnat/tuote_export.php
- rajapinnat/tuote_export_functions.php
Viedään kielikäännöksenä tuotteen mainosteksti sekä
tuotteen_avainsanoista parametrit, mikäli kieliversioita määritelty
kauppoihin.
> Magento-rajapinta, kielikäännöksiä

- pankkiyhteys.php
Määritellään oletushakemistot ennen kuin käytetään niitä
> Oletushakemistot

- rajapinnat/edi.php
- rajapinnat/tuote_export.php
> Kauppakohtianen asiakasnumero

- tilauskasittely/tulosta_lahete_kerayslista.inc
- tilauskasittely/tulostakopio.php
Excel tilausvahvistukselle tuodaan myös kappalehinta rivihinnan lisäksi. Kappalehinta tuodaan alennuksien ja alvien suhteen saman logiikan mukaan kuin rivihinta tuodaan.
> Excel tilausvahvistus: kplhinta riveille

- rajapinnat/magento_client.php
> Magento notice fix

- inc/maksuvalmius.inc
Voidaan valita mitkä pankkitilit huomioidaan limittilaskennassa.
> * Maksuvalmius

- rajapinnat/magento_client.php
Logataan enemmän atribuuttien hakuun liittyen Magento-Pupesoft rajapinnassa.
> Magento logs

- magento_toimita_tilaus.php
Funktionkutsun parametri korjattu oikeanlaiseksi.
> Tilausten toimituskuittaus Magentoon

- inc/functions.inc
- tilauskasittely/editilaus_in.inc
- tilauskasittely/rahtikirja_unifaun_uo_siirto.inc
Siirretään Pupen tilaukselle yhteyshenkilöksi Magento-tilauksen yhteyshenkilö.
> Magentotilauksen yhteyshenkilö

- inc/valitse_tulostin.inc
- tilauskasittely/tulostakopio.php
Voidaan jatkossa tulostaa tarjous exceliin mm tarjouskopion kautta.
> * Tarjous exceliin

- inc/functions.inc
- js/tilaus_myynti/tilaus_myynti.js
- tilauskasittely/tilaus_myynti.php
> Korjattu hintojen esisyöttö

- inc/functions.inc
- rahtikirja-tulostus.php
- tilauskasittely/toimitusvahvistus_email.inc
Korjauksia toimitusvahvistuksen seurantakoodilinkin muodostamiseen ja mikäli kyseessä on monipakettilähetys niin pakettien seurantakoodilinkit tulevat päällekkäin, niin että jokainen linkki on omalla rivillään.
> Toimitusvahvistus sähköpostiin: seurantakoodilinkki

- tilauskasittely/tarkistarivi.inc
Jälkitoimitusrivi tai asiakkaalle tai varastoon myyntitilaukselta tilattavan tilausrivin määrä ei saa olla negatiivinen.
> Myyntitilaus: tilausrivin määrä

- raportit/varastonarvo-super.php
Varastonarvon voi laskea tuotemerkeittäin
> * Varastonarvo tuotemerkeittäin

- inc/yhtion_parametritrivi.inc
- muokkaatilaus.php
Yhtiön parametreihin on lisätty uusi parametri (tyomaaraykset_muokkaatilaus_ohjelmassa), jolla voidaan rajata Muokkaa tilaus-näkymästä myyntitilaukset pois.
> Muokkaa tilaus: työmääräysten näkyminen

- extranet_tyomaaraykset.php
> Muutettu teksti ext työmääräyksiin

- inc/tilisaldot.inc
Numerokentät exceliin numerokenttinä
> Tiliensaldot excel fix

- inc/toimitustaparivi.inc
Lisätty Unifauniin FedEx ja pari sen toimitustapaa
> Lisätty Unifaun / FedEx

- crm/asiakaslista.php
- inc/parametrit.inc
Voidaan generoida Haas-siirto komentoriviltä.
> CRM Haas komentoriviltä

- tilauskasittely/tilaus_myynti.php
Mitätöinti nappi jäi pois rivilliseltä myyntitilaukselta, jota ei vielä oltu valmistettu.
> Valmista tilaus: mitätöintinappi

- raportit/myyntitilasto_gauge.php
Näytetään valitulla aikavälillä tehdyt mutta laskuttamattomat luvut
omissa sarakkeissaan.
> Myyntilastoon avoimet

- inc/factoringrivi.inc
- inc/functions.inc
- inc/pankkiyhteys_functions.inc
- inc/pankkiyhteys_send.inc
- nordeafactoring.php
- pankkiyhteys.php
- tilauskasittely/verkkolasku.php
Jatkossa voidaan tehdä Factoring sopimus Aktia pankille
> Aktia factoring

- raportit/myyntiseuranta.php
Näytetään laskutuspäivä ja maksupäivä samassa formaatissa
> Myynninseuranta

- rajapinnat/logmaster/logmaster-functions.php
> RecCustPhone max 20 merkkiä

- matkalasku.php
Syötettäessä useamman päivän kestäneitä matkoja tuli ongelmia, mikäli rivejä halusi muokata. Tämä käsitteli muokattavaa osaa itsenäisenä matkana eikä osana pidempää matkaa, mikä aiheutti päivärahamäärän muuttumisen. Korjattu nyt niin, että pidemmät matkat osataan käsitellä kokokaisuuksina.
Samalla korjattiin tietyn kilometrimäärän jälkeen käyttööntulevan alennetun kilometrikorvauksen tarkistus, jotta haetaan ajetut kilometrit oikein.
> Matkalasku: korjauksia ohjelman toimintaan

- rajapinnat/edi.php
Osataan hakea toimitusosoitteen (katuosoite) perästä mahdollinen noutopisteen koodi. Sitä voidaan Pupesoftissa käyttää mm Unifaun-lähetyksissä.
> Magento noutopiste

- valmistatuotteita.inc
Näytetään suoraan valmistuksella miten valmisteen keskihankintahinta on
muuttunut
> Valmistuksille tieto kehamuutoksesta

- rajapinnat/logmaster/logmaster-functions.php
Laitetaan LogMaster keräyssanomalle mahdollinen noutopisteen tunnus
> LogMasteriin noutopisteen tunnus

- rajapinnat/edi.php
Siivotaan noutopiste katuosoitteesta veke.
> Magento noutopiste pienkehitys

- myyntires/tee_korkolasku.inc
- myyntires/tulosta_korkoerittely.inc
- tilauskasittely/laskutus.inc
- tilauskasittely/tilaus-valmis.inc
- korkoerittelyyn laskutusosoite
- korkolaskun voi tehdä myös myyntikiellossa olevalle asiakkaalle
> Korkolaskumuutoksia

- inc/functions.inc
- tilauskasittely/verkkolasku.php
> Korjattu alehinta-funktio

- crm/viikkosuunnitelma_raportti.php
Ei näytetä lähetettyjä viestejä asiakaiskäynteinä
> Edustajaraportista pois viestit

- extranet/asiakashinnasto.php
Lisätään tuotemerkki valittavaksi ja näytettäväksi CRM asiakashinnastoon
> Asiakashinnastoon tuotemerkki

- inc/functions.inc
- inc/toimitustaparivi.inc
- rahtikirja-tulostus.php
- rahtikirja.php
- rahtikirja_custom.php
- tilauskasittely/editilaus_in.inc
- tilauskasittely/keraa.php
- tilauskasittely/osoitelappu_kesko_pdf.inc
- tilauskasittely/osoitelappu_pdf.inc
- tilauskasittely/tilaus_in.php
- tilauskasittely/tulosta_lahete.inc
- tilauskasittely/tulostakopio.php
Uusi versio osoitelapusta
Lisäksi editilaus_in var h ominaisuus
> Kesko osoitelappu

- nordeafactoring.php
Lisätään puuttuvat 13 spacea ostajatietueen loppuun
> Aktia factoring ostajatietue fix

- tilauskasittely/tilaus_myynti.php
Poistetaan rivit myös laitteen_sopimuksista, kun ne poistetaan sopimukselta
> Laitteen sopimusrivit

- inc/viitemaksut_kohdistus.inc
- muutosite.php
Saldo_maksettu nollaksi, kun lasku merkitään maksetuksi
> Myyntilasku merkitään maksetuksi

- inc/unifaun_send.inc
- rajapinnat/unifaun/unifaun-functions.php
Lisätään Unifauniin tunnelikoodi jos vak-tietokanta käytössä ja tehdään lähetystä vak-tuotteista.
> Unifaun vak tunnelikoodi

- inc/asiakasalennustarkista.inc
- inc/functions.inc
- rajapinnat/presta/presta_functions.php
Käytetään myymälähintaa myös jos asiakasalennus tehty kaikille
tuotteille
> Myymälähinta kaikielle tuotteille

- rajapinnat/unifaun/unifaun-functions.php
Unifaun XML:n container-tason alla oleviin article-tasoihin
siirrettävät vak-painot uudella logiikalla, jotta näkyy Unifaunin dokumenteissa fiksummin.
> Vak-painot per tuote per kpl

- tilauskasittely/tilaus_myynti.php
Voidaan tallentaa tilauksen kaikki aletasot asiakasalennuksiin.
> * Tilaukselta kaikki alennustasot talteen asiakasalennuksiin

- tilauskasittely/keraa.php
Näytetään riveillä tuotteen enakoodi ja puutekappaleen määrä suoraan,
mikäli tietty osoitelappu käytössä
> Keräyspoikkeama-email spessukeissi

- inc/functions.inc
- inc/yhtion_parametritrivi.inc
- Uusi yhtiön parametri jossa livehakua voidaan säätää erikseen
extranetissa
- Lisätty uusi vaihtoehto, saatavuus esitetään vain kyllä/ei tyylisesti
> Saldot extranetissä

- tilauskasittely/toimitusvahvistus_email.inc
Ei näytetä lapsirivejä jos tuoteperheellä niin määritelty.
Piilotettujen lapsien hinnat summataan isälle.
> Toimvahv_email tuoteperheen lapset

- ylaframe.php
> Poistetaan yhtiön nimi extranetistä

- tuote.php
Tuotekyselyn tuotteentilaukset kohdassa saattoi näkyä mitätöityjä valmistuksia. Tätä on nyt muokattu niin etteivät mitätöidyt valmistukset tuotekyselyn tuotteen tilaukset kohdassa näkyisi.
> Tuotekysely: tuotteen tilaukset

- inc/avainsanarivi.inc
- tilauskasittely/tulosta_asiakkaan_kuitti.inc
- Lisätään avainsana kuitin vakiotekstille
- Tulostetaan footer teksti myös pdf-kuitille
> Kuitin vakioteksti

- yllapito.php
Mikäli tuotteen toimittajan tuotenumero sattui vastaamaan päivämäärä sql-muodossa ilmaistuna muutettiin se tuotteen tiedoissa tuotteen toimittaja-tieto kohdassa ja tuotteen toimittajat listauksessa päivämäärä muotoon. Eli esimerkiksi tuotteen toimittajan tuotenumerosta 1000-01-01 tulisi listauksessa 1.1.1000. Tämä on nyt korjattu ja tuotten toimittajan tuotenumero näytetään siinä muodossa kun se on tallennettu.
> Tuotteen toimittajatiedot: toimittajan tuotenumero

- rajapinnat/unifaun/unifaun-functions.php
Katsotaan paremmin onko tilauksella vak-tuotteita toimitettavana. Rajataan pois rivit joita ei olla toimittamassa.
> Unifaun vak tarkistuksen korjaus

- tilauskasittely/keraa.php
Jos käytetään kerays_riveittain ominaisuutta, niin jatkossa nähdään
kerää-näkymässä myös tuotteen toimittajan tuotenumero (päätoimittajan,
mikäli useita toimittajia).
> Keräykseen toim_tuoteno

- inc/avainsanarivi.inc
- Lisätään avainsana woo-kentälle
> Woocommerce parametrointi

- directdebit.php
- inc/directdebit.inc
- inc/directdebit_asiakas.inc
- inc/directdebit_asiakasrivi.inc
- inc/directdebit_asiakastarkista.inc
- inc/directdebitrivi.inc
- inc/directdebittarkista.inc
- inc/factoring.inc
- inc/factoringrivi.inc
- inc/factoringtarkista.inc
- nordeafactoring.php
- sveafactoring.php
- uusiyritys.php
- yllapito.php
Luodaan Nordea speksien mukaan SEPA Direct debit tyyppinen aineisto
> * SEPA Direct debit

- inc/functions.inc
- rajapinnat/huutokaupat_viiteaineisto.php
Skripti joka hakee laskuerittelyn ja muodostaa siitä viiteaineiston
Pupea varten eräässä spessukeississä.
> Custom viiteaineistot

- tilauskasittely/otsik.inc
Myyntitilauksen otsikolla oli rajaus, että Email toimitukseen-kenttä näytettiin vain kassamyyjille. Tehtiin muutos, että tämä tieto näytetään kaikille käyttäjille.
> Myyntitilaus: email toimitukseen

- myyntires/factoringkorko.php
Ajettaessa factoringkorot ohjelmaa ohjelma ajautui virheeseen. Tämä virhe on nyt korjattu.
> Factoringkorot: virhetilanteen korjaus

- tilauskasittely/otsik.inc
- tilauskasittely/tilaus_myynti.php
Ei muutella toimitustapaa myynnissä noudoksi, jos tilaus maksettu etukäteen
> Maksettu verkkokauppatilaus fix

- inc/unifaun_send.inc
Jos tehdään lähetys Yhdysvaltoihin, lisätään sanomaan myös “state” eli osavaltio/alue. Staten tulee olla tallennettuna Pupesoftissa postitoimipaikka-kentässä oikean postitoimipaikan perässä välilyönnillä eroteltuna, esim “LAREDO TX”.
> Unifaun US state

- tilauskasittely/lahetteen_tulostusjono.php
- tilauskasittely/tilaus-valmis-tulostus.inc
- tilauskasittely/toimita.php
- tilauskasittely/tulosta_lahete_kerayslista.inc
Tulostetaan kaikki keräyslistat yhteen pdf-dokumenttiin kun listat otetaan sähköpostiin.
> Tulosta kaikki keräyslistat

- inc/asiakasrivi.inc
- inc/yhtion_parametritrivi.inc
- tilauskasittely/keraa.php
Jos kerättävällä tilauksella on asiakas jonka keräyspoikkeama on asetettu asentoon "myyjälle ja asiakkaalle (vaikka olisi poikkeamia)", lähetetään keräyspoikkeama-sähköposti vaikkei keräyspoikkeamia olisikaan. Silloin poikkeamarivien tilalla lukee "Ei keräyspoikkeamia".
> Keräyspoikkeamat sähköposti

- iltasiivo.php
Kun SEPA-pankkinyhteyden sertifikaattin on vanhenemassa seuraavan kuukauden aikana lähetetään yöajojen yhteydessä muistutusviesti. Viesti lähetetään yhtiön parametreistä löytyvään osoitteeseen (ensisijaisesti talhal, toissijaisesti alert ja jos kumpaakaan edellisistä ei löydy, niin silloin admin). Viestiä ei lähetetä enää sen jälkeen, kun sertifikaatti on vanhentunut.
> SEPA-pankkiyhteyden sertifikaatin uusimismuistutusviesti

- editilaus.pl
Voidaan antaa editilaus_in.incille kolmas parametri väkisinmyyntiin liittyen.
> Editilaukselle lisäparametri

- inc/unifaun_send.inc
Jos ei ole shipment tasolla LTD QTY päällä, ei sitä tule laittaa
article tasollekkaan
> LTD QTY pois article tasolta

- varauskalenteri/varauskalenteri.php
- varauskalenteri/varauskalenteri_syota.php
Varauskalenterissa kello 16 eteenpäin aikaväli muuttui tunniksi. Muutettu nyt niin, että myös loppupäivän aikaväli varauskalenterissa on 30-minuuttia.
> Varauskalenteri: aikavälit 30-minuutiksi

- inc/functions.inc
- tilauskasittely/tulosta_lasku.inc
Uusi laskupohja, jossa rivien toimitusaika tiedon paikalle on laitettu verollinen a-hinta.
> Uusi laskupohja: verollinen a-hinta

- crm/kalenteri.php
- inc/yhtion_parametritrivi.inc
Kalenteri ohjelman voi jatkossa valita näyttävän tapahtumien aikavälin 15 minuutin aikavälillä. Tehtiin uusi yhtiön parametri, jolla tätä säädellään.
> Kalenteri: aikaväliksi voi valita 15 minuuttia

- raportit/paivan_laskut.php
Päivän laskut ohjelmassa ei ollut tietoa kaikista mahdollisita Pupen tukemista operaattoreista. Päivitetty uusimmatkin Pupen tukemat operaattorit ohjelmaan, jotta osataan näyttää okein operaattoritieto laskujen kohdalla.
> Päivän laskut: operaattoritiedot ajan tasalle

- uutiset.php
Levennetty tekstiensyöttökenttiä ja uutisten tekstikenttiä.
> Uutiset ja extranet-uutiset

- rajapinnat/tuotehinnasto_csv_ftp.php
Pupesoftin tuotehinnasto sisällöltään semmoisenaan CSV-muotoisena
FTP:llä eteenpäin. Tarkoitettu ajettavaksi komentoriviltä.
> Tuotehinnasto CSV to FTP

- inc/functions.inc
- jos yhtiön parametreissa on se sallittu
> Siirretään kaikki vientilaskut Arvatolle

- extranet/view.php
- inc/liitetiedostotrivi.inc
- tiedostofunkkarit.inc
- tiedostokirjasto.php
- Lisätään tiedostokirjasto-ohjelmaan tuki asiakkaan tiedostoille
- Haetaan liitetiedostotyypit myös jos liitetään asiakkaaseen ja näytetään Yleinen-tyyppi myös jos tyyppejä löytyy kannasta asiakkaan ylläpidossa
> Asiakkaan extranet tiedostot

- monistalasku.php
Tilausten ja laskujen monistuksessa luodaan kokonaan uusi tilaus/lasku, joten directdebit tunnus tulee nollata - tämä uusi monistettu tilaus/lasku menee omalle uudelle aineistolleen, joten sille luodaan oma uusi directdebitaineistotunnus aineiston luonnin yhteydessä.
> Tilausten/laskujen monistus: directdebittunnus

- tilauskasittely/tilaus_osto.php
- tilauskasittely/tuotetiedot.inc
Ostotilauksella tuotenumeron päältä aukeavaan hooveriin lisää tietoa
> Tuotetietoihin myynti- & myymalahinta

- inc/unifaun_send.inc
Voidaan lähettää vakeissa alle yhden miniminettopaino, eikä väkisin nosteta sitä ykköseksi.
> Unifaun vak-tuotteen paino

- inc/pankkiyhteys_functions.inc
Add break clauses to switch statement so that Nordea renew certificate works correctly
> Nordea renew certificate fix

- directdebit.php
Viite Ref-tagiin, ei Issr-tagiin
> DirectDebit-aineisto

- inc/asiakashinta.inc
Näytetään tuotteen nimitys asiakaskortin asiakashinnoissa, jos asiakashinta on tehty tuotenumerolla.
> Asiakaskortilla asiakashinnat

- crm/tarrat.php
Voidaan valita että excel -tulosteelle otetaan mukaan myös asiakkaan ja yhteyshenkilön id:t
> CRM: tarrat exceliin

- varauskalenteri/varauskalenteri_lisaa.php
Kaikista varauskalenteriin tehdyistä lisäyksistä lähetetään email yhtiön parametreissa olevaan osoitteeseen
> Varauskalenterimerkintä

- sepa.php
Aktian pankki SEPA maksuaineisto muutos: ei täytetä laskun tyhjiä osoitetietoja viivalla tai usealla viivalla.
> SEPA Aktia fix

- tilauskasittely/editilaus_in.inc
Verkkotilaukselle valuutan mukainen kurssi, kun tilausken valuutta eri kuin yhtiön valuutta
> Verkkokauppatilausten sisäänluku

- tilauskasittely/keraa.php
Tietyssä tapauksessa laitetaan keräyspoikkeama-sähköpostiin subjectiin myös asiakkaan_tilausnumero.
> Keräyspoikkeama email subject

- tilauskasittely/jtselaus.php
- tilauskasittely/tee_jt_tilaus.inc
Tarkistetaan oikeasti, onko ennakkotilausrivit myytävissä, jos osatoimituskielto
> Ennakkoselaus

- inc/pankkiyhteys_functions.inc
- pankkiyhteysadmin.php
Add support for OP certificate renewal
> OP Certificate Renewal

- tilauskasittely/jtselaus.php
- tilauskasittely/tee_jt_tilaus.inc
Reverts devlab-oy/pupesoft#3721
> Revert "Ennakkoselaus"

- tilauskasittely/tilaus_myynti.php
- tilauskasittely/tuote_selaus_haku.php
- tilauskasittely/verkkolasku.php
Etukäteen maksetut tilaukset laskutetaan aina, eikä niitä voi muokata
> Etukäteen maksetut tilaukset

- rajapinnat/logmaster/logmaster-functions.php
Vastaanottajan kielikoodi sanomaan
> outbounddelivery-sanoma

- inc/toimitustaparivi.inc
- inc/unifaun_send.inc
> Unifaun sanoma

- inc/tuoterivi.inc
- tilauskasittely/tarkistarivi.inc
Mahdollisuus asettaa tuote kommentoitavaksi vain reklamaatiolla. Asetus tehdään tuotteen ylläpidossa "kommentoitava" kentällä (johon on tullut uusi optio aikaisempien lisäksi).
> Kommentoitava rivi reklamaatiolla

- extranet/tervetuloa.php
Ei piirretä laatikkoa, jos ei ole mitään tekstiä siihen
> Extranet-etusivu

- lue_data.php
Varmasti "unohdetaan" kenttien arvot rivien välissä.
> Sisäänlue dataa korjaus

- tilauskasittely/tulosta_lahete_kerayslista.inc
Näytetään jatkossa lisätietona Magento-tilauksilla tilauksen sähköpostiosoitetta.
> Lisätietoja keräyslistaan

- asiakasvalinta.inc
- extranet_laiterekisteri.php
Haetaan valitun toimipisteen laitteet
> Laiterekisteri

- raportit/alv_laskelma_uusi.php
> ALV-laskelma

- lue_tuoteketjuja.php
- tuoteperhe.php
Yhdelle tuotteelle voidaan lisätä suositeltavia tuotteita. Ominaisuus
sisältää vain ylläpidon toistaiseksi, eli tällä ei ole muuta
toiminnallisuutta toistaiseksi Pupessa.
> Tuotesuositukset

- tilauskasittely/editilaus_out_apix.inc
Lisätty nollarivit, kilot ja tilavuuden tuotteiden perusteella
> Apix toimitussanoma pakkaus

- dynaaminen_puu.php
- extranet/tervetuloa.php
- extranet/view.php
- inc/dynaaminen_puu_avainsanat.inc
- inc/dynaaminen_puu_avainsanatrivi.inc
- tiedostofunkkarit.inc
- uutiset.php
Voidaan raja mille asiakassegmenteille extraet-uutinen näytetään.
> Extranet-uutiset

- raportit/puutteet.php
Voidaan jatkossa tehdä puutelistalla asiakasrajaus. 
Rajaus joko asiakkaalla kuten ennenkin, tai asiakkaan ytunnuksella.
Asiakashaku toimii kuten ennenkin, vaikka olisikin ytunnuksella rajaus
käytössä (tulokset rajataan silloin ytunnuksella, vaikka joku tietty
asiakas haussa valitaankin).
> Puutelistan asiakasrajaus

- js/tilaus_myynti/tilaus_myynti.js
- tilauskasittely/otsik.inc
- tilauskasittely/tilaus_myynti.php
Tilauksella “puhelin toimitukseen” kentän puhelinnumero osataan jatkossa hakea myös tilauksen yhteyshenkilön takaa.
> Yhteyshenkilön puh->toim_puh

- raportit/puutteet.php
Näytetään jatkossa myös myyntikappaleet
> Puuteraportti muutoksia

- asiakasvalinta.inc
Näytetään vain asiakkaan selausnimi jos se löytyy, muuten nimi+nimitarkenne
> Portaali asiakkuus nimi

- inc/yhtion_parametritrivi.inc
- tilauskasittely/keraa.php
Voidaan tilauksen keräyksessä laittaa keräyspoikkeama oletuksena puutteeksi
> Keräyspoikkeamakäsittely puute

- lue_data.php
Käytetään funkkaria vain jos sellainen löytyy
> Luedata oikeellisuustarkistus

- extranet_laiterekisteri.php
Extranet laiterekisteriin kutsu/tsekki on ko laite jo avoimella työmääräyksellä
> Extranet laiterekisteri

- extranet_tyomaaraykset.php
Extranetin työmääräyshistoriaan aikarajaus.
> Aikarajaus suljettuihin

- tilauskasittely/otsik.inc
Ei siirretä ensi vuoden puolella olevaa toimituspäivää takaisin kuluvalle vuodelle.
> Toimitus- / Keräysviikko

- inc/yhtion_parametritrivi.inc
- rajapinnat/myyntihinnan_muutos_cron.php
- rajapinnat/tuloutetut_tuotteet_cron.php
- rajapinnat/uudet_tuotteet_cron.php
Muutama uusi excel-aineisto joita voi ajastaa esim kerran päivässä lähetettäväksi sähköpostilla. 
Aineistot ovat:
- Uudet perustetut tuotteet
- Tuloutetut tuotteet
- Myyntihinnan muutokset
> Excelillä dataa sähköpostiin

- inc/hinnastoriviautomaster.inc
- inc/hinnastorivifutur.inc
- inc/hinnastorivitab.inc
EANkoodi tuotteen toimittajatiedoista ellei löydy tuotetiedoista
> Extranet hinnasto

- tilauskasittely/editilaus_in.inc
Yritetään tunnistaa kaikki tiedoston tilaukset myös ytunnus/ovt-tunnus -yhdistelmällä eikä vain ensimmäistä tilausta
> Edi-tilaus-asiakkaan tunnistus

- muokkaatilaus.php
> Hyväksyttävät tilaukset -fix

- rajapinnat/logmaster/synchronize_products.php
Lisätty tullinimike tuotedataan
> Lisätty tullinimike tuotedataan

- muokkaatilaus.php
- tilauskasittely/tilaus-valmis-tulostus.inc
Ei tehdä tulostusjonossa saldotarkistusta jos on tietty keräyserät
parametri päällä.
> Saldotarkistus tulostusjonossa fix

- muokkaatilaus.php
Muokkaa tilausta -ohjelmaan lavakeräys viilaus: Näytä tilaus -nappi muokkaus-nappien tilalle. Lavakeräyksessä ei sallita
muokkausta.
> Lavakeräys näytä tilaus

- inc/verkkolasku-in.inc
- inc/yhtion_parametritrivi.inc
Yhtiön parametriin ostolaskujen_oletusiban tehty uusi lisäoptio, joka
vie verkkolaskun ibanin ja bicin toimittajan taakse oletukseksi.
> Lisäoptio ostolaskujen_oletusiban

- crm/asiakaslista.php
> Asiakaslista

- inc/liitetiedostot.inc
Reklamaatioille voi lisätä liitetiedostoja
> Liitetiedostot

- tilauskasittely/otsik.inc
- tilauskasittely/tilaus_myynti.php
Toimitusehdon takana voidaan kertoa kumman rahtisopimusta
myyntitilauksella käytetään. Tätä ei huomioitu aikaisemmin jos
myyntitilauksen otsikolla toimitustapaa / toimitusehtoa muutettiin. Nyt
huomioidaan.
> Toimitusehto rahtisopimus fix

- rajapinnat/logmaster/logmaster-functions.php
Pieniä korjauksia ulkoinen varasto -rajapintaan (case Velox)
> Ulkoinen varasto: Velox

- rajapinnat/tuloutetut_tuotteet_cron.php
> Tuloutetut tuotteet sähköposti

- inc/functions.inc
- yllapito_tuotekuvat.php
Olemassa olevaan ohjelmaan hieman lisäominaisuuksia / parannuksia:
- Voidaan hakea tiedoston nimellä
- Liitteille “näytä” nappi
- Käyttötarkoitukset luetaan avainsanoista
- Näytetään listauksessa muutospäivä
- Hakutulos Pupesoft datatablesiin, jossa voi hakea & sortata tulosta helpommin
- Haku tuotteen avainsanalla "KEMOM" (jos niitä on tuotteille annettu) ja sen näyttäminen myös tuloksissa
> Tuotteen liitetiedostojen ylläpito

- raportit/tuloslaskelma.php
Osataan jatkossa näyttää budjettivertailut tilitasolla ja vaihtoehtoisesti myös tileiltä summata eri tasoille
> Tase ja tuloslaskelma budjettivertailu

- pdflib/phppdflib.class.php
- tilauskasittely/tulosta_tarjous.inc
Korjattu bugi tarjouksen PDF-tulostuksen sivutuksessa
> Tulosta tarjous sivutus hotfix

- inc/functions.inc
- rajapinnat/logmaster/outbound_delivery.php
- rajapinnat/logmaster/outbound_delivery_confirmation.php
- tilauskasittely/vaihda_tila.php
- tilauskasittely/verkkolasku.php
- tilauskasittely/vientitilauksen_lisatiedot.php
Syötetään viennin lisätiedot automaattisesti ja laskutetaan tilaus ja lähetetään se ulkoiseen varastoon.
> Vientilasku ulkoiseen varastoon

- rajapinnat/logisticar.php
Postinumero lisätty asiakas-aineistoon
> Logisticar-rajapinta

- ulask.php
Sallitaan myös pilkut desimaalisummissa
> Uusi ostolasku

- inc/toimitustaparivi.inc
- inc/unifaun_send.inc
Uusi Unifaun Postnord palvelu. 
Tuki lisäksi “ennakkoilmoitus puhelimitse” sekä “Vastaanottaja maksaa rahdin” lisäpalveluille.
> Unifaun Postnord Groupage

- inc/functions.inc
Jos tuoteperheellä on kokonaishinta, joka jaetaan lapsiriveille, niin tuoteperheen mahd. pyöristys ensimm. riville, jonka rivihinta > 0
> Lapsituotteiden rivihinta

- inc/parametrit.inc
- muokkaatilaus.php
- raportit/asiakkaan_tilaukset_tuotteittain.php
Lisätään asiakkaan tilausnumero ja viite avoimet tilaukset, muokkaa tilausta ja asiakkaan tuoteostot raportteihin
> Asiakkaan tilausnumero ja viite näkyviin

- intrastat.php
Luodaan tullille ladattava CSV-tiedosto.
> * Intrastat CSV

- tilauskasittely/tilaus_myynti.php
Ei päivitetä enää perheid2:sta
> Tarjousrivit

- inc/yhtion_parametritrivi.inc
- tilauskasittely/tilaus_myynti.php
Voidaan yhtiön parametrillä “tilaukselle_mittatiedot “ sanoa halutaanko myyntiruudulla, ostolla tai tarjouksella nähdä syötettyjen tilausrivien kappalemäärä summattuna.
> Kappalemäärien yhteenveto

- inc/avainsana.inc
- inc/avainsanarivi.inc
- messenger.php
Voidaan luoda yhtiön avainsanoissa messenger ryhmiä, joihin voi sitoa
käyttäjiä. Messengerillä voi lähettää ryhmälle viestin, joka siis
lähetetään ryhmän käyttäjille.
> Messenger ryhmät

- inc/asiakaskommentti.inc
Näkymään lisätty asiakkaan nimi ja tuotteen nimitys
> Asiakaskommentti

- inc/tulosta_lavakeraystarrat_tec.inc
- rahtikirja.php
- tilauskasittely/keraa.php
- tilauskasittely/lavatarra_pdf.inc
- tilauskasittely/tulostakopio.php
Lavakeräykseen uusia ominaisuuksia.
> Lavakeräykseen uusia ominaisuuksia.

- inc/yhtion_parametritrivi.inc
- tilauskasittely/tarkistarivi.inc
Mahdollisuus huomattaa myyntitilauksella tuotteesta joka on jo tarjouksella
> Huomautetaan tarjouksella olevasta tuotteesta

- inc/functions.inc
- raportit/topten.php
Lisätään myyntien viereej indeksisarake edelliseltä kaudelta (edellinen vuosi, muuten sama ajankohta).
> Topten raportin muutos

- datan_massalisays.php
Kyseessä tuotekuvien/liitteiden sisäänluku-ohjelma.
Voidaan jatkossa kertoa käyttötarkoitus jos tuotteiden ja kuvien linkki kerrotaan tiedostossa. Kolmas sarake on käyttötarkoituksen koodi, esim MU, TK, TH jne.
Käyttötarkoitusta ei ole pakko antaa (silloin toimitaan kuten ennenkin, eli käyttötarkoitus tulee riippuen mihin kansioon tiedostot on laitettu).
> Liitetiedostot aineistosta

- rajapinnat/logmaster/outbound_delivery_confirmation.php
Tuki var P/J keräyksille, mikäli yhtiön parametri Kerayspoikkeama_kasittely on arvossa J tai U (kerääjä valitsee poikkeaman, oletus jälkitoimitus tai puute).
> Ulkoinen varasto keräyspoikkeamat

- rajapinnat/logisticar.php
> Logisticar-siirtotiedosto: customer

- rajapinnat/logisticar.php
Customer-tiedosto eri tiedoilla komentorivi-parametrin avulla
> Logisticar-siirtotiedostot

- tilauskasittely/tulostakopio.php
Ei huomioida pakkausveloitus_tuotenumeroita kun tehdään lavatarroja.
> Lavakeräyksen lavatarra-pdf fix

- inc/verkkolasku-in-luo-keikkafile.inc
Tarkistetaan toimittajan tiedoista saako laskusta luoda saapumisen
> Saapuminen laskusta

- inc/toimitustaparivi.inc
SCHENKER Noutopistepaketti lisätty
> Toimitustapojen viralliset nimet

- inc/asiakaskommentti.inc
- inc/asiakaskommenttirivi.inc
- inc/tuotehaku.inc
- rahtikirja-tulostus.php
- tilauskasittely/myyntierat_ja_tuotetiedot.inc
- tilauskasittely/tulosta_lahete.inc
- tilauskasittely/tulosta_lasku.inc
- tilauskasittely/tulosta_tarjous.inc
- tilauskasittely/uudelleenluo_laskuaineisto.php
- tilauskasittely/verkkolasku.php
- yhdistaasiakas.php
Asiakaskomenttiin lisätty tyyppi:
voidaan tehdä myös sisäsisiä asiakaskommentteja, jotka eivät näy asiakkaalle
> Asiakaskomentti

- rajapinnat/paivita_myytavissa_static.php
Hienosäätöä Pupeshop verkkokauppojen saldojen päivitykseen, että toimii erilaisilla kombinaatioilla niin kuin kuuluu.
> Pupeshop saldot hienosäätö

- tilauskasittely/tulosta_purkulista.inc
Ennakkotilauksilla olevat näkyviin purkulistalle omina riveinään kuten jälkitoimituksetkin
> Purkulista

- rajapinnat/uudet_tuotteet_cron.php
Myymälähinta lisätty excel-raporttiin
> Uudet tuotteet -raportti

- tilauskasittely/tilaus_osto.php
Logitetaan myös “vahvista toimitus” napin takana toimitusajat.
> Logitetaan kaikki rivit case myös

- inc/verkkolasku-in-luo-keikkafile.inc
Korjaus, laskun manuaalisyötöstäkin voi luoda saapumisen
> Laskusta saapuminen

- inc/tulosta_lavakeraystarrat_tec.inc
- tilauskasittely/lavakeraystarrakopio.php
Uusi ohjelma jolla voidaan tulostaa Lavakeräystarrakopioita
> Lavakeräystarrakopio

- tilauskasittely/tuotelista.php
Tuotelistaus joka muistuttaa Tuote selaus hakua, mutta vain private label tuotteille
> Tuotelistaus

- muokkaatilaus.php
- tilauskasittely/tilaus_myynti.php
- tilauskasittely/vaihda_tila.php
Voidaan pitää tilauksia lavakeräysjonossa / siirtää tilauksia takaisin lavakeräysjonoon.
> Lavakeräysjono

- rajapinnat/logmaster/logmaster-functions.php
Laitetaan ulkoiseen varastoon toim_email jos asetettu, muuten asiakas.email
> Toimituksen email ulkoiseen varastoon

- raportit/ostotilaus_myohassa_email.php
Uusi ominaisuus: email toimittajalle
Lisäksi voidaan paremmin säätää mihin emaileja halutaan (viides
parametri).
> Ostotilaus myöhässä email lisäkehityksiä

- inc/verkkolasku-in-finvoice.inc
Konvertoidaan RowFreeTextin erikoismerkit oikein
> Verkkolaskujen sisäänluku

- inc/myymyyjat.inc
- raportit/myymyyjat.php
Konsernimyynti-vaihtoehto lisätty perusraporttiin
> Myyjien myynnit

- inc/tulosta_lavakeraystarrat_tec.inc
- tilauskasittely/lavakeraystarrakopio.php
Lavakeräykseen muutamia fiilauksia
> Sarvimaki fixs

- tilauskasittely/editilaus_in.inc
Editilauksen sisäänluvussa HB-tuotehakuvaihtoehtoja lisätty
> Editilauksen sisäänluku

- inc/avainsanarivi.inc
- inc/unifaun_send.inc
Mahdollisuus tallentaa oma vakioteksti Unifaun ennakkoilmoitusviestille
> Unifaun ENOT vakioteksti

- raportit/varastonarvo-super.php
Uusi summaustaso: Varasto / tuoteryhmä / tuote. Välisummat ja yhteensäsummat lisätään myös excel-tiedostoon.
> Varastonarvo tuotteittain. Uusi summaustaso: Varasto / tuoteryhmä / tuote

- inc/functions.inc
Osataan käsitellä myös sellainen yrityksen tili, jonka tilino on tyhjä
> Viitemaksujen sisäänluku

- raportit/kateismyynnit.php
Rajauksia käteismyyntiraporttiin
> Käteismyynnit-raportti

- inc/yhtion_parametritrivi.inc
- tilauskasittely/verkkolasku.php
Voidaan tarkistaa saldo vain valitusta varastosta ja estää laskutus, jos valitussa varastossa saldo menee miinukselle
> Saldon tarkastus laskutusvaiheessa

- raportit/myyntiseuranta.php
Näytetään haluttaessa myös myyntitilauksen luokittelu (label)
> Mahdollisuus näyttää laskun label

- tilauskasittely/tilaus_myynti.php
- tilauskasittely/tilausvahvistus-email.inc
Lähetetään "tilausvahvistus" hyvaksyttavat_extranet_email-osiotteeseen kun extranet tilaus lisätään hyväksyntäjonoon.
> Notifikaatio uudesta hyväksyttävästä extranet-tilauksesta

- inc/tuoterivi.inc
- tilauskasittely/tarkistarivi.inc
- tilauskasittely/tarkistarivi_ostotilaus.inc
Tuotteelle voi asettaa pakkokommentoinnin myös ostopuolelle
> Ostolle tuotteen pakkokommentointi

- rajapinnat/logisticar.php
Aineistoon lisätty luontipäivä ja myyjänä käytetään asiakkaan taakse määriteltyä myyjään
> Logisticar-aineisto

- intrastat.php
Ei enää tägätä tekstisarakkeita "-merkeillä csv:ssä.
> Ei enää tägätä tekstisarakkeita "-merkeillä csv:ssä.

- dokumentti_raportti.php
- dokumenttien_hyvaksynta.php
- dokumenttityypit.php
- inc/dokumenttien_hyvaksynta.inc
- uusi_dokumentti.php
- view.php
Dokumenttityypit ja käyttäjäryhmät hyväksyttäville dokkareille.
> Dokumenttityypit ja käyttäjäryhmät hyväksyttäville dokkareille.

- inc/yhtion_parametritrivi.inc
- rahtikirja.php
- tilauskasittely/verkkolasku.php
Vientitilauksille lisätiedot automaattisesti ja "viennit_"-paramilla saadaan mukaan myös cronilaskutukseen.
Ominaisuutta ohjataan vientitietojen_autosyotto-paramilla.
> * Vientitilauksen lisätietosyöttö ja laskutus automaattiseksi

- tyomaarays/etsi.php
Hae kaikista kentistä ei sisällä enää asiakasnimestä hakua
> Työmääräin haku

- muokkaatilaus.php
- tilauskasittely/keraa.php
- tilauskasittely/lavakerayslista_pdf.inc
- tilauskasittely/tilaus-valmis-tulostus.inc
- tilauskasittely/tulostakopio.php
Uusi koontikeräyslista lavakeräyksille.
> * Koontikeräyslista lavakeräyksille

- muokkaatilaus.php
Jos käyttäjällä ei oletus-toimipaikkaa, niin exceliin kaikki avoimet tilaukset
> Avoimet myyntitilaukset

- inc/lasku.inc
Voi muuttaa vanhojakin laskuja, jos hakee laskun laskunumerolla.
> Muuta laskun tietoja

- db_sql_query.php
Kun SQL-hakugeneraattorilla halutaan rajata tuotehakua toimittajalla, niin rajaus ei toiminut oikein.
> Tuotteet ja tuotteen toimittajatiedot exceliin

- tikon.php
Rivinvaihdot ja html-koodit pois
> Tikon-aineisto

- raportit/varastonarvo-super.php
Tuotteen kustannuspaikka lisätty exceliin
> Varastonarvo tuote -raportti

- hae_valuutat.php
curl-komennot poistettu, koska eivät toimineet enää
> Valuuttakurssien haku manuaalisesti

- raportit/varastonarvo-super.php
> Varastonarvo tuote

- extranet/view.php
- inc/avainsanarivi.inc
- tiedostofunkkarit.inc
- tiedostokirjasto.php
- tiedostotallennus.php
Käytetään samoja avainsanoja kuin LAATU (Muut avainsanat / Laatuasiakirjaselain), mutta tiedostotyyppien selitetark_2 kentässä voidaan määritellä maakoodi (tai * joka on kaikille). Extranetissä asiakas näkee sen jälkeen vain oman maansa tiedostoja, tai ne jotka on merkitty *:llä. Jos selitetark_2 kenttää ei ole määritelty, niin extranetissä ei näe mitään dokumentteja.
LAATU avainsanat ovat siis:
- AIHEAL_LAATUAS (Laatuasiakirjaselaimessa näytettävä aihealue)
- LITETY_LAATUAS (Laatuasiakirjaselaimessa näytettävä tiedostotyyppi)
Ohjelma tehdään luomalla menuihin tiedostonimi tiedostokirjasto.php ja laittamalla alanimeksi YLEISET_TIEDOSTOT.
> Tiedostokirjasto YLEISET_TIEDOSTOT

- yllapito_tuotekuvat.php
> Tuotekuvien ylläpito

- tilauskasittely/tulostakopio.php
Lavatarrakopio, kun keräyslista-tilaus mitätöity.
> Lavatarrakopio

- tilauskasittely/tulosta_lahete.inc
Jos tilausta ei saa osatoimittaa, ilmoitetaan se tilausvahvistuksella
> pdf- tilausvahvistus

- tilauskasittely/tilaus-valmis.inc
Tarkistetaan oikein, onko kokonaistoimitus mahdollinen
> Osatoimitus

- tilauskasittely/tulosta_lahete.inc
Toimitustapa, rahtisopimus ja kokonaistoimitus oikeaan järjestykseen
> Tilausvahvistus

- rajapinnat/presta/presta_products.php
> Presta-rajapinta

- rajapinnat/presta/presta_products.php
Reverts devlab-oy/pupesoft#3957
> Revert "Presta-rajapinta"

- rajapinnat/presta/presta_products.php
Reverts devlab-oy/pupesoft#3959
> Revert "Product_bundle pois"

- dokumenttien_hyvaksynta.php
- inc/dokumenttien_hyvaksynta.inc
- tervetuloa.php
- uutiset.php
Hyväksyttävät dokumentit näytetään Pupesoftin etusivulla
> Hyväksyttävät dokumentit etusivulle

- tilauskasittely/osoitelappu_intrade_pdf.inc
> Osoitelappu-pdf

- inc/myymyyjat.inc
Lisätty myyjäkohtaisesti myynnit yhteensä/kausi sekä kate yhteensä/kausi
> Myyjien myynnit -raportti

- inc/asiakashintarivi.inc
Näytetään piiri vain yhteen kertaan alasvetovalikossa
> Maantieteellinen piiri uudessa asiakashinnassa

- inc/toimitustavan_avainsanatrivi.inc
- rajapinnat/logmaster/logmaster-functions.php
Voidaan määritellä toimitustavan takana toimitustavan avainsanoissa (laji "ulkoisen varaston parametri") poikkeava arvo kenttään custordernumber, joka oletuksena on asiakkaan tilausnumero.
> Logmaster custordernumber

- inc/asiakashaku.inc
- inc/avainsanarivi.inc
- inc/avainsanatarkista.inc
- tilauskasittely/tilaus_myynti.php
Vastuumyyjä näkyviin asiakashakuun ja myyntitilausrivien otsikko-osaan, kun avainsana olemassa
> Myyntitilaus

- inc/unifaun_send.inc
Kun Posti-rahdilla vastaanottaja maksaa rahdin, rahdinmaksajan tiedot annettava sanomalla, vaikka olisi sama kuin ostaja
> Unifaun-sanoma

- tilauskasittely/tilauskanta_saatavuus.php
Uusi raportti: Tilauskanta/saatavuus
> Uusi raportti: Tilauskanta/saatavuus

- vaihda_tuoteno.php
Ei deleteoida puun_alkiota, jos vaihdetaan tuotenumerossa pieniä kirjaimia isoiksi tai toisinpäin
> Vaihda tuotenumeroita

- raportit/masterdata_excel.php
Tyyppi "Masterdata" tuotteet voidaan jatkossa rajata myös myyntitilauksien tilausnumeroilla
> Masterdata_excel tilausnumero

- inc/avainsanarivi.inc
- maksa.php
Kustannuspaikka maksatukseen näkyviin, jos avainsana olemassa
> Maksa laskuja

- inventoi.php
- inventointi_listat.php
Inventointilistalle voidaan lukea lasketut määrät Excelistä. Vaatii laajan inventointilistan käytön.
> * Inventointilistalle voidaan lukea lasketut määrät Excelistä

- inc/yhtion_parametritrivi.inc
- tilauskasittely/luo_myyntitilausotsikko.inc
- tilauskasittely/otsik.inc
Uusi yhtiön parametri asiakasmyyja_tilaukselle, jolla voidaan säätää valitaanko tilaukselle myyjäksi laatijan sijaan automaattisesti asiakkaan myyjä.
> Asiakasmyyjä tilaukselle

- inc/functions.inc
- inc/yhtion_parametritrivi.inc
- inc/yhtiorivi.inc
- muuvarastopaikka.php
- tilauskasittely/teelaskuntiliointi.inc
- tilauskasittely/tilauksesta_varastosiirto.inc
- tilauskasittely/tilaus-valmis.inc
- tilauskasittely/verkkolasku.php
100% ennakkotilausten tuotteet siirretään ennakkolaskutuksen yhteydessä parametreissä annettuun varastoon odottomaan noutoa.
> Ennakkomaksut

- rahtikirja-tulostus.php
- rajapinnat/logmaster/tracking_code.php
- unifaun_fetch.php
Voi olla mm WooCommerce ja Magento verkkokaupat samanaikaisesti käytössä. Molemmissa on tilauksissa ohjelma_moduli MAGENTO, eli erotellaan toimitusvahvistuksien käsittely jatkossa myös laatijalla.
> Magento toimitusvahvistus fix

- inc/functions.inc
- inc/yhtion_parametritrivi.inc
- raportit/paivan_laskut.php
- tilauskasittely/uudelleenluo_laskuaineisto.php
- tilauskasittely/verkkolasku.php
- tilauskasittely/verkkolasku_finvoice_201.inc
- verkkolasku_resend.php
> Verkkolaskut

- tilauskasittely/tarkistarivi.inc
Myyntitilausrivin Var ei voi olla O ( = optio )
> Myyntirivitietojen lisätarkistus

- inc/avoimet.inc
Maksutekstit näkyviin avainsanalla
> Avoimet myyntilaskut -raportti

- asiakasvalinta.inc
- inc/yhtion_parametritrivi.inc
- tilauskasittely/syotarivi.inc
Voidaan sallia extranettiin asiakasalennusten antaminen (special case) myyntitilauksella.
Alennukset aktivoituu extranetin salasanat.php:ssä muuttujalla $extranet_alennukset ja arvolla 'JOO'.
> Extranet alennus

- asiakasvalinta.inc
- tilauskasittely/syotarivi.inc
Hieman lisää hienosäätöä edelliseen ominaisuuteen
> Extranet alennukset 2

- tilauskasittely/jalkilaskenta.inc
Huomioidaan jälkilaskennassa asiakasvarasto-ominaisuuden kautta tulleet poikkeavat varasto-tilit.
> Asiakasvarasto jälkilaskenta fix

- inc/functions.inc
- tilauskasittely/tulosta_lasku.inc
- tilauskasittely/uudelleenluo_laskuaineisto.php
- tilauskasittely/verkkolasku.php
- verkkolasku_resend.php
> Verkkolasku

- rahtikirja.php
Huomioidaan kerääjän oletusvarasto, kun palataan keräämään
> Rahtikirjan syötöstä takaisin keräämään

- rajapinnat/logmaster/outbound_delivery_confirmation.php
Osataan jatkossa ottaa seurantakoodi myös keräyskuittaus sanomassa, ilman erillistä seurantakoodi-sanomaa.
> Ulkoisen varaston seurantakoodi

- dokumenttien_hyvaksynta.php
- uusi_dokumentti.php
Dokumenttien palauttaminen aiemmalle hyväksyjälle oli koodattu osittain. Koodattiin viimeiset silaukset, jotta tämä ominaisuus saadaan käyttöön.
> Korjattu dokumenttien palauttaminen aiemmalle hyvaksyjalle

- raportit/myyntiseuranta.php
Myynninseuranta-raportin tuotelistaus 2 listauksen luomien kenttien nimitykset muutettu toiseen muotoon ja siihen on lisätty tuotenumero, lisättiin nämä kentät huomioimaan aikarajausta ja katsomaan kappalemäärää myykplnyt kentän tapaan.
> Myynninseuranta tuotelistaus 2 viilauksia

- tilauskasittely/tulosta_lahete_kerayslista.inc
- tilauskasittely/tulostakopio.php
Tarjous exceliin lisätty yhteensäsummarivi tilauksen loppuun. Yheissummarivi lisätty samalla myös hinnalliseen tilausvahvistusexceliin, koska se rakennetaan samalla tavalla kuin tarjousexcel.
> Tarjous excel hintatiedoilla

- raportit/myyntitilasto_gauge.php
Huomioidaan epäkurantoidut tuotteet katetta laskettaessa
> Myyntimittarit

- rajapinnat/logmaster/synchronize_products.php
> Hälytysraja ulkoiseen varastoon

- inc/toimirivi.inc
- tilauskasittely/otsik_ostotilaus.inc
Toimittajan taakse lisätty uusi vapaa teksti-kenttä. Tähän kenttään kirjoitettu teksti tulee ostotilaukselle viesti-kenttään.
> Toimitajan taakse uusi kenttä

- inc/unifaun_send.inc
Kun tilauksen postinumero on AX-xxxxx, osataan Unifaun-sanomaan vaihtaa maakoodiksi AX
> Ahvenanmaa Unifaunissa

- inc/functions.inc
- inc/valitse_tulostin.inc
- tilauskasittely/tulosta_lahete.inc
- tilauskasittely/tulosta_tilausvahvistus_pdf.inc
Tehty uusi tilausvahvistuspohja "Näytetään asiakkaan hinta ja alennus" pohjalta. Uudessa tilausvahvistuspohjassa myös JT-rivit lasketaan mukaan yhteensä summaan.
> Uusi ominaisuus: uusi tilausvahvistuspohja

- inc/functions.inc
- inc/tulosta_pullopanttitarra_pdf.inc
- inc/tuoterivi.inc
- pdflib/phppdflib.class.php
- tilauskasittely/keraa.php
- tilauskasittely/sarjanumeroseuranta.php
- tilauskasittely/tulostakopio.php
Sarjanumerollisille tuotteille voi tulostaa keräyksessä pullopanttitarroja. Tuotteiden takana on uusi valinta, jolla tämän ominaisuuden saa päälle. Keräyksessä tehdään pdf jonka voi sitten tulostaa haluamalleen tulostimelle.
> Uusi ominaisuus: pullopanttitarrojen tulostus kerayksessa

- tilauskasittely/tilaus_myynti.php
Rahtivapaan alarajasummaa verrataan alv käsittely-parametrin perusteella joko verolliseen tai verottomaan summan. Muutettu niin, että myös rahtihintalaskuri osaa noudattaa tätä periaatetta.
> Rahtihintalaskuri noudattamaan alv käsittelyä

- tilauskasittely/tilaus_myynti.php
Reverts devlab-oy/pupesoft#4038
> Revert "Rahtihintalaskuri noudattamaan alv käsittelyä"

- inc/tulosta_siirtoraportti_pdf.inc
- muuvarastopaikka.php
- tilauskasittely/tulostakopio.php
Käytettäessä muuvarastopaikka-ohjelmaa varastosiirtoihin vainsiirto-parametrillä tehdään siirrosta pdf:lle tulostettava siirtoraportti.
> Siirtoraportti muuvarastopaikan siirtoihin

- raportit/varastonarvo-super.php
Varastonarvo tuote-raporttiin lisätty mahdollisuus ottaa mukaan raporttii tuotteiden tuotepaikkakohtainen hälytysraja.
> Tuotepaikkakohtainen hälytysraja varastonarvo tuote rapsaan

- rajapinnat/mycashflow/mycf_tilaukset.php
- rajapinnat/mycashflow/mycf_tuote_export.php
Mahdollisuus ohjata myyntejä omalle asiakasnumerolle verkkokaupan tilauksen "versiokoodin" mukaan
> MyCashflow tilauskanavat

- inc/avainsanarivi.inc
- tilauskasittely/tilaus_myynti.php
Uusi yhtiön avainsana, jolla voi hallita tilausrivien ulkoasua. Tällä hetkellä avainsanalla on vain yksi käyttötarkoitus, jos avainsana on olemassa niin tilausrivit, joissa myytävissä oleva saldo menee miinukselle tausta värjätään punaisella.
> Uusi ominaisuus: avainsana myyntirivin ulkoasun hallintaan

- tilauskasittely/tilaus_myynti.php
Rahtikulu nollaksi mikäli tilausrivien yhteensä arvo ylittää rahtivapauden alarajasumman
> tilausmyynti rahtikulu korjaus

- inc/tulosta_pullopanttitarra_pdf.inc
Muokattu tarran tekstien sijaintia ja sisältöä hieman.
> Pieniä muutoksia tarran ulkoasuun ja teksteihin

- verkkolasku_resend.php
Lisätty uusi operaattorin palvelin
> Verkkolaskujen lähetys operaattorille

- inc/yhtion_parametritrivi.inc
- tilauskasittely/tilaus_myynti.php
- tilauskasittely/tuote_selaus_haku.php
Lisätään saldo myytävissä näkyminen extranet tilaukselle. Samalla lisätään ominaisuus, että jos saldo menee miinukselle kyseinen sarake värjätään punaisella. Tämä tehdään vain jos tietty avainsana on määriteltynä.
> Extranetin tuoterivimuokkaukseen saldo näkyville

- verkkolaskuvirheet.php
Virheellisissä verkkolaskuissa kun painetaan perusta uusi toimittaja
Muutettu kenttiä joihin laskuttajan tilino, vat ja ovt päivittyvät.
> Virheelliset_verkkolaskut

- raportit/myyntiseuranta.php
Myynninseurantaraportin tuotelistaus 2 ei toiminut enää suunnitellulla tavalla, koska yksi sen sisältämä haku oli rikkoutunut. Haku on nyt korjattu.
> Myynninseurantaraportin tuotelistaus 2 korjaus

- inc/avoimet.inc
Myyntireskontran avoimet laskut ohjelmaa lisätty kaksi uutta täppää jolla voi lisätä kaksi uutta vaihtoehtoista kenttää raporttiin. Uudet kentät ovat asiakkaan takaa tuleva asiakasfakta ja laskun tiedoista tuleva kommentti.
> Asiakasfakta ja myyntilaskun kommentit avoimien laskujen listaukseen

- tilauskasittely/uudelleenluo_laskuaineisto.php
- tilauskasittely/verkkolasku_finvoice_201.inc
Lisätty uusi senderintermediator vaihtoehto
> Uusi tapaus senderintermediatoriin

- tilauskasittely/verkkolasku_finvoice_201.inc
Mikäli avainsanoissa on lajin VERKLASKKENTSIS selitetark kentässä BuyerEmailaddressIdentifier	silloin finvoicessa ko. kenttään viedään asiakas.lasku_email sisältö
> finvoicessa email BuyerEmailaddressIdentifier kenttään

- inventoi.php
Mikäli tuotteella on sarjanumeroseuranta myynti käytössä niin sarjanumeroseurantaa ei huomioida inventoinnissa
> sarjanumeroseurannan myynti ei mukaan inventointiin

- raportit/vuosisopimusasiakkaat.php
Tuodaan vuosisopimusraportille myös kulutustiedot tuotteilta joilla tuoteryhmä on 0
> Vuosisopimusraportti korjaus

- rajapinnat/relex/relex_transactions.php
Lisätty ale1 kenttä relex transactions scriptiin viimeiseksi sarakkeeksi.
> Lisätty ale1 kenttä relex transactions scriptiin

- tilauskasittely/tulosta_tarjous.inc
- tyomaarays/tulosta_tyomaarays.inc
Tarjouksen ja työmääräyksen sivutuksessa ja rivityksessä oli ongelma tietyssä spesiaalissa tapauksessa jos tuoteperheen viimeisenä tuotteena oli tuotenumero joka oli täyisin numeerinen -> tämä rikkoi tietyissä tapauksissa sivutuksen. Sivutus ja rivitys on nyt korjattu.
> Tarjouksen ja työmääräyksen sivutus ja rivit

- inc/functions.inc
- inc/yhtion_parametritrivi.inc
- rajapinnat/magento_client.php
- rajapinnat/tuote_export.php
- raportit/paivan_laskut.php
- tilauskasittely/tilaus-valmis-tulostus.inc
- tilauskasittely/tulosta_lasku.inc
- tilauskasittely/uudelleenluo_laskuaineisto.php
- tilauskasittely/varastoon.inc
- tilauskasittely/verkkolasku.php
- tilauskasittely/verkkolasku_finvoice_201.inc
- verkkolasku_resend.php
Poistetaan Fitek-Viro FI-Pupesta
> Pieniä korjauksia ja poistetaan Fitek-Viro FI-pupesta

- rajapinnat/magento_client.php
- rajapinnat/tuote_export.php
Lisätty logitus siitä onko saldomuutos ajettu kaikille tuotteille vai vain tuotteille jolle on muutoksia
> Lisätty logitusta magento saldoajoon

- inc/avainsanarivi.inc
- tilauskasittely/tulosta_lahete.inc
Lisätty uusi yhtiön avainsana jonka avulla tilausvahvistukselle voidaan lisätä ehtoja.
> Tilausvahvistukselle voi lisätä ehtoja

- inc/laskurivi.inc
Lisätty tilaustyyppejä ja korjattu ääkköset
> laskurivi_inc_korjaus

- inc/tiliotesaannot.inc
- inc/viitemaksut.inc
- tiliotesaannot.php
Voidaan estää viitemaksuja menemästä myyntireskontraan.
> Viitemaksut vain kirjanpitoon

- datain/Finvoice3.0.xsd
- datain/Finvoice_3.0.css
- datain/Finvoice_3.0.xsl
- inc/verkkolasku-in-erittele-laskut.inc
Otetaan vastaan Finvoice 3.0 version laskuja
> Finvoice 3.0 vastaanotto

- maksusopimus_laskutukseen.php
Erikoisalennus oli oikein hyvin otettu huomioon ennakkolaskujen teossa kaikkialla muualla paitsi rivien insertissä.
> Otetaan erikoisalennus mukaan myös inserttiin

- inc/maksupaate_funktiot.inc
- kayttajat.php
- rajapinnat/NetsCloudClient.php
- rajapinnat/lumo_handler.inc
Replace obsolete NETS lumo client with new cloud client
> NETS Cloud

- rajapinnat/mycashflow/mycf_tilaukset.php
- rajapinnat/mycashflow/mycf_tuote_export.php
Reverts devlab-oy/pupesoft#4132
> Revert "Igor/mycashflow maksuehto"

- inc/toimitustaparivi.inc
DB SCHENKER Noutopistepaketti SBTLFIRREX
> Unifaun virallisen nimen tunnuksen päivitys

- inc/unifaun_send.inc
sessions  on jatkossa aina ufo_SE packsoft poistui käytöstä 05-2022
> Unifaun packsoft

- inc/functions.inc
Pyöristetään summa maksupäätteellä lähimpään 5 senttiin, jos maksuehdossa on valittu pyöristys.
> Pyöristetään oikein maksupäätteen kanssa
